# 2D / 3D Mapping

config Completer.use_jedi = False #to fix problem with my tab completion under jupyter (must find a better solution)

 ## Boreholes 2D mapping from files

### imports

In [1]:
import matplotlib.pyplot as plt
#from striplog import Component, Decor, Legend
#from core.omf import Borehole3D, striplog_legend_to_omf_legend 

import geopandas as gpd, pandas as pd
from shapely import wkt
import folium as fm
from folium import plugins
from utils.io import boreholes_from_files, striplog_from_text, save_loc, read_geodf_file
from os import remove
from core.core import Project
from core.orm import BoreholeOrm, PositionOrm, Base
from striplog import Lexicon, Striplog
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from definitions import ROOT_DIR

### Data from a shapefile

In [2]:
file = ["/CF_data/Pilote_v7.0/Pilote_v7.0.shp","/CF_data/Pilote_v8.0/Pilote_v8.0.shp"]
shp = gpd.read_file(ROOT_DIR+file[1])
shp

,Id,Type,Pilote,Ref,diam,Valid,Syscal,Impo,Inox,Impo_perm,GPS2021,geometry
0,0,1,1,111,2,1,1,0,1,0,OUI,POINT (152894.891 122592.127)
1,0,1,1,120,2,1,1,0,1,0,OUI,POINT (152881.447 122588.102)
2,0,2,1,217,3,1,1,1,1,0,OUI,POINT (152885.995 122587.127)
3,0,1,1,116,2,1,1,0,1,0,OUI,POINT (152883.768 122589.754)
4,0,2,1,214,2,1,1,1,1,0,OUI,POINT (152888.128 122588.436)
...,...,...,...,...,...,...,...,...,...,...,...,...
83,0,6,0,50,0,0,0,0,0,0,OUI,POINT (152893.126 122602.456)
84,0,6,0,52,0,0,0,0,0,0,OUI,POINT (152889.301 122592.517)
85,0,6,0,51,0,0,0,0,0,0,OUI,POINT (152889.534 122591.686)
86,0,6,0,53,0,0,0,0,0,0,OUI,POINT (152889.786 122588.802)
87,0,3,0,304,0,0,0,0,0,0,OUI,POINT (152884.742 122588.503)

**Rmq** : ici à quoi correspondent :

    - ID (tout est à 0!), 
    - Ref
    - Type

In [3]:
if 'Id' in shp.columns:
    shp=shp.drop(['Id'], axis=1)
    #shp.index.name='Id'
shp

,Type,Pilote,Ref,diam,Valid,Syscal,Impo,Inox,Impo_perm,GPS2021,geometry
0,1,1,111,2,1,1,0,1,0,OUI,POINT (152894.891 122592.127)
1,1,1,120,2,1,1,0,1,0,OUI,POINT (152881.447 122588.102)
2,2,1,217,3,1,1,1,1,0,OUI,POINT (152885.995 122587.127)
3,1,1,116,2,1,1,0,1,0,OUI,POINT (152883.768 122589.754)
4,2,1,214,2,1,1,1,1,0,OUI,POINT (152888.128 122588.436)
...,...,...,...,...,...,...,...,...,...,...,...
83,6,0,50,0,0,0,0,0,0,OUI,POINT (152893.126 122602.456)
84,6,0,52,0,0,0,0,0,0,OUI,POINT (152889.301 122592.517)
85,6,0,51,0,0,0,0,0,0,OUI,POINT (152889.534 122591.686)
86,6,0,53,0,0,0,0,0,0,OUI,POINT (152889.786 122588.802)
87,3,0,304,0,0,0,0,0,0,OUI,POINT (152884.742 122588.503)

In [4]:
print("nombre de données :", len(shp))
print("nombre de forages (diam > 0 ??) :", len(shp.query('diam>0')))
#shp.loc[41]

nombre de données : 88
nombre de forages (diam > 0 ??) : 60

### Save location data in a Geopackage / GeoJson / csv

In [5]:
save_loc(shp, 31370, 'tmp_files/test_loc.csv')

tmp_files/test_loc.csv has been saved !

In [6]:
cat 'tmp_files/test_loc.csv'

X,Y,Type,Pilote,Ref,diam,Valid,Syscal,Impo,Inox,Impo_perm,GPS2021,geometry
152894.89100002544,122592.12713904586,1,1,111,2,1,1,0,1,0,OUI,POINT (152894.8910000254 122592.1271390459)
152881.4470000254,122588.10213904455,1,1,120,2,1,1,0,1,0,OUI,POINT (152881.4470000254 122588.1021390446)
152885.99500002537,122587.12713904679,2,1,217,3,1,1,1,1,0,OUI,POINT (152885.9950000254 122587.1271390468)
152883.7680000254,122589.75413904712,1,1,116,2,1,1,0,1,0,OUI,POINT (152883.7680000254 122589.7541390471)
152888.1280000254,122588.43613904715,2,1,214,2,1,1,1,1,0,OUI,POINT (152888.1280000254 122588.4361390471)
152886.2260000254,122591.65513904672,1,1,113,2,1,1,0,1,0,OUI,POINT (152886.2260000254 122591.6551390467)
152880.9800000254,122583.69313904643,2,1,223,3,1,1,1,1,1,OUI,POINT (152880.9800000254 122583.6931390464)
152883.65800002537,122585.62313904893,2,1,221,2,1,1,1,1,1,OUI,POINT (152883.6580000254 122585.6231390489)
152889.1520000254,122587.1761390483,1,1,118,2,1,1,0,1,0,OUI,POINT (152889.1520000254 122587.1761390483)
152883.43300002534,122588.32313904725,2,1,216,2,1,1,1,1,1,OUI,POINT (152883.4330000253 122588.3231390473)
152883.43300002534,122580.26613904629,2,1,226,2,1,1,1,1,1,OUI,POINT (152883.4330000253 122580.2661390463)
152883.57100002537,122593.02013904788,1,1,112,2,1,1,0,1,0,OUI,POINT (152883.5710000254 122593.0201390479)
152891.94900002552,122593.72213904653,1,1,110,2,1,1,0,1,0,OUI,POINT (152891.9490000255 122593.7221390465)
152884.22600002537,122583.90313904826,1,1,125,2,1,1,0,1,0,OUI,POINT (152884.2260000254 122583.9031390483)
152888.80200002543,122590.0531390477,1,1,114,2,1,1,0,1,0,OUI,POINT (152888.8020000254 122590.0531390477)
152886.53400002536,122588.83313904703,1,1,117,2,1,1,0,1,0,OUI,POINT (152886.5340000254 122588.833139047)
152885.4830000254,122590.19413904846,2,1,213,2,1,1,1,1,1,OUI,POINT (152885.4830000254 122590.1941390485)
152888.76800002545,122585.85713904724,2,1,218,2,1,1,1,1,1,OUI,POINT (152888.7680000254 122585.8571390472)
152885.03158300993,122585.3671309175,4,1,400,0,0,0,0,0,0,NON,POINT (152885.0315830099 122585.3671309175)
152890.6620000255,122587.51713904738,2,1,215,2,1,1,1,1,1,OUI,POINT (152890.6620000255 122587.5171390474)
152881.17100002535,122580.4831390474,2,1,225,2,1,1,1,1,0,OUI,POINT (152881.1710000254 122580.4831390474)
152883.5060000254,122582.57913904637,2,1,224,2,1,1,1,1,0,OUI,POINT (152883.5060000254 122582.5791390464)
152879.12900002534,122583.27013904788,2,1,210,2,1,0,0,0,0,OUI,POINT (152879.1290000253 122583.2701390479)
152885.8040000254,122584.37513904646,2,1,222,2,1,1,1,1,1,OUI,POINT (152885.8040000254 122584.3751390465)
152884.55900002542,122586.86513904855,1,1,121,2,1,1,0,1,0,OUI,POINT (152884.5590000254 122586.8651390485)
152886.79600002544,122583.44613904692,1,1,126,2,1,1,0,1,0,OUI,POINT (152886.7960000254 122583.4461390469)
152881.57883449996,122585.08690298628,1,1,124,2,1,1,0,1,0,OUI,POINT (152881.5788345 122585.0869029863)
152886.77900002545,122585.61413904652,1,1,122,2,1,1,0,1,0,OUI,POINT (152886.7790000254 122585.6141390465)
152881.7110000254,122582.22613904905,1,1,127,2,1,1,0,1,0,OUI,POINT (152881.7110000254 122582.226139049)
152893.79900002544,122593.65913904738,1,1,107,2,1,1,0,1,0,OUI,POINT (152893.7990000254 122593.6591390474)
152886.1190000254,122594.53213904705,1,1,108,2,1,1,0,1,0,OUI,POINT (152886.1190000254 122594.532139047)
152891.25200002544,122595.00913904794,1,1,106,2,1,1,0,1,0,OUI,POINT (152891.2520000254 122595.0091390479)
152890.82431275706,122583.5798753826,5,1,500,0,0,0,0,0,0,NON,POINT (152890.8243127571 122583.5798753826)
152892.8790000254,122592.58713904768,2,1,207,2,1,1,1,1,1,OUI,POINT (152892.8790000254 122592.5871390477)
152885.19800002538,122592.74513904564,2,1,208,2,1,1,1,1,1,OUI,POINT (152885.1980000254 122592.7451390456)
152888.16400002537,122591.69413904753,2,1,209,2,1,1,1,1,1,OUI,POINT (152888.1640000254 122591.6941390475)
152890.42400002546,122593.64313904569,2,1,206,2,1,1,1,1,1,OUI,POINT (152890.4240000255 122593.6431390457)
152888.12300002543,122599.14613904711,1,1,100,2,1,1,0,1,0,OUI,POINT (152888.1230000254 122599.1461390471)
152891.16600002543,122597.62813904602,1,1,101,2,1,1,0,1,0,OUI,POINT (152891.1660000254 122597.628139046)
152893.33600002548,122595.92013904639,1,1,102,2,1,1,0,1,0,OUI,POINT (152893.3360000255 122595.9201390464)
152895.43100002548,122594.85713904817,1,1,103,2,1,1,0,1,0,OUI,POINT (152895.4310000255 122594.8571390482)
152888.20900002544,122596.49213904701,1,1,105,2,1,1,0,1,0,OUI,POINT (152888.2090000254 122596.492139047)
152891.32900002546,122588.78113904875,1,1,115,2,1,1,0,1,0,OUI,POINT (152891.3290000255 122588.7811390487)
152889.47000002547,122584.78213904798,1,1,123,2,1,1,0,1,0,OUI,POINT (152889.4700000255 122584.782139048)
152887.7500000254,122594.56613904703,2,1,205,3,1,1,1,1,0,OUI,POINT (152887.7500000254 122594.566139047)
152885.1050000254,122596.29513904639,2,1,204,2,1,1,0,1,0,OUI,POINT (152885.1050000254 122596.2951390464)
152892.8990000255,122594.97613904811,2,1,202,2,1,1,1,1,1,OUI,POINT (152892.8990000255 122594.9761390481)
152890.24100002553,122596.46113904752,2,1,201,2,1,1,1,1,0,OUI,POINT (152890.2410000255 122596.4611390475)
152887.63100002534,122598.04613904748,2,1,200,2,1,1,1,1,1,OUI,POINT (152887.6310000253 122598.0461390475)
152885.82300002544,122597.76613904722,1,1,104,2,1,1,0,1,0,OUI,POINT (152885.8230000254 122597.7661390472)
152888.5570000254,122593.31413904857,1,1,109,2,1,1,0,1,0,OUI,POINT (152888.5570000254 122593.3141390486)
152891.79100002543,122586.1501390487,1,1,119,2,1,1,0,1,0,OUI,POINT (152891.7910000254 122586.1501390487)
152879.13500002536,122580.17613904737,1,1,128,2,1,1,0,1,0,OUI,POINT (152879.1350000254 122580.1761390474)
152882.02200002535,122579.22513904702,1,1,129,2,1,1,0,1,0,OUI,POINT (152882.0220000253 122579.225139047)
152895.35400002546,122593.70113904681,2,1,203,2,1,1,1,1,0,OUI,POINT (152895.3540000255 122593.7011390468)
152882.76500002542,122591.41413904633,2,1,212,2,1,1,0,1,0,OUI,POINT (152882.7650000254 122591.4141390463)
152888.10200002545,122583.96013904642,2,1,211,2,1,1,1,1,0,OUI,POINT (152888.1020000255 122583.9601390464)
152891.5540000255,122584.95313904714,2,1,219,2,1,1,0,1,0,OUI,POINT (152891.5540000255 122584.9531390471)
152880.74000002534,122586.3991390476,2,1,220,2,1,1,0,1,0,OUI,POINT (152880.7400000253 122586.3991390476)
152893.9330000255,122594.96413904615,3,1,301,0,0,0,0,0,0,OUI,POINT (152893.9330000255 122594.9641390461)
152887.10600002544,122593.01613904722,3,1,302,0,0,0,0,0,0,OUI,POINT (152887.1060000254 122593.0161390472)
152891.63200002545,122591.38213904668,3,1,303,0,0,0,0,0,0,OUI,POINT (152891.6320000254 122591.3821390467)
152880.26600002535,122582.55413904414,3,1,305,0,0,0,0,0,0,OUI,POINT (152880.2660000254 122582.5541390441)
152867.45209745003,122588.87729745824,3,1,306,0,0,0,0,0,0,NON,POINT (152867.45209745 122588.8772974582)
152876.61200002534,122584.35813904833,2,0,227,2,0,1,1,0,0,OUI,POINT (152876.6120000253 122584.3581390483)
152889.81200002544,122581.22613904811,1,0,13,0,0,1,0,1,0,OUI,POINT (152889.8120000254 122581.2261390481)
152887.3020000254,122579.5511390455,1,0,16,0,0,1,0,1,0,OUI,POINT (152887.3020000254 122579.5511390455)
152884.5820000254,122580.77813904732,1,0,15,0,0,1,0,1,0,OUI,POINT (152884.5820000254 122580.7781390473)
152884.69700002536,122577.76113904733,1,0,10,2,1,1,0,1,0,OUI,POINT (152884.6970000254 122577.7611390473)
152887.41200002545,122576.40913904551,1,0,11,2,1,1,0,1,0,OUI,POINT (152887.4120000254 122576.4091390455)
152885.5410000254,122579.35213904642,2,0,25,0,0,0,0,0,0,OUI,POINT (152885.5410000254 122579.3521390464)
152888.36700002546,122577.94413904753,2,0,21,0,1,0,0,0,0,OUI,POINT (152888.3670000255 122577.9441390475)
152888.55500002543,122581.87813904788,2,0,23,0,0,0,0,0,0,OUI,POINT (152888.5550000254 122581.8781390479)
152886.29900002538,122580.93113904726,1,0,24,0,1,1,1,1,1,OUI,POINT (152886.2990000254 122580.9311390473)
152888.5000000254,122580.49013904762,1,0,22,0,1,0,0,0,0,OUI,POINT (152888.5000000254 122580.4901390476)
152886.46500002543,122577.94913904741,1,0,20,0,1,1,1,1,1,OUI,POINT (152886.4650000254 122577.9491390474)
152888.05000002543,122581.03613904584,3,0,30,0,0,0,0,0,0,???,POINT (152888.0500000254 122581.0361390458)
152885.90100002542,122581.71113904845,3,0,32,0,0,0,0,0,0,OUI,POINT (152885.9010000254 122581.7111390484)
152886.0900000254,122578.42713904567,3,0,31,0,0,0,0,0,0,OUI,POINT (152886.0900000254 122578.4271390457)
152883.68000002543,122577.58713904768,4,0,40,0,0,0,0,0,0,OUI,POINT (152883.6800000254 122577.5871390477)
152884.2410000254,122576.75213904679,4,0,41,0,0,0,0,0,0,OUI,POINT (152884.2410000254 122576.7521390468)
152888.6360000254,122578.79613904748,1,0,12,0,1,0,0,0,0,OUI,POINT (152888.6360000254 122578.7961390475)
152887.36800002542,122581.00713904761,1,0,14,0,0,0,0,0,0,OUI,POINT (152887.3680000254 122581.0071390476)
152893.12600002543,122602.45613904763,6,0,50,0,0,0,0,0,0,OUI,POINT (152893.1260000254 122602.4561390476)
152889.3010000254,122592.51713904738,6,0,52,0,0,0,0,0,0,OUI,POINT (152889.3010000254 122592.5171390474)
152889.53400002542,122591.68613904808,6,0,51,0,0,0,0,0,0,OUI,POINT (152889.5340000254 122591.6861390481)
152889.78600002543,122588.80213904474,6,0,53,0,0,0,0,0,0,OUI,POINT (152889.7860000254 122588.8021390447)
152884.7420000254,122588.50313904788,3,0,304,0,0,0,0,0,0,OUI,POINT (152884.7420000254 122588.5031390479)

### 2D Map

-idée à explorer : fonction pour générer une carte des forages présents dans un projet

In [7]:
#Change CRS EPSG 31370 (Lambert 72) into EPSG 4326 (WGS 84)
shp = shp.to_crs(epsg=4326)
center=[shp.geometry.y.mean(), shp.geometry.x.mean()]

# Use a satellite map
tile_name = ["Satellite"]
tile_attr = ["Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community"]
tile_url = ["https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"]

BH_map=fm.Map(location=center, tiles='OpenStreetMap', zoom_start=19, max_zoom=25, control_scale=True)

ch1 = fm.FeatureGroup(name='Boreholes')

for idx, row in shp.iterrows():
    fm.CircleMarker([row.geometry.y, row.geometry.x], popup=str(idx) , radius=0.1,
                     color='red', fill_color='red',
                    opacity=0.6
                    ).add_to(ch1)
    
#fm.GeoJson('BH_loc.json').add_to(fm_map)

mini_map = plugins.MiniMap(toggle_display=True, zoom_level_offset=-6)

#adding features to the base_map
fm.TileLayer(name=tile_name[0], tiles=tile_url[0], max_zoom=25, attr=tile_attr[0], control=True).add_to(BH_map)
ch1.add_to(BH_map)
fm.LayerControl().add_to(BH_map)
BH_map.add_child(mini_map)

#save in a file
BH_map.save('tmp_files/BH_location.html')
BH_map

### Reading location data from a csv, Geo(package/Json) file

In [8]:
file_dir=ROOT_DIR+'/playground/TFE_test/tmp_files/'

In [9]:
print(file_dir)

/home/yanathan/Projects/GSDMA/playground/TFE_test/tmp_files/

In [10]:
bh_loc=read_geodf_file('test_loc.csv', 31370, 4326, file_dir)
bh_loc.head(2)

Last step before create the geodataframe
 Overwrite X,Y coordinates fields ? (y/n) : n

,X,Y,Type,Pilote,Ref,diam,Valid,Syscal,Impo,Inox,Impo_perm,GPS2021,geometry
0,152894.891,122592.127139,1,1,111,2,1,1,0,1,0,OUI,POINT (4.40948 50.41421)
1,152881.447,122588.102139,1,1,120,2,1,1,0,1,0,OUI,POINT (4.40929 50.41417)

**Rmq** : la coordonnée Z est manquante dans les données de base !

### Create a boreholes positions list

bh_loc.loc[:2, ['X','Y','Ref', ]]

In [11]:
x_list=bh_loc['X'].to_list()
y_list=bh_loc['Y'].to_list()
len(x_list)

88

## Borehole 3D mapping

### Build Borehole3D objects

Puisqu'on ne dispose que de la localisation des forages (pas d'infos sur la géométrie et le "contenu" des forages), l'idée est de créer **une géométrie et un contenu par défaut** pour chaque forage, **tout en respectant les positions**, puis les enregistrer dans la BD afin de pouvoir les afficher tous dans l'environnement 3D. La mise à jour des données manquantes se fera plus tard.

In [12]:
remove('tmp_files/tfe_orm_db.db')

Create the db engine and the database structure

In [13]:
engine = create_engine('sqlite:///tmp_files/tfe_orm_db.db', echo=True)
Base.metadata.create_all(engine)

2021-02-01 11:00:48,289 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2021-02-01 11:00:48,290 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:48,293 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2021-02-01 11:00:48,294 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:48,297 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Boreholes")
2021-02-01 11:00:48,299 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:48,308 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("Boreholes")
2021-02-01 11:00:48,309 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:48,313 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Positions")
2021-02-01 11:00:48,314 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:48,315 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("Positions")
2021-02-01 11:00:48,317 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:48,318 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Intervals")
2021-02-01 11:00:48,319 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:48,321 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("Intervals")
2021-02-01 11:00:48,322 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:48,323 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Components")
2021-02-01 11:00:48,324 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:48,326 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("Components")
2021-02-01 11:00:48,327 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:48,328 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Linkintervalcomponent")
2021-02-01 11:00:48,330 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:48,333 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("Linkintervalcomponent")
2021-02-01 11:00:48,335 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:48,337 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "Boreholes" (
	id VARCHAR(32) NOT NULL,
	PRIMARY KEY (id)
)


2021-02-01 11:00:48,339 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:48,413 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:00:48,415 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "Positions" (
	id INTEGER NOT NULL,
	upper FLOAT,
	middle FLOAT,
	lower FLOAT,
	x FLOAT,
	y FLOAT,
	PRIMARY KEY (id)
)


2021-02-01 11:00:48,416 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:48,514 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:00:48,516 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "Components" (
	id VARCHAR(32) NOT NULL,
	description VARCHAR(32),
	PRIMARY KEY (id)
)


2021-02-01 11:00:48,517 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:48,598 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:00:48,602 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "Intervals" (
	id INTEGER NOT NULL,
	borehole VARCHAR(32),
	interval_number INTEGER,
	description VARCHAR(32),
	top_id INTEGER,
	base_id INTEGER,
	PRIMARY KEY (id),
	FOREIGN KEY(borehole) REFERENCES "Boreholes" (id),
	FOREIGN KEY(top_id) REFERENCES "Positions" (id),
	FOREIGN KEY(base_id) REFERENCES "Positions" (id)
)


2021-02-01 11:00:48,603 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:48,690 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:00:48,692 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "Linkintervalcomponent" (
	int_id INTEGER NOT NULL,
	comp_id INTEGER NOT NULL,
	PRIMARY KEY (int_id, comp_id),
	FOREIGN KEY(int_id) REFERENCES "Intervals" (id),
	FOREIGN KEY(comp_id) REFERENCES "Components" (id)
)


2021-02-01 11:00:48,694 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:48,782 INFO sqlalchemy.engine.base.Engine COMMIT

creation of the Boreholes from las, csv files

In [14]:
lexicon = Lexicon.default() #to do : create our own lexicon

In [15]:
borehole_dict = {'F1':ROOT_DIR+'/data/test.las'}#, 'F2':ROOT_DIR+'/data/test.csv'} # boreholes to insert into the db

In [16]:
boreholes, components= boreholes_from_files(borehole_dict, x=x_list, y=y_list, verbose=0)

Create the session and the project

In [17]:
Session = sessionmaker(bind=engine)
session = Session()

p = Project(session)
p.add_components(components)

2021-02-01 11:00:49,944 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:00:49,946 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:00:49,948 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:49,953 INFO sqlalchemy.engine.base.Engine INSERT INTO "Components" (id, description) VALUES (?, ?)
2021-02-01 11:00:49,955 INFO sqlalchemy.engine.base.Engine ((0, 'Siltstone, grey'), (1, 'Anhydrite'), (2, 'Sandstone, vf-f, grey'), (3, 'Dolomite'), (4, 'Siltstone, red'), (5, 'Limestone'))
2021-02-01 11:00:49,960 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:00:50,192 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:00:50,194 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:00:50,195 INFO sqlalchemy.engine.base.Engine ()

Add boreholes into the database

In [18]:
for bh in boreholes:
    p.add_borehole(bh)

2021-02-01 11:00:50,267 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:50,269 INFO sqlalchemy.engine.base.Engine ((0, 14.3, 14.3, 14.3, 152894.89100002544, 122592.12713904586), (1, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152894.89100002544, 122592.12713904586), (2, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152894.89100002544, 122592.12713904586), (3, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152894.89100002544, 122592.12713904586), (4, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152894.89100002544, 122592.12713904586), (5, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152894.89100002544, 122592.12713904586), (6, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152894.89100002544, 122592.12713904586), (7, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152894.89100002544, 122592.12713904586)  ... displaying 10 of 50 total bound parameter sets ...  (48, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152894.89100002544, 122592.12713904586), (49, 135.9, 135.9, 135.9, 152894.89100002544, 122592.12713904586))
2021-02-01 11:00:50,273 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:00:50,274 INFO sqlalchemy.engine.base.Engine ('F1',)
2021-02-01 11:00:50,279 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:50,280 INFO sqlalchemy.engine.base.Engine ((0, 'F1', 0, 'Anhydrite', 0, 1), (1, 'F1', 1, 'Sandstone, grey, vf-f', 2, 3), (2, 'F1', 2, 'Anhydrite', 4, 5), (3, 'F1', 3, 'Dolomite', 6, 7), (4, 'F1', 4, 'Anhydrite', 8, 9), (5, 'F1', 5, 'Sandstone, grey, vf-f', 10, 11), (6, 'F1', 6, 'Siltstone, red', 12, 13), (7, 'F1', 7, 'Dolomite', 14, 15)  ... displaying 10 of 25 total bound parameter sets ...  (23, 'F1', 23, 'Limestone', 46, 47), (24, 'F1', 24, 'Volcanic', 48, 49))
2021-02-01 11:00:50,283 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:00:50,409 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:00:50,412 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:00:50,414 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:50,419 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:00:50,419 INFO sqlalchemy.engine.base.Engine ('F1',)
2021-02-01 11:00:50,423 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,424 INFO sqlalchemy.engine.base.Engine (0,)
2021-02-01 11:00:50,427 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,428 INFO sqlalchemy.engine.base.Engine (1,)
2021-02-01 11:00:50,431 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,432 INFO sqlalchemy.engine.base.Engine (2,)
2021-02-01 11:00:50,435 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,436 INFO sqlalchemy.engine.base.Engine (3,)
2021-02-01 11:00:50,440 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,442 INFO sqlalchemy.engine.base.Engine (4,)
2021-02-01 11:00:50,444 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,446 INFO sqlalchemy.engine.base.Engine (5,)
2021-02-01 11:00:50,449 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,450 INFO sqlalchemy.engine.base.Engine (6,)
2021-02-01 11:00:50,452 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,454 INFO sqlalchemy.engine.base.Engine (7,)
2021-02-01 11:00:50,457 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,460 INFO sqlalchemy.engine.base.Engine (8,)
2021-02-01 11:00:50,463 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,465 INFO sqlalchemy.engine.base.Engine (9,)
2021-02-01 11:00:50,471 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,473 INFO sqlalchemy.engine.base.Engine (10,)
2021-02-01 11:00:50,475 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,477 INFO sqlalchemy.engine.base.Engine (11,)
2021-02-01 11:00:50,479 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,483 INFO sqlalchemy.engine.base.Engine (12,)
2021-02-01 11:00:50,486 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:50,488 INFO sqlalchemy.engine.base.Engine (13,)
2021-02-01 11:00:50,491 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,494 INFO sqlalchemy.engine.base.Engine (14,)
2021-02-01 11:00:50,498 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,499 INFO sqlalchemy.engine.base.Engine (15,)
2021-02-01 11:00:50,501 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,503 INFO sqlalchemy.engine.base.Engine (16,)
2021-02-01 11:00:50,505 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,506 INFO sqlalchemy.engine.base.Engine (17,)
2021-02-01 11:00:50,509 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,512 INFO sqlalchemy.engine.base.Engine (18,)
2021-02-01 11:00:50,518 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,521 INFO sqlalchemy.engine.base.Engine (19,)
2021-02-01 11:00:50,523 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,525 INFO sqlalchemy.engine.base.Engine (20,)
2021-02-01 11:00:50,527 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,528 INFO sqlalchemy.engine.base.Engine (21,)
2021-02-01 11:00:50,531 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,532 INFO sqlalchemy.engine.base.Engine (22,)
2021-02-01 11:00:50,534 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,535 INFO sqlalchemy.engine.base.Engine (23,)
2021-02-01 11:00:50,538 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,541 INFO sqlalchemy.engine.base.Engine (24,)
2021-02-01 11:00:50,543 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,545 INFO sqlalchemy.engine.base.Engine (25,)
2021-02-01 11:00:50,547 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,551 INFO sqlalchemy.engine.base.Engine (26,)
2021-02-01 11:00:50,554 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,555 INFO sqlalchemy.engine.base.Engine (27,)
2021-02-01 11:00:50,557 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,558 INFO sqlalchemy.engine.base.Engine (28,)
2021-02-01 11:00:50,561 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,562 INFO sqlalchemy.engine.base.Engine (29,)
2021-02-01 11:00:50,565 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,566 INFO sqlalchemy.engine.base.Engine (30,)
2021-02-01 11:00:50,568 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,569 INFO sqlalchemy.engine.base.Engine (31,)
2021-02-01 11:00:50,571 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,573 INFO sqlalchemy.engine.base.Engine (32,)
2021-02-01 11:00:50,576 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,577 INFO sqlalchemy.engine.base.Engine (33,)
2021-02-01 11:00:50,583 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:50,585 INFO sqlalchemy.engine.base.Engine (34,)
2021-02-01 11:00:50,587 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,588 INFO sqlalchemy.engine.base.Engine (35,)
2021-02-01 11:00:50,592 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,598 INFO sqlalchemy.engine.base.Engine (36,)
2021-02-01 11:00:50,602 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,603 INFO sqlalchemy.engine.base.Engine (37,)
2021-02-01 11:00:50,606 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,607 INFO sqlalchemy.engine.base.Engine (38,)
2021-02-01 11:00:50,610 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,611 INFO sqlalchemy.engine.base.Engine (39,)
2021-02-01 11:00:50,614 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,615 INFO sqlalchemy.engine.base.Engine (40,)
2021-02-01 11:00:50,620 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,622 INFO sqlalchemy.engine.base.Engine (41,)
2021-02-01 11:00:50,626 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,627 INFO sqlalchemy.engine.base.Engine (42,)
2021-02-01 11:00:50,630 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,634 INFO sqlalchemy.engine.base.Engine (43,)
2021-02-01 11:00:50,636 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,638 INFO sqlalchemy.engine.base.Engine (44,)
2021-02-01 11:00:50,641 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,641 INFO sqlalchemy.engine.base.Engine (45,)
2021-02-01 11:00:50,644 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,645 INFO sqlalchemy.engine.base.Engine (46,)
2021-02-01 11:00:50,648 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,651 INFO sqlalchemy.engine.base.Engine (47,)
2021-02-01 11:00:50,653 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,655 INFO sqlalchemy.engine.base.Engine (48,)
2021-02-01 11:00:50,658 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,659 INFO sqlalchemy.engine.base.Engine (49,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:00:50,820 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:50,821 INFO sqlalchemy.engine.base.Engine ((50, 14.3, 14.3, 14.3, 152881.4470000254, 122588.10213904455), (51, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152881.4470000254, 122588.10213904455), (52, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152881.4470000254, 122588.10213904455), (53, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152881.4470000254, 122588.10213904455), (54, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152881.4470000254, 122588.10213904455), (55, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152881.4470000254, 122588.10213904455), (56, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152881.4470000254, 122588.10213904455), (57, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152881.4470000254, 122588.10213904455)  ... displaying 10 of 50 total bound parameter sets ...  (98, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152881.4470000254, 122588.10213904455), (99, 135.9, 135.9, 135.9, 152881.4470000254, 122588.10213904455))
2021-02-01 11:00:50,826 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:00:50,827 INFO sqlalchemy.engine.base.Engine ('F2',)
2021-02-01 11:00:50,834 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:50,836 INFO sqlalchemy.engine.base.Engine ((25, 'F2', 0, 'Anhydrite', 50, 51), (26, 'F2', 1, 'Sandstone, grey, vf-f', 52, 53), (27, 'F2', 2, 'Anhydrite', 54, 55), (28, 'F2', 3, 'Dolomite', 56, 57), (29, 'F2', 4, 'Anhydrite', 58, 59), (30, 'F2', 5, 'Sandstone, grey, vf-f', 60, 61), (31, 'F2', 6, 'Siltstone, red', 62, 63), (32, 'F2', 7, 'Dolomite', 64, 65)  ... displaying 10 of 25 total bound parameter sets ...  (48, 'F2', 23, 'Limestone', 96, 97), (49, 'F2', 24, 'Volcanic', 98, 99))
2021-02-01 11:00:50,840 INFO sqlalchemy.engine.base.Engine COMMIT

2021-02-01 11:00:50,949 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:00:50,951 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:00:50,953 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:50,956 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:00:50,956 INFO sqlalchemy.engine.base.Engine ('F2',)
2021-02-01 11:00:50,959 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,960 INFO sqlalchemy.engine.base.Engine (50,)
2021-02-01 11:00:50,962 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,963 INFO sqlalchemy.engine.base.Engine (51,)
2021-02-01 11:00:50,967 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,969 INFO sqlalchemy.engine.base.Engine (52,)
2021-02-01 11:00:50,971 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,972 INFO sqlalchemy.engine.base.Engine (53,)
2021-02-01 11:00:50,974 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,975 INFO sqlalchemy.engine.base.Engine (54,)
2021-02-01 11:00:50,977 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,977 INFO sqlalchemy.engine.base.Engine (55,)
2021-02-01 11:00:50,979 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,981 INFO sqlalchemy.engine.base.Engine (56,)
2021-02-01 11:00:50,982 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,983 INFO sqlalchemy.engine.base.Engine (57,)
2021-02-01 11:00:50,985 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,986 INFO sqlalchemy.engine.base.Engine (58,)
2021-02-01 11:00:50,988 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,989 INFO sqlalchemy.engine.base.Engine (59,)
2021-02-01 11:00:50,992 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,993 INFO sqlalchemy.engine.base.Engine (60,)
2021-02-01 11:00:50,995 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,996 INFO sqlalchemy.engine.base.Engine (61,)
2021-02-01 11:00:50,998 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:50,999 INFO sqlalchemy.engine.base.Engine (62,)
2021-02-01 11:00:51,001 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,002 INFO sqlalchemy.engine.base.Engine (63,)
2021-02-01 11:00:51,004 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,004 INFO sqlalchemy.engine.base.Engine (64,)
2021-02-01 11:00:51,006 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,007 INFO sqlalchemy.engine.base.Engine (65,)
2021-02-01 11:00:51,010 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,014 INFO sqlalchemy.engine.base.Engine (66,)
2021-02-01 11:00:51,020 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,021 INFO sqlalchemy.engine.base.Engine (67,)
2021-02-01 11:00:51,024 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,024 INFO sqlalchemy.engine.base.Engine (68,)

2021-02-01 11:00:51,027 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,028 INFO sqlalchemy.engine.base.Engine (69,)
2021-02-01 11:00:51,032 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,035 INFO sqlalchemy.engine.base.Engine (70,)
2021-02-01 11:00:51,037 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,038 INFO sqlalchemy.engine.base.Engine (71,)
2021-02-01 11:00:51,042 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,043 INFO sqlalchemy.engine.base.Engine (72,)
2021-02-01 11:00:51,044 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,045 INFO sqlalchemy.engine.base.Engine (73,)
2021-02-01 11:00:51,049 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,050 INFO sqlalchemy.engine.base.Engine (74,)
2021-02-01 11:00:51,052 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,055 INFO sqlalchemy.engine.base.Engine (75,)
2021-02-01 11:00:51,057 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,060 INFO sqlalchemy.engine.base.Engine (76,)
2021-02-01 11:00:51,061 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,062 INFO sqlalchemy.engine.base.Engine (77,)
2021-02-01 11:00:51,065 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,066 INFO sqlalchemy.engine.base.Engine (78,)
2021-02-01 11:00:51,068 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,069 INFO sqlalchemy.engine.base.Engine (79,)
2021-02-01 11:00:51,072 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,073 INFO sqlalchemy.engine.base.Engine (80,)
2021-02-01 11:00:51,075 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,076 INFO sqlalchemy.engine.base.Engine (81,)
2021-02-01 11:00:51,078 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,079 INFO sqlalchemy.engine.base.Engine (82,)
2021-02-01 11:00:51,082 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,084 INFO sqlalchemy.engine.base.Engine (83,)
2021-02-01 11:00:51,086 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,087 INFO sqlalchemy.engine.base.Engine (84,)
2021-02-01 11:00:51,089 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,090 INFO sqlalchemy.engine.base.Engine (85,)
2021-02-01 11:00:51,094 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,097 INFO sqlalchemy.engine.base.Engine (86,)
2021-02-01 11:00:51,099 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,100 INFO sqlalchemy.engine.base.Engine (87,)
2021-02-01 11:00:51,103 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,104 INFO sqlalchemy.engine.base.Engine (88,)
2021-02-01 11:00:51,106 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:51,108 INFO sqlalchemy.engine.base.Engine (89,)
2021-02-01 11:00:51,111 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,112 INFO sqlalchemy.engine.base.Engine (90,)
2021-02-01 11:00:51,116 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,117 INFO sqlalchemy.engine.base.Engine (91,)
2021-02-01 11:00:51,121 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,122 INFO sqlalchemy.engine.base.Engine (92,)
2021-02-01 11:00:51,124 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,125 INFO sqlalchemy.engine.base.Engine (93,)
2021-02-01 11:00:51,127 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,128 INFO sqlalchemy.engine.base.Engine (94,)
2021-02-01 11:00:51,130 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,132 INFO sqlalchemy.engine.base.Engine (95,)
2021-02-01 11:00:51,136 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,138 INFO sqlalchemy.engine.base.Engine (96,)
2021-02-01 11:00:51,140 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,141 INFO sqlalchemy.engine.base.Engine (97,)
2021-02-01 11:00:51,145 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,146 INFO sqlalchemy.engine.base.Engine (98,)
2021-02-01 11:00:51,150 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,151 INFO sqlalchemy.engine.base.Engine (99,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:00:51,288 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:00:51,290 INFO sqlalchemy.engine.base.Engine ('F3',)
2021-02-01 11:00:51,295 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:51,296 INFO sqlalchemy.engine.base.Engine ((100, 14.3, 14.3, 14.3, 152885.99500002534, 122587.1271390468), (101, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152885.99500002534, 122587.1271390468), (102, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152885.99500002534, 122587.1271390468), (103, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152885.99500002534, 122587.1271390468), (104, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152885.99500002534, 122587.1271390468), (105, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152885.99500002534, 122587.1271390468), (106, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152885.99500002534, 122587.1271390468), (107, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152885.99500002534, 122587.1271390468)  ... displaying 10 of 50 total bound parameter sets ...  (148, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152885.99500002534, 122587.1271390468), (149, 135.9, 135.9, 135.9, 152885.99500002534, 122587.1271390468))
2021-02-01 11:00:51,304 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:51,305 INFO sqlalchemy.engine.base.Engine ((50, 'F3', 0, 'Anhydrite', 100, 101), (51, 'F3', 1, 'Sandstone, grey, vf-f', 102, 103), (52, 'F3', 2, 'Anhydrite', 104, 105), (53, 'F3', 3, 'Dolomite', 106, 107), (54, 'F3', 4, 'Anhydrite', 108, 109), (55, 'F3', 5, 'Sandstone, grey, vf-f', 110, 111), (56, 'F3', 6, 'Siltstone, red', 112, 113), (57, 'F3', 7, 'Dolomite', 114, 115)  ... displaying 10 of 25 total bound parameter sets ...  (73, 'F3', 23, 'Limestone', 146, 147), (74, 'F3', 24, 'Volcanic', 148, 149))
2021-02-01 11:00:51,307 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:00:51,394 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:00:51,396 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:00:51,398 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:51,401 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:00:51,402 INFO sqlalchemy.engine.base.Engine ('F3',)
2021-02-01 11:00:51,404 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,406 INFO sqlalchemy.engine.base.Engine (100,)
2021-02-01 11:00:51,408 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,409 INFO sqlalchemy.engine.base.Engine (101,)
2021-02-01 11:00:51,411 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,413 INFO sqlalchemy.engine.base.Engine (102,)
2021-02-01 11:00:51,415 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:51,416 INFO sqlalchemy.engine.base.Engine (103,)
2021-02-01 11:00:51,421 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,422 INFO sqlalchemy.engine.base.Engine (104,)
2021-02-01 11:00:51,424 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,427 INFO sqlalchemy.engine.base.Engine (105,)
2021-02-01 11:00:51,429 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,430 INFO sqlalchemy.engine.base.Engine (106,)
2021-02-01 11:00:51,433 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,435 INFO sqlalchemy.engine.base.Engine (107,)
2021-02-01 11:00:51,437 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,438 INFO sqlalchemy.engine.base.Engine (108,)
2021-02-01 11:00:51,440 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,442 INFO sqlalchemy.engine.base.Engine (109,)
2021-02-01 11:00:51,444 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,445 INFO sqlalchemy.engine.base.Engine (110,)
2021-02-01 11:00:51,447 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,448 INFO sqlalchemy.engine.base.Engine (111,)
2021-02-01 11:00:51,450 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,451 INFO sqlalchemy.engine.base.Engine (112,)
2021-02-01 11:00:51,453 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,454 INFO sqlalchemy.engine.base.Engine (113,)
2021-02-01 11:00:51,456 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,457 INFO sqlalchemy.engine.base.Engine (114,)
2021-02-01 11:00:51,459 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,461 INFO sqlalchemy.engine.base.Engine (115,)
2021-02-01 11:00:51,467 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,468 INFO sqlalchemy.engine.base.Engine (116,)
2021-02-01 11:00:51,469 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,470 INFO sqlalchemy.engine.base.Engine (117,)
2021-02-01 11:00:51,472 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,473 INFO sqlalchemy.engine.base.Engine (118,)
2021-02-01 11:00:51,475 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,477 INFO sqlalchemy.engine.base.Engine (119,)
2021-02-01 11:00:51,483 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,484 INFO sqlalchemy.engine.base.Engine (120,)
2021-02-01 11:00:51,485 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,486 INFO sqlalchemy.engine.base.Engine (121,)
2021-02-01 11:00:51,487 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,488 INFO sqlalchemy.engine.base.Engine (122,)
2021-02-01 11:00:51,490 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,493 INFO sqlalchemy.engine.base.Engine (123,)
2021-02-01 11:00:51,500 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:51,501 INFO sqlalchemy.engine.base.Engine (124,)
2021-02-01 11:00:51,503 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,504 INFO sqlalchemy.engine.base.Engine (125,)
2021-02-01 11:00:51,506 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,507 INFO sqlalchemy.engine.base.Engine (126,)
2021-02-01 11:00:51,508 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,509 INFO sqlalchemy.engine.base.Engine (127,)
2021-02-01 11:00:51,514 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,515 INFO sqlalchemy.engine.base.Engine (128,)
2021-02-01 11:00:51,517 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,518 INFO sqlalchemy.engine.base.Engine (129,)
2021-02-01 11:00:51,521 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,521 INFO sqlalchemy.engine.base.Engine (130,)
2021-02-01 11:00:51,523 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,524 INFO sqlalchemy.engine.base.Engine (131,)
2021-02-01 11:00:51,527 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,530 INFO sqlalchemy.engine.base.Engine (132,)
2021-02-01 11:00:51,538 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,539 INFO sqlalchemy.engine.base.Engine (133,)
2021-02-01 11:00:51,541 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,543 INFO sqlalchemy.engine.base.Engine (134,)
2021-02-01 11:00:51,551 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,553 INFO sqlalchemy.engine.base.Engine (135,)
2021-02-01 11:00:51,556 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,557 INFO sqlalchemy.engine.base.Engine (136,)
2021-02-01 11:00:51,559 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,560 INFO sqlalchemy.engine.base.Engine (137,)
2021-02-01 11:00:51,563 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,564 INFO sqlalchemy.engine.base.Engine (138,)
2021-02-01 11:00:51,566 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,569 INFO sqlalchemy.engine.base.Engine (139,)
2021-02-01 11:00:51,572 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,573 INFO sqlalchemy.engine.base.Engine (140,)
2021-02-01 11:00:51,575 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,576 INFO sqlalchemy.engine.base.Engine (141,)
2021-02-01 11:00:51,580 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,581 INFO sqlalchemy.engine.base.Engine (142,)
2021-02-01 11:00:51,584 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,586 INFO sqlalchemy.engine.base.Engine (143,)
2021-02-01 11:00:51,589 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,590 INFO sqlalchemy.engine.base.Engine (144,)
2021-02-01 11:00:51,593 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:51,594 INFO sqlalchemy.engine.base.Engine (145,)
2021-02-01 11:00:51,596 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,598 INFO sqlalchemy.engine.base.Engine (146,)
2021-02-01 11:00:51,600 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,601 INFO sqlalchemy.engine.base.Engine (147,)
2021-02-01 11:00:51,604 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,605 INFO sqlalchemy.engine.base.Engine (148,)
2021-02-01 11:00:51,606 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,608 INFO sqlalchemy.engine.base.Engine (149,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:00:51,777 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:51,783 INFO sqlalchemy.engine.base.Engine ((150, 14.3, 14.3, 14.3, 152883.7680000254, 122589.75413904713), (151, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152883.7680000254, 122589.75413904713), (152, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152883.7680000254, 122589.75413904713), (153, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152883.7680000254, 122589.75413904713), (154, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152883.7680000254, 122589.75413904713), (155, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152883.7680000254, 122589.75413904713), (156, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152883.7680000254, 122589.75413904713), (157, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152883.7680000254, 122589.75413904713)  ... displaying 10 of 50 total bound parameter sets ...  (198, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152883.7680000254, 122589.75413904713), (199, 135.9, 135.9, 135.9, 152883.7680000254, 122589.75413904713))
2021-02-01 11:00:51,786 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:00:51,786 INFO sqlalchemy.engine.base.Engine ('F4',)
2021-02-01 11:00:51,789 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:51,791 INFO sqlalchemy.engine.base.Engine ((75, 'F4', 0, 'Anhydrite', 150, 151), (76, 'F4', 1, 'Sandstone, grey, vf-f', 152, 153), (77, 'F4', 2, 'Anhydrite', 154, 155), (78, 'F4', 3, 'Dolomite', 156, 157), (79, 'F4', 4, 'Anhydrite', 158, 159), (80, 'F4', 5, 'Sandstone, grey, vf-f', 160, 161), (81, 'F4', 6, 'Siltstone, red', 162, 163), (82, 'F4', 7, 'Dolomite', 164, 165)  ... displaying 10 of 25 total bound parameter sets ...  (98, 'F4', 23, 'Limestone', 196, 197), (99, 'F4', 24, 'Volcanic', 198, 199))
2021-02-01 11:00:51,793 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:00:51,901 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:00:51,902 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:00:51,903 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:51,905 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:00:51,907 INFO sqlalchemy.engine.base.Engine ('F4',)
2021-02-01 11:00:51,909 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,909 INFO sqlalchemy.engine.base.Engine (150,)
2021-02-01 11:00:51,911 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,912 INFO sqlalchemy.engine.base.Engine (151,)
2021-02-01 11:00:51,915 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,918 INFO sqlalchemy.engine.base.Engine (152,)
2021-02-01 11:00:51,922 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,923 INFO sqlalchemy.engine.base.Engine (153,)
2021-02-01 11:00:51,925 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,926 INFO sqlalchemy.engine.base.Engine (154,)
2021-02-01 11:00:51,928 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,929 INFO sqlalchemy.engine.base.Engine (155,)
2021-02-01 11:00:51,932 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,933 INFO sqlalchemy.engine.base.Engine (156,)
2021-02-01 11:00:51,938 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,938 INFO sqlalchemy.engine.base.Engine (157,)
2021-02-01 11:00:51,941 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,942 INFO sqlalchemy.engine.base.Engine (158,)
2021-02-01 11:00:51,944 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:51,945 INFO sqlalchemy.engine.base.Engine (159,)
2021-02-01 11:00:51,947 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,948 INFO sqlalchemy.engine.base.Engine (160,)
2021-02-01 11:00:51,957 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,958 INFO sqlalchemy.engine.base.Engine (161,)
2021-02-01 11:00:51,961 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,962 INFO sqlalchemy.engine.base.Engine (162,)
2021-02-01 11:00:51,964 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,965 INFO sqlalchemy.engine.base.Engine (163,)
2021-02-01 11:00:51,968 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,971 INFO sqlalchemy.engine.base.Engine (164,)
2021-02-01 11:00:51,975 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,976 INFO sqlalchemy.engine.base.Engine (165,)
2021-02-01 11:00:51,979 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,980 INFO sqlalchemy.engine.base.Engine (166,)
2021-02-01 11:00:51,982 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,985 INFO sqlalchemy.engine.base.Engine (167,)
2021-02-01 11:00:51,988 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,990 INFO sqlalchemy.engine.base.Engine (168,)
2021-02-01 11:00:51,992 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,994 INFO sqlalchemy.engine.base.Engine (169,)
2021-02-01 11:00:51,996 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:51,997 INFO sqlalchemy.engine.base.Engine (170,)
2021-02-01 11:00:52,000 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,001 INFO sqlalchemy.engine.base.Engine (171,)
2021-02-01 11:00:52,003 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,004 INFO sqlalchemy.engine.base.Engine (172,)
2021-02-01 11:00:52,007 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,009 INFO sqlalchemy.engine.base.Engine (173,)
2021-02-01 11:00:52,011 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,015 INFO sqlalchemy.engine.base.Engine (174,)
2021-02-01 11:00:52,018 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,020 INFO sqlalchemy.engine.base.Engine (175,)
2021-02-01 11:00:52,022 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,023 INFO sqlalchemy.engine.base.Engine (176,)
2021-02-01 11:00:52,026 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,027 INFO sqlalchemy.engine.base.Engine (177,)
2021-02-01 11:00:52,029 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,031 INFO sqlalchemy.engine.base.Engine (178,)
2021-02-01 11:00:52,033 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,033 INFO sqlalchemy.engine.base.Engine (179,)
2021-02-01 11:00:52,038 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:52,039 INFO sqlalchemy.engine.base.Engine (180,)
2021-02-01 11:00:52,042 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,043 INFO sqlalchemy.engine.base.Engine (181,)
2021-02-01 11:00:52,045 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,048 INFO sqlalchemy.engine.base.Engine (182,)
2021-02-01 11:00:52,050 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,051 INFO sqlalchemy.engine.base.Engine (183,)
2021-02-01 11:00:52,054 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,055 INFO sqlalchemy.engine.base.Engine (184,)
2021-02-01 11:00:52,059 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,060 INFO sqlalchemy.engine.base.Engine (185,)
2021-02-01 11:00:52,064 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,065 INFO sqlalchemy.engine.base.Engine (186,)
2021-02-01 11:00:52,067 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,068 INFO sqlalchemy.engine.base.Engine (187,)
2021-02-01 11:00:52,070 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,072 INFO sqlalchemy.engine.base.Engine (188,)
2021-02-01 11:00:52,075 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,076 INFO sqlalchemy.engine.base.Engine (189,)
2021-02-01 11:00:52,078 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,080 INFO sqlalchemy.engine.base.Engine (190,)
2021-02-01 11:00:52,082 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,084 INFO sqlalchemy.engine.base.Engine (191,)
2021-02-01 11:00:52,086 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,087 INFO sqlalchemy.engine.base.Engine (192,)
2021-02-01 11:00:52,088 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,094 INFO sqlalchemy.engine.base.Engine (193,)
2021-02-01 11:00:52,096 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,098 INFO sqlalchemy.engine.base.Engine (194,)
2021-02-01 11:00:52,100 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,101 INFO sqlalchemy.engine.base.Engine (195,)
2021-02-01 11:00:52,102 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,103 INFO sqlalchemy.engine.base.Engine (196,)
2021-02-01 11:00:52,105 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,106 INFO sqlalchemy.engine.base.Engine (197,)
2021-02-01 11:00:52,108 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,110 INFO sqlalchemy.engine.base.Engine (198,)
2021-02-01 11:00:52,117 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,118 INFO sqlalchemy.engine.base.Engine (199,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:00:52,236 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:00:52,237 INFO sqlalchemy.engine.base.Engine ('F5',)
2021-02-01 11:00:52,241 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:52,242 INFO sqlalchemy.engine.base.Engine ((200, 14.3, 14.3, 14.3, 152888.1280000254, 122588.43613904715), (201, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.1280000254, 122588.43613904715), (202, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.1280000254, 122588.43613904715), (203, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.1280000254, 122588.43613904715), (204, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.1280000254, 122588.43613904715), (205, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.1280000254, 122588.43613904715), (206, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.1280000254, 122588.43613904715), (207, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152888.1280000254, 122588.43613904715)  ... displaying 10 of 50 total bound parameter sets ...  (248, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152888.1280000254, 122588.43613904715), (249, 135.9, 135.9, 135.9, 152888.1280000254, 122588.43613904715))

2021-02-01 11:00:52,248 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:52,248 INFO sqlalchemy.engine.base.Engine ((100, 'F5', 0, 'Anhydrite', 200, 201), (101, 'F5', 1, 'Sandstone, grey, vf-f', 202, 203), (102, 'F5', 2, 'Anhydrite', 204, 205), (103, 'F5', 3, 'Dolomite', 206, 207), (104, 'F5', 4, 'Anhydrite', 208, 209), (105, 'F5', 5, 'Sandstone, grey, vf-f', 210, 211), (106, 'F5', 6, 'Siltstone, red', 212, 213), (107, 'F5', 7, 'Dolomite', 214, 215)  ... displaying 10 of 25 total bound parameter sets ...  (123, 'F5', 23, 'Limestone', 246, 247), (124, 'F5', 24, 'Volcanic', 248, 249))
2021-02-01 11:00:52,253 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:00:52,410 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:00:52,412 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:00:52,413 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:52,416 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:00:52,417 INFO sqlalchemy.engine.base.Engine ('F5',)
2021-02-01 11:00:52,421 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,422 INFO sqlalchemy.engine.base.Engine (200,)
2021-02-01 11:00:52,424 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,425 INFO sqlalchemy.engine.base.Engine (201,)
2021-02-01 11:00:52,428 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,429 INFO sqlalchemy.engine.base.Engine (202,)
2021-02-01 11:00:52,433 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,434 INFO sqlalchemy.engine.base.Engine (203,)
2021-02-01 11:00:52,436 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,439 INFO sqlalchemy.engine.base.Engine (204,)
2021-02-01 11:00:52,441 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,443 INFO sqlalchemy.engine.base.Engine (205,)
2021-02-01 11:00:52,449 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,450 INFO sqlalchemy.engine.base.Engine (206,)
2021-02-01 11:00:52,453 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,455 INFO sqlalchemy.engine.base.Engine (207,)
2021-02-01 11:00:52,458 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,460 INFO sqlalchemy.engine.base.Engine (208,)
2021-02-01 11:00:52,463 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,466 INFO sqlalchemy.engine.base.Engine (209,)
2021-02-01 11:00:52,471 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,473 INFO sqlalchemy.engine.base.Engine (210,)
2021-02-01 11:00:52,475 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,477 INFO sqlalchemy.engine.base.Engine (211,)
2021-02-01 11:00:52,479 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,482 INFO sqlalchemy.engine.base.Engine (212,)
2021-02-01 11:00:52,484 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,485 INFO sqlalchemy.engine.base.Engine (213,)
2021-02-01 11:00:52,487 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,488 INFO sqlalchemy.engine.base.Engine (214,)
2021-02-01 11:00:52,490 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,492 INFO sqlalchemy.engine.base.Engine (215,)
2021-02-01 11:00:52,494 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,495 INFO sqlalchemy.engine.base.Engine (216,)

2021-02-01 11:00:52,498 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,500 INFO sqlalchemy.engine.base.Engine (217,)
2021-02-01 11:00:52,507 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,508 INFO sqlalchemy.engine.base.Engine (218,)
2021-02-01 11:00:52,511 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,512 INFO sqlalchemy.engine.base.Engine (219,)
2021-02-01 11:00:52,514 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,515 INFO sqlalchemy.engine.base.Engine (220,)
2021-02-01 11:00:52,517 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,520 INFO sqlalchemy.engine.base.Engine (221,)
2021-02-01 11:00:52,522 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,523 INFO sqlalchemy.engine.base.Engine (222,)
2021-02-01 11:00:52,527 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,528 INFO sqlalchemy.engine.base.Engine (223,)
2021-02-01 11:00:52,532 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,534 INFO sqlalchemy.engine.base.Engine (224,)
2021-02-01 11:00:52,536 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,537 INFO sqlalchemy.engine.base.Engine (225,)
2021-02-01 11:00:52,539 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,542 INFO sqlalchemy.engine.base.Engine (226,)
2021-02-01 11:00:52,545 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,548 INFO sqlalchemy.engine.base.Engine (227,)
2021-02-01 11:00:52,552 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,553 INFO sqlalchemy.engine.base.Engine (228,)
2021-02-01 11:00:52,555 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,556 INFO sqlalchemy.engine.base.Engine (229,)
2021-02-01 11:00:52,558 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,559 INFO sqlalchemy.engine.base.Engine (230,)
2021-02-01 11:00:52,562 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,564 INFO sqlalchemy.engine.base.Engine (231,)
2021-02-01 11:00:52,570 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,572 INFO sqlalchemy.engine.base.Engine (232,)
2021-02-01 11:00:52,574 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,575 INFO sqlalchemy.engine.base.Engine (233,)
2021-02-01 11:00:52,579 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,580 INFO sqlalchemy.engine.base.Engine (234,)
2021-02-01 11:00:52,582 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,583 INFO sqlalchemy.engine.base.Engine (235,)
2021-02-01 11:00:52,588 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,591 INFO sqlalchemy.engine.base.Engine (236,)
2021-02-01 11:00:52,594 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:52,596 INFO sqlalchemy.engine.base.Engine (237,)
2021-02-01 11:00:52,599 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,600 INFO sqlalchemy.engine.base.Engine (238,)
2021-02-01 11:00:52,602 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,604 INFO sqlalchemy.engine.base.Engine (239,)
2021-02-01 11:00:52,610 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,611 INFO sqlalchemy.engine.base.Engine (240,)
2021-02-01 11:00:52,613 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,614 INFO sqlalchemy.engine.base.Engine (241,)
2021-02-01 11:00:52,618 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,622 INFO sqlalchemy.engine.base.Engine (242,)
2021-02-01 11:00:52,624 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,626 INFO sqlalchemy.engine.base.Engine (243,)
2021-02-01 11:00:52,628 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,630 INFO sqlalchemy.engine.base.Engine (244,)
2021-02-01 11:00:52,634 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,635 INFO sqlalchemy.engine.base.Engine (245,)
2021-02-01 11:00:52,637 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,638 INFO sqlalchemy.engine.base.Engine (246,)
2021-02-01 11:00:52,641 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,642 INFO sqlalchemy.engine.base.Engine (247,)
2021-02-01 11:00:52,646 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,648 INFO sqlalchemy.engine.base.Engine (248,)
2021-02-01 11:00:52,650 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,654 INFO sqlalchemy.engine.base.Engine (249,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:00:52,783 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:52,784 INFO sqlalchemy.engine.base.Engine ((250, 14.3, 14.3, 14.3, 152886.2260000254, 122591.65513904672), (251, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152886.2260000254, 122591.65513904672), (252, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152886.2260000254, 122591.65513904672), (253, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152886.2260000254, 122591.65513904672), (254, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152886.2260000254, 122591.65513904672), (255, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152886.2260000254, 122591.65513904672), (256, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152886.2260000254, 122591.65513904672), (257, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152886.2260000254, 122591.65513904672)  ... displaying 10 of 50 total bound parameter sets ...  (298, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152886.2260000254, 122591.65513904672), (299, 135.9, 135.9, 135.9, 152886.2260000254, 122591.65513904672))
2021-02-01 11:00:52,787 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:00:52,788 INFO sqlalchemy.engine.base.Engine ('F6',)
2021-02-01 11:00:52,794 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:52,795 INFO sqlalchemy.engine.base.Engine ((125, 'F6', 0, 'Anhydrite', 250, 251), (126, 'F6', 1, 'Sandstone, grey, vf-f', 252, 253), (127, 'F6', 2, 'Anhydrite', 254, 255), (128, 'F6', 3, 'Dolomite', 256, 257), (129, 'F6', 4, 'Anhydrite', 258, 259), (130, 'F6', 5, 'Sandstone, grey, vf-f', 260, 261), (131, 'F6', 6, 'Siltstone, red', 262, 263), (132, 'F6', 7, 'Dolomite', 264, 265)  ... displaying 10 of 25 total bound parameter sets ...  (148, 'F6', 23, 'Limestone', 296, 297), (149, 'F6', 24, 'Volcanic', 298, 299))
2021-02-01 11:00:52,799 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:00:52,879 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:00:52,880 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:00:52,882 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:52,885 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:00:52,886 INFO sqlalchemy.engine.base.Engine ('F6',)
2021-02-01 11:00:52,889 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,891 INFO sqlalchemy.engine.base.Engine (250,)
2021-02-01 11:00:52,895 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:52,896 INFO sqlalchemy.engine.base.Engine (251,)
2021-02-01 11:00:52,898 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,899 INFO sqlalchemy.engine.base.Engine (252,)
2021-02-01 11:00:52,902 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,903 INFO sqlalchemy.engine.base.Engine (253,)
2021-02-01 11:00:52,907 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,908 INFO sqlalchemy.engine.base.Engine (254,)
2021-02-01 11:00:52,910 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,912 INFO sqlalchemy.engine.base.Engine (255,)
2021-02-01 11:00:52,917 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,918 INFO sqlalchemy.engine.base.Engine (256,)
2021-02-01 11:00:52,921 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,922 INFO sqlalchemy.engine.base.Engine (257,)
2021-02-01 11:00:52,925 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,926 INFO sqlalchemy.engine.base.Engine (258,)
2021-02-01 11:00:52,929 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,930 INFO sqlalchemy.engine.base.Engine (259,)
2021-02-01 11:00:52,934 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,935 INFO sqlalchemy.engine.base.Engine (260,)
2021-02-01 11:00:52,938 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,940 INFO sqlalchemy.engine.base.Engine (261,)
2021-02-01 11:00:52,942 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,944 INFO sqlalchemy.engine.base.Engine (262,)
2021-02-01 11:00:52,948 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,950 INFO sqlalchemy.engine.base.Engine (263,)
2021-02-01 11:00:52,952 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,956 INFO sqlalchemy.engine.base.Engine (264,)
2021-02-01 11:00:52,960 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,961 INFO sqlalchemy.engine.base.Engine (265,)
2021-02-01 11:00:52,963 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,964 INFO sqlalchemy.engine.base.Engine (266,)
2021-02-01 11:00:52,969 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,970 INFO sqlalchemy.engine.base.Engine (267,)
2021-02-01 11:00:52,972 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,973 INFO sqlalchemy.engine.base.Engine (268,)
2021-02-01 11:00:52,975 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,977 INFO sqlalchemy.engine.base.Engine (269,)
2021-02-01 11:00:52,980 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,984 INFO sqlalchemy.engine.base.Engine (270,)
2021-02-01 11:00:52,988 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,989 INFO sqlalchemy.engine.base.Engine (271,)
2021-02-01 11:00:52,992 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:52,993 INFO sqlalchemy.engine.base.Engine (272,)
2021-02-01 11:00:52,996 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:52,998 INFO sqlalchemy.engine.base.Engine (273,)
2021-02-01 11:00:53,002 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,002 INFO sqlalchemy.engine.base.Engine (274,)
2021-02-01 11:00:53,005 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,006 INFO sqlalchemy.engine.base.Engine (275,)
2021-02-01 11:00:53,009 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,011 INFO sqlalchemy.engine.base.Engine (276,)
2021-02-01 11:00:53,013 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,015 INFO sqlalchemy.engine.base.Engine (277,)
2021-02-01 11:00:53,017 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,019 INFO sqlalchemy.engine.base.Engine (278,)
2021-02-01 11:00:53,021 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,022 INFO sqlalchemy.engine.base.Engine (279,)
2021-02-01 11:00:53,025 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,026 INFO sqlalchemy.engine.base.Engine (280,)
2021-02-01 11:00:53,033 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,037 INFO sqlalchemy.engine.base.Engine (281,)
2021-02-01 11:00:53,040 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,042 INFO sqlalchemy.engine.base.Engine (282,)
2021-02-01 11:00:53,044 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,047 INFO sqlalchemy.engine.base.Engine (283,)
2021-02-01 11:00:53,049 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,050 INFO sqlalchemy.engine.base.Engine (284,)
2021-02-01 11:00:53,056 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,057 INFO sqlalchemy.engine.base.Engine (285,)
2021-02-01 11:00:53,061 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,062 INFO sqlalchemy.engine.base.Engine (286,)
2021-02-01 11:00:53,065 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,067 INFO sqlalchemy.engine.base.Engine (287,)
2021-02-01 11:00:53,070 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,071 INFO sqlalchemy.engine.base.Engine (288,)
2021-02-01 11:00:53,073 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,075 INFO sqlalchemy.engine.base.Engine (289,)
2021-02-01 11:00:53,080 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,082 INFO sqlalchemy.engine.base.Engine (290,)
2021-02-01 11:00:53,083 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,085 INFO sqlalchemy.engine.base.Engine (291,)
2021-02-01 11:00:53,087 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,089 INFO sqlalchemy.engine.base.Engine (292,)
2021-02-01 11:00:53,091 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:53,092 INFO sqlalchemy.engine.base.Engine (293,)
2021-02-01 11:00:53,095 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,097 INFO sqlalchemy.engine.base.Engine (294,)
2021-02-01 11:00:53,100 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,103 INFO sqlalchemy.engine.base.Engine (295,)
2021-02-01 11:00:53,106 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,107 INFO sqlalchemy.engine.base.Engine (296,)
2021-02-01 11:00:53,109 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,110 INFO sqlalchemy.engine.base.Engine (297,)
2021-02-01 11:00:53,112 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,116 INFO sqlalchemy.engine.base.Engine (298,)
2021-02-01 11:00:53,120 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,121 INFO sqlalchemy.engine.base.Engine (299,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:00:53,245 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:53,248 INFO sqlalchemy.engine.base.Engine ((300, 14.3, 14.3, 14.3, 152880.9800000254, 122583.69313904645), (301, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152880.9800000254, 122583.69313904645), (302, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152880.9800000254, 122583.69313904645), (303, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152880.9800000254, 122583.69313904645), (304, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152880.9800000254, 122583.69313904645), (305, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152880.9800000254, 122583.69313904645), (306, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152880.9800000254, 122583.69313904645), (307, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152880.9800000254, 122583.69313904645)  ... displaying 10 of 50 total bound parameter sets ...  (348, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152880.9800000254, 122583.69313904645), (349, 135.9, 135.9, 135.9, 152880.9800000254, 122583.69313904645))
2021-02-01 11:00:53,251 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:00:53,253 INFO sqlalchemy.engine.base.Engine ('F7',)
2021-02-01 11:00:53,257 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:53,259 INFO sqlalchemy.engine.base.Engine ((150, 'F7', 0, 'Anhydrite', 300, 301), (151, 'F7', 1, 'Sandstone, grey, vf-f', 302, 303), (152, 'F7', 2, 'Anhydrite', 304, 305), (153, 'F7', 3, 'Dolomite', 306, 307), (154, 'F7', 4, 'Anhydrite', 308, 309), (155, 'F7', 5, 'Sandstone, grey, vf-f', 310, 311), (156, 'F7', 6, 'Siltstone, red', 312, 313), (157, 'F7', 7, 'Dolomite', 314, 315)  ... displaying 10 of 25 total bound parameter sets ...  (173, 'F7', 23, 'Limestone', 346, 347), (174, 'F7', 24, 'Volcanic', 348, 349))
2021-02-01 11:00:53,263 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:00:53,370 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:00:53,371 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:00:53,373 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:53,375 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:00:53,376 INFO sqlalchemy.engine.base.Engine ('F7',)
2021-02-01 11:00:53,379 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,381 INFO sqlalchemy.engine.base.Engine (300,)
2021-02-01 11:00:53,383 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,384 INFO sqlalchemy.engine.base.Engine (301,)
2021-02-01 11:00:53,386 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,388 INFO sqlalchemy.engine.base.Engine (302,)
2021-02-01 11:00:53,390 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,391 INFO sqlalchemy.engine.base.Engine (303,)
2021-02-01 11:00:53,396 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,398 INFO sqlalchemy.engine.base.Engine (304,)
2021-02-01 11:00:53,400 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,401 INFO sqlalchemy.engine.base.Engine (305,)
2021-02-01 11:00:53,404 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,405 INFO sqlalchemy.engine.base.Engine (306,)
2021-02-01 11:00:53,407 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:53,410 INFO sqlalchemy.engine.base.Engine (307,)
2021-02-01 11:00:53,414 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,415 INFO sqlalchemy.engine.base.Engine (308,)
2021-02-01 11:00:53,418 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,419 INFO sqlalchemy.engine.base.Engine (309,)
2021-02-01 11:00:53,423 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,427 INFO sqlalchemy.engine.base.Engine (310,)
2021-02-01 11:00:53,429 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,430 INFO sqlalchemy.engine.base.Engine (311,)
2021-02-01 11:00:53,432 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,433 INFO sqlalchemy.engine.base.Engine (312,)
2021-02-01 11:00:53,435 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,435 INFO sqlalchemy.engine.base.Engine (313,)
2021-02-01 11:00:53,437 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,438 INFO sqlalchemy.engine.base.Engine (314,)
2021-02-01 11:00:53,439 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,441 INFO sqlalchemy.engine.base.Engine (315,)
2021-02-01 11:00:53,444 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,447 INFO sqlalchemy.engine.base.Engine (316,)
2021-02-01 11:00:53,449 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,450 INFO sqlalchemy.engine.base.Engine (317,)
2021-02-01 11:00:53,455 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,457 INFO sqlalchemy.engine.base.Engine (318,)
2021-02-01 11:00:53,460 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,461 INFO sqlalchemy.engine.base.Engine (319,)
2021-02-01 11:00:53,466 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,467 INFO sqlalchemy.engine.base.Engine (320,)
2021-02-01 11:00:53,469 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,471 INFO sqlalchemy.engine.base.Engine (321,)
2021-02-01 11:00:53,477 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,478 INFO sqlalchemy.engine.base.Engine (322,)
2021-02-01 11:00:53,481 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,482 INFO sqlalchemy.engine.base.Engine (323,)
2021-02-01 11:00:53,487 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,488 INFO sqlalchemy.engine.base.Engine (324,)
2021-02-01 11:00:53,491 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,492 INFO sqlalchemy.engine.base.Engine (325,)
2021-02-01 11:00:53,496 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,497 INFO sqlalchemy.engine.base.Engine (326,)
2021-02-01 11:00:53,499 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,500 INFO sqlalchemy.engine.base.Engine (327,)
2021-02-01 11:00:53,502 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:53,504 INFO sqlalchemy.engine.base.Engine (328,)
2021-02-01 11:00:53,506 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,507 INFO sqlalchemy.engine.base.Engine (329,)
2021-02-01 11:00:53,509 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,510 INFO sqlalchemy.engine.base.Engine (330,)
2021-02-01 11:00:53,514 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,515 INFO sqlalchemy.engine.base.Engine (331,)
2021-02-01 11:00:53,517 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,518 INFO sqlalchemy.engine.base.Engine (332,)
2021-02-01 11:00:53,520 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,521 INFO sqlalchemy.engine.base.Engine (333,)
2021-02-01 11:00:53,525 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,526 INFO sqlalchemy.engine.base.Engine (334,)
2021-02-01 11:00:53,528 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,529 INFO sqlalchemy.engine.base.Engine (335,)
2021-02-01 11:00:53,531 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,534 INFO sqlalchemy.engine.base.Engine (336,)
2021-02-01 11:00:53,537 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,539 INFO sqlalchemy.engine.base.Engine (337,)
2021-02-01 11:00:53,543 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,547 INFO sqlalchemy.engine.base.Engine (338,)
2021-02-01 11:00:53,549 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,551 INFO sqlalchemy.engine.base.Engine (339,)
2021-02-01 11:00:53,553 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,555 INFO sqlalchemy.engine.base.Engine (340,)
2021-02-01 11:00:53,558 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,560 INFO sqlalchemy.engine.base.Engine (341,)
2021-02-01 11:00:53,561 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,563 INFO sqlalchemy.engine.base.Engine (342,)
2021-02-01 11:00:53,566 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,567 INFO sqlalchemy.engine.base.Engine (343,)
2021-02-01 11:00:53,571 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,572 INFO sqlalchemy.engine.base.Engine (344,)
2021-02-01 11:00:53,575 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,576 INFO sqlalchemy.engine.base.Engine (345,)
2021-02-01 11:00:53,580 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,584 INFO sqlalchemy.engine.base.Engine (346,)
2021-02-01 11:00:53,586 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,588 INFO sqlalchemy.engine.base.Engine (347,)
2021-02-01 11:00:53,591 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,592 INFO sqlalchemy.engine.base.Engine (348,)
2021-02-01 11:00:53,595 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:53,596 INFO sqlalchemy.engine.base.Engine (349,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:00:53,742 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:53,743 INFO sqlalchemy.engine.base.Engine ((350, 14.3, 14.3, 14.3, 152883.65800002535, 122585.62313904893), (351, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152883.65800002535, 122585.62313904893), (352, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152883.65800002535, 122585.62313904893), (353, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152883.65800002535, 122585.62313904893), (354, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152883.65800002535, 122585.62313904893), (355, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152883.65800002535, 122585.62313904893), (356, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152883.65800002535, 122585.62313904893), (357, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152883.65800002535, 122585.62313904893)  ... displaying 10 of 50 total bound parameter sets ...  (398, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152883.65800002535, 122585.62313904893), (399, 135.9, 135.9, 135.9, 152883.65800002535, 122585.62313904893))
2021-02-01 11:00:53,750 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:00:53,751 INFO sqlalchemy.engine.base.Engine ('F8',)
2021-02-01 11:00:53,755 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:53,759 INFO sqlalchemy.engine.base.Engine ((175, 'F8', 0, 'Anhydrite', 350, 351), (176, 'F8', 1, 'Sandstone, grey, vf-f', 352, 353), (177, 'F8', 2, 'Anhydrite', 354, 355), (178, 'F8', 3, 'Dolomite', 356, 357), (179, 'F8', 4, 'Anhydrite', 358, 359), (180, 'F8', 5, 'Sandstone, grey, vf-f', 360, 361), (181, 'F8', 6, 'Siltstone, red', 362, 363), (182, 'F8', 7, 'Dolomite', 364, 365)  ... displaying 10 of 25 total bound parameter sets ...  (198, 'F8', 23, 'Limestone', 396, 397), (199, 'F8', 24, 'Volcanic', 398, 399))
2021-02-01 11:00:53,768 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:00:53,896 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:00:53,897 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:00:53,898 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:53,900 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:00:53,901 INFO sqlalchemy.engine.base.Engine ('F8',)
2021-02-01 11:00:53,904 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,905 INFO sqlalchemy.engine.base.Engine (350,)
2021-02-01 11:00:53,908 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,909 INFO sqlalchemy.engine.base.Engine (351,)
2021-02-01 11:00:53,910 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,912 INFO sqlalchemy.engine.base.Engine (352,)
2021-02-01 11:00:53,913 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,914 INFO sqlalchemy.engine.base.Engine (353,)
2021-02-01 11:00:53,917 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,918 INFO sqlalchemy.engine.base.Engine (354,)
2021-02-01 11:00:53,920 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,920 INFO sqlalchemy.engine.base.Engine (355,)
2021-02-01 11:00:53,923 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,924 INFO sqlalchemy.engine.base.Engine (356,)
2021-02-01 11:00:53,926 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,927 INFO sqlalchemy.engine.base.Engine (357,)
2021-02-01 11:00:53,928 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,929 INFO sqlalchemy.engine.base.Engine (358,)
2021-02-01 11:00:53,931 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,932 INFO sqlalchemy.engine.base.Engine (359,)
2021-02-01 11:00:53,934 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,936 INFO sqlalchemy.engine.base.Engine (360,)
2021-02-01 11:00:53,938 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,939 INFO sqlalchemy.engine.base.Engine (361,)
2021-02-01 11:00:53,941 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,942 INFO sqlalchemy.engine.base.Engine (362,)
2021-02-01 11:00:53,944 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:53,945 INFO sqlalchemy.engine.base.Engine (363,)
2021-02-01 11:00:53,947 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,949 INFO sqlalchemy.engine.base.Engine (364,)
2021-02-01 11:00:53,951 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,952 INFO sqlalchemy.engine.base.Engine (365,)
2021-02-01 11:00:53,956 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,957 INFO sqlalchemy.engine.base.Engine (366,)
2021-02-01 11:00:53,959 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,960 INFO sqlalchemy.engine.base.Engine (367,)
2021-02-01 11:00:53,963 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,966 INFO sqlalchemy.engine.base.Engine (368,)
2021-02-01 11:00:53,969 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,972 INFO sqlalchemy.engine.base.Engine (369,)
2021-02-01 11:00:53,975 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,977 INFO sqlalchemy.engine.base.Engine (370,)
2021-02-01 11:00:53,979 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,980 INFO sqlalchemy.engine.base.Engine (371,)
2021-02-01 11:00:53,984 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,986 INFO sqlalchemy.engine.base.Engine (372,)
2021-02-01 11:00:53,989 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,990 INFO sqlalchemy.engine.base.Engine (373,)
2021-02-01 11:00:53,994 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,996 INFO sqlalchemy.engine.base.Engine (374,)
2021-02-01 11:00:53,998 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:53,999 INFO sqlalchemy.engine.base.Engine (375,)
2021-02-01 11:00:54,001 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,002 INFO sqlalchemy.engine.base.Engine (376,)
2021-02-01 11:00:54,004 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,005 INFO sqlalchemy.engine.base.Engine (377,)
2021-02-01 11:00:54,008 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,010 INFO sqlalchemy.engine.base.Engine (378,)
2021-02-01 11:00:54,011 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,012 INFO sqlalchemy.engine.base.Engine (379,)
2021-02-01 11:00:54,014 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,015 INFO sqlalchemy.engine.base.Engine (380,)
2021-02-01 11:00:54,017 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,018 INFO sqlalchemy.engine.base.Engine (381,)
2021-02-01 11:00:54,023 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,023 INFO sqlalchemy.engine.base.Engine (382,)
2021-02-01 11:00:54,026 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,030 INFO sqlalchemy.engine.base.Engine (383,)
2021-02-01 11:00:54,032 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:54,033 INFO sqlalchemy.engine.base.Engine (384,)
2021-02-01 11:00:54,036 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,037 INFO sqlalchemy.engine.base.Engine (385,)
2021-02-01 11:00:54,042 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,043 INFO sqlalchemy.engine.base.Engine (386,)
2021-02-01 11:00:54,046 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,049 INFO sqlalchemy.engine.base.Engine (387,)
2021-02-01 11:00:54,053 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,054 INFO sqlalchemy.engine.base.Engine (388,)
2021-02-01 11:00:54,057 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,058 INFO sqlalchemy.engine.base.Engine (389,)
2021-02-01 11:00:54,060 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,061 INFO sqlalchemy.engine.base.Engine (390,)
2021-02-01 11:00:54,064 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,065 INFO sqlalchemy.engine.base.Engine (391,)
2021-02-01 11:00:54,068 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,070 INFO sqlalchemy.engine.base.Engine (392,)
2021-02-01 11:00:54,072 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,073 INFO sqlalchemy.engine.base.Engine (393,)
2021-02-01 11:00:54,075 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,076 INFO sqlalchemy.engine.base.Engine (394,)
2021-02-01 11:00:54,078 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,079 INFO sqlalchemy.engine.base.Engine (395,)
2021-02-01 11:00:54,081 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,082 INFO sqlalchemy.engine.base.Engine (396,)
2021-02-01 11:00:54,084 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,085 INFO sqlalchemy.engine.base.Engine (397,)
2021-02-01 11:00:54,088 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,089 INFO sqlalchemy.engine.base.Engine (398,)
2021-02-01 11:00:54,090 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,097 INFO sqlalchemy.engine.base.Engine (399,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:00:54,220 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:00:54,222 INFO sqlalchemy.engine.base.Engine ('F9',)
2021-02-01 11:00:54,226 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:54,227 INFO sqlalchemy.engine.base.Engine ((400, 14.3, 14.3, 14.3, 152889.15200002538, 122587.1761390483), (401, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152889.15200002538, 122587.1761390483), (402, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152889.15200002538, 122587.1761390483), (403, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152889.15200002538, 122587.1761390483), (404, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152889.15200002538, 122587.1761390483), (405, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152889.15200002538, 122587.1761390483), (406, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152889.15200002538, 122587.1761390483), (407, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152889.15200002538, 122587.1761390483)  ... displaying 10 of 50 total bound parameter sets ...  (448, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152889.15200002538, 122587.1761390483), (449, 135.9, 135.9, 135.9, 152889.15200002538, 122587.1761390483))
2021-02-01 11:00:54,235 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:54,237 INFO sqlalchemy.engine.base.Engine ((200, 'F9', 0, 'Anhydrite', 400, 401), (201, 'F9', 1, 'Sandstone, grey, vf-f', 402, 403), (202, 'F9', 2, 'Anhydrite', 404, 405), (203, 'F9', 3, 'Dolomite', 406, 407), (204, 'F9', 4, 'Anhydrite', 408, 409), (205, 'F9', 5, 'Sandstone, grey, vf-f', 410, 411), (206, 'F9', 6, 'Siltstone, red', 412, 413), (207, 'F9', 7, 'Dolomite', 414, 415)  ... displaying 10 of 25 total bound parameter sets ...  (223, 'F9', 23, 'Limestone', 446, 447), (224, 'F9', 24, 'Volcanic', 448, 449))
2021-02-01 11:00:54,239 INFO sqlalchemy.engine.base.Engine COMMIT

2021-02-01 11:00:54,346 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:00:54,348 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:00:54,351 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:54,355 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:00:54,358 INFO sqlalchemy.engine.base.Engine ('F9',)
2021-02-01 11:00:54,362 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,363 INFO sqlalchemy.engine.base.Engine (400,)
2021-02-01 11:00:54,365 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,367 INFO sqlalchemy.engine.base.Engine (401,)
2021-02-01 11:00:54,370 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,373 INFO sqlalchemy.engine.base.Engine (402,)
2021-02-01 11:00:54,375 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,376 INFO sqlalchemy.engine.base.Engine (403,)
2021-02-01 11:00:54,378 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,379 INFO sqlalchemy.engine.base.Engine (404,)
2021-02-01 11:00:54,383 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,384 INFO sqlalchemy.engine.base.Engine (405,)
2021-02-01 11:00:54,386 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,387 INFO sqlalchemy.engine.base.Engine (406,)
2021-02-01 11:00:54,389 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,391 INFO sqlalchemy.engine.base.Engine (407,)
2021-02-01 11:00:54,394 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,395 INFO sqlalchemy.engine.base.Engine (408,)
2021-02-01 11:00:54,397 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,399 INFO sqlalchemy.engine.base.Engine (409,)
2021-02-01 11:00:54,401 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,403 INFO sqlalchemy.engine.base.Engine (410,)
2021-02-01 11:00:54,409 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,410 INFO sqlalchemy.engine.base.Engine (411,)
2021-02-01 11:00:54,413 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,414 INFO sqlalchemy.engine.base.Engine (412,)
2021-02-01 11:00:54,416 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,417 INFO sqlalchemy.engine.base.Engine (413,)
2021-02-01 11:00:54,420 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,422 INFO sqlalchemy.engine.base.Engine (414,)
2021-02-01 11:00:54,424 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,424 INFO sqlalchemy.engine.base.Engine (415,)
2021-02-01 11:00:54,427 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,428 INFO sqlalchemy.engine.base.Engine (416,)
2021-02-01 11:00:54,431 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,437 INFO sqlalchemy.engine.base.Engine (417,)
2021-02-01 11:00:54,439 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,442 INFO sqlalchemy.engine.base.Engine (418,)

2021-02-01 11:00:54,444 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,445 INFO sqlalchemy.engine.base.Engine (419,)
2021-02-01 11:00:54,448 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,449 INFO sqlalchemy.engine.base.Engine (420,)
2021-02-01 11:00:54,451 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,452 INFO sqlalchemy.engine.base.Engine (421,)
2021-02-01 11:00:54,458 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,460 INFO sqlalchemy.engine.base.Engine (422,)
2021-02-01 11:00:54,462 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,465 INFO sqlalchemy.engine.base.Engine (423,)
2021-02-01 11:00:54,467 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,468 INFO sqlalchemy.engine.base.Engine (424,)
2021-02-01 11:00:54,471 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,472 INFO sqlalchemy.engine.base.Engine (425,)
2021-02-01 11:00:54,475 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,476 INFO sqlalchemy.engine.base.Engine (426,)
2021-02-01 11:00:54,479 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,480 INFO sqlalchemy.engine.base.Engine (427,)
2021-02-01 11:00:54,483 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,484 INFO sqlalchemy.engine.base.Engine (428,)
2021-02-01 11:00:54,486 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,488 INFO sqlalchemy.engine.base.Engine (429,)
2021-02-01 11:00:54,493 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,494 INFO sqlalchemy.engine.base.Engine (430,)
2021-02-01 11:00:54,496 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,498 INFO sqlalchemy.engine.base.Engine (431,)
2021-02-01 11:00:54,502 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,507 INFO sqlalchemy.engine.base.Engine (432,)
2021-02-01 11:00:54,510 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,511 INFO sqlalchemy.engine.base.Engine (433,)
2021-02-01 11:00:54,514 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,515 INFO sqlalchemy.engine.base.Engine (434,)
2021-02-01 11:00:54,519 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,520 INFO sqlalchemy.engine.base.Engine (435,)
2021-02-01 11:00:54,522 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,529 INFO sqlalchemy.engine.base.Engine (436,)
2021-02-01 11:00:54,532 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,534 INFO sqlalchemy.engine.base.Engine (437,)
2021-02-01 11:00:54,536 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,538 INFO sqlalchemy.engine.base.Engine (438,)
2021-02-01 11:00:54,539 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:54,541 INFO sqlalchemy.engine.base.Engine (439,)
2021-02-01 11:00:54,543 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,544 INFO sqlalchemy.engine.base.Engine (440,)
2021-02-01 11:00:54,548 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,552 INFO sqlalchemy.engine.base.Engine (441,)
2021-02-01 11:00:54,554 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,557 INFO sqlalchemy.engine.base.Engine (442,)
2021-02-01 11:00:54,562 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,565 INFO sqlalchemy.engine.base.Engine (443,)
2021-02-01 11:00:54,567 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,569 INFO sqlalchemy.engine.base.Engine (444,)
2021-02-01 11:00:54,571 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,572 INFO sqlalchemy.engine.base.Engine (445,)
2021-02-01 11:00:54,574 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,576 INFO sqlalchemy.engine.base.Engine (446,)
2021-02-01 11:00:54,582 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,586 INFO sqlalchemy.engine.base.Engine (447,)
2021-02-01 11:00:54,588 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,590 INFO sqlalchemy.engine.base.Engine (448,)
2021-02-01 11:00:54,592 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,593 INFO sqlalchemy.engine.base.Engine (449,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:00:54,729 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:00:54,731 INFO sqlalchemy.engine.base.Engine ('F10',)
2021-02-01 11:00:54,736 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:54,737 INFO sqlalchemy.engine.base.Engine ((450, 14.3, 14.3, 14.3, 152883.43300002534, 122588.32313904725), (451, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152883.43300002534, 122588.32313904725), (452, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152883.43300002534, 122588.32313904725), (453, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152883.43300002534, 122588.32313904725), (454, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152883.43300002534, 122588.32313904725), (455, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152883.43300002534, 122588.32313904725), (456, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152883.43300002534, 122588.32313904725), (457, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152883.43300002534, 122588.32313904725)  ... displaying 10 of 50 total bound parameter sets ...  (498, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152883.43300002534, 122588.32313904725), (499, 135.9, 135.9, 135.9, 152883.43300002534, 122588.32313904725))
2021-02-01 11:00:54,747 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:54,748 INFO sqlalchemy.engine.base.Engine ((225, 'F10', 0, 'Anhydrite', 450, 451), (226, 'F10', 1, 'Sandstone, grey, vf-f', 452, 453), (227, 'F10', 2, 'Anhydrite', 454, 455), (228, 'F10', 3, 'Dolomite', 456, 457), (229, 'F10', 4, 'Anhydrite', 458, 459), (230, 'F10', 5, 'Sandstone, grey, vf-f', 460, 461), (231, 'F10', 6, 'Siltstone, red', 462, 463), (232, 'F10', 7, 'Dolomite', 464, 465)  ... displaying 10 of 25 total bound parameter sets ...  (248, 'F10', 23, 'Limestone', 496, 497), (249, 'F10', 24, 'Volcanic', 498, 499))
2021-02-01 11:00:54,750 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:00:54,834 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:00:54,835 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:00:54,836 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:54,839 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:00:54,840 INFO sqlalchemy.engine.base.Engine ('F10',)
2021-02-01 11:00:54,844 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,846 INFO sqlalchemy.engine.base.Engine (450,)
2021-02-01 11:00:54,850 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,851 INFO sqlalchemy.engine.base.Engine (451,)
2021-02-01 11:00:54,853 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,853 INFO sqlalchemy.engine.base.Engine (452,)

2021-02-01 11:00:54,855 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,856 INFO sqlalchemy.engine.base.Engine (453,)
2021-02-01 11:00:54,859 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,860 INFO sqlalchemy.engine.base.Engine (454,)
2021-02-01 11:00:54,863 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,865 INFO sqlalchemy.engine.base.Engine (455,)
2021-02-01 11:00:54,867 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,868 INFO sqlalchemy.engine.base.Engine (456,)
2021-02-01 11:00:54,870 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,871 INFO sqlalchemy.engine.base.Engine (457,)
2021-02-01 11:00:54,874 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,874 INFO sqlalchemy.engine.base.Engine (458,)
2021-02-01 11:00:54,877 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,878 INFO sqlalchemy.engine.base.Engine (459,)
2021-02-01 11:00:54,882 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,884 INFO sqlalchemy.engine.base.Engine (460,)
2021-02-01 11:00:54,887 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,889 INFO sqlalchemy.engine.base.Engine (461,)
2021-02-01 11:00:54,891 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,892 INFO sqlalchemy.engine.base.Engine (462,)
2021-02-01 11:00:54,895 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,897 INFO sqlalchemy.engine.base.Engine (463,)
2021-02-01 11:00:54,900 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,901 INFO sqlalchemy.engine.base.Engine (464,)
2021-02-01 11:00:54,904 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,905 INFO sqlalchemy.engine.base.Engine (465,)
2021-02-01 11:00:54,908 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,911 INFO sqlalchemy.engine.base.Engine (466,)
2021-02-01 11:00:54,915 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,916 INFO sqlalchemy.engine.base.Engine (467,)
2021-02-01 11:00:54,919 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,920 INFO sqlalchemy.engine.base.Engine (468,)
2021-02-01 11:00:54,922 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,924 INFO sqlalchemy.engine.base.Engine (469,)
2021-02-01 11:00:54,927 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,928 INFO sqlalchemy.engine.base.Engine (470,)
2021-02-01 11:00:54,931 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,932 INFO sqlalchemy.engine.base.Engine (471,)
2021-02-01 11:00:54,937 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,938 INFO sqlalchemy.engine.base.Engine (472,)
2021-02-01 11:00:54,941 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:54,942 INFO sqlalchemy.engine.base.Engine (473,)
2021-02-01 11:00:54,946 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,947 INFO sqlalchemy.engine.base.Engine (474,)
2021-02-01 11:00:54,950 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,950 INFO sqlalchemy.engine.base.Engine (475,)
2021-02-01 11:00:54,953 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,954 INFO sqlalchemy.engine.base.Engine (476,)
2021-02-01 11:00:54,957 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,959 INFO sqlalchemy.engine.base.Engine (477,)
2021-02-01 11:00:54,961 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,963 INFO sqlalchemy.engine.base.Engine (478,)
2021-02-01 11:00:54,967 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,971 INFO sqlalchemy.engine.base.Engine (479,)
2021-02-01 11:00:54,975 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,977 INFO sqlalchemy.engine.base.Engine (480,)
2021-02-01 11:00:54,979 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,980 INFO sqlalchemy.engine.base.Engine (481,)
2021-02-01 11:00:54,982 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,983 INFO sqlalchemy.engine.base.Engine (482,)
2021-02-01 11:00:54,989 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,990 INFO sqlalchemy.engine.base.Engine (483,)
2021-02-01 11:00:54,992 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,993 INFO sqlalchemy.engine.base.Engine (484,)
2021-02-01 11:00:54,996 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:54,998 INFO sqlalchemy.engine.base.Engine (485,)
2021-02-01 11:00:55,000 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,001 INFO sqlalchemy.engine.base.Engine (486,)
2021-02-01 11:00:55,004 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,005 INFO sqlalchemy.engine.base.Engine (487,)
2021-02-01 11:00:55,008 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,009 INFO sqlalchemy.engine.base.Engine (488,)
2021-02-01 11:00:55,014 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,017 INFO sqlalchemy.engine.base.Engine (489,)
2021-02-01 11:00:55,019 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,020 INFO sqlalchemy.engine.base.Engine (490,)
2021-02-01 11:00:55,023 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,024 INFO sqlalchemy.engine.base.Engine (491,)
2021-02-01 11:00:55,026 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,028 INFO sqlalchemy.engine.base.Engine (492,)
2021-02-01 11:00:55,030 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,034 INFO sqlalchemy.engine.base.Engine (493,)
2021-02-01 11:00:55,038 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:55,039 INFO sqlalchemy.engine.base.Engine (494,)
2021-02-01 11:00:55,041 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,043 INFO sqlalchemy.engine.base.Engine (495,)
2021-02-01 11:00:55,045 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,048 INFO sqlalchemy.engine.base.Engine (496,)
2021-02-01 11:00:55,053 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,056 INFO sqlalchemy.engine.base.Engine (497,)
2021-02-01 11:00:55,059 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,060 INFO sqlalchemy.engine.base.Engine (498,)
2021-02-01 11:00:55,062 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,066 INFO sqlalchemy.engine.base.Engine (499,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:00:55,198 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:55,201 INFO sqlalchemy.engine.base.Engine ((500, 14.3, 14.3, 14.3, 152883.43300002534, 122580.26613904627), (501, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152883.43300002534, 122580.26613904627), (502, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152883.43300002534, 122580.26613904627), (503, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152883.43300002534, 122580.26613904627), (504, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152883.43300002534, 122580.26613904627), (505, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152883.43300002534, 122580.26613904627), (506, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152883.43300002534, 122580.26613904627), (507, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152883.43300002534, 122580.26613904627)  ... displaying 10 of 50 total bound parameter sets ...  (548, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152883.43300002534, 122580.26613904627), (549, 135.9, 135.9, 135.9, 152883.43300002534, 122580.26613904627))
2021-02-01 11:00:55,203 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:00:55,204 INFO sqlalchemy.engine.base.Engine ('F11',)
2021-02-01 11:00:55,209 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:55,210 INFO sqlalchemy.engine.base.Engine ((250, 'F11', 0, 'Anhydrite', 500, 501), (251, 'F11', 1, 'Sandstone, grey, vf-f', 502, 503), (252, 'F11', 2, 'Anhydrite', 504, 505), (253, 'F11', 3, 'Dolomite', 506, 507), (254, 'F11', 4, 'Anhydrite', 508, 509), (255, 'F11', 5, 'Sandstone, grey, vf-f', 510, 511), (256, 'F11', 6, 'Siltstone, red', 512, 513), (257, 'F11', 7, 'Dolomite', 514, 515)  ... displaying 10 of 25 total bound parameter sets ...  (273, 'F11', 23, 'Limestone', 546, 547), (274, 'F11', 24, 'Volcanic', 548, 549))
2021-02-01 11:00:55,213 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:00:55,325 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:00:55,326 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:00:55,326 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:55,329 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:00:55,330 INFO sqlalchemy.engine.base.Engine ('F11',)
2021-02-01 11:00:55,335 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,336 INFO sqlalchemy.engine.base.Engine (500,)
2021-02-01 11:00:55,338 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,338 INFO sqlalchemy.engine.base.Engine (501,)
2021-02-01 11:00:55,340 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,341 INFO sqlalchemy.engine.base.Engine (502,)
2021-02-01 11:00:55,343 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,344 INFO sqlalchemy.engine.base.Engine (503,)
2021-02-01 11:00:55,346 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,347 INFO sqlalchemy.engine.base.Engine (504,)
2021-02-01 11:00:55,349 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,349 INFO sqlalchemy.engine.base.Engine (505,)
2021-02-01 11:00:55,351 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,353 INFO sqlalchemy.engine.base.Engine (506,)
2021-02-01 11:00:55,354 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,355 INFO sqlalchemy.engine.base.Engine (507,)

2021-02-01 11:00:55,357 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,358 INFO sqlalchemy.engine.base.Engine (508,)
2021-02-01 11:00:55,360 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,362 INFO sqlalchemy.engine.base.Engine (509,)
2021-02-01 11:00:55,365 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,366 INFO sqlalchemy.engine.base.Engine (510,)
2021-02-01 11:00:55,368 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,368 INFO sqlalchemy.engine.base.Engine (511,)
2021-02-01 11:00:55,370 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,371 INFO sqlalchemy.engine.base.Engine (512,)
2021-02-01 11:00:55,373 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,374 INFO sqlalchemy.engine.base.Engine (513,)
2021-02-01 11:00:55,376 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,378 INFO sqlalchemy.engine.base.Engine (514,)
2021-02-01 11:00:55,383 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,383 INFO sqlalchemy.engine.base.Engine (515,)
2021-02-01 11:00:55,386 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,386 INFO sqlalchemy.engine.base.Engine (516,)
2021-02-01 11:00:55,388 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,390 INFO sqlalchemy.engine.base.Engine (517,)
2021-02-01 11:00:55,391 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,393 INFO sqlalchemy.engine.base.Engine (518,)
2021-02-01 11:00:55,395 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,396 INFO sqlalchemy.engine.base.Engine (519,)
2021-02-01 11:00:55,398 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,401 INFO sqlalchemy.engine.base.Engine (520,)
2021-02-01 11:00:55,403 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,405 INFO sqlalchemy.engine.base.Engine (521,)
2021-02-01 11:00:55,409 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,410 INFO sqlalchemy.engine.base.Engine (522,)
2021-02-01 11:00:55,412 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,413 INFO sqlalchemy.engine.base.Engine (523,)
2021-02-01 11:00:55,417 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,420 INFO sqlalchemy.engine.base.Engine (524,)
2021-02-01 11:00:55,422 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,423 INFO sqlalchemy.engine.base.Engine (525,)
2021-02-01 11:00:55,425 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,427 INFO sqlalchemy.engine.base.Engine (526,)
2021-02-01 11:00:55,430 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,431 INFO sqlalchemy.engine.base.Engine (527,)
2021-02-01 11:00:55,434 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:55,435 INFO sqlalchemy.engine.base.Engine (528,)
2021-02-01 11:00:55,437 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,438 INFO sqlalchemy.engine.base.Engine (529,)
2021-02-01 11:00:55,440 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,441 INFO sqlalchemy.engine.base.Engine (530,)
2021-02-01 11:00:55,443 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,445 INFO sqlalchemy.engine.base.Engine (531,)
2021-02-01 11:00:55,447 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,449 INFO sqlalchemy.engine.base.Engine (532,)
2021-02-01 11:00:55,451 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,453 INFO sqlalchemy.engine.base.Engine (533,)
2021-02-01 11:00:55,456 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,457 INFO sqlalchemy.engine.base.Engine (534,)
2021-02-01 11:00:55,459 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,460 INFO sqlalchemy.engine.base.Engine (535,)
2021-02-01 11:00:55,463 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,470 INFO sqlalchemy.engine.base.Engine (536,)
2021-02-01 11:00:55,472 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,473 INFO sqlalchemy.engine.base.Engine (537,)
2021-02-01 11:00:55,476 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,477 INFO sqlalchemy.engine.base.Engine (538,)
2021-02-01 11:00:55,479 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,480 INFO sqlalchemy.engine.base.Engine (539,)
2021-02-01 11:00:55,483 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,484 INFO sqlalchemy.engine.base.Engine (540,)
2021-02-01 11:00:55,487 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,489 INFO sqlalchemy.engine.base.Engine (541,)
2021-02-01 11:00:55,493 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,494 INFO sqlalchemy.engine.base.Engine (542,)
2021-02-01 11:00:55,496 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,497 INFO sqlalchemy.engine.base.Engine (543,)
2021-02-01 11:00:55,500 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,501 INFO sqlalchemy.engine.base.Engine (544,)
2021-02-01 11:00:55,504 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,511 INFO sqlalchemy.engine.base.Engine (545,)
2021-02-01 11:00:55,513 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,514 INFO sqlalchemy.engine.base.Engine (546,)
2021-02-01 11:00:55,516 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,517 INFO sqlalchemy.engine.base.Engine (547,)
2021-02-01 11:00:55,520 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,521 INFO sqlalchemy.engine.base.Engine (548,)
2021-02-01 11:00:55,523 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:55,523 INFO sqlalchemy.engine.base.Engine (549,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:00:55,650 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:00:55,654 INFO sqlalchemy.engine.base.Engine ('F12',)
2021-02-01 11:00:55,658 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:55,660 INFO sqlalchemy.engine.base.Engine ((550, 14.3, 14.3, 14.3, 152883.57100002535, 122593.02013904788), (551, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152883.57100002535, 122593.02013904788), (552, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152883.57100002535, 122593.02013904788), (553, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152883.57100002535, 122593.02013904788), (554, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152883.57100002535, 122593.02013904788), (555, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152883.57100002535, 122593.02013904788), (556, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152883.57100002535, 122593.02013904788), (557, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152883.57100002535, 122593.02013904788)  ... displaying 10 of 50 total bound parameter sets ...  (598, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152883.57100002535, 122593.02013904788), (599, 135.9, 135.9, 135.9, 152883.57100002535, 122593.02013904788))
2021-02-01 11:00:55,667 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:55,671 INFO sqlalchemy.engine.base.Engine ((275, 'F12', 0, 'Anhydrite', 550, 551), (276, 'F12', 1, 'Sandstone, grey, vf-f', 552, 553), (277, 'F12', 2, 'Anhydrite', 554, 555), (278, 'F12', 3, 'Dolomite', 556, 557), (279, 'F12', 4, 'Anhydrite', 558, 559), (280, 'F12', 5, 'Sandstone, grey, vf-f', 560, 561), (281, 'F12', 6, 'Siltstone, red', 562, 563), (282, 'F12', 7, 'Dolomite', 564, 565)  ... displaying 10 of 25 total bound parameter sets ...  (298, 'F12', 23, 'Limestone', 596, 597), (299, 'F12', 24, 'Volcanic', 598, 599))
2021-02-01 11:00:55,676 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:00:55,769 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:00:55,771 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:00:55,772 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:55,777 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:00:55,780 INFO sqlalchemy.engine.base.Engine ('F12',)
2021-02-01 11:00:55,783 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,784 INFO sqlalchemy.engine.base.Engine (550,)
2021-02-01 11:00:55,786 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,788 INFO sqlalchemy.engine.base.Engine (551,)
2021-02-01 11:00:55,791 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,792 INFO sqlalchemy.engine.base.Engine (552,)
2021-02-01 11:00:55,795 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,796 INFO sqlalchemy.engine.base.Engine (553,)
2021-02-01 11:00:55,800 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,801 INFO sqlalchemy.engine.base.Engine (554,)
2021-02-01 11:00:55,803 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,805 INFO sqlalchemy.engine.base.Engine (555,)
2021-02-01 11:00:55,806 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,807 INFO sqlalchemy.engine.base.Engine (556,)
2021-02-01 11:00:55,810 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,813 INFO sqlalchemy.engine.base.Engine (557,)
2021-02-01 11:00:55,816 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,819 INFO sqlalchemy.engine.base.Engine (558,)
2021-02-01 11:00:55,822 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,823 INFO sqlalchemy.engine.base.Engine (559,)
2021-02-01 11:00:55,825 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,826 INFO sqlalchemy.engine.base.Engine (560,)
2021-02-01 11:00:55,830 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,831 INFO sqlalchemy.engine.base.Engine (561,)
2021-02-01 11:00:55,834 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,836 INFO sqlalchemy.engine.base.Engine (562,)

2021-02-01 11:00:55,838 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,840 INFO sqlalchemy.engine.base.Engine (563,)
2021-02-01 11:00:55,842 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,843 INFO sqlalchemy.engine.base.Engine (564,)
2021-02-01 11:00:55,847 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,848 INFO sqlalchemy.engine.base.Engine (565,)
2021-02-01 11:00:55,851 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,856 INFO sqlalchemy.engine.base.Engine (566,)
2021-02-01 11:00:55,859 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,860 INFO sqlalchemy.engine.base.Engine (567,)
2021-02-01 11:00:55,865 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,866 INFO sqlalchemy.engine.base.Engine (568,)
2021-02-01 11:00:55,869 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,870 INFO sqlalchemy.engine.base.Engine (569,)
2021-02-01 11:00:55,872 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,875 INFO sqlalchemy.engine.base.Engine (570,)
2021-02-01 11:00:55,877 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,880 INFO sqlalchemy.engine.base.Engine (571,)
2021-02-01 11:00:55,884 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,886 INFO sqlalchemy.engine.base.Engine (572,)
2021-02-01 11:00:55,888 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,889 INFO sqlalchemy.engine.base.Engine (573,)
2021-02-01 11:00:55,894 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,896 INFO sqlalchemy.engine.base.Engine (574,)
2021-02-01 11:00:55,898 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,899 INFO sqlalchemy.engine.base.Engine (575,)
2021-02-01 11:00:55,902 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,903 INFO sqlalchemy.engine.base.Engine (576,)
2021-02-01 11:00:55,905 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,906 INFO sqlalchemy.engine.base.Engine (577,)
2021-02-01 11:00:55,911 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,915 INFO sqlalchemy.engine.base.Engine (578,)
2021-02-01 11:00:55,918 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,920 INFO sqlalchemy.engine.base.Engine (579,)
2021-02-01 11:00:55,922 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,923 INFO sqlalchemy.engine.base.Engine (580,)
2021-02-01 11:00:55,926 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,927 INFO sqlalchemy.engine.base.Engine (581,)
2021-02-01 11:00:55,930 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,931 INFO sqlalchemy.engine.base.Engine (582,)
2021-02-01 11:00:55,933 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:55,937 INFO sqlalchemy.engine.base.Engine (583,)
2021-02-01 11:00:55,939 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,941 INFO sqlalchemy.engine.base.Engine (584,)
2021-02-01 11:00:55,943 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,945 INFO sqlalchemy.engine.base.Engine (585,)
2021-02-01 11:00:55,948 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,953 INFO sqlalchemy.engine.base.Engine (586,)
2021-02-01 11:00:55,957 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,958 INFO sqlalchemy.engine.base.Engine (587,)
2021-02-01 11:00:55,962 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,964 INFO sqlalchemy.engine.base.Engine (588,)
2021-02-01 11:00:55,965 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,966 INFO sqlalchemy.engine.base.Engine (589,)
2021-02-01 11:00:55,969 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,970 INFO sqlalchemy.engine.base.Engine (590,)
2021-02-01 11:00:55,973 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,974 INFO sqlalchemy.engine.base.Engine (591,)
2021-02-01 11:00:55,976 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,978 INFO sqlalchemy.engine.base.Engine (592,)
2021-02-01 11:00:55,982 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,984 INFO sqlalchemy.engine.base.Engine (593,)
2021-02-01 11:00:55,987 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,988 INFO sqlalchemy.engine.base.Engine (594,)
2021-02-01 11:00:55,990 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,991 INFO sqlalchemy.engine.base.Engine (595,)
2021-02-01 11:00:55,994 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:55,997 INFO sqlalchemy.engine.base.Engine (596,)
2021-02-01 11:00:55,999 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,000 INFO sqlalchemy.engine.base.Engine (597,)
2021-02-01 11:00:56,004 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,005 INFO sqlalchemy.engine.base.Engine (598,)
2021-02-01 11:00:56,008 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,009 INFO sqlalchemy.engine.base.Engine (599,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:00:56,155 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:56,162 INFO sqlalchemy.engine.base.Engine ((600, 14.3, 14.3, 14.3, 152891.94900002552, 122593.72213904653), (601, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152891.94900002552, 122593.72213904653), (602, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152891.94900002552, 122593.72213904653), (603, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152891.94900002552, 122593.72213904653), (604, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152891.94900002552, 122593.72213904653), (605, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152891.94900002552, 122593.72213904653), (606, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152891.94900002552, 122593.72213904653), (607, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152891.94900002552, 122593.72213904653)  ... displaying 10 of 50 total bound parameter sets ...  (648, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152891.94900002552, 122593.72213904653), (649, 135.9, 135.9, 135.9, 152891.94900002552, 122593.72213904653))
2021-02-01 11:00:56,169 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:00:56,170 INFO sqlalchemy.engine.base.Engine ('F13',)
2021-02-01 11:00:56,173 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:56,174 INFO sqlalchemy.engine.base.Engine ((300, 'F13', 0, 'Anhydrite', 600, 601), (301, 'F13', 1, 'Sandstone, grey, vf-f', 602, 603), (302, 'F13', 2, 'Anhydrite', 604, 605), (303, 'F13', 3, 'Dolomite', 606, 607), (304, 'F13', 4, 'Anhydrite', 608, 609), (305, 'F13', 5, 'Sandstone, grey, vf-f', 610, 611), (306, 'F13', 6, 'Siltstone, red', 612, 613), (307, 'F13', 7, 'Dolomite', 614, 615)  ... displaying 10 of 25 total bound parameter sets ...  (323, 'F13', 23, 'Limestone', 646, 647), (324, 'F13', 24, 'Volcanic', 648, 649))

2021-02-01 11:00:56,177 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:00:56,262 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:00:56,264 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:00:56,266 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:56,269 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:00:56,271 INFO sqlalchemy.engine.base.Engine ('F13',)
2021-02-01 11:00:56,274 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,275 INFO sqlalchemy.engine.base.Engine (600,)
2021-02-01 11:00:56,277 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,279 INFO sqlalchemy.engine.base.Engine (601,)
2021-02-01 11:00:56,281 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,282 INFO sqlalchemy.engine.base.Engine (602,)
2021-02-01 11:00:56,285 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,286 INFO sqlalchemy.engine.base.Engine (603,)
2021-02-01 11:00:56,289 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,291 INFO sqlalchemy.engine.base.Engine (604,)
2021-02-01 11:00:56,293 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,295 INFO sqlalchemy.engine.base.Engine (605,)
2021-02-01 11:00:56,297 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,298 INFO sqlalchemy.engine.base.Engine (606,)
2021-02-01 11:00:56,301 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,307 INFO sqlalchemy.engine.base.Engine (607,)
2021-02-01 11:00:56,309 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,311 INFO sqlalchemy.engine.base.Engine (608,)
2021-02-01 11:00:56,313 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,314 INFO sqlalchemy.engine.base.Engine (609,)
2021-02-01 11:00:56,316 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,317 INFO sqlalchemy.engine.base.Engine (610,)
2021-02-01 11:00:56,320 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,321 INFO sqlalchemy.engine.base.Engine (611,)
2021-02-01 11:00:56,323 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,323 INFO sqlalchemy.engine.base.Engine (612,)
2021-02-01 11:00:56,328 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,329 INFO sqlalchemy.engine.base.Engine (613,)
2021-02-01 11:00:56,331 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,335 INFO sqlalchemy.engine.base.Engine (614,)
2021-02-01 11:00:56,338 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,339 INFO sqlalchemy.engine.base.Engine (615,)
2021-02-01 11:00:56,341 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,343 INFO sqlalchemy.engine.base.Engine (616,)
2021-02-01 11:00:56,346 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,349 INFO sqlalchemy.engine.base.Engine (617,)
2021-02-01 11:00:56,353 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:56,354 INFO sqlalchemy.engine.base.Engine (618,)
2021-02-01 11:00:56,356 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,360 INFO sqlalchemy.engine.base.Engine (619,)
2021-02-01 11:00:56,363 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,364 INFO sqlalchemy.engine.base.Engine (620,)
2021-02-01 11:00:56,368 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,370 INFO sqlalchemy.engine.base.Engine (621,)
2021-02-01 11:00:56,373 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,374 INFO sqlalchemy.engine.base.Engine (622,)
2021-02-01 11:00:56,377 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,378 INFO sqlalchemy.engine.base.Engine (623,)
2021-02-01 11:00:56,381 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,382 INFO sqlalchemy.engine.base.Engine (624,)
2021-02-01 11:00:56,385 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,386 INFO sqlalchemy.engine.base.Engine (625,)
2021-02-01 11:00:56,388 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,389 INFO sqlalchemy.engine.base.Engine (626,)
2021-02-01 11:00:56,391 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,392 INFO sqlalchemy.engine.base.Engine (627,)
2021-02-01 11:00:56,395 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,396 INFO sqlalchemy.engine.base.Engine (628,)
2021-02-01 11:00:56,398 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,399 INFO sqlalchemy.engine.base.Engine (629,)
2021-02-01 11:00:56,401 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,402 INFO sqlalchemy.engine.base.Engine (630,)
2021-02-01 11:00:56,404 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,405 INFO sqlalchemy.engine.base.Engine (631,)
2021-02-01 11:00:56,409 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,411 INFO sqlalchemy.engine.base.Engine (632,)
2021-02-01 11:00:56,413 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,414 INFO sqlalchemy.engine.base.Engine (633,)
2021-02-01 11:00:56,416 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,417 INFO sqlalchemy.engine.base.Engine (634,)
2021-02-01 11:00:56,420 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,420 INFO sqlalchemy.engine.base.Engine (635,)
2021-02-01 11:00:56,423 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,424 INFO sqlalchemy.engine.base.Engine (636,)
2021-02-01 11:00:56,426 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,427 INFO sqlalchemy.engine.base.Engine (637,)
2021-02-01 11:00:56,430 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,431 INFO sqlalchemy.engine.base.Engine (638,)
2021-02-01 11:00:56,433 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:56,434 INFO sqlalchemy.engine.base.Engine (639,)
2021-02-01 11:00:56,436 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,441 INFO sqlalchemy.engine.base.Engine (640,)
2021-02-01 11:00:56,445 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,446 INFO sqlalchemy.engine.base.Engine (641,)
2021-02-01 11:00:56,448 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,451 INFO sqlalchemy.engine.base.Engine (642,)
2021-02-01 11:00:56,453 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,454 INFO sqlalchemy.engine.base.Engine (643,)
2021-02-01 11:00:56,456 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,457 INFO sqlalchemy.engine.base.Engine (644,)
2021-02-01 11:00:56,459 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,460 INFO sqlalchemy.engine.base.Engine (645,)
2021-02-01 11:00:56,462 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,466 INFO sqlalchemy.engine.base.Engine (646,)
2021-02-01 11:00:56,473 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,475 INFO sqlalchemy.engine.base.Engine (647,)
2021-02-01 11:00:56,477 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,479 INFO sqlalchemy.engine.base.Engine (648,)
2021-02-01 11:00:56,481 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,482 INFO sqlalchemy.engine.base.Engine (649,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:00:56,624 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:56,627 INFO sqlalchemy.engine.base.Engine ((650, 14.3, 14.3, 14.3, 152884.22600002534, 122583.90313904824), (651, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152884.22600002534, 122583.90313904824), (652, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152884.22600002534, 122583.90313904824), (653, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152884.22600002534, 122583.90313904824), (654, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152884.22600002534, 122583.90313904824), (655, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152884.22600002534, 122583.90313904824), (656, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152884.22600002534, 122583.90313904824), (657, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152884.22600002534, 122583.90313904824)  ... displaying 10 of 50 total bound parameter sets ...  (698, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152884.22600002534, 122583.90313904824), (699, 135.9, 135.9, 135.9, 152884.22600002534, 122583.90313904824))
2021-02-01 11:00:56,632 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:00:56,633 INFO sqlalchemy.engine.base.Engine ('F14',)
2021-02-01 11:00:56,638 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:56,640 INFO sqlalchemy.engine.base.Engine ((325, 'F14', 0, 'Anhydrite', 650, 651), (326, 'F14', 1, 'Sandstone, grey, vf-f', 652, 653), (327, 'F14', 2, 'Anhydrite', 654, 655), (328, 'F14', 3, 'Dolomite', 656, 657), (329, 'F14', 4, 'Anhydrite', 658, 659), (330, 'F14', 5, 'Sandstone, grey, vf-f', 660, 661), (331, 'F14', 6, 'Siltstone, red', 662, 663), (332, 'F14', 7, 'Dolomite', 664, 665)  ... displaying 10 of 25 total bound parameter sets ...  (348, 'F14', 23, 'Limestone', 696, 697), (349, 'F14', 24, 'Volcanic', 698, 699))
2021-02-01 11:00:56,648 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:00:56,752 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:00:56,753 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:00:56,754 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:56,757 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:00:56,758 INFO sqlalchemy.engine.base.Engine ('F14',)
2021-02-01 11:00:56,760 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,761 INFO sqlalchemy.engine.base.Engine (650,)
2021-02-01 11:00:56,763 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,764 INFO sqlalchemy.engine.base.Engine (651,)
2021-02-01 11:00:56,766 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,767 INFO sqlalchemy.engine.base.Engine (652,)

2021-02-01 11:00:56,769 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,770 INFO sqlalchemy.engine.base.Engine (653,)
2021-02-01 11:00:56,772 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,773 INFO sqlalchemy.engine.base.Engine (654,)
2021-02-01 11:00:56,775 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,776 INFO sqlalchemy.engine.base.Engine (655,)
2021-02-01 11:00:56,779 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,780 INFO sqlalchemy.engine.base.Engine (656,)
2021-02-01 11:00:56,782 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,783 INFO sqlalchemy.engine.base.Engine (657,)
2021-02-01 11:00:56,786 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,787 INFO sqlalchemy.engine.base.Engine (658,)
2021-02-01 11:00:56,789 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,790 INFO sqlalchemy.engine.base.Engine (659,)
2021-02-01 11:00:56,792 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,793 INFO sqlalchemy.engine.base.Engine (660,)
2021-02-01 11:00:56,796 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,797 INFO sqlalchemy.engine.base.Engine (661,)
2021-02-01 11:00:56,799 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,800 INFO sqlalchemy.engine.base.Engine (662,)
2021-02-01 11:00:56,803 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,804 INFO sqlalchemy.engine.base.Engine (663,)
2021-02-01 11:00:56,807 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,811 INFO sqlalchemy.engine.base.Engine (664,)
2021-02-01 11:00:56,813 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,815 INFO sqlalchemy.engine.base.Engine (665,)
2021-02-01 11:00:56,817 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,818 INFO sqlalchemy.engine.base.Engine (666,)
2021-02-01 11:00:56,820 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,822 INFO sqlalchemy.engine.base.Engine (667,)
2021-02-01 11:00:56,825 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,826 INFO sqlalchemy.engine.base.Engine (668,)
2021-02-01 11:00:56,828 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,830 INFO sqlalchemy.engine.base.Engine (669,)
2021-02-01 11:00:56,833 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,834 INFO sqlalchemy.engine.base.Engine (670,)
2021-02-01 11:00:56,838 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,839 INFO sqlalchemy.engine.base.Engine (671,)
2021-02-01 11:00:56,842 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,844 INFO sqlalchemy.engine.base.Engine (672,)
2021-02-01 11:00:56,845 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:56,848 INFO sqlalchemy.engine.base.Engine (673,)
2021-02-01 11:00:56,852 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,859 INFO sqlalchemy.engine.base.Engine (674,)
2021-02-01 11:00:56,861 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,862 INFO sqlalchemy.engine.base.Engine (675,)
2021-02-01 11:00:56,864 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,871 INFO sqlalchemy.engine.base.Engine (676,)
2021-02-01 11:00:56,873 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,875 INFO sqlalchemy.engine.base.Engine (677,)
2021-02-01 11:00:56,878 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,881 INFO sqlalchemy.engine.base.Engine (678,)
2021-02-01 11:00:56,883 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,884 INFO sqlalchemy.engine.base.Engine (679,)
2021-02-01 11:00:56,888 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,889 INFO sqlalchemy.engine.base.Engine (680,)
2021-02-01 11:00:56,892 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,893 INFO sqlalchemy.engine.base.Engine (681,)
2021-02-01 11:00:56,896 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,899 INFO sqlalchemy.engine.base.Engine (682,)
2021-02-01 11:00:56,902 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,906 INFO sqlalchemy.engine.base.Engine (683,)
2021-02-01 11:00:56,910 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,911 INFO sqlalchemy.engine.base.Engine (684,)
2021-02-01 11:00:56,913 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,914 INFO sqlalchemy.engine.base.Engine (685,)
2021-02-01 11:00:56,917 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,918 INFO sqlalchemy.engine.base.Engine (686,)
2021-02-01 11:00:56,922 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,923 INFO sqlalchemy.engine.base.Engine (687,)
2021-02-01 11:00:56,929 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,930 INFO sqlalchemy.engine.base.Engine (688,)
2021-02-01 11:00:56,933 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,940 INFO sqlalchemy.engine.base.Engine (689,)
2021-02-01 11:00:56,947 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,949 INFO sqlalchemy.engine.base.Engine (690,)
2021-02-01 11:00:56,950 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,951 INFO sqlalchemy.engine.base.Engine (691,)
2021-02-01 11:00:56,954 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,955 INFO sqlalchemy.engine.base.Engine (692,)
2021-02-01 11:00:56,959 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,960 INFO sqlalchemy.engine.base.Engine (693,)
2021-02-01 11:00:56,963 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:56,964 INFO sqlalchemy.engine.base.Engine (694,)
2021-02-01 11:00:56,967 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,968 INFO sqlalchemy.engine.base.Engine (695,)
2021-02-01 11:00:56,970 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,972 INFO sqlalchemy.engine.base.Engine (696,)
2021-02-01 11:00:56,977 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,979 INFO sqlalchemy.engine.base.Engine (697,)
2021-02-01 11:00:56,983 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,984 INFO sqlalchemy.engine.base.Engine (698,)
2021-02-01 11:00:56,987 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:56,988 INFO sqlalchemy.engine.base.Engine (699,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:00:57,184 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:57,185 INFO sqlalchemy.engine.base.Engine ((700, 14.3, 14.3, 14.3, 152888.80200002546, 122590.0531390477), (701, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.80200002546, 122590.0531390477), (702, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.80200002546, 122590.0531390477), (703, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.80200002546, 122590.0531390477), (704, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.80200002546, 122590.0531390477), (705, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.80200002546, 122590.0531390477), (706, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.80200002546, 122590.0531390477), (707, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152888.80200002546, 122590.0531390477)  ... displaying 10 of 50 total bound parameter sets ...  (748, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152888.80200002546, 122590.0531390477), (749, 135.9, 135.9, 135.9, 152888.80200002546, 122590.0531390477))
2021-02-01 11:00:57,188 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:00:57,189 INFO sqlalchemy.engine.base.Engine ('F15',)
2021-02-01 11:00:57,195 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:57,198 INFO sqlalchemy.engine.base.Engine ((350, 'F15', 0, 'Anhydrite', 700, 701), (351, 'F15', 1, 'Sandstone, grey, vf-f', 702, 703), (352, 'F15', 2, 'Anhydrite', 704, 705), (353, 'F15', 3, 'Dolomite', 706, 707), (354, 'F15', 4, 'Anhydrite', 708, 709), (355, 'F15', 5, 'Sandstone, grey, vf-f', 710, 711), (356, 'F15', 6, 'Siltstone, red', 712, 713), (357, 'F15', 7, 'Dolomite', 714, 715)  ... displaying 10 of 25 total bound parameter sets ...  (373, 'F15', 23, 'Limestone', 746, 747), (374, 'F15', 24, 'Volcanic', 748, 749))
2021-02-01 11:00:57,204 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:00:57,303 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:00:57,304 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:00:57,305 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:57,308 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:00:57,309 INFO sqlalchemy.engine.base.Engine ('F15',)
2021-02-01 11:00:57,311 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,312 INFO sqlalchemy.engine.base.Engine (700,)
2021-02-01 11:00:57,315 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,316 INFO sqlalchemy.engine.base.Engine (701,)
2021-02-01 11:00:57,319 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,322 INFO sqlalchemy.engine.base.Engine (702,)
2021-02-01 11:00:57,326 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,327 INFO sqlalchemy.engine.base.Engine (703,)
2021-02-01 11:00:57,330 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,332 INFO sqlalchemy.engine.base.Engine (704,)
2021-02-01 11:00:57,334 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,335 INFO sqlalchemy.engine.base.Engine (705,)
2021-02-01 11:00:57,339 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,340 INFO sqlalchemy.engine.base.Engine (706,)
2021-02-01 11:00:57,344 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,345 INFO sqlalchemy.engine.base.Engine (707,)
2021-02-01 11:00:57,349 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:57,350 INFO sqlalchemy.engine.base.Engine (708,)
2021-02-01 11:00:57,351 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,352 INFO sqlalchemy.engine.base.Engine (709,)
2021-02-01 11:00:57,354 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,359 INFO sqlalchemy.engine.base.Engine (710,)
2021-02-01 11:00:57,361 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,365 INFO sqlalchemy.engine.base.Engine (711,)
2021-02-01 11:00:57,369 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,373 INFO sqlalchemy.engine.base.Engine (712,)
2021-02-01 11:00:57,385 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,386 INFO sqlalchemy.engine.base.Engine (713,)
2021-02-01 11:00:57,389 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,390 INFO sqlalchemy.engine.base.Engine (714,)
2021-02-01 11:00:57,392 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,395 INFO sqlalchemy.engine.base.Engine (715,)
2021-02-01 11:00:57,398 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,399 INFO sqlalchemy.engine.base.Engine (716,)
2021-02-01 11:00:57,401 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,402 INFO sqlalchemy.engine.base.Engine (717,)
2021-02-01 11:00:57,405 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,406 INFO sqlalchemy.engine.base.Engine (718,)
2021-02-01 11:00:57,409 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,410 INFO sqlalchemy.engine.base.Engine (719,)
2021-02-01 11:00:57,414 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,416 INFO sqlalchemy.engine.base.Engine (720,)
2021-02-01 11:00:57,420 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,421 INFO sqlalchemy.engine.base.Engine (721,)
2021-02-01 11:00:57,424 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,426 INFO sqlalchemy.engine.base.Engine (722,)
2021-02-01 11:00:57,429 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,430 INFO sqlalchemy.engine.base.Engine (723,)
2021-02-01 11:00:57,433 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,437 INFO sqlalchemy.engine.base.Engine (724,)
2021-02-01 11:00:57,440 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,441 INFO sqlalchemy.engine.base.Engine (725,)
2021-02-01 11:00:57,443 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,444 INFO sqlalchemy.engine.base.Engine (726,)
2021-02-01 11:00:57,446 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,450 INFO sqlalchemy.engine.base.Engine (727,)
2021-02-01 11:00:57,454 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,455 INFO sqlalchemy.engine.base.Engine (728,)
2021-02-01 11:00:57,457 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:57,458 INFO sqlalchemy.engine.base.Engine (729,)
2021-02-01 11:00:57,462 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,464 INFO sqlalchemy.engine.base.Engine (730,)
2021-02-01 11:00:57,466 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,468 INFO sqlalchemy.engine.base.Engine (731,)
2021-02-01 11:00:57,470 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,471 INFO sqlalchemy.engine.base.Engine (732,)
2021-02-01 11:00:57,473 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,476 INFO sqlalchemy.engine.base.Engine (733,)
2021-02-01 11:00:57,478 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,479 INFO sqlalchemy.engine.base.Engine (734,)
2021-02-01 11:00:57,486 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,488 INFO sqlalchemy.engine.base.Engine (735,)
2021-02-01 11:00:57,490 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,493 INFO sqlalchemy.engine.base.Engine (736,)
2021-02-01 11:00:57,495 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,497 INFO sqlalchemy.engine.base.Engine (737,)
2021-02-01 11:00:57,500 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,501 INFO sqlalchemy.engine.base.Engine (738,)
2021-02-01 11:00:57,504 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,504 INFO sqlalchemy.engine.base.Engine (739,)
2021-02-01 11:00:57,508 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,509 INFO sqlalchemy.engine.base.Engine (740,)
2021-02-01 11:00:57,512 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,513 INFO sqlalchemy.engine.base.Engine (741,)
2021-02-01 11:00:57,519 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,521 INFO sqlalchemy.engine.base.Engine (742,)
2021-02-01 11:00:57,523 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,525 INFO sqlalchemy.engine.base.Engine (743,)
2021-02-01 11:00:57,527 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,529 INFO sqlalchemy.engine.base.Engine (744,)
2021-02-01 11:00:57,535 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,537 INFO sqlalchemy.engine.base.Engine (745,)
2021-02-01 11:00:57,539 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,540 INFO sqlalchemy.engine.base.Engine (746,)
2021-02-01 11:00:57,543 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,544 INFO sqlalchemy.engine.base.Engine (747,)
2021-02-01 11:00:57,548 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,549 INFO sqlalchemy.engine.base.Engine (748,)
2021-02-01 11:00:57,552 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,553 INFO sqlalchemy.engine.base.Engine (749,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:00:57,669 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:00:57,669 INFO sqlalchemy.engine.base.Engine ('F16',)

2021-02-01 11:00:57,673 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:57,675 INFO sqlalchemy.engine.base.Engine ((750, 14.3, 14.3, 14.3, 152886.53400002536, 122588.83313904706), (751, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152886.53400002536, 122588.83313904706), (752, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152886.53400002536, 122588.83313904706), (753, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152886.53400002536, 122588.83313904706), (754, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152886.53400002536, 122588.83313904706), (755, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152886.53400002536, 122588.83313904706), (756, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152886.53400002536, 122588.83313904706), (757, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152886.53400002536, 122588.83313904706)  ... displaying 10 of 50 total bound parameter sets ...  (798, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152886.53400002536, 122588.83313904706), (799, 135.9, 135.9, 135.9, 152886.53400002536, 122588.83313904706))
2021-02-01 11:00:57,683 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:57,685 INFO sqlalchemy.engine.base.Engine ((375, 'F16', 0, 'Anhydrite', 750, 751), (376, 'F16', 1, 'Sandstone, grey, vf-f', 752, 753), (377, 'F16', 2, 'Anhydrite', 754, 755), (378, 'F16', 3, 'Dolomite', 756, 757), (379, 'F16', 4, 'Anhydrite', 758, 759), (380, 'F16', 5, 'Sandstone, grey, vf-f', 760, 761), (381, 'F16', 6, 'Siltstone, red', 762, 763), (382, 'F16', 7, 'Dolomite', 764, 765)  ... displaying 10 of 25 total bound parameter sets ...  (398, 'F16', 23, 'Limestone', 796, 797), (399, 'F16', 24, 'Volcanic', 798, 799))
2021-02-01 11:00:57,693 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:00:57,813 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:00:57,814 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:00:57,815 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:57,818 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:00:57,819 INFO sqlalchemy.engine.base.Engine ('F16',)
2021-02-01 11:00:57,822 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,824 INFO sqlalchemy.engine.base.Engine (750,)
2021-02-01 11:00:57,827 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,828 INFO sqlalchemy.engine.base.Engine (751,)
2021-02-01 11:00:57,830 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,832 INFO sqlalchemy.engine.base.Engine (752,)
2021-02-01 11:00:57,834 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,837 INFO sqlalchemy.engine.base.Engine (753,)
2021-02-01 11:00:57,840 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,841 INFO sqlalchemy.engine.base.Engine (754,)
2021-02-01 11:00:57,843 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,844 INFO sqlalchemy.engine.base.Engine (755,)
2021-02-01 11:00:57,846 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,847 INFO sqlalchemy.engine.base.Engine (756,)
2021-02-01 11:00:57,849 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,850 INFO sqlalchemy.engine.base.Engine (757,)
2021-02-01 11:00:57,852 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,853 INFO sqlalchemy.engine.base.Engine (758,)
2021-02-01 11:00:57,855 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,856 INFO sqlalchemy.engine.base.Engine (759,)
2021-02-01 11:00:57,859 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,860 INFO sqlalchemy.engine.base.Engine (760,)
2021-02-01 11:00:57,862 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,863 INFO sqlalchemy.engine.base.Engine (761,)
2021-02-01 11:00:57,867 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,868 INFO sqlalchemy.engine.base.Engine (762,)
2021-02-01 11:00:57,870 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,871 INFO sqlalchemy.engine.base.Engine (763,)

2021-02-01 11:00:57,874 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,875 INFO sqlalchemy.engine.base.Engine (764,)
2021-02-01 11:00:57,878 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,879 INFO sqlalchemy.engine.base.Engine (765,)
2021-02-01 11:00:57,884 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,886 INFO sqlalchemy.engine.base.Engine (766,)
2021-02-01 11:00:57,888 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,889 INFO sqlalchemy.engine.base.Engine (767,)
2021-02-01 11:00:57,892 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,895 INFO sqlalchemy.engine.base.Engine (768,)
2021-02-01 11:00:57,897 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,900 INFO sqlalchemy.engine.base.Engine (769,)
2021-02-01 11:00:57,902 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,904 INFO sqlalchemy.engine.base.Engine (770,)
2021-02-01 11:00:57,906 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,908 INFO sqlalchemy.engine.base.Engine (771,)
2021-02-01 11:00:57,910 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,912 INFO sqlalchemy.engine.base.Engine (772,)
2021-02-01 11:00:57,917 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,918 INFO sqlalchemy.engine.base.Engine (773,)
2021-02-01 11:00:57,921 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,922 INFO sqlalchemy.engine.base.Engine (774,)
2021-02-01 11:00:57,925 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,926 INFO sqlalchemy.engine.base.Engine (775,)
2021-02-01 11:00:57,929 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,930 INFO sqlalchemy.engine.base.Engine (776,)
2021-02-01 11:00:57,936 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,937 INFO sqlalchemy.engine.base.Engine (777,)
2021-02-01 11:00:57,939 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,942 INFO sqlalchemy.engine.base.Engine (778,)
2021-02-01 11:00:57,945 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,946 INFO sqlalchemy.engine.base.Engine (779,)
2021-02-01 11:00:57,949 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,951 INFO sqlalchemy.engine.base.Engine (780,)
2021-02-01 11:00:57,953 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,954 INFO sqlalchemy.engine.base.Engine (781,)
2021-02-01 11:00:57,956 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,959 INFO sqlalchemy.engine.base.Engine (782,)
2021-02-01 11:00:57,963 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,964 INFO sqlalchemy.engine.base.Engine (783,)
2021-02-01 11:00:57,968 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:57,969 INFO sqlalchemy.engine.base.Engine (784,)
2021-02-01 11:00:57,971 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,972 INFO sqlalchemy.engine.base.Engine (785,)
2021-02-01 11:00:57,978 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,979 INFO sqlalchemy.engine.base.Engine (786,)
2021-02-01 11:00:57,981 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,982 INFO sqlalchemy.engine.base.Engine (787,)
2021-02-01 11:00:57,985 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,986 INFO sqlalchemy.engine.base.Engine (788,)
2021-02-01 11:00:57,989 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,991 INFO sqlalchemy.engine.base.Engine (789,)
2021-02-01 11:00:57,994 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:57,995 INFO sqlalchemy.engine.base.Engine (790,)
2021-02-01 11:00:57,999 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,000 INFO sqlalchemy.engine.base.Engine (791,)
2021-02-01 11:00:58,002 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,003 INFO sqlalchemy.engine.base.Engine (792,)
2021-02-01 11:00:58,006 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,007 INFO sqlalchemy.engine.base.Engine (793,)
2021-02-01 11:00:58,009 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,011 INFO sqlalchemy.engine.base.Engine (794,)
2021-02-01 11:00:58,013 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,017 INFO sqlalchemy.engine.base.Engine (795,)
2021-02-01 11:00:58,020 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,022 INFO sqlalchemy.engine.base.Engine (796,)
2021-02-01 11:00:58,025 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,026 INFO sqlalchemy.engine.base.Engine (797,)
2021-02-01 11:00:58,028 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,031 INFO sqlalchemy.engine.base.Engine (798,)
2021-02-01 11:00:58,034 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,035 INFO sqlalchemy.engine.base.Engine (799,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:00:58,206 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:58,208 INFO sqlalchemy.engine.base.Engine ((800, 14.3, 14.3, 14.3, 152885.4830000254, 122590.19413904846), (801, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152885.4830000254, 122590.19413904846), (802, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152885.4830000254, 122590.19413904846), (803, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152885.4830000254, 122590.19413904846), (804, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152885.4830000254, 122590.19413904846), (805, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152885.4830000254, 122590.19413904846), (806, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152885.4830000254, 122590.19413904846), (807, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152885.4830000254, 122590.19413904846)  ... displaying 10 of 50 total bound parameter sets ...  (848, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152885.4830000254, 122590.19413904846), (849, 135.9, 135.9, 135.9, 152885.4830000254, 122590.19413904846))
2021-02-01 11:00:58,213 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:00:58,215 INFO sqlalchemy.engine.base.Engine ('F17',)
2021-02-01 11:00:58,221 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:58,222 INFO sqlalchemy.engine.base.Engine ((400, 'F17', 0, 'Anhydrite', 800, 801), (401, 'F17', 1, 'Sandstone, grey, vf-f', 802, 803), (402, 'F17', 2, 'Anhydrite', 804, 805), (403, 'F17', 3, 'Dolomite', 806, 807), (404, 'F17', 4, 'Anhydrite', 808, 809), (405, 'F17', 5, 'Sandstone, grey, vf-f', 810, 811), (406, 'F17', 6, 'Siltstone, red', 812, 813), (407, 'F17', 7, 'Dolomite', 814, 815)  ... displaying 10 of 25 total bound parameter sets ...  (423, 'F17', 23, 'Limestone', 846, 847), (424, 'F17', 24, 'Volcanic', 848, 849))

2021-02-01 11:00:58,226 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:00:58,319 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:00:58,321 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:00:58,322 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:58,325 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:00:58,326 INFO sqlalchemy.engine.base.Engine ('F17',)
2021-02-01 11:00:58,329 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,330 INFO sqlalchemy.engine.base.Engine (800,)
2021-02-01 11:00:58,332 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,334 INFO sqlalchemy.engine.base.Engine (801,)
2021-02-01 11:00:58,336 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,338 INFO sqlalchemy.engine.base.Engine (802,)
2021-02-01 11:00:58,340 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,342 INFO sqlalchemy.engine.base.Engine (803,)
2021-02-01 11:00:58,345 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,346 INFO sqlalchemy.engine.base.Engine (804,)
2021-02-01 11:00:58,350 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,351 INFO sqlalchemy.engine.base.Engine (805,)
2021-02-01 11:00:58,353 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,354 INFO sqlalchemy.engine.base.Engine (806,)
2021-02-01 11:00:58,356 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,356 INFO sqlalchemy.engine.base.Engine (807,)
2021-02-01 11:00:58,359 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,360 INFO sqlalchemy.engine.base.Engine (808,)
2021-02-01 11:00:58,363 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,364 INFO sqlalchemy.engine.base.Engine (809,)
2021-02-01 11:00:58,369 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,373 INFO sqlalchemy.engine.base.Engine (810,)
2021-02-01 11:00:58,375 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,376 INFO sqlalchemy.engine.base.Engine (811,)
2021-02-01 11:00:58,378 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,379 INFO sqlalchemy.engine.base.Engine (812,)
2021-02-01 11:00:58,381 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,382 INFO sqlalchemy.engine.base.Engine (813,)
2021-02-01 11:00:58,384 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,386 INFO sqlalchemy.engine.base.Engine (814,)
2021-02-01 11:00:58,389 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,391 INFO sqlalchemy.engine.base.Engine (815,)
2021-02-01 11:00:58,393 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,394 INFO sqlalchemy.engine.base.Engine (816,)
2021-02-01 11:00:58,397 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,399 INFO sqlalchemy.engine.base.Engine (817,)
2021-02-01 11:00:58,402 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:58,404 INFO sqlalchemy.engine.base.Engine (818,)
2021-02-01 11:00:58,406 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,407 INFO sqlalchemy.engine.base.Engine (819,)
2021-02-01 11:00:58,409 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,410 INFO sqlalchemy.engine.base.Engine (820,)
2021-02-01 11:00:58,412 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,413 INFO sqlalchemy.engine.base.Engine (821,)
2021-02-01 11:00:58,415 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,416 INFO sqlalchemy.engine.base.Engine (822,)
2021-02-01 11:00:58,418 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,419 INFO sqlalchemy.engine.base.Engine (823,)
2021-02-01 11:00:58,421 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,422 INFO sqlalchemy.engine.base.Engine (824,)
2021-02-01 11:00:58,430 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,432 INFO sqlalchemy.engine.base.Engine (825,)
2021-02-01 11:00:58,434 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,435 INFO sqlalchemy.engine.base.Engine (826,)
2021-02-01 11:00:58,437 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,438 INFO sqlalchemy.engine.base.Engine (827,)
2021-02-01 11:00:58,440 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,441 INFO sqlalchemy.engine.base.Engine (828,)
2021-02-01 11:00:58,443 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,444 INFO sqlalchemy.engine.base.Engine (829,)
2021-02-01 11:00:58,446 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,448 INFO sqlalchemy.engine.base.Engine (830,)
2021-02-01 11:00:58,454 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,455 INFO sqlalchemy.engine.base.Engine (831,)
2021-02-01 11:00:58,457 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,460 INFO sqlalchemy.engine.base.Engine (832,)
2021-02-01 11:00:58,461 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,464 INFO sqlalchemy.engine.base.Engine (833,)
2021-02-01 11:00:58,466 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,467 INFO sqlalchemy.engine.base.Engine (834,)
2021-02-01 11:00:58,470 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,472 INFO sqlalchemy.engine.base.Engine (835,)
2021-02-01 11:00:58,474 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,475 INFO sqlalchemy.engine.base.Engine (836,)
2021-02-01 11:00:58,477 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,479 INFO sqlalchemy.engine.base.Engine (837,)
2021-02-01 11:00:58,481 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,483 INFO sqlalchemy.engine.base.Engine (838,)
2021-02-01 11:00:58,485 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:58,486 INFO sqlalchemy.engine.base.Engine (839,)
2021-02-01 11:00:58,488 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,489 INFO sqlalchemy.engine.base.Engine (840,)
2021-02-01 11:00:58,493 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,495 INFO sqlalchemy.engine.base.Engine (841,)
2021-02-01 11:00:58,497 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,500 INFO sqlalchemy.engine.base.Engine (842,)
2021-02-01 11:00:58,502 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,504 INFO sqlalchemy.engine.base.Engine (843,)
2021-02-01 11:00:58,508 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,511 INFO sqlalchemy.engine.base.Engine (844,)
2021-02-01 11:00:58,513 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,514 INFO sqlalchemy.engine.base.Engine (845,)
2021-02-01 11:00:58,516 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,517 INFO sqlalchemy.engine.base.Engine (846,)
2021-02-01 11:00:58,519 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,520 INFO sqlalchemy.engine.base.Engine (847,)
2021-02-01 11:00:58,523 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,524 INFO sqlalchemy.engine.base.Engine (848,)
2021-02-01 11:00:58,526 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,528 INFO sqlalchemy.engine.base.Engine (849,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:00:58,696 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:00:58,698 INFO sqlalchemy.engine.base.Engine ('F18',)
2021-02-01 11:00:58,703 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:58,705 INFO sqlalchemy.engine.base.Engine ((850, 14.3, 14.3, 14.3, 152888.76800002545, 122585.85713904725), (851, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.76800002545, 122585.85713904725), (852, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.76800002545, 122585.85713904725), (853, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.76800002545, 122585.85713904725), (854, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.76800002545, 122585.85713904725), (855, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.76800002545, 122585.85713904725), (856, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.76800002545, 122585.85713904725), (857, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152888.76800002545, 122585.85713904725)  ... displaying 10 of 50 total bound parameter sets ...  (898, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152888.76800002545, 122585.85713904725), (899, 135.9, 135.9, 135.9, 152888.76800002545, 122585.85713904725))
2021-02-01 11:00:58,712 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:58,716 INFO sqlalchemy.engine.base.Engine ((425, 'F18', 0, 'Anhydrite', 850, 851), (426, 'F18', 1, 'Sandstone, grey, vf-f', 852, 853), (427, 'F18', 2, 'Anhydrite', 854, 855), (428, 'F18', 3, 'Dolomite', 856, 857), (429, 'F18', 4, 'Anhydrite', 858, 859), (430, 'F18', 5, 'Sandstone, grey, vf-f', 860, 861), (431, 'F18', 6, 'Siltstone, red', 862, 863), (432, 'F18', 7, 'Dolomite', 864, 865)  ... displaying 10 of 25 total bound parameter sets ...  (448, 'F18', 23, 'Limestone', 896, 897), (449, 'F18', 24, 'Volcanic', 898, 899))
2021-02-01 11:00:58,720 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:00:58,855 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:00:58,857 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:00:58,858 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:58,860 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:00:58,861 INFO sqlalchemy.engine.base.Engine ('F18',)
2021-02-01 11:00:58,864 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,867 INFO sqlalchemy.engine.base.Engine (850,)
2021-02-01 11:00:58,870 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,871 INFO sqlalchemy.engine.base.Engine (851,)
2021-02-01 11:00:58,874 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,875 INFO sqlalchemy.engine.base.Engine (852,)

2021-02-01 11:00:58,878 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,879 INFO sqlalchemy.engine.base.Engine (853,)
2021-02-01 11:00:58,882 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,882 INFO sqlalchemy.engine.base.Engine (854,)
2021-02-01 11:00:58,885 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,886 INFO sqlalchemy.engine.base.Engine (855,)
2021-02-01 11:00:58,888 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,890 INFO sqlalchemy.engine.base.Engine (856,)
2021-02-01 11:00:58,892 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,893 INFO sqlalchemy.engine.base.Engine (857,)
2021-02-01 11:00:58,896 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,897 INFO sqlalchemy.engine.base.Engine (858,)
2021-02-01 11:00:58,900 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,901 INFO sqlalchemy.engine.base.Engine (859,)
2021-02-01 11:00:58,904 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,905 INFO sqlalchemy.engine.base.Engine (860,)
2021-02-01 11:00:58,908 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,909 INFO sqlalchemy.engine.base.Engine (861,)
2021-02-01 11:00:58,913 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,914 INFO sqlalchemy.engine.base.Engine (862,)
2021-02-01 11:00:58,917 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,917 INFO sqlalchemy.engine.base.Engine (863,)
2021-02-01 11:00:58,920 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,921 INFO sqlalchemy.engine.base.Engine (864,)
2021-02-01 11:00:58,924 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,925 INFO sqlalchemy.engine.base.Engine (865,)
2021-02-01 11:00:58,928 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,929 INFO sqlalchemy.engine.base.Engine (866,)
2021-02-01 11:00:58,931 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,932 INFO sqlalchemy.engine.base.Engine (867,)
2021-02-01 11:00:58,934 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,935 INFO sqlalchemy.engine.base.Engine (868,)
2021-02-01 11:00:58,937 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,938 INFO sqlalchemy.engine.base.Engine (869,)
2021-02-01 11:00:58,941 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,942 INFO sqlalchemy.engine.base.Engine (870,)
2021-02-01 11:00:58,944 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,946 INFO sqlalchemy.engine.base.Engine (871,)
2021-02-01 11:00:58,947 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,949 INFO sqlalchemy.engine.base.Engine (872,)
2021-02-01 11:00:58,952 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:58,953 INFO sqlalchemy.engine.base.Engine (873,)
2021-02-01 11:00:58,956 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,957 INFO sqlalchemy.engine.base.Engine (874,)
2021-02-01 11:00:58,959 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,961 INFO sqlalchemy.engine.base.Engine (875,)
2021-02-01 11:00:58,964 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,966 INFO sqlalchemy.engine.base.Engine (876,)
2021-02-01 11:00:58,968 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,971 INFO sqlalchemy.engine.base.Engine (877,)
2021-02-01 11:00:58,973 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,975 INFO sqlalchemy.engine.base.Engine (878,)
2021-02-01 11:00:58,979 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,980 INFO sqlalchemy.engine.base.Engine (879,)
2021-02-01 11:00:58,982 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,984 INFO sqlalchemy.engine.base.Engine (880,)
2021-02-01 11:00:58,986 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,989 INFO sqlalchemy.engine.base.Engine (881,)
2021-02-01 11:00:58,991 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,993 INFO sqlalchemy.engine.base.Engine (882,)
2021-02-01 11:00:58,994 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:58,995 INFO sqlalchemy.engine.base.Engine (883,)
2021-02-01 11:00:58,998 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,000 INFO sqlalchemy.engine.base.Engine (884,)
2021-02-01 11:00:59,003 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,005 INFO sqlalchemy.engine.base.Engine (885,)
2021-02-01 11:00:59,007 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,009 INFO sqlalchemy.engine.base.Engine (886,)
2021-02-01 11:00:59,011 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,012 INFO sqlalchemy.engine.base.Engine (887,)
2021-02-01 11:00:59,015 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,016 INFO sqlalchemy.engine.base.Engine (888,)
2021-02-01 11:00:59,018 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,019 INFO sqlalchemy.engine.base.Engine (889,)
2021-02-01 11:00:59,022 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,023 INFO sqlalchemy.engine.base.Engine (890,)
2021-02-01 11:00:59,026 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,027 INFO sqlalchemy.engine.base.Engine (891,)
2021-02-01 11:00:59,029 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,030 INFO sqlalchemy.engine.base.Engine (892,)
2021-02-01 11:00:59,033 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,034 INFO sqlalchemy.engine.base.Engine (893,)
2021-02-01 11:00:59,036 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:59,037 INFO sqlalchemy.engine.base.Engine (894,)
2021-02-01 11:00:59,040 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,041 INFO sqlalchemy.engine.base.Engine (895,)
2021-02-01 11:00:59,044 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,045 INFO sqlalchemy.engine.base.Engine (896,)
2021-02-01 11:00:59,047 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,048 INFO sqlalchemy.engine.base.Engine (897,)
2021-02-01 11:00:59,051 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,052 INFO sqlalchemy.engine.base.Engine (898,)
2021-02-01 11:00:59,055 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,056 INFO sqlalchemy.engine.base.Engine (899,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:00:59,256 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:00:59,261 INFO sqlalchemy.engine.base.Engine ('F19',)
2021-02-01 11:00:59,269 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:59,270 INFO sqlalchemy.engine.base.Engine ((900, 14.3, 14.3, 14.3, 152885.03158300993, 122585.3671309175), (901, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152885.03158300993, 122585.3671309175), (902, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152885.03158300993, 122585.3671309175), (903, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152885.03158300993, 122585.3671309175), (904, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152885.03158300993, 122585.3671309175), (905, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152885.03158300993, 122585.3671309175), (906, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152885.03158300993, 122585.3671309175), (907, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152885.03158300993, 122585.3671309175)  ... displaying 10 of 50 total bound parameter sets ...  (948, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152885.03158300993, 122585.3671309175), (949, 135.9, 135.9, 135.9, 152885.03158300993, 122585.3671309175))
2021-02-01 11:00:59,277 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:59,280 INFO sqlalchemy.engine.base.Engine ((450, 'F19', 0, 'Anhydrite', 900, 901), (451, 'F19', 1, 'Sandstone, grey, vf-f', 902, 903), (452, 'F19', 2, 'Anhydrite', 904, 905), (453, 'F19', 3, 'Dolomite', 906, 907), (454, 'F19', 4, 'Anhydrite', 908, 909), (455, 'F19', 5, 'Sandstone, grey, vf-f', 910, 911), (456, 'F19', 6, 'Siltstone, red', 912, 913), (457, 'F19', 7, 'Dolomite', 914, 915)  ... displaying 10 of 25 total bound parameter sets ...  (473, 'F19', 23, 'Limestone', 946, 947), (474, 'F19', 24, 'Volcanic', 948, 949))
2021-02-01 11:00:59,282 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:00:59,417 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:00:59,419 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:00:59,421 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:59,423 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:00:59,424 INFO sqlalchemy.engine.base.Engine ('F19',)
2021-02-01 11:00:59,426 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,427 INFO sqlalchemy.engine.base.Engine (900,)
2021-02-01 11:00:59,429 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,431 INFO sqlalchemy.engine.base.Engine (901,)
2021-02-01 11:00:59,432 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,433 INFO sqlalchemy.engine.base.Engine (902,)
2021-02-01 11:00:59,435 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,436 INFO sqlalchemy.engine.base.Engine (903,)
2021-02-01 11:00:59,437 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,438 INFO sqlalchemy.engine.base.Engine (904,)
2021-02-01 11:00:59,440 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,441 INFO sqlalchemy.engine.base.Engine (905,)
2021-02-01 11:00:59,443 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,445 INFO sqlalchemy.engine.base.Engine (906,)
2021-02-01 11:00:59,447 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,449 INFO sqlalchemy.engine.base.Engine (907,)
2021-02-01 11:00:59,454 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:59,455 INFO sqlalchemy.engine.base.Engine (908,)
2021-02-01 11:00:59,460 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,461 INFO sqlalchemy.engine.base.Engine (909,)
2021-02-01 11:00:59,463 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,465 INFO sqlalchemy.engine.base.Engine (910,)
2021-02-01 11:00:59,467 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,468 INFO sqlalchemy.engine.base.Engine (911,)
2021-02-01 11:00:59,470 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,471 INFO sqlalchemy.engine.base.Engine (912,)
2021-02-01 11:00:59,472 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,474 INFO sqlalchemy.engine.base.Engine (913,)
2021-02-01 11:00:59,477 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,478 INFO sqlalchemy.engine.base.Engine (914,)
2021-02-01 11:00:59,481 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,482 INFO sqlalchemy.engine.base.Engine (915,)
2021-02-01 11:00:59,486 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,488 INFO sqlalchemy.engine.base.Engine (916,)
2021-02-01 11:00:59,493 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,494 INFO sqlalchemy.engine.base.Engine (917,)
2021-02-01 11:00:59,498 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,499 INFO sqlalchemy.engine.base.Engine (918,)
2021-02-01 11:00:59,502 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,503 INFO sqlalchemy.engine.base.Engine (919,)
2021-02-01 11:00:59,506 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,507 INFO sqlalchemy.engine.base.Engine (920,)
2021-02-01 11:00:59,510 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,511 INFO sqlalchemy.engine.base.Engine (921,)
2021-02-01 11:00:59,515 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,516 INFO sqlalchemy.engine.base.Engine (922,)
2021-02-01 11:00:59,519 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,520 INFO sqlalchemy.engine.base.Engine (923,)
2021-02-01 11:00:59,522 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,523 INFO sqlalchemy.engine.base.Engine (924,)
2021-02-01 11:00:59,524 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,525 INFO sqlalchemy.engine.base.Engine (925,)
2021-02-01 11:00:59,530 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,532 INFO sqlalchemy.engine.base.Engine (926,)
2021-02-01 11:00:59,533 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,534 INFO sqlalchemy.engine.base.Engine (927,)
2021-02-01 11:00:59,536 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,537 INFO sqlalchemy.engine.base.Engine (928,)
2021-02-01 11:00:59,539 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:59,540 INFO sqlalchemy.engine.base.Engine (929,)
2021-02-01 11:00:59,543 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,545 INFO sqlalchemy.engine.base.Engine (930,)
2021-02-01 11:00:59,547 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,550 INFO sqlalchemy.engine.base.Engine (931,)
2021-02-01 11:00:59,552 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,553 INFO sqlalchemy.engine.base.Engine (932,)
2021-02-01 11:00:59,554 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,555 INFO sqlalchemy.engine.base.Engine (933,)
2021-02-01 11:00:59,557 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,559 INFO sqlalchemy.engine.base.Engine (934,)
2021-02-01 11:00:59,562 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,564 INFO sqlalchemy.engine.base.Engine (935,)
2021-02-01 11:00:59,566 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,569 INFO sqlalchemy.engine.base.Engine (936,)
2021-02-01 11:00:59,572 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,572 INFO sqlalchemy.engine.base.Engine (937,)
2021-02-01 11:00:59,575 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,579 INFO sqlalchemy.engine.base.Engine (938,)
2021-02-01 11:00:59,581 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,582 INFO sqlalchemy.engine.base.Engine (939,)
2021-02-01 11:00:59,586 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,587 INFO sqlalchemy.engine.base.Engine (940,)
2021-02-01 11:00:59,589 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,590 INFO sqlalchemy.engine.base.Engine (941,)
2021-02-01 11:00:59,593 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,594 INFO sqlalchemy.engine.base.Engine (942,)
2021-02-01 11:00:59,597 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,598 INFO sqlalchemy.engine.base.Engine (943,)
2021-02-01 11:00:59,602 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,603 INFO sqlalchemy.engine.base.Engine (944,)
2021-02-01 11:00:59,605 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,606 INFO sqlalchemy.engine.base.Engine (945,)
2021-02-01 11:00:59,611 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,612 INFO sqlalchemy.engine.base.Engine (946,)
2021-02-01 11:00:59,615 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,615 INFO sqlalchemy.engine.base.Engine (947,)
2021-02-01 11:00:59,618 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,619 INFO sqlalchemy.engine.base.Engine (948,)
2021-02-01 11:00:59,621 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,622 INFO sqlalchemy.engine.base.Engine (949,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:00:59,766 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)

2021-02-01 11:00:59,767 INFO sqlalchemy.engine.base.Engine ((950, 14.3, 14.3, 14.3, 152890.6620000255, 122587.51713904738), (951, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152890.6620000255, 122587.51713904738), (952, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152890.6620000255, 122587.51713904738), (953, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152890.6620000255, 122587.51713904738), (954, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152890.6620000255, 122587.51713904738), (955, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152890.6620000255, 122587.51713904738), (956, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152890.6620000255, 122587.51713904738), (957, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152890.6620000255, 122587.51713904738)  ... displaying 10 of 50 total bound parameter sets ...  (998, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152890.6620000255, 122587.51713904738), (999, 135.9, 135.9, 135.9, 152890.6620000255, 122587.51713904738))
2021-02-01 11:00:59,769 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:00:59,770 INFO sqlalchemy.engine.base.Engine ('F20',)
2021-02-01 11:00:59,773 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:00:59,775 INFO sqlalchemy.engine.base.Engine ((475, 'F20', 0, 'Anhydrite', 950, 951), (476, 'F20', 1, 'Sandstone, grey, vf-f', 952, 953), (477, 'F20', 2, 'Anhydrite', 954, 955), (478, 'F20', 3, 'Dolomite', 956, 957), (479, 'F20', 4, 'Anhydrite', 958, 959), (480, 'F20', 5, 'Sandstone, grey, vf-f', 960, 961), (481, 'F20', 6, 'Siltstone, red', 962, 963), (482, 'F20', 7, 'Dolomite', 964, 965)  ... displaying 10 of 25 total bound parameter sets ...  (498, 'F20', 23, 'Limestone', 996, 997), (499, 'F20', 24, 'Volcanic', 998, 999))
2021-02-01 11:00:59,777 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:00:59,868 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:00:59,869 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:00:59,869 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:00:59,872 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:00:59,872 INFO sqlalchemy.engine.base.Engine ('F20',)
2021-02-01 11:00:59,875 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,877 INFO sqlalchemy.engine.base.Engine (950,)
2021-02-01 11:00:59,879 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,880 INFO sqlalchemy.engine.base.Engine (951,)
2021-02-01 11:00:59,882 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,883 INFO sqlalchemy.engine.base.Engine (952,)
2021-02-01 11:00:59,886 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,887 INFO sqlalchemy.engine.base.Engine (953,)
2021-02-01 11:00:59,891 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,892 INFO sqlalchemy.engine.base.Engine (954,)
2021-02-01 11:00:59,895 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,896 INFO sqlalchemy.engine.base.Engine (955,)
2021-02-01 11:00:59,898 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,899 INFO sqlalchemy.engine.base.Engine (956,)
2021-02-01 11:00:59,901 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,904 INFO sqlalchemy.engine.base.Engine (957,)
2021-02-01 11:00:59,907 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,908 INFO sqlalchemy.engine.base.Engine (958,)
2021-02-01 11:00:59,910 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,911 INFO sqlalchemy.engine.base.Engine (959,)
2021-02-01 11:00:59,915 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,915 INFO sqlalchemy.engine.base.Engine (960,)
2021-02-01 11:00:59,917 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,919 INFO sqlalchemy.engine.base.Engine (961,)
2021-02-01 11:00:59,922 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,922 INFO sqlalchemy.engine.base.Engine (962,)
2021-02-01 11:00:59,924 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:00:59,925 INFO sqlalchemy.engine.base.Engine (963,)
2021-02-01 11:00:59,929 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,933 INFO sqlalchemy.engine.base.Engine (964,)
2021-02-01 11:00:59,936 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,937 INFO sqlalchemy.engine.base.Engine (965,)
2021-02-01 11:00:59,939 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,940 INFO sqlalchemy.engine.base.Engine (966,)
2021-02-01 11:00:59,941 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,949 INFO sqlalchemy.engine.base.Engine (967,)
2021-02-01 11:00:59,951 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,952 INFO sqlalchemy.engine.base.Engine (968,)
2021-02-01 11:00:59,953 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,954 INFO sqlalchemy.engine.base.Engine (969,)
2021-02-01 11:00:59,957 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,959 INFO sqlalchemy.engine.base.Engine (970,)
2021-02-01 11:00:59,963 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,963 INFO sqlalchemy.engine.base.Engine (971,)
2021-02-01 11:00:59,966 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,967 INFO sqlalchemy.engine.base.Engine (972,)
2021-02-01 11:00:59,970 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,971 INFO sqlalchemy.engine.base.Engine (973,)
2021-02-01 11:00:59,975 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,978 INFO sqlalchemy.engine.base.Engine (974,)
2021-02-01 11:00:59,981 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,983 INFO sqlalchemy.engine.base.Engine (975,)
2021-02-01 11:00:59,987 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,988 INFO sqlalchemy.engine.base.Engine (976,)
2021-02-01 11:00:59,990 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,990 INFO sqlalchemy.engine.base.Engine (977,)
2021-02-01 11:00:59,993 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,993 INFO sqlalchemy.engine.base.Engine (978,)
2021-02-01 11:00:59,996 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:00:59,997 INFO sqlalchemy.engine.base.Engine (979,)
2021-02-01 11:01:00,000 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,003 INFO sqlalchemy.engine.base.Engine (980,)
2021-02-01 11:01:00,007 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,008 INFO sqlalchemy.engine.base.Engine (981,)
2021-02-01 11:01:00,011 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,012 INFO sqlalchemy.engine.base.Engine (982,)
2021-02-01 11:01:00,014 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,015 INFO sqlalchemy.engine.base.Engine (983,)
2021-02-01 11:01:00,017 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:00,018 INFO sqlalchemy.engine.base.Engine (984,)
2021-02-01 11:01:00,019 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,020 INFO sqlalchemy.engine.base.Engine (985,)
2021-02-01 11:01:00,023 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,027 INFO sqlalchemy.engine.base.Engine (986,)
2021-02-01 11:01:00,029 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,031 INFO sqlalchemy.engine.base.Engine (987,)
2021-02-01 11:01:00,033 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,035 INFO sqlalchemy.engine.base.Engine (988,)
2021-02-01 11:01:00,040 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,041 INFO sqlalchemy.engine.base.Engine (989,)
2021-02-01 11:01:00,043 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,045 INFO sqlalchemy.engine.base.Engine (990,)
2021-02-01 11:01:00,049 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,050 INFO sqlalchemy.engine.base.Engine (991,)
2021-02-01 11:01:00,053 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,054 INFO sqlalchemy.engine.base.Engine (992,)
2021-02-01 11:01:00,056 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,057 INFO sqlalchemy.engine.base.Engine (993,)
2021-02-01 11:01:00,060 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,061 INFO sqlalchemy.engine.base.Engine (994,)
2021-02-01 11:01:00,064 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,065 INFO sqlalchemy.engine.base.Engine (995,)
2021-02-01 11:01:00,068 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,069 INFO sqlalchemy.engine.base.Engine (996,)
2021-02-01 11:01:00,073 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,075 INFO sqlalchemy.engine.base.Engine (997,)
2021-02-01 11:01:00,077 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,078 INFO sqlalchemy.engine.base.Engine (998,)
2021-02-01 11:01:00,082 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,083 INFO sqlalchemy.engine.base.Engine (999,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:00,207 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:00,209 INFO sqlalchemy.engine.base.Engine ((1000, 14.3, 14.3, 14.3, 152881.17100002535, 122580.4831390474), (1001, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152881.17100002535, 122580.4831390474), (1002, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152881.17100002535, 122580.4831390474), (1003, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152881.17100002535, 122580.4831390474), (1004, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152881.17100002535, 122580.4831390474), (1005, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152881.17100002535, 122580.4831390474), (1006, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152881.17100002535, 122580.4831390474), (1007, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152881.17100002535, 122580.4831390474)  ... displaying 10 of 50 total bound parameter sets ...  (1048, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152881.17100002535, 122580.4831390474), (1049, 135.9, 135.9, 135.9, 152881.17100002535, 122580.4831390474))
2021-02-01 11:01:00,211 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:00,212 INFO sqlalchemy.engine.base.Engine ('F21',)
2021-02-01 11:01:00,217 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:00,222 INFO sqlalchemy.engine.base.Engine ((500, 'F21', 0, 'Anhydrite', 1000, 1001), (501, 'F21', 1, 'Sandstone, grey, vf-f', 1002, 1003), (502, 'F21', 2, 'Anhydrite', 1004, 1005), (503, 'F21', 3, 'Dolomite', 1006, 1007), (504, 'F21', 4, 'Anhydrite', 1008, 1009), (505, 'F21', 5, 'Sandstone, grey, vf-f', 1010, 1011), (506, 'F21', 6, 'Siltstone, red', 1012, 1013), (507, 'F21', 7, 'Dolomite', 1014, 1015)  ... displaying 10 of 25 total bound parameter sets ...  (523, 'F21', 23, 'Limestone', 1046, 1047), (524, 'F21', 24, 'Volcanic', 1048, 1049))

2021-02-01 11:01:00,225 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:00,325 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:00,327 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:00,328 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:00,331 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:00,333 INFO sqlalchemy.engine.base.Engine ('F21',)
2021-02-01 11:01:00,337 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,341 INFO sqlalchemy.engine.base.Engine (1000,)
2021-02-01 11:01:00,344 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,346 INFO sqlalchemy.engine.base.Engine (1001,)
2021-02-01 11:01:00,349 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,350 INFO sqlalchemy.engine.base.Engine (1002,)
2021-02-01 11:01:00,352 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,353 INFO sqlalchemy.engine.base.Engine (1003,)
2021-02-01 11:01:00,356 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,361 INFO sqlalchemy.engine.base.Engine (1004,)
2021-02-01 11:01:00,363 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,365 INFO sqlalchemy.engine.base.Engine (1005,)
2021-02-01 11:01:00,368 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,369 INFO sqlalchemy.engine.base.Engine (1006,)
2021-02-01 11:01:00,370 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,372 INFO sqlalchemy.engine.base.Engine (1007,)
2021-02-01 11:01:00,374 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,376 INFO sqlalchemy.engine.base.Engine (1008,)
2021-02-01 11:01:00,378 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,379 INFO sqlalchemy.engine.base.Engine (1009,)
2021-02-01 11:01:00,384 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,386 INFO sqlalchemy.engine.base.Engine (1010,)
2021-02-01 11:01:00,388 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,389 INFO sqlalchemy.engine.base.Engine (1011,)
2021-02-01 11:01:00,392 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,393 INFO sqlalchemy.engine.base.Engine (1012,)
2021-02-01 11:01:00,394 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,396 INFO sqlalchemy.engine.base.Engine (1013,)
2021-02-01 11:01:00,400 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,401 INFO sqlalchemy.engine.base.Engine (1014,)
2021-02-01 11:01:00,402 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,405 INFO sqlalchemy.engine.base.Engine (1015,)
2021-02-01 11:01:00,407 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,408 INFO sqlalchemy.engine.base.Engine (1016,)
2021-02-01 11:01:00,410 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,412 INFO sqlalchemy.engine.base.Engine (1017,)
2021-02-01 11:01:00,414 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:00,415 INFO sqlalchemy.engine.base.Engine (1018,)
2021-02-01 11:01:00,417 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,418 INFO sqlalchemy.engine.base.Engine (1019,)
2021-02-01 11:01:00,424 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,425 INFO sqlalchemy.engine.base.Engine (1020,)
2021-02-01 11:01:00,428 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,429 INFO sqlalchemy.engine.base.Engine (1021,)
2021-02-01 11:01:00,434 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,436 INFO sqlalchemy.engine.base.Engine (1022,)
2021-02-01 11:01:00,440 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,441 INFO sqlalchemy.engine.base.Engine (1023,)
2021-02-01 11:01:00,444 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,446 INFO sqlalchemy.engine.base.Engine (1024,)
2021-02-01 11:01:00,449 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,451 INFO sqlalchemy.engine.base.Engine (1025,)
2021-02-01 11:01:00,453 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,455 INFO sqlalchemy.engine.base.Engine (1026,)
2021-02-01 11:01:00,457 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,458 INFO sqlalchemy.engine.base.Engine (1027,)
2021-02-01 11:01:00,462 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,464 INFO sqlalchemy.engine.base.Engine (1028,)
2021-02-01 11:01:00,466 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,468 INFO sqlalchemy.engine.base.Engine (1029,)
2021-02-01 11:01:00,470 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,471 INFO sqlalchemy.engine.base.Engine (1030,)
2021-02-01 11:01:00,476 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,477 INFO sqlalchemy.engine.base.Engine (1031,)
2021-02-01 11:01:00,480 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,481 INFO sqlalchemy.engine.base.Engine (1032,)
2021-02-01 11:01:00,483 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,485 INFO sqlalchemy.engine.base.Engine (1033,)
2021-02-01 11:01:00,487 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,488 INFO sqlalchemy.engine.base.Engine (1034,)
2021-02-01 11:01:00,491 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,492 INFO sqlalchemy.engine.base.Engine (1035,)
2021-02-01 11:01:00,495 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,499 INFO sqlalchemy.engine.base.Engine (1036,)
2021-02-01 11:01:00,504 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,505 INFO sqlalchemy.engine.base.Engine (1037,)
2021-02-01 11:01:00,507 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,510 INFO sqlalchemy.engine.base.Engine (1038,)
2021-02-01 11:01:00,512 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:00,513 INFO sqlalchemy.engine.base.Engine (1039,)
2021-02-01 11:01:00,516 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,519 INFO sqlalchemy.engine.base.Engine (1040,)
2021-02-01 11:01:00,523 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,524 INFO sqlalchemy.engine.base.Engine (1041,)
2021-02-01 11:01:00,527 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,528 INFO sqlalchemy.engine.base.Engine (1042,)
2021-02-01 11:01:00,530 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,531 INFO sqlalchemy.engine.base.Engine (1043,)
2021-02-01 11:01:00,534 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,535 INFO sqlalchemy.engine.base.Engine (1044,)
2021-02-01 11:01:00,538 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,539 INFO sqlalchemy.engine.base.Engine (1045,)
2021-02-01 11:01:00,541 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,543 INFO sqlalchemy.engine.base.Engine (1046,)
2021-02-01 11:01:00,545 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,547 INFO sqlalchemy.engine.base.Engine (1047,)
2021-02-01 11:01:00,552 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,553 INFO sqlalchemy.engine.base.Engine (1048,)
2021-02-01 11:01:00,555 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,556 INFO sqlalchemy.engine.base.Engine (1049,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:00,669 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:00,670 INFO sqlalchemy.engine.base.Engine ('F22',)
2021-02-01 11:01:00,676 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:00,680 INFO sqlalchemy.engine.base.Engine ((1050, 14.3, 14.3, 14.3, 152883.5060000254, 122582.57913904634), (1051, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152883.5060000254, 122582.57913904634), (1052, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152883.5060000254, 122582.57913904634), (1053, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152883.5060000254, 122582.57913904634), (1054, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152883.5060000254, 122582.57913904634), (1055, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152883.5060000254, 122582.57913904634), (1056, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152883.5060000254, 122582.57913904634), (1057, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152883.5060000254, 122582.57913904634)  ... displaying 10 of 50 total bound parameter sets ...  (1098, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152883.5060000254, 122582.57913904634), (1099, 135.9, 135.9, 135.9, 152883.5060000254, 122582.57913904634))
2021-02-01 11:01:00,685 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:00,688 INFO sqlalchemy.engine.base.Engine ((525, 'F22', 0, 'Anhydrite', 1050, 1051), (526, 'F22', 1, 'Sandstone, grey, vf-f', 1052, 1053), (527, 'F22', 2, 'Anhydrite', 1054, 1055), (528, 'F22', 3, 'Dolomite', 1056, 1057), (529, 'F22', 4, 'Anhydrite', 1058, 1059), (530, 'F22', 5, 'Sandstone, grey, vf-f', 1060, 1061), (531, 'F22', 6, 'Siltstone, red', 1062, 1063), (532, 'F22', 7, 'Dolomite', 1064, 1065)  ... displaying 10 of 25 total bound parameter sets ...  (548, 'F22', 23, 'Limestone', 1096, 1097), (549, 'F22', 24, 'Volcanic', 1098, 1099))
2021-02-01 11:01:00,692 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:00,812 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:00,813 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:00,814 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:00,816 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:00,817 INFO sqlalchemy.engine.base.Engine ('F22',)
2021-02-01 11:01:00,820 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,821 INFO sqlalchemy.engine.base.Engine (1050,)
2021-02-01 11:01:00,823 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,824 INFO sqlalchemy.engine.base.Engine (1051,)
2021-02-01 11:01:00,827 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,828 INFO sqlalchemy.engine.base.Engine (1052,)

2021-02-01 11:01:00,829 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,831 INFO sqlalchemy.engine.base.Engine (1053,)
2021-02-01 11:01:00,834 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,835 INFO sqlalchemy.engine.base.Engine (1054,)
2021-02-01 11:01:00,837 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,838 INFO sqlalchemy.engine.base.Engine (1055,)
2021-02-01 11:01:00,841 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,842 INFO sqlalchemy.engine.base.Engine (1056,)
2021-02-01 11:01:00,844 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,845 INFO sqlalchemy.engine.base.Engine (1057,)
2021-02-01 11:01:00,848 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,849 INFO sqlalchemy.engine.base.Engine (1058,)
2021-02-01 11:01:00,851 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,852 INFO sqlalchemy.engine.base.Engine (1059,)
2021-02-01 11:01:00,854 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,857 INFO sqlalchemy.engine.base.Engine (1060,)
2021-02-01 11:01:00,860 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,861 INFO sqlalchemy.engine.base.Engine (1061,)
2021-02-01 11:01:00,863 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,867 INFO sqlalchemy.engine.base.Engine (1062,)
2021-02-01 11:01:00,869 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,870 INFO sqlalchemy.engine.base.Engine (1063,)
2021-02-01 11:01:00,872 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,873 INFO sqlalchemy.engine.base.Engine (1064,)
2021-02-01 11:01:00,875 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,878 INFO sqlalchemy.engine.base.Engine (1065,)
2021-02-01 11:01:00,882 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,884 INFO sqlalchemy.engine.base.Engine (1066,)
2021-02-01 11:01:00,886 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,888 INFO sqlalchemy.engine.base.Engine (1067,)
2021-02-01 11:01:00,891 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,892 INFO sqlalchemy.engine.base.Engine (1068,)
2021-02-01 11:01:00,895 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,896 INFO sqlalchemy.engine.base.Engine (1069,)
2021-02-01 11:01:00,899 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,900 INFO sqlalchemy.engine.base.Engine (1070,)
2021-02-01 11:01:00,902 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,903 INFO sqlalchemy.engine.base.Engine (1071,)
2021-02-01 11:01:00,905 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,907 INFO sqlalchemy.engine.base.Engine (1072,)
2021-02-01 11:01:00,910 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:00,913 INFO sqlalchemy.engine.base.Engine (1073,)
2021-02-01 11:01:00,916 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,918 INFO sqlalchemy.engine.base.Engine (1074,)
2021-02-01 11:01:00,921 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,922 INFO sqlalchemy.engine.base.Engine (1075,)
2021-02-01 11:01:00,926 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,928 INFO sqlalchemy.engine.base.Engine (1076,)
2021-02-01 11:01:00,930 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,932 INFO sqlalchemy.engine.base.Engine (1077,)
2021-02-01 11:01:00,935 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,938 INFO sqlalchemy.engine.base.Engine (1078,)
2021-02-01 11:01:00,940 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,944 INFO sqlalchemy.engine.base.Engine (1079,)
2021-02-01 11:01:00,949 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,949 INFO sqlalchemy.engine.base.Engine (1080,)
2021-02-01 11:01:00,953 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,954 INFO sqlalchemy.engine.base.Engine (1081,)
2021-02-01 11:01:00,957 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,958 INFO sqlalchemy.engine.base.Engine (1082,)
2021-02-01 11:01:00,961 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,962 INFO sqlalchemy.engine.base.Engine (1083,)
2021-02-01 11:01:00,966 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,969 INFO sqlalchemy.engine.base.Engine (1084,)
2021-02-01 11:01:00,971 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,977 INFO sqlalchemy.engine.base.Engine (1085,)
2021-02-01 11:01:00,979 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,981 INFO sqlalchemy.engine.base.Engine (1086,)
2021-02-01 11:01:00,983 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,985 INFO sqlalchemy.engine.base.Engine (1087,)
2021-02-01 11:01:00,988 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,989 INFO sqlalchemy.engine.base.Engine (1088,)
2021-02-01 11:01:00,992 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,993 INFO sqlalchemy.engine.base.Engine (1089,)
2021-02-01 11:01:00,997 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:00,998 INFO sqlalchemy.engine.base.Engine (1090,)
2021-02-01 11:01:01,005 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,006 INFO sqlalchemy.engine.base.Engine (1091,)
2021-02-01 11:01:01,009 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,010 INFO sqlalchemy.engine.base.Engine (1092,)
2021-02-01 11:01:01,013 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,014 INFO sqlalchemy.engine.base.Engine (1093,)
2021-02-01 11:01:01,016 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:01,018 INFO sqlalchemy.engine.base.Engine (1094,)
2021-02-01 11:01:01,020 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,021 INFO sqlalchemy.engine.base.Engine (1095,)
2021-02-01 11:01:01,024 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,025 INFO sqlalchemy.engine.base.Engine (1096,)
2021-02-01 11:01:01,028 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,030 INFO sqlalchemy.engine.base.Engine (1097,)
2021-02-01 11:01:01,032 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,033 INFO sqlalchemy.engine.base.Engine (1098,)
2021-02-01 11:01:01,037 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,038 INFO sqlalchemy.engine.base.Engine (1099,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:01,154 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:01,155 INFO sqlalchemy.engine.base.Engine ('F23',)
2021-02-01 11:01:01,159 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:01,161 INFO sqlalchemy.engine.base.Engine ((1100, 14.3, 14.3, 14.3, 152879.12900002536, 122583.27013904788), (1101, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152879.12900002536, 122583.27013904788), (1102, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152879.12900002536, 122583.27013904788), (1103, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152879.12900002536, 122583.27013904788), (1104, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152879.12900002536, 122583.27013904788), (1105, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152879.12900002536, 122583.27013904788), (1106, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152879.12900002536, 122583.27013904788), (1107, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152879.12900002536, 122583.27013904788)  ... displaying 10 of 50 total bound parameter sets ...  (1148, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152879.12900002536, 122583.27013904788), (1149, 135.9, 135.9, 135.9, 152879.12900002536, 122583.27013904788))
2021-02-01 11:01:01,166 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:01,168 INFO sqlalchemy.engine.base.Engine ((550, 'F23', 0, 'Anhydrite', 1100, 1101), (551, 'F23', 1, 'Sandstone, grey, vf-f', 1102, 1103), (552, 'F23', 2, 'Anhydrite', 1104, 1105), (553, 'F23', 3, 'Dolomite', 1106, 1107), (554, 'F23', 4, 'Anhydrite', 1108, 1109), (555, 'F23', 5, 'Sandstone, grey, vf-f', 1110, 1111), (556, 'F23', 6, 'Siltstone, red', 1112, 1113), (557, 'F23', 7, 'Dolomite', 1114, 1115)  ... displaying 10 of 25 total bound parameter sets ...  (573, 'F23', 23, 'Limestone', 1146, 1147), (574, 'F23', 24, 'Volcanic', 1148, 1149))
2021-02-01 11:01:01,170 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:01,252 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:01,253 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:01,254 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:01,257 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:01,258 INFO sqlalchemy.engine.base.Engine ('F23',)
2021-02-01 11:01:01,261 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,263 INFO sqlalchemy.engine.base.Engine (1100,)
2021-02-01 11:01:01,265 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,266 INFO sqlalchemy.engine.base.Engine (1101,)
2021-02-01 11:01:01,268 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,271 INFO sqlalchemy.engine.base.Engine (1102,)
2021-02-01 11:01:01,272 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,273 INFO sqlalchemy.engine.base.Engine (1103,)
2021-02-01 11:01:01,276 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,278 INFO sqlalchemy.engine.base.Engine (1104,)
2021-02-01 11:01:01,280 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,282 INFO sqlalchemy.engine.base.Engine (1105,)
2021-02-01 11:01:01,283 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,286 INFO sqlalchemy.engine.base.Engine (1106,)
2021-02-01 11:01:01,289 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,291 INFO sqlalchemy.engine.base.Engine (1107,)

2021-02-01 11:01:01,293 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,296 INFO sqlalchemy.engine.base.Engine (1108,)
2021-02-01 11:01:01,298 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,303 INFO sqlalchemy.engine.base.Engine (1109,)
2021-02-01 11:01:01,307 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,308 INFO sqlalchemy.engine.base.Engine (1110,)
2021-02-01 11:01:01,309 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,312 INFO sqlalchemy.engine.base.Engine (1111,)
2021-02-01 11:01:01,315 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,315 INFO sqlalchemy.engine.base.Engine (1112,)
2021-02-01 11:01:01,318 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,321 INFO sqlalchemy.engine.base.Engine (1113,)
2021-02-01 11:01:01,324 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,325 INFO sqlalchemy.engine.base.Engine (1114,)
2021-02-01 11:01:01,326 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,327 INFO sqlalchemy.engine.base.Engine (1115,)
2021-02-01 11:01:01,329 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,330 INFO sqlalchemy.engine.base.Engine (1116,)
2021-02-01 11:01:01,332 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,333 INFO sqlalchemy.engine.base.Engine (1117,)
2021-02-01 11:01:01,335 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,337 INFO sqlalchemy.engine.base.Engine (1118,)
2021-02-01 11:01:01,339 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,343 INFO sqlalchemy.engine.base.Engine (1119,)
2021-02-01 11:01:01,345 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,346 INFO sqlalchemy.engine.base.Engine (1120,)
2021-02-01 11:01:01,349 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,350 INFO sqlalchemy.engine.base.Engine (1121,)
2021-02-01 11:01:01,353 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,354 INFO sqlalchemy.engine.base.Engine (1122,)
2021-02-01 11:01:01,358 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,359 INFO sqlalchemy.engine.base.Engine (1123,)
2021-02-01 11:01:01,362 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,364 INFO sqlalchemy.engine.base.Engine (1124,)
2021-02-01 11:01:01,370 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,371 INFO sqlalchemy.engine.base.Engine (1125,)
2021-02-01 11:01:01,373 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,375 INFO sqlalchemy.engine.base.Engine (1126,)
2021-02-01 11:01:01,376 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,378 INFO sqlalchemy.engine.base.Engine (1127,)
2021-02-01 11:01:01,380 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:01,381 INFO sqlalchemy.engine.base.Engine (1128,)
2021-02-01 11:01:01,383 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,384 INFO sqlalchemy.engine.base.Engine (1129,)
2021-02-01 11:01:01,387 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,388 INFO sqlalchemy.engine.base.Engine (1130,)
2021-02-01 11:01:01,391 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,392 INFO sqlalchemy.engine.base.Engine (1131,)
2021-02-01 11:01:01,395 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,396 INFO sqlalchemy.engine.base.Engine (1132,)
2021-02-01 11:01:01,398 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,400 INFO sqlalchemy.engine.base.Engine (1133,)
2021-02-01 11:01:01,405 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,406 INFO sqlalchemy.engine.base.Engine (1134,)
2021-02-01 11:01:01,409 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,410 INFO sqlalchemy.engine.base.Engine (1135,)
2021-02-01 11:01:01,413 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,415 INFO sqlalchemy.engine.base.Engine (1136,)
2021-02-01 11:01:01,417 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,418 INFO sqlalchemy.engine.base.Engine (1137,)
2021-02-01 11:01:01,421 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,422 INFO sqlalchemy.engine.base.Engine (1138,)
2021-02-01 11:01:01,424 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,425 INFO sqlalchemy.engine.base.Engine (1139,)
2021-02-01 11:01:01,428 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,429 INFO sqlalchemy.engine.base.Engine (1140,)
2021-02-01 11:01:01,431 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,432 INFO sqlalchemy.engine.base.Engine (1141,)
2021-02-01 11:01:01,434 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,435 INFO sqlalchemy.engine.base.Engine (1142,)
2021-02-01 11:01:01,437 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,438 INFO sqlalchemy.engine.base.Engine (1143,)
2021-02-01 11:01:01,441 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,442 INFO sqlalchemy.engine.base.Engine (1144,)
2021-02-01 11:01:01,446 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,448 INFO sqlalchemy.engine.base.Engine (1145,)
2021-02-01 11:01:01,450 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,451 INFO sqlalchemy.engine.base.Engine (1146,)
2021-02-01 11:01:01,453 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,454 INFO sqlalchemy.engine.base.Engine (1147,)
2021-02-01 11:01:01,457 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,458 INFO sqlalchemy.engine.base.Engine (1148,)
2021-02-01 11:01:01,462 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:01,463 INFO sqlalchemy.engine.base.Engine (1149,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:01,601 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:01,602 INFO sqlalchemy.engine.base.Engine ((1150, 14.3, 14.3, 14.3, 152885.80400002538, 122584.37513904645), (1151, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152885.80400002538, 122584.37513904645), (1152, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152885.80400002538, 122584.37513904645), (1153, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152885.80400002538, 122584.37513904645), (1154, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152885.80400002538, 122584.37513904645), (1155, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152885.80400002538, 122584.37513904645), (1156, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152885.80400002538, 122584.37513904645), (1157, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152885.80400002538, 122584.37513904645)  ... displaying 10 of 50 total bound parameter sets ...  (1198, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152885.80400002538, 122584.37513904645), (1199, 135.9, 135.9, 135.9, 152885.80400002538, 122584.37513904645))
2021-02-01 11:01:01,604 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:01,605 INFO sqlalchemy.engine.base.Engine ('F24',)
2021-02-01 11:01:01,610 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:01,611 INFO sqlalchemy.engine.base.Engine ((575, 'F24', 0, 'Anhydrite', 1150, 1151), (576, 'F24', 1, 'Sandstone, grey, vf-f', 1152, 1153), (577, 'F24', 2, 'Anhydrite', 1154, 1155), (578, 'F24', 3, 'Dolomite', 1156, 1157), (579, 'F24', 4, 'Anhydrite', 1158, 1159), (580, 'F24', 5, 'Sandstone, grey, vf-f', 1160, 1161), (581, 'F24', 6, 'Siltstone, red', 1162, 1163), (582, 'F24', 7, 'Dolomite', 1164, 1165)  ... displaying 10 of 25 total bound parameter sets ...  (598, 'F24', 23, 'Limestone', 1196, 1197), (599, 'F24', 24, 'Volcanic', 1198, 1199))
2021-02-01 11:01:01,614 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:01,704 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:01,705 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:01,706 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:01,709 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:01,710 INFO sqlalchemy.engine.base.Engine ('F24',)
2021-02-01 11:01:01,713 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,714 INFO sqlalchemy.engine.base.Engine (1150,)
2021-02-01 11:01:01,715 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,716 INFO sqlalchemy.engine.base.Engine (1151,)
2021-02-01 11:01:01,718 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,719 INFO sqlalchemy.engine.base.Engine (1152,)
2021-02-01 11:01:01,721 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,721 INFO sqlalchemy.engine.base.Engine (1153,)
2021-02-01 11:01:01,724 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,725 INFO sqlalchemy.engine.base.Engine (1154,)
2021-02-01 11:01:01,728 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,730 INFO sqlalchemy.engine.base.Engine (1155,)
2021-02-01 11:01:01,733 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,736 INFO sqlalchemy.engine.base.Engine (1156,)
2021-02-01 11:01:01,739 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,740 INFO sqlalchemy.engine.base.Engine (1157,)
2021-02-01 11:01:01,742 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,745 INFO sqlalchemy.engine.base.Engine (1158,)
2021-02-01 11:01:01,747 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,748 INFO sqlalchemy.engine.base.Engine (1159,)
2021-02-01 11:01:01,757 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,759 INFO sqlalchemy.engine.base.Engine (1160,)
2021-02-01 11:01:01,761 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,763 INFO sqlalchemy.engine.base.Engine (1161,)
2021-02-01 11:01:01,766 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,768 INFO sqlalchemy.engine.base.Engine (1162,)

2021-02-01 11:01:01,771 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,772 INFO sqlalchemy.engine.base.Engine (1163,)
2021-02-01 11:01:01,776 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,777 INFO sqlalchemy.engine.base.Engine (1164,)
2021-02-01 11:01:01,779 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,781 INFO sqlalchemy.engine.base.Engine (1165,)
2021-02-01 11:01:01,784 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,787 INFO sqlalchemy.engine.base.Engine (1166,)
2021-02-01 11:01:01,791 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,792 INFO sqlalchemy.engine.base.Engine (1167,)
2021-02-01 11:01:01,795 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,796 INFO sqlalchemy.engine.base.Engine (1168,)
2021-02-01 11:01:01,800 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,802 INFO sqlalchemy.engine.base.Engine (1169,)
2021-02-01 11:01:01,805 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,805 INFO sqlalchemy.engine.base.Engine (1170,)
2021-02-01 11:01:01,807 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,809 INFO sqlalchemy.engine.base.Engine (1171,)
2021-02-01 11:01:01,811 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,812 INFO sqlalchemy.engine.base.Engine (1172,)
2021-02-01 11:01:01,814 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,815 INFO sqlalchemy.engine.base.Engine (1173,)
2021-02-01 11:01:01,821 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,823 INFO sqlalchemy.engine.base.Engine (1174,)
2021-02-01 11:01:01,830 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,831 INFO sqlalchemy.engine.base.Engine (1175,)
2021-02-01 11:01:01,834 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,835 INFO sqlalchemy.engine.base.Engine (1176,)
2021-02-01 11:01:01,839 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,840 INFO sqlalchemy.engine.base.Engine (1177,)
2021-02-01 11:01:01,843 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,844 INFO sqlalchemy.engine.base.Engine (1178,)
2021-02-01 11:01:01,848 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,850 INFO sqlalchemy.engine.base.Engine (1179,)
2021-02-01 11:01:01,853 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,855 INFO sqlalchemy.engine.base.Engine (1180,)
2021-02-01 11:01:01,858 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,859 INFO sqlalchemy.engine.base.Engine (1181,)
2021-02-01 11:01:01,861 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,862 INFO sqlalchemy.engine.base.Engine (1182,)
2021-02-01 11:01:01,864 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:01,865 INFO sqlalchemy.engine.base.Engine (1183,)
2021-02-01 11:01:01,869 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,870 INFO sqlalchemy.engine.base.Engine (1184,)
2021-02-01 11:01:01,872 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,873 INFO sqlalchemy.engine.base.Engine (1185,)
2021-02-01 11:01:01,876 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,877 INFO sqlalchemy.engine.base.Engine (1186,)
2021-02-01 11:01:01,880 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,884 INFO sqlalchemy.engine.base.Engine (1187,)
2021-02-01 11:01:01,886 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,887 INFO sqlalchemy.engine.base.Engine (1188,)
2021-02-01 11:01:01,890 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,891 INFO sqlalchemy.engine.base.Engine (1189,)
2021-02-01 11:01:01,894 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,896 INFO sqlalchemy.engine.base.Engine (1190,)
2021-02-01 11:01:01,898 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,899 INFO sqlalchemy.engine.base.Engine (1191,)
2021-02-01 11:01:01,901 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,901 INFO sqlalchemy.engine.base.Engine (1192,)
2021-02-01 11:01:01,903 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,904 INFO sqlalchemy.engine.base.Engine (1193,)
2021-02-01 11:01:01,906 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,907 INFO sqlalchemy.engine.base.Engine (1194,)
2021-02-01 11:01:01,910 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,911 INFO sqlalchemy.engine.base.Engine (1195,)
2021-02-01 11:01:01,915 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,916 INFO sqlalchemy.engine.base.Engine (1196,)
2021-02-01 11:01:01,920 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,923 INFO sqlalchemy.engine.base.Engine (1197,)
2021-02-01 11:01:01,926 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,928 INFO sqlalchemy.engine.base.Engine (1198,)
2021-02-01 11:01:01,930 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:01,931 INFO sqlalchemy.engine.base.Engine (1199,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:02,056 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:02,057 INFO sqlalchemy.engine.base.Engine ((1200, 14.3, 14.3, 14.3, 152884.55900002542, 122586.86513904856), (1201, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152884.55900002542, 122586.86513904856), (1202, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152884.55900002542, 122586.86513904856), (1203, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152884.55900002542, 122586.86513904856), (1204, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152884.55900002542, 122586.86513904856), (1205, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152884.55900002542, 122586.86513904856), (1206, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152884.55900002542, 122586.86513904856), (1207, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152884.55900002542, 122586.86513904856)  ... displaying 10 of 50 total bound parameter sets ...  (1248, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152884.55900002542, 122586.86513904856), (1249, 135.9, 135.9, 135.9, 152884.55900002542, 122586.86513904856))
2021-02-01 11:01:02,059 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:02,060 INFO sqlalchemy.engine.base.Engine ('F25',)
2021-02-01 11:01:02,063 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:02,064 INFO sqlalchemy.engine.base.Engine ((600, 'F25', 0, 'Anhydrite', 1200, 1201), (601, 'F25', 1, 'Sandstone, grey, vf-f', 1202, 1203), (602, 'F25', 2, 'Anhydrite', 1204, 1205), (603, 'F25', 3, 'Dolomite', 1206, 1207), (604, 'F25', 4, 'Anhydrite', 1208, 1209), (605, 'F25', 5, 'Sandstone, grey, vf-f', 1210, 1211), (606, 'F25', 6, 'Siltstone, red', 1212, 1213), (607, 'F25', 7, 'Dolomite', 1214, 1215)  ... displaying 10 of 25 total bound parameter sets ...  (623, 'F25', 23, 'Limestone', 1246, 1247), (624, 'F25', 24, 'Volcanic', 1248, 1249))

2021-02-01 11:01:02,066 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:02,160 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:02,162 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:02,166 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:02,169 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:02,171 INFO sqlalchemy.engine.base.Engine ('F25',)
2021-02-01 11:01:02,173 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,175 INFO sqlalchemy.engine.base.Engine (1200,)
2021-02-01 11:01:02,177 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,178 INFO sqlalchemy.engine.base.Engine (1201,)
2021-02-01 11:01:02,181 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,182 INFO sqlalchemy.engine.base.Engine (1202,)
2021-02-01 11:01:02,184 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,186 INFO sqlalchemy.engine.base.Engine (1203,)
2021-02-01 11:01:02,188 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,189 INFO sqlalchemy.engine.base.Engine (1204,)
2021-02-01 11:01:02,191 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,193 INFO sqlalchemy.engine.base.Engine (1205,)
2021-02-01 11:01:02,195 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,196 INFO sqlalchemy.engine.base.Engine (1206,)
2021-02-01 11:01:02,198 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,199 INFO sqlalchemy.engine.base.Engine (1207,)
2021-02-01 11:01:02,201 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,202 INFO sqlalchemy.engine.base.Engine (1208,)
2021-02-01 11:01:02,205 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,206 INFO sqlalchemy.engine.base.Engine (1209,)
2021-02-01 11:01:02,209 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,211 INFO sqlalchemy.engine.base.Engine (1210,)
2021-02-01 11:01:02,213 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,215 INFO sqlalchemy.engine.base.Engine (1211,)
2021-02-01 11:01:02,219 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,223 INFO sqlalchemy.engine.base.Engine (1212,)
2021-02-01 11:01:02,226 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,227 INFO sqlalchemy.engine.base.Engine (1213,)
2021-02-01 11:01:02,229 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,233 INFO sqlalchemy.engine.base.Engine (1214,)
2021-02-01 11:01:02,237 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,239 INFO sqlalchemy.engine.base.Engine (1215,)
2021-02-01 11:01:02,242 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,243 INFO sqlalchemy.engine.base.Engine (1216,)
2021-02-01 11:01:02,246 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,247 INFO sqlalchemy.engine.base.Engine (1217,)
2021-02-01 11:01:02,252 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:02,253 INFO sqlalchemy.engine.base.Engine (1218,)
2021-02-01 11:01:02,256 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,258 INFO sqlalchemy.engine.base.Engine (1219,)
2021-02-01 11:01:02,261 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,262 INFO sqlalchemy.engine.base.Engine (1220,)
2021-02-01 11:01:02,268 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,270 INFO sqlalchemy.engine.base.Engine (1221,)
2021-02-01 11:01:02,274 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,275 INFO sqlalchemy.engine.base.Engine (1222,)
2021-02-01 11:01:02,279 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,280 INFO sqlalchemy.engine.base.Engine (1223,)
2021-02-01 11:01:02,283 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,284 INFO sqlalchemy.engine.base.Engine (1224,)
2021-02-01 11:01:02,287 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,288 INFO sqlalchemy.engine.base.Engine (1225,)
2021-02-01 11:01:02,292 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,294 INFO sqlalchemy.engine.base.Engine (1226,)
2021-02-01 11:01:02,297 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,299 INFO sqlalchemy.engine.base.Engine (1227,)
2021-02-01 11:01:02,301 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,304 INFO sqlalchemy.engine.base.Engine (1228,)
2021-02-01 11:01:02,306 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,307 INFO sqlalchemy.engine.base.Engine (1229,)
2021-02-01 11:01:02,310 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,311 INFO sqlalchemy.engine.base.Engine (1230,)
2021-02-01 11:01:02,314 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,317 INFO sqlalchemy.engine.base.Engine (1231,)
2021-02-01 11:01:02,320 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,321 INFO sqlalchemy.engine.base.Engine (1232,)
2021-02-01 11:01:02,325 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,327 INFO sqlalchemy.engine.base.Engine (1233,)
2021-02-01 11:01:02,331 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,333 INFO sqlalchemy.engine.base.Engine (1234,)
2021-02-01 11:01:02,335 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,336 INFO sqlalchemy.engine.base.Engine (1235,)
2021-02-01 11:01:02,339 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,341 INFO sqlalchemy.engine.base.Engine (1236,)
2021-02-01 11:01:02,344 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,345 INFO sqlalchemy.engine.base.Engine (1237,)
2021-02-01 11:01:02,347 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,351 INFO sqlalchemy.engine.base.Engine (1238,)
2021-02-01 11:01:02,354 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:02,356 INFO sqlalchemy.engine.base.Engine (1239,)
2021-02-01 11:01:02,359 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,361 INFO sqlalchemy.engine.base.Engine (1240,)
2021-02-01 11:01:02,365 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,366 INFO sqlalchemy.engine.base.Engine (1241,)
2021-02-01 11:01:02,370 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,373 INFO sqlalchemy.engine.base.Engine (1242,)
2021-02-01 11:01:02,375 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,376 INFO sqlalchemy.engine.base.Engine (1243,)
2021-02-01 11:01:02,381 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,384 INFO sqlalchemy.engine.base.Engine (1244,)
2021-02-01 11:01:02,386 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,387 INFO sqlalchemy.engine.base.Engine (1245,)
2021-02-01 11:01:02,395 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,397 INFO sqlalchemy.engine.base.Engine (1246,)
2021-02-01 11:01:02,400 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,402 INFO sqlalchemy.engine.base.Engine (1247,)
2021-02-01 11:01:02,404 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,405 INFO sqlalchemy.engine.base.Engine (1248,)
2021-02-01 11:01:02,407 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,409 INFO sqlalchemy.engine.base.Engine (1249,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:02,569 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:02,570 INFO sqlalchemy.engine.base.Engine ('F26',)
2021-02-01 11:01:02,573 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:02,574 INFO sqlalchemy.engine.base.Engine ((1250, 14.3, 14.3, 14.3, 152886.79600002544, 122583.44613904694), (1251, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152886.79600002544, 122583.44613904694), (1252, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152886.79600002544, 122583.44613904694), (1253, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152886.79600002544, 122583.44613904694), (1254, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152886.79600002544, 122583.44613904694), (1255, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152886.79600002544, 122583.44613904694), (1256, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152886.79600002544, 122583.44613904694), (1257, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152886.79600002544, 122583.44613904694)  ... displaying 10 of 50 total bound parameter sets ...  (1298, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152886.79600002544, 122583.44613904694), (1299, 135.9, 135.9, 135.9, 152886.79600002544, 122583.44613904694))
2021-02-01 11:01:02,580 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:02,581 INFO sqlalchemy.engine.base.Engine ((625, 'F26', 0, 'Anhydrite', 1250, 1251), (626, 'F26', 1, 'Sandstone, grey, vf-f', 1252, 1253), (627, 'F26', 2, 'Anhydrite', 1254, 1255), (628, 'F26', 3, 'Dolomite', 1256, 1257), (629, 'F26', 4, 'Anhydrite', 1258, 1259), (630, 'F26', 5, 'Sandstone, grey, vf-f', 1260, 1261), (631, 'F26', 6, 'Siltstone, red', 1262, 1263), (632, 'F26', 7, 'Dolomite', 1264, 1265)  ... displaying 10 of 25 total bound parameter sets ...  (648, 'F26', 23, 'Limestone', 1296, 1297), (649, 'F26', 24, 'Volcanic', 1298, 1299))
2021-02-01 11:01:02,584 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:02,705 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:02,706 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:02,707 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:02,709 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:02,710 INFO sqlalchemy.engine.base.Engine ('F26',)
2021-02-01 11:01:02,713 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,714 INFO sqlalchemy.engine.base.Engine (1250,)
2021-02-01 11:01:02,716 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,717 INFO sqlalchemy.engine.base.Engine (1251,)
2021-02-01 11:01:02,719 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,720 INFO sqlalchemy.engine.base.Engine (1252,)

2021-02-01 11:01:02,722 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,723 INFO sqlalchemy.engine.base.Engine (1253,)
2021-02-01 11:01:02,725 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,726 INFO sqlalchemy.engine.base.Engine (1254,)
2021-02-01 11:01:02,728 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,729 INFO sqlalchemy.engine.base.Engine (1255,)
2021-02-01 11:01:02,731 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,732 INFO sqlalchemy.engine.base.Engine (1256,)
2021-02-01 11:01:02,733 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,734 INFO sqlalchemy.engine.base.Engine (1257,)
2021-02-01 11:01:02,736 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,737 INFO sqlalchemy.engine.base.Engine (1258,)
2021-02-01 11:01:02,739 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,740 INFO sqlalchemy.engine.base.Engine (1259,)
2021-02-01 11:01:02,742 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,743 INFO sqlalchemy.engine.base.Engine (1260,)
2021-02-01 11:01:02,747 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,750 INFO sqlalchemy.engine.base.Engine (1261,)
2021-02-01 11:01:02,752 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,752 INFO sqlalchemy.engine.base.Engine (1262,)
2021-02-01 11:01:02,754 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,755 INFO sqlalchemy.engine.base.Engine (1263,)
2021-02-01 11:01:02,756 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,757 INFO sqlalchemy.engine.base.Engine (1264,)
2021-02-01 11:01:02,760 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,766 INFO sqlalchemy.engine.base.Engine (1265,)
2021-02-01 11:01:02,769 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,770 INFO sqlalchemy.engine.base.Engine (1266,)
2021-02-01 11:01:02,772 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,773 INFO sqlalchemy.engine.base.Engine (1267,)
2021-02-01 11:01:02,777 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,780 INFO sqlalchemy.engine.base.Engine (1268,)
2021-02-01 11:01:02,781 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,782 INFO sqlalchemy.engine.base.Engine (1269,)
2021-02-01 11:01:02,784 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,785 INFO sqlalchemy.engine.base.Engine (1270,)
2021-02-01 11:01:02,787 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,787 INFO sqlalchemy.engine.base.Engine (1271,)
2021-02-01 11:01:02,790 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,792 INFO sqlalchemy.engine.base.Engine (1272,)
2021-02-01 11:01:02,794 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:02,797 INFO sqlalchemy.engine.base.Engine (1273,)
2021-02-01 11:01:02,799 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,800 INFO sqlalchemy.engine.base.Engine (1274,)
2021-02-01 11:01:02,803 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,805 INFO sqlalchemy.engine.base.Engine (1275,)
2021-02-01 11:01:02,807 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,810 INFO sqlalchemy.engine.base.Engine (1276,)
2021-02-01 11:01:02,813 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,814 INFO sqlalchemy.engine.base.Engine (1277,)
2021-02-01 11:01:02,817 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,817 INFO sqlalchemy.engine.base.Engine (1278,)
2021-02-01 11:01:02,820 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,823 INFO sqlalchemy.engine.base.Engine (1279,)
2021-02-01 11:01:02,826 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,831 INFO sqlalchemy.engine.base.Engine (1280,)
2021-02-01 11:01:02,833 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,834 INFO sqlalchemy.engine.base.Engine (1281,)
2021-02-01 11:01:02,838 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,839 INFO sqlalchemy.engine.base.Engine (1282,)
2021-02-01 11:01:02,841 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,843 INFO sqlalchemy.engine.base.Engine (1283,)
2021-02-01 11:01:02,845 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,847 INFO sqlalchemy.engine.base.Engine (1284,)
2021-02-01 11:01:02,849 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,852 INFO sqlalchemy.engine.base.Engine (1285,)
2021-02-01 11:01:02,855 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,856 INFO sqlalchemy.engine.base.Engine (1286,)
2021-02-01 11:01:02,858 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,859 INFO sqlalchemy.engine.base.Engine (1287,)
2021-02-01 11:01:02,862 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,863 INFO sqlalchemy.engine.base.Engine (1288,)
2021-02-01 11:01:02,865 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,867 INFO sqlalchemy.engine.base.Engine (1289,)
2021-02-01 11:01:02,872 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,873 INFO sqlalchemy.engine.base.Engine (1290,)
2021-02-01 11:01:02,876 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,877 INFO sqlalchemy.engine.base.Engine (1291,)
2021-02-01 11:01:02,880 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,882 INFO sqlalchemy.engine.base.Engine (1292,)
2021-02-01 11:01:02,885 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,886 INFO sqlalchemy.engine.base.Engine (1293,)
2021-02-01 11:01:02,889 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:02,890 INFO sqlalchemy.engine.base.Engine (1294,)
2021-02-01 11:01:02,892 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,894 INFO sqlalchemy.engine.base.Engine (1295,)
2021-02-01 11:01:02,896 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,898 INFO sqlalchemy.engine.base.Engine (1296,)
2021-02-01 11:01:02,899 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,901 INFO sqlalchemy.engine.base.Engine (1297,)
2021-02-01 11:01:02,903 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,904 INFO sqlalchemy.engine.base.Engine (1298,)
2021-02-01 11:01:02,906 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:02,907 INFO sqlalchemy.engine.base.Engine (1299,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:03,039 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:03,041 INFO sqlalchemy.engine.base.Engine ((1300, 14.3, 14.3, 14.3, 152881.57883449993, 122585.08690298627), (1301, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152881.57883449993, 122585.08690298627), (1302, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152881.57883449993, 122585.08690298627), (1303, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152881.57883449993, 122585.08690298627), (1304, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152881.57883449993, 122585.08690298627), (1305, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152881.57883449993, 122585.08690298627), (1306, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152881.57883449993, 122585.08690298627), (1307, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152881.57883449993, 122585.08690298627)  ... displaying 10 of 50 total bound parameter sets ...  (1348, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152881.57883449993, 122585.08690298627), (1349, 135.9, 135.9, 135.9, 152881.57883449993, 122585.08690298627))
2021-02-01 11:01:03,045 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:03,046 INFO sqlalchemy.engine.base.Engine ('F27',)
2021-02-01 11:01:03,050 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:03,054 INFO sqlalchemy.engine.base.Engine ((650, 'F27', 0, 'Anhydrite', 1300, 1301), (651, 'F27', 1, 'Sandstone, grey, vf-f', 1302, 1303), (652, 'F27', 2, 'Anhydrite', 1304, 1305), (653, 'F27', 3, 'Dolomite', 1306, 1307), (654, 'F27', 4, 'Anhydrite', 1308, 1309), (655, 'F27', 5, 'Sandstone, grey, vf-f', 1310, 1311), (656, 'F27', 6, 'Siltstone, red', 1312, 1313), (657, 'F27', 7, 'Dolomite', 1314, 1315)  ... displaying 10 of 25 total bound parameter sets ...  (673, 'F27', 23, 'Limestone', 1346, 1347), (674, 'F27', 24, 'Volcanic', 1348, 1349))
2021-02-01 11:01:03,058 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:03,189 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:03,190 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:03,192 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:03,196 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:03,197 INFO sqlalchemy.engine.base.Engine ('F27',)
2021-02-01 11:01:03,200 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,201 INFO sqlalchemy.engine.base.Engine (1300,)
2021-02-01 11:01:03,204 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,204 INFO sqlalchemy.engine.base.Engine (1301,)
2021-02-01 11:01:03,206 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,208 INFO sqlalchemy.engine.base.Engine (1302,)
2021-02-01 11:01:03,210 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,211 INFO sqlalchemy.engine.base.Engine (1303,)
2021-02-01 11:01:03,214 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,214 INFO sqlalchemy.engine.base.Engine (1304,)
2021-02-01 11:01:03,216 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,217 INFO sqlalchemy.engine.base.Engine (1305,)
2021-02-01 11:01:03,219 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,220 INFO sqlalchemy.engine.base.Engine (1306,)
2021-02-01 11:01:03,223 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,223 INFO sqlalchemy.engine.base.Engine (1307,)

2021-02-01 11:01:03,226 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,227 INFO sqlalchemy.engine.base.Engine (1308,)
2021-02-01 11:01:03,231 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,232 INFO sqlalchemy.engine.base.Engine (1309,)
2021-02-01 11:01:03,234 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,236 INFO sqlalchemy.engine.base.Engine (1310,)
2021-02-01 11:01:03,238 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,238 INFO sqlalchemy.engine.base.Engine (1311,)
2021-02-01 11:01:03,240 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,241 INFO sqlalchemy.engine.base.Engine (1312,)
2021-02-01 11:01:03,244 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,245 INFO sqlalchemy.engine.base.Engine (1313,)
2021-02-01 11:01:03,247 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,252 INFO sqlalchemy.engine.base.Engine (1314,)
2021-02-01 11:01:03,254 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,256 INFO sqlalchemy.engine.base.Engine (1315,)
2021-02-01 11:01:03,257 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,259 INFO sqlalchemy.engine.base.Engine (1316,)
2021-02-01 11:01:03,261 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,264 INFO sqlalchemy.engine.base.Engine (1317,)
2021-02-01 11:01:03,268 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,268 INFO sqlalchemy.engine.base.Engine (1318,)
2021-02-01 11:01:03,271 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,273 INFO sqlalchemy.engine.base.Engine (1319,)
2021-02-01 11:01:03,275 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,276 INFO sqlalchemy.engine.base.Engine (1320,)
2021-02-01 11:01:03,278 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,279 INFO sqlalchemy.engine.base.Engine (1321,)
2021-02-01 11:01:03,281 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,282 INFO sqlalchemy.engine.base.Engine (1322,)
2021-02-01 11:01:03,286 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,287 INFO sqlalchemy.engine.base.Engine (1323,)
2021-02-01 11:01:03,290 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,292 INFO sqlalchemy.engine.base.Engine (1324,)
2021-02-01 11:01:03,294 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,300 INFO sqlalchemy.engine.base.Engine (1325,)
2021-02-01 11:01:03,303 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,304 INFO sqlalchemy.engine.base.Engine (1326,)
2021-02-01 11:01:03,308 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,309 INFO sqlalchemy.engine.base.Engine (1327,)
2021-02-01 11:01:03,312 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:03,313 INFO sqlalchemy.engine.base.Engine (1328,)
2021-02-01 11:01:03,315 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,316 INFO sqlalchemy.engine.base.Engine (1329,)
2021-02-01 11:01:03,319 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,319 INFO sqlalchemy.engine.base.Engine (1330,)
2021-02-01 11:01:03,323 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,326 INFO sqlalchemy.engine.base.Engine (1331,)
2021-02-01 11:01:03,329 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,330 INFO sqlalchemy.engine.base.Engine (1332,)
2021-02-01 11:01:03,332 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,334 INFO sqlalchemy.engine.base.Engine (1333,)
2021-02-01 11:01:03,336 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,337 INFO sqlalchemy.engine.base.Engine (1334,)
2021-02-01 11:01:03,340 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,342 INFO sqlalchemy.engine.base.Engine (1335,)
2021-02-01 11:01:03,347 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,348 INFO sqlalchemy.engine.base.Engine (1336,)
2021-02-01 11:01:03,351 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,352 INFO sqlalchemy.engine.base.Engine (1337,)
2021-02-01 11:01:03,354 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,356 INFO sqlalchemy.engine.base.Engine (1338,)
2021-02-01 11:01:03,357 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,359 INFO sqlalchemy.engine.base.Engine (1339,)
2021-02-01 11:01:03,361 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,362 INFO sqlalchemy.engine.base.Engine (1340,)
2021-02-01 11:01:03,371 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,375 INFO sqlalchemy.engine.base.Engine (1341,)
2021-02-01 11:01:03,378 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,379 INFO sqlalchemy.engine.base.Engine (1342,)
2021-02-01 11:01:03,381 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,382 INFO sqlalchemy.engine.base.Engine (1343,)
2021-02-01 11:01:03,385 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,386 INFO sqlalchemy.engine.base.Engine (1344,)
2021-02-01 11:01:03,389 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,390 INFO sqlalchemy.engine.base.Engine (1345,)
2021-02-01 11:01:03,393 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,394 INFO sqlalchemy.engine.base.Engine (1346,)
2021-02-01 11:01:03,397 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,400 INFO sqlalchemy.engine.base.Engine (1347,)
2021-02-01 11:01:03,403 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,403 INFO sqlalchemy.engine.base.Engine (1348,)
2021-02-01 11:01:03,407 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"

WHERE "Positions".id = ?
2021-02-01 11:01:03,409 INFO sqlalchemy.engine.base.Engine (1349,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:03,536 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:03,538 INFO sqlalchemy.engine.base.Engine ('F28',)
2021-02-01 11:01:03,543 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:03,544 INFO sqlalchemy.engine.base.Engine ((1350, 14.3, 14.3, 14.3, 152886.77900002545, 122585.61413904652), (1351, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152886.77900002545, 122585.61413904652), (1352, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152886.77900002545, 122585.61413904652), (1353, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152886.77900002545, 122585.61413904652), (1354, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152886.77900002545, 122585.61413904652), (1355, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152886.77900002545, 122585.61413904652), (1356, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152886.77900002545, 122585.61413904652), (1357, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152886.77900002545, 122585.61413904652)  ... displaying 10 of 50 total bound parameter sets ...  (1398, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152886.77900002545, 122585.61413904652), (1399, 135.9, 135.9, 135.9, 152886.77900002545, 122585.61413904652))
2021-02-01 11:01:03,548 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:03,549 INFO sqlalchemy.engine.base.Engine ((675, 'F28', 0, 'Anhydrite', 1350, 1351), (676, 'F28', 1, 'Sandstone, grey, vf-f', 1352, 1353), (677, 'F28', 2, 'Anhydrite', 1354, 1355), (678, 'F28', 3, 'Dolomite', 1356, 1357), (679, 'F28', 4, 'Anhydrite', 1358, 1359), (680, 'F28', 5, 'Sandstone, grey, vf-f', 1360, 1361), (681, 'F28', 6, 'Siltstone, red', 1362, 1363), (682, 'F28', 7, 'Dolomite', 1364, 1365)  ... displaying 10 of 25 total bound parameter sets ...  (698, 'F28', 23, 'Limestone', 1396, 1397), (699, 'F28', 24, 'Volcanic', 1398, 1399))
2021-02-01 11:01:03,551 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:03,656 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:03,657 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:03,659 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:03,662 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:03,664 INFO sqlalchemy.engine.base.Engine ('F28',)
2021-02-01 11:01:03,667 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,668 INFO sqlalchemy.engine.base.Engine (1350,)
2021-02-01 11:01:03,670 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,671 INFO sqlalchemy.engine.base.Engine (1351,)
2021-02-01 11:01:03,674 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,675 INFO sqlalchemy.engine.base.Engine (1352,)
2021-02-01 11:01:03,680 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,681 INFO sqlalchemy.engine.base.Engine (1353,)
2021-02-01 11:01:03,683 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,685 INFO sqlalchemy.engine.base.Engine (1354,)
2021-02-01 11:01:03,688 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,690 INFO sqlalchemy.engine.base.Engine (1355,)
2021-02-01 11:01:03,693 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,694 INFO sqlalchemy.engine.base.Engine (1356,)
2021-02-01 11:01:03,696 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,697 INFO sqlalchemy.engine.base.Engine (1357,)
2021-02-01 11:01:03,701 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,704 INFO sqlalchemy.engine.base.Engine (1358,)
2021-02-01 11:01:03,706 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,708 INFO sqlalchemy.engine.base.Engine (1359,)
2021-02-01 11:01:03,710 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,712 INFO sqlalchemy.engine.base.Engine (1360,)
2021-02-01 11:01:03,714 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,716 INFO sqlalchemy.engine.base.Engine (1361,)
2021-02-01 11:01:03,718 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:03,719 INFO sqlalchemy.engine.base.Engine (1362,)
2021-02-01 11:01:03,721 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,722 INFO sqlalchemy.engine.base.Engine (1363,)
2021-02-01 11:01:03,724 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,726 INFO sqlalchemy.engine.base.Engine (1364,)
2021-02-01 11:01:03,729 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,730 INFO sqlalchemy.engine.base.Engine (1365,)
2021-02-01 11:01:03,735 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,736 INFO sqlalchemy.engine.base.Engine (1366,)
2021-02-01 11:01:03,737 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,738 INFO sqlalchemy.engine.base.Engine (1367,)
2021-02-01 11:01:03,740 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,741 INFO sqlalchemy.engine.base.Engine (1368,)
2021-02-01 11:01:03,743 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,744 INFO sqlalchemy.engine.base.Engine (1369,)
2021-02-01 11:01:03,747 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,751 INFO sqlalchemy.engine.base.Engine (1370,)
2021-02-01 11:01:03,752 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,754 INFO sqlalchemy.engine.base.Engine (1371,)
2021-02-01 11:01:03,755 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,756 INFO sqlalchemy.engine.base.Engine (1372,)
2021-02-01 11:01:03,758 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,763 INFO sqlalchemy.engine.base.Engine (1373,)
2021-02-01 11:01:03,765 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,766 INFO sqlalchemy.engine.base.Engine (1374,)
2021-02-01 11:01:03,768 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,769 INFO sqlalchemy.engine.base.Engine (1375,)
2021-02-01 11:01:03,770 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,771 INFO sqlalchemy.engine.base.Engine (1376,)
2021-02-01 11:01:03,773 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,774 INFO sqlalchemy.engine.base.Engine (1377,)
2021-02-01 11:01:03,776 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,777 INFO sqlalchemy.engine.base.Engine (1378,)
2021-02-01 11:01:03,779 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,780 INFO sqlalchemy.engine.base.Engine (1379,)
2021-02-01 11:01:03,782 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,783 INFO sqlalchemy.engine.base.Engine (1380,)
2021-02-01 11:01:03,785 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,786 INFO sqlalchemy.engine.base.Engine (1381,)
2021-02-01 11:01:03,788 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,789 INFO sqlalchemy.engine.base.Engine (1382,)
2021-02-01 11:01:03,790 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:03,795 INFO sqlalchemy.engine.base.Engine (1383,)
2021-02-01 11:01:03,803 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,804 INFO sqlalchemy.engine.base.Engine (1384,)
2021-02-01 11:01:03,807 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,808 INFO sqlalchemy.engine.base.Engine (1385,)
2021-02-01 11:01:03,810 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,812 INFO sqlalchemy.engine.base.Engine (1386,)
2021-02-01 11:01:03,815 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,817 INFO sqlalchemy.engine.base.Engine (1387,)
2021-02-01 11:01:03,819 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,820 INFO sqlalchemy.engine.base.Engine (1388,)
2021-02-01 11:01:03,823 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,824 INFO sqlalchemy.engine.base.Engine (1389,)
2021-02-01 11:01:03,826 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,828 INFO sqlalchemy.engine.base.Engine (1390,)
2021-02-01 11:01:03,833 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,836 INFO sqlalchemy.engine.base.Engine (1391,)
2021-02-01 11:01:03,838 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,840 INFO sqlalchemy.engine.base.Engine (1392,)
2021-02-01 11:01:03,843 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,847 INFO sqlalchemy.engine.base.Engine (1393,)
2021-02-01 11:01:03,849 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,852 INFO sqlalchemy.engine.base.Engine (1394,)
2021-02-01 11:01:03,853 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,854 INFO sqlalchemy.engine.base.Engine (1395,)
2021-02-01 11:01:03,857 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,859 INFO sqlalchemy.engine.base.Engine (1396,)
2021-02-01 11:01:03,861 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,862 INFO sqlalchemy.engine.base.Engine (1397,)
2021-02-01 11:01:03,865 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,867 INFO sqlalchemy.engine.base.Engine (1398,)
2021-02-01 11:01:03,869 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:03,871 INFO sqlalchemy.engine.base.Engine (1399,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:04,018 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:04,019 INFO sqlalchemy.engine.base.Engine ('F29',)
2021-02-01 11:01:04,022 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:04,024 INFO sqlalchemy.engine.base.Engine ((1400, 14.3, 14.3, 14.3, 152881.7110000254, 122582.22613904905), (1401, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152881.7110000254, 122582.22613904905), (1402, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152881.7110000254, 122582.22613904905), (1403, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152881.7110000254, 122582.22613904905), (1404, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152881.7110000254, 122582.22613904905), (1405, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152881.7110000254, 122582.22613904905), (1406, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152881.7110000254, 122582.22613904905), (1407, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152881.7110000254, 122582.22613904905)  ... displaying 10 of 50 total bound parameter sets ...  (1448, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152881.7110000254, 122582.22613904905), (1449, 135.9, 135.9, 135.9, 152881.7110000254, 122582.22613904905))
2021-02-01 11:01:04,029 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:04,030 INFO sqlalchemy.engine.base.Engine ((700, 'F29', 0, 'Anhydrite', 1400, 1401), (701, 'F29', 1, 'Sandstone, grey, vf-f', 1402, 1403), (702, 'F29', 2, 'Anhydrite', 1404, 1405), (703, 'F29', 3, 'Dolomite', 1406, 1407), (704, 'F29', 4, 'Anhydrite', 1408, 1409), (705, 'F29', 5, 'Sandstone, grey, vf-f', 1410, 1411), (706, 'F29', 6, 'Siltstone, red', 1412, 1413), (707, 'F29', 7, 'Dolomite', 1414, 1415)  ... displaying 10 of 25 total bound parameter sets ...  (723, 'F29', 23, 'Limestone', 1446, 1447), (724, 'F29', 24, 'Volcanic', 1448, 1449))

2021-02-01 11:01:04,035 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:04,150 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:04,151 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:04,153 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:04,155 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:04,156 INFO sqlalchemy.engine.base.Engine ('F29',)
2021-02-01 11:01:04,157 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,158 INFO sqlalchemy.engine.base.Engine (1400,)
2021-02-01 11:01:04,160 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,161 INFO sqlalchemy.engine.base.Engine (1401,)
2021-02-01 11:01:04,163 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,165 INFO sqlalchemy.engine.base.Engine (1402,)
2021-02-01 11:01:04,167 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,168 INFO sqlalchemy.engine.base.Engine (1403,)
2021-02-01 11:01:04,171 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,172 INFO sqlalchemy.engine.base.Engine (1404,)
2021-02-01 11:01:04,175 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,176 INFO sqlalchemy.engine.base.Engine (1405,)
2021-02-01 11:01:04,178 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,179 INFO sqlalchemy.engine.base.Engine (1406,)
2021-02-01 11:01:04,181 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,183 INFO sqlalchemy.engine.base.Engine (1407,)
2021-02-01 11:01:04,186 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,187 INFO sqlalchemy.engine.base.Engine (1408,)
2021-02-01 11:01:04,190 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,192 INFO sqlalchemy.engine.base.Engine (1409,)
2021-02-01 11:01:04,197 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,198 INFO sqlalchemy.engine.base.Engine (1410,)
2021-02-01 11:01:04,200 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,201 INFO sqlalchemy.engine.base.Engine (1411,)
2021-02-01 11:01:04,203 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,205 INFO sqlalchemy.engine.base.Engine (1412,)
2021-02-01 11:01:04,210 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,213 INFO sqlalchemy.engine.base.Engine (1413,)
2021-02-01 11:01:04,218 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,219 INFO sqlalchemy.engine.base.Engine (1414,)
2021-02-01 11:01:04,220 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,221 INFO sqlalchemy.engine.base.Engine (1415,)
2021-02-01 11:01:04,224 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,225 INFO sqlalchemy.engine.base.Engine (1416,)
2021-02-01 11:01:04,228 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,229 INFO sqlalchemy.engine.base.Engine (1417,)
2021-02-01 11:01:04,232 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:04,233 INFO sqlalchemy.engine.base.Engine (1418,)
2021-02-01 11:01:04,235 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,237 INFO sqlalchemy.engine.base.Engine (1419,)
2021-02-01 11:01:04,239 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,240 INFO sqlalchemy.engine.base.Engine (1420,)
2021-02-01 11:01:04,245 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,250 INFO sqlalchemy.engine.base.Engine (1421,)
2021-02-01 11:01:04,252 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,254 INFO sqlalchemy.engine.base.Engine (1422,)
2021-02-01 11:01:04,256 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,257 INFO sqlalchemy.engine.base.Engine (1423,)
2021-02-01 11:01:04,261 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,262 INFO sqlalchemy.engine.base.Engine (1424,)
2021-02-01 11:01:04,266 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,269 INFO sqlalchemy.engine.base.Engine (1425,)
2021-02-01 11:01:04,271 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,273 INFO sqlalchemy.engine.base.Engine (1426,)
2021-02-01 11:01:04,276 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,277 INFO sqlalchemy.engine.base.Engine (1427,)
2021-02-01 11:01:04,279 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,280 INFO sqlalchemy.engine.base.Engine (1428,)
2021-02-01 11:01:04,284 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,285 INFO sqlalchemy.engine.base.Engine (1429,)
2021-02-01 11:01:04,291 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,292 INFO sqlalchemy.engine.base.Engine (1430,)
2021-02-01 11:01:04,295 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,295 INFO sqlalchemy.engine.base.Engine (1431,)
2021-02-01 11:01:04,298 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,299 INFO sqlalchemy.engine.base.Engine (1432,)
2021-02-01 11:01:04,301 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,303 INFO sqlalchemy.engine.base.Engine (1433,)
2021-02-01 11:01:04,305 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,306 INFO sqlalchemy.engine.base.Engine (1434,)
2021-02-01 11:01:04,308 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,309 INFO sqlalchemy.engine.base.Engine (1435,)
2021-02-01 11:01:04,312 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,315 INFO sqlalchemy.engine.base.Engine (1436,)
2021-02-01 11:01:04,317 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,318 INFO sqlalchemy.engine.base.Engine (1437,)
2021-02-01 11:01:04,320 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,321 INFO sqlalchemy.engine.base.Engine (1438,)
2021-02-01 11:01:04,323 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:04,325 INFO sqlalchemy.engine.base.Engine (1439,)
2021-02-01 11:01:04,328 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,330 INFO sqlalchemy.engine.base.Engine (1440,)
2021-02-01 11:01:04,332 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,333 INFO sqlalchemy.engine.base.Engine (1441,)
2021-02-01 11:01:04,336 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,336 INFO sqlalchemy.engine.base.Engine (1442,)
2021-02-01 11:01:04,338 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,339 INFO sqlalchemy.engine.base.Engine (1443,)
2021-02-01 11:01:04,341 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,342 INFO sqlalchemy.engine.base.Engine (1444,)
2021-02-01 11:01:04,344 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,345 INFO sqlalchemy.engine.base.Engine (1445,)
2021-02-01 11:01:04,347 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,352 INFO sqlalchemy.engine.base.Engine (1446,)
2021-02-01 11:01:04,355 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,356 INFO sqlalchemy.engine.base.Engine (1447,)
2021-02-01 11:01:04,358 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,359 INFO sqlalchemy.engine.base.Engine (1448,)
2021-02-01 11:01:04,362 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,365 INFO sqlalchemy.engine.base.Engine (1449,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:04,489 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:04,490 INFO sqlalchemy.engine.base.Engine ((1450, 14.3, 14.3, 14.3, 152893.79900002544, 122593.65913904738), (1451, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152893.79900002544, 122593.65913904738), (1452, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152893.79900002544, 122593.65913904738), (1453, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152893.79900002544, 122593.65913904738), (1454, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152893.79900002544, 122593.65913904738), (1455, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152893.79900002544, 122593.65913904738), (1456, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152893.79900002544, 122593.65913904738), (1457, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152893.79900002544, 122593.65913904738)  ... displaying 10 of 50 total bound parameter sets ...  (1498, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152893.79900002544, 122593.65913904738), (1499, 135.9, 135.9, 135.9, 152893.79900002544, 122593.65913904738))
2021-02-01 11:01:04,494 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:04,496 INFO sqlalchemy.engine.base.Engine ('F30',)
2021-02-01 11:01:04,502 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:04,503 INFO sqlalchemy.engine.base.Engine ((725, 'F30', 0, 'Anhydrite', 1450, 1451), (726, 'F30', 1, 'Sandstone, grey, vf-f', 1452, 1453), (727, 'F30', 2, 'Anhydrite', 1454, 1455), (728, 'F30', 3, 'Dolomite', 1456, 1457), (729, 'F30', 4, 'Anhydrite', 1458, 1459), (730, 'F30', 5, 'Sandstone, grey, vf-f', 1460, 1461), (731, 'F30', 6, 'Siltstone, red', 1462, 1463), (732, 'F30', 7, 'Dolomite', 1464, 1465)  ... displaying 10 of 25 total bound parameter sets ...  (748, 'F30', 23, 'Limestone', 1496, 1497), (749, 'F30', 24, 'Volcanic', 1498, 1499))
2021-02-01 11:01:04,505 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:04,624 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:04,626 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:04,628 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:04,631 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:04,634 INFO sqlalchemy.engine.base.Engine ('F30',)
2021-02-01 11:01:04,639 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,640 INFO sqlalchemy.engine.base.Engine (1450,)
2021-02-01 11:01:04,642 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,644 INFO sqlalchemy.engine.base.Engine (1451,)
2021-02-01 11:01:04,647 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,648 INFO sqlalchemy.engine.base.Engine (1452,)

2021-02-01 11:01:04,650 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,651 INFO sqlalchemy.engine.base.Engine (1453,)
2021-02-01 11:01:04,654 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,655 INFO sqlalchemy.engine.base.Engine (1454,)
2021-02-01 11:01:04,657 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,659 INFO sqlalchemy.engine.base.Engine (1455,)
2021-02-01 11:01:04,661 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,663 INFO sqlalchemy.engine.base.Engine (1456,)
2021-02-01 11:01:04,666 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,667 INFO sqlalchemy.engine.base.Engine (1457,)
2021-02-01 11:01:04,669 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,670 INFO sqlalchemy.engine.base.Engine (1458,)
2021-02-01 11:01:04,672 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,675 INFO sqlalchemy.engine.base.Engine (1459,)
2021-02-01 11:01:04,677 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,679 INFO sqlalchemy.engine.base.Engine (1460,)
2021-02-01 11:01:04,686 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,690 INFO sqlalchemy.engine.base.Engine (1461,)
2021-02-01 11:01:04,694 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,695 INFO sqlalchemy.engine.base.Engine (1462,)
2021-02-01 11:01:04,697 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,698 INFO sqlalchemy.engine.base.Engine (1463,)
2021-02-01 11:01:04,700 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,701 INFO sqlalchemy.engine.base.Engine (1464,)
2021-02-01 11:01:04,702 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,703 INFO sqlalchemy.engine.base.Engine (1465,)
2021-02-01 11:01:04,709 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,710 INFO sqlalchemy.engine.base.Engine (1466,)
2021-02-01 11:01:04,714 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,715 INFO sqlalchemy.engine.base.Engine (1467,)
2021-02-01 11:01:04,717 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,718 INFO sqlalchemy.engine.base.Engine (1468,)
2021-02-01 11:01:04,720 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,720 INFO sqlalchemy.engine.base.Engine (1469,)
2021-02-01 11:01:04,722 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,724 INFO sqlalchemy.engine.base.Engine (1470,)
2021-02-01 11:01:04,730 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,731 INFO sqlalchemy.engine.base.Engine (1471,)
2021-02-01 11:01:04,732 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,733 INFO sqlalchemy.engine.base.Engine (1472,)
2021-02-01 11:01:04,735 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:04,736 INFO sqlalchemy.engine.base.Engine (1473,)
2021-02-01 11:01:04,739 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,743 INFO sqlalchemy.engine.base.Engine (1474,)
2021-02-01 11:01:04,747 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,749 INFO sqlalchemy.engine.base.Engine (1475,)
2021-02-01 11:01:04,752 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,753 INFO sqlalchemy.engine.base.Engine (1476,)
2021-02-01 11:01:04,756 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,757 INFO sqlalchemy.engine.base.Engine (1477,)
2021-02-01 11:01:04,759 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,761 INFO sqlalchemy.engine.base.Engine (1478,)
2021-02-01 11:01:04,763 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,764 INFO sqlalchemy.engine.base.Engine (1479,)
2021-02-01 11:01:04,770 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,771 INFO sqlalchemy.engine.base.Engine (1480,)
2021-02-01 11:01:04,773 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,775 INFO sqlalchemy.engine.base.Engine (1481,)
2021-02-01 11:01:04,778 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,781 INFO sqlalchemy.engine.base.Engine (1482,)
2021-02-01 11:01:04,783 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,784 INFO sqlalchemy.engine.base.Engine (1483,)
2021-02-01 11:01:04,787 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,788 INFO sqlalchemy.engine.base.Engine (1484,)
2021-02-01 11:01:04,791 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,792 INFO sqlalchemy.engine.base.Engine (1485,)
2021-02-01 11:01:04,794 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,795 INFO sqlalchemy.engine.base.Engine (1486,)
2021-02-01 11:01:04,799 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,802 INFO sqlalchemy.engine.base.Engine (1487,)
2021-02-01 11:01:04,805 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,807 INFO sqlalchemy.engine.base.Engine (1488,)
2021-02-01 11:01:04,809 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,811 INFO sqlalchemy.engine.base.Engine (1489,)
2021-02-01 11:01:04,813 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,814 INFO sqlalchemy.engine.base.Engine (1490,)
2021-02-01 11:01:04,818 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,819 INFO sqlalchemy.engine.base.Engine (1491,)
2021-02-01 11:01:04,822 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,823 INFO sqlalchemy.engine.base.Engine (1492,)
2021-02-01 11:01:04,825 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,829 INFO sqlalchemy.engine.base.Engine (1493,)
2021-02-01 11:01:04,832 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:04,833 INFO sqlalchemy.engine.base.Engine (1494,)
2021-02-01 11:01:04,835 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,837 INFO sqlalchemy.engine.base.Engine (1495,)
2021-02-01 11:01:04,841 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,844 INFO sqlalchemy.engine.base.Engine (1496,)
2021-02-01 11:01:04,850 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,853 INFO sqlalchemy.engine.base.Engine (1497,)
2021-02-01 11:01:04,856 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,857 INFO sqlalchemy.engine.base.Engine (1498,)
2021-02-01 11:01:04,859 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:04,861 INFO sqlalchemy.engine.base.Engine (1499,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:04,990 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:04,999 INFO sqlalchemy.engine.base.Engine ((1500, 14.3, 14.3, 14.3, 152886.11900002538, 122594.53213904705), (1501, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152886.11900002538, 122594.53213904705), (1502, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152886.11900002538, 122594.53213904705), (1503, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152886.11900002538, 122594.53213904705), (1504, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152886.11900002538, 122594.53213904705), (1505, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152886.11900002538, 122594.53213904705), (1506, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152886.11900002538, 122594.53213904705), (1507, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152886.11900002538, 122594.53213904705)  ... displaying 10 of 50 total bound parameter sets ...  (1548, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152886.11900002538, 122594.53213904705), (1549, 135.9, 135.9, 135.9, 152886.11900002538, 122594.53213904705))
2021-02-01 11:01:05,002 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:05,003 INFO sqlalchemy.engine.base.Engine ('F31',)
2021-02-01 11:01:05,008 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:05,009 INFO sqlalchemy.engine.base.Engine ((750, 'F31', 0, 'Anhydrite', 1500, 1501), (751, 'F31', 1, 'Sandstone, grey, vf-f', 1502, 1503), (752, 'F31', 2, 'Anhydrite', 1504, 1505), (753, 'F31', 3, 'Dolomite', 1506, 1507), (754, 'F31', 4, 'Anhydrite', 1508, 1509), (755, 'F31', 5, 'Sandstone, grey, vf-f', 1510, 1511), (756, 'F31', 6, 'Siltstone, red', 1512, 1513), (757, 'F31', 7, 'Dolomite', 1514, 1515)  ... displaying 10 of 25 total bound parameter sets ...  (773, 'F31', 23, 'Limestone', 1546, 1547), (774, 'F31', 24, 'Volcanic', 1548, 1549))
2021-02-01 11:01:05,018 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:05,083 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:05,084 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:05,085 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:05,088 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:05,089 INFO sqlalchemy.engine.base.Engine ('F31',)
2021-02-01 11:01:05,091 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,092 INFO sqlalchemy.engine.base.Engine (1500,)
2021-02-01 11:01:05,094 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,095 INFO sqlalchemy.engine.base.Engine (1501,)
2021-02-01 11:01:05,098 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,099 INFO sqlalchemy.engine.base.Engine (1502,)
2021-02-01 11:01:05,101 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,101 INFO sqlalchemy.engine.base.Engine (1503,)
2021-02-01 11:01:05,103 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,104 INFO sqlalchemy.engine.base.Engine (1504,)
2021-02-01 11:01:05,106 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,107 INFO sqlalchemy.engine.base.Engine (1505,)
2021-02-01 11:01:05,109 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,111 INFO sqlalchemy.engine.base.Engine (1506,)
2021-02-01 11:01:05,112 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,113 INFO sqlalchemy.engine.base.Engine (1507,)

2021-02-01 11:01:05,115 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,116 INFO sqlalchemy.engine.base.Engine (1508,)
2021-02-01 11:01:05,119 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,120 INFO sqlalchemy.engine.base.Engine (1509,)
2021-02-01 11:01:05,123 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,124 INFO sqlalchemy.engine.base.Engine (1510,)
2021-02-01 11:01:05,126 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,128 INFO sqlalchemy.engine.base.Engine (1511,)
2021-02-01 11:01:05,130 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,132 INFO sqlalchemy.engine.base.Engine (1512,)
2021-02-01 11:01:05,133 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,135 INFO sqlalchemy.engine.base.Engine (1513,)
2021-02-01 11:01:05,140 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,141 INFO sqlalchemy.engine.base.Engine (1514,)
2021-02-01 11:01:05,144 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,145 INFO sqlalchemy.engine.base.Engine (1515,)
2021-02-01 11:01:05,151 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,152 INFO sqlalchemy.engine.base.Engine (1516,)
2021-02-01 11:01:05,153 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,154 INFO sqlalchemy.engine.base.Engine (1517,)
2021-02-01 11:01:05,156 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,159 INFO sqlalchemy.engine.base.Engine (1518,)
2021-02-01 11:01:05,162 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,163 INFO sqlalchemy.engine.base.Engine (1519,)
2021-02-01 11:01:05,166 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,167 INFO sqlalchemy.engine.base.Engine (1520,)
2021-02-01 11:01:05,169 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,171 INFO sqlalchemy.engine.base.Engine (1521,)
2021-02-01 11:01:05,178 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,179 INFO sqlalchemy.engine.base.Engine (1522,)
2021-02-01 11:01:05,181 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,184 INFO sqlalchemy.engine.base.Engine (1523,)
2021-02-01 11:01:05,187 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,188 INFO sqlalchemy.engine.base.Engine (1524,)
2021-02-01 11:01:05,190 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,191 INFO sqlalchemy.engine.base.Engine (1525,)
2021-02-01 11:01:05,194 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,197 INFO sqlalchemy.engine.base.Engine (1526,)
2021-02-01 11:01:05,203 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,204 INFO sqlalchemy.engine.base.Engine (1527,)
2021-02-01 11:01:05,207 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:05,208 INFO sqlalchemy.engine.base.Engine (1528,)
2021-02-01 11:01:05,212 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,213 INFO sqlalchemy.engine.base.Engine (1529,)
2021-02-01 11:01:05,216 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,217 INFO sqlalchemy.engine.base.Engine (1530,)
2021-02-01 11:01:05,221 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,223 INFO sqlalchemy.engine.base.Engine (1531,)
2021-02-01 11:01:05,227 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,229 INFO sqlalchemy.engine.base.Engine (1532,)
2021-02-01 11:01:05,232 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,233 INFO sqlalchemy.engine.base.Engine (1533,)
2021-02-01 11:01:05,236 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,237 INFO sqlalchemy.engine.base.Engine (1534,)
2021-02-01 11:01:05,240 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,242 INFO sqlalchemy.engine.base.Engine (1535,)
2021-02-01 11:01:05,247 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,248 INFO sqlalchemy.engine.base.Engine (1536,)
2021-02-01 11:01:05,251 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,252 INFO sqlalchemy.engine.base.Engine (1537,)
2021-02-01 11:01:05,254 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,256 INFO sqlalchemy.engine.base.Engine (1538,)
2021-02-01 11:01:05,258 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,262 INFO sqlalchemy.engine.base.Engine (1539,)
2021-02-01 11:01:05,266 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,267 INFO sqlalchemy.engine.base.Engine (1540,)
2021-02-01 11:01:05,269 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,270 INFO sqlalchemy.engine.base.Engine (1541,)
2021-02-01 11:01:05,273 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,275 INFO sqlalchemy.engine.base.Engine (1542,)
2021-02-01 11:01:05,278 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,281 INFO sqlalchemy.engine.base.Engine (1543,)
2021-02-01 11:01:05,284 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,285 INFO sqlalchemy.engine.base.Engine (1544,)
2021-02-01 11:01:05,289 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,290 INFO sqlalchemy.engine.base.Engine (1545,)
2021-02-01 11:01:05,293 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,294 INFO sqlalchemy.engine.base.Engine (1546,)
2021-02-01 11:01:05,296 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,298 INFO sqlalchemy.engine.base.Engine (1547,)
2021-02-01 11:01:05,300 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,301 INFO sqlalchemy.engine.base.Engine (1548,)
2021-02-01 11:01:05,306 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:05,309 INFO sqlalchemy.engine.base.Engine (1549,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:05,450 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:05,451 INFO sqlalchemy.engine.base.Engine ((1550, 14.3, 14.3, 14.3, 152891.25200002544, 122595.00913904795), (1551, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152891.25200002544, 122595.00913904795), (1552, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152891.25200002544, 122595.00913904795), (1553, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152891.25200002544, 122595.00913904795), (1554, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152891.25200002544, 122595.00913904795), (1555, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152891.25200002544, 122595.00913904795), (1556, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152891.25200002544, 122595.00913904795), (1557, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152891.25200002544, 122595.00913904795)  ... displaying 10 of 50 total bound parameter sets ...  (1598, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152891.25200002544, 122595.00913904795), (1599, 135.9, 135.9, 135.9, 152891.25200002544, 122595.00913904795))
2021-02-01 11:01:05,455 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:05,456 INFO sqlalchemy.engine.base.Engine ('F32',)
2021-02-01 11:01:05,460 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:05,462 INFO sqlalchemy.engine.base.Engine ((775, 'F32', 0, 'Anhydrite', 1550, 1551), (776, 'F32', 1, 'Sandstone, grey, vf-f', 1552, 1553), (777, 'F32', 2, 'Anhydrite', 1554, 1555), (778, 'F32', 3, 'Dolomite', 1556, 1557), (779, 'F32', 4, 'Anhydrite', 1558, 1559), (780, 'F32', 5, 'Sandstone, grey, vf-f', 1560, 1561), (781, 'F32', 6, 'Siltstone, red', 1562, 1563), (782, 'F32', 7, 'Dolomite', 1564, 1565)  ... displaying 10 of 25 total bound parameter sets ...  (798, 'F32', 23, 'Limestone', 1596, 1597), (799, 'F32', 24, 'Volcanic', 1598, 1599))
2021-02-01 11:01:05,465 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:05,585 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:05,586 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:05,587 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:05,589 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:05,590 INFO sqlalchemy.engine.base.Engine ('F32',)
2021-02-01 11:01:05,593 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,595 INFO sqlalchemy.engine.base.Engine (1550,)
2021-02-01 11:01:05,598 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,599 INFO sqlalchemy.engine.base.Engine (1551,)
2021-02-01 11:01:05,601 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,602 INFO sqlalchemy.engine.base.Engine (1552,)
2021-02-01 11:01:05,605 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,606 INFO sqlalchemy.engine.base.Engine (1553,)
2021-02-01 11:01:05,608 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,610 INFO sqlalchemy.engine.base.Engine (1554,)
2021-02-01 11:01:05,611 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,613 INFO sqlalchemy.engine.base.Engine (1555,)
2021-02-01 11:01:05,617 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,618 INFO sqlalchemy.engine.base.Engine (1556,)
2021-02-01 11:01:05,620 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,621 INFO sqlalchemy.engine.base.Engine (1557,)
2021-02-01 11:01:05,625 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,627 INFO sqlalchemy.engine.base.Engine (1558,)
2021-02-01 11:01:05,630 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,634 INFO sqlalchemy.engine.base.Engine (1559,)
2021-02-01 11:01:05,637 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,638 INFO sqlalchemy.engine.base.Engine (1560,)
2021-02-01 11:01:05,643 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,644 INFO sqlalchemy.engine.base.Engine (1561,)
2021-02-01 11:01:05,646 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,647 INFO sqlalchemy.engine.base.Engine (1562,)

2021-02-01 11:01:05,650 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,651 INFO sqlalchemy.engine.base.Engine (1563,)
2021-02-01 11:01:05,655 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,658 INFO sqlalchemy.engine.base.Engine (1564,)
2021-02-01 11:01:05,663 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,664 INFO sqlalchemy.engine.base.Engine (1565,)
2021-02-01 11:01:05,668 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,669 INFO sqlalchemy.engine.base.Engine (1566,)
2021-02-01 11:01:05,670 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,672 INFO sqlalchemy.engine.base.Engine (1567,)
2021-02-01 11:01:05,675 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,677 INFO sqlalchemy.engine.base.Engine (1568,)
2021-02-01 11:01:05,679 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,681 INFO sqlalchemy.engine.base.Engine (1569,)
2021-02-01 11:01:05,687 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,688 INFO sqlalchemy.engine.base.Engine (1570,)
2021-02-01 11:01:05,691 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,692 INFO sqlalchemy.engine.base.Engine (1571,)
2021-02-01 11:01:05,695 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,696 INFO sqlalchemy.engine.base.Engine (1572,)
2021-02-01 11:01:05,697 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,698 INFO sqlalchemy.engine.base.Engine (1573,)
2021-02-01 11:01:05,702 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,704 INFO sqlalchemy.engine.base.Engine (1574,)
2021-02-01 11:01:05,707 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,713 INFO sqlalchemy.engine.base.Engine (1575,)
2021-02-01 11:01:05,716 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,718 INFO sqlalchemy.engine.base.Engine (1576,)
2021-02-01 11:01:05,720 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,727 INFO sqlalchemy.engine.base.Engine (1577,)
2021-02-01 11:01:05,730 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,732 INFO sqlalchemy.engine.base.Engine (1578,)
2021-02-01 11:01:05,734 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,735 INFO sqlalchemy.engine.base.Engine (1579,)
2021-02-01 11:01:05,741 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,742 INFO sqlalchemy.engine.base.Engine (1580,)
2021-02-01 11:01:05,745 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,745 INFO sqlalchemy.engine.base.Engine (1581,)
2021-02-01 11:01:05,748 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,749 INFO sqlalchemy.engine.base.Engine (1582,)
2021-02-01 11:01:05,751 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:05,752 INFO sqlalchemy.engine.base.Engine (1583,)
2021-02-01 11:01:05,754 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,756 INFO sqlalchemy.engine.base.Engine (1584,)
2021-02-01 11:01:05,761 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,762 INFO sqlalchemy.engine.base.Engine (1585,)
2021-02-01 11:01:05,765 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,766 INFO sqlalchemy.engine.base.Engine (1586,)
2021-02-01 11:01:05,768 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,770 INFO sqlalchemy.engine.base.Engine (1587,)
2021-02-01 11:01:05,772 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,773 INFO sqlalchemy.engine.base.Engine (1588,)
2021-02-01 11:01:05,776 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,777 INFO sqlalchemy.engine.base.Engine (1589,)
2021-02-01 11:01:05,783 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,785 INFO sqlalchemy.engine.base.Engine (1590,)
2021-02-01 11:01:05,787 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,789 INFO sqlalchemy.engine.base.Engine (1591,)
2021-02-01 11:01:05,793 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,794 INFO sqlalchemy.engine.base.Engine (1592,)
2021-02-01 11:01:05,796 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,799 INFO sqlalchemy.engine.base.Engine (1593,)
2021-02-01 11:01:05,802 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,808 INFO sqlalchemy.engine.base.Engine (1594,)
2021-02-01 11:01:05,811 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,812 INFO sqlalchemy.engine.base.Engine (1595,)
2021-02-01 11:01:05,817 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,818 INFO sqlalchemy.engine.base.Engine (1596,)
2021-02-01 11:01:05,821 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,822 INFO sqlalchemy.engine.base.Engine (1597,)
2021-02-01 11:01:05,825 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,828 INFO sqlalchemy.engine.base.Engine (1598,)
2021-02-01 11:01:05,835 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:05,837 INFO sqlalchemy.engine.base.Engine (1599,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:05,951 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:05,954 INFO sqlalchemy.engine.base.Engine ('F33',)
2021-02-01 11:01:05,959 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:05,961 INFO sqlalchemy.engine.base.Engine ((1600, 14.3, 14.3, 14.3, 152890.82431275706, 122583.5798753826), (1601, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152890.82431275706, 122583.5798753826), (1602, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152890.82431275706, 122583.5798753826), (1603, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152890.82431275706, 122583.5798753826), (1604, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152890.82431275706, 122583.5798753826), (1605, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152890.82431275706, 122583.5798753826), (1606, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152890.82431275706, 122583.5798753826), (1607, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152890.82431275706, 122583.5798753826)  ... displaying 10 of 50 total bound parameter sets ...  (1648, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152890.82431275706, 122583.5798753826), (1649, 135.9, 135.9, 135.9, 152890.82431275706, 122583.5798753826))
2021-02-01 11:01:05,966 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:05,967 INFO sqlalchemy.engine.base.Engine ((800, 'F33', 0, 'Anhydrite', 1600, 1601), (801, 'F33', 1, 'Sandstone, grey, vf-f', 1602, 1603), (802, 'F33', 2, 'Anhydrite', 1604, 1605), (803, 'F33', 3, 'Dolomite', 1606, 1607), (804, 'F33', 4, 'Anhydrite', 1608, 1609), (805, 'F33', 5, 'Sandstone, grey, vf-f', 1610, 1611), (806, 'F33', 6, 'Siltstone, red', 1612, 1613), (807, 'F33', 7, 'Dolomite', 1614, 1615)  ... displaying 10 of 25 total bound parameter sets ...  (823, 'F33', 23, 'Limestone', 1646, 1647), (824, 'F33', 24, 'Volcanic', 1648, 1649))

2021-02-01 11:01:05,971 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:06,084 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:06,087 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:06,090 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:06,093 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:06,095 INFO sqlalchemy.engine.base.Engine ('F33',)
2021-02-01 11:01:06,098 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,099 INFO sqlalchemy.engine.base.Engine (1600,)
2021-02-01 11:01:06,101 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,102 INFO sqlalchemy.engine.base.Engine (1601,)
2021-02-01 11:01:06,104 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,105 INFO sqlalchemy.engine.base.Engine (1602,)
2021-02-01 11:01:06,110 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,111 INFO sqlalchemy.engine.base.Engine (1603,)
2021-02-01 11:01:06,113 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,114 INFO sqlalchemy.engine.base.Engine (1604,)
2021-02-01 11:01:06,116 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,117 INFO sqlalchemy.engine.base.Engine (1605,)
2021-02-01 11:01:06,119 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,120 INFO sqlalchemy.engine.base.Engine (1606,)
2021-02-01 11:01:06,121 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,122 INFO sqlalchemy.engine.base.Engine (1607,)
2021-02-01 11:01:06,124 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,125 INFO sqlalchemy.engine.base.Engine (1608,)
2021-02-01 11:01:06,128 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,130 INFO sqlalchemy.engine.base.Engine (1609,)
2021-02-01 11:01:06,132 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,134 INFO sqlalchemy.engine.base.Engine (1610,)
2021-02-01 11:01:06,138 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,139 INFO sqlalchemy.engine.base.Engine (1611,)
2021-02-01 11:01:06,142 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,143 INFO sqlalchemy.engine.base.Engine (1612,)
2021-02-01 11:01:06,146 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,147 INFO sqlalchemy.engine.base.Engine (1613,)
2021-02-01 11:01:06,151 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,153 INFO sqlalchemy.engine.base.Engine (1614,)
2021-02-01 11:01:06,155 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,157 INFO sqlalchemy.engine.base.Engine (1615,)
2021-02-01 11:01:06,160 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,165 INFO sqlalchemy.engine.base.Engine (1616,)
2021-02-01 11:01:06,169 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,170 INFO sqlalchemy.engine.base.Engine (1617,)
2021-02-01 11:01:06,171 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:06,172 INFO sqlalchemy.engine.base.Engine (1618,)
2021-02-01 11:01:06,176 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,177 INFO sqlalchemy.engine.base.Engine (1619,)
2021-02-01 11:01:06,180 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,181 INFO sqlalchemy.engine.base.Engine (1620,)
2021-02-01 11:01:06,184 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,186 INFO sqlalchemy.engine.base.Engine (1621,)
2021-02-01 11:01:06,188 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,189 INFO sqlalchemy.engine.base.Engine (1622,)
2021-02-01 11:01:06,191 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,194 INFO sqlalchemy.engine.base.Engine (1623,)
2021-02-01 11:01:06,197 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,198 INFO sqlalchemy.engine.base.Engine (1624,)
2021-02-01 11:01:06,208 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,209 INFO sqlalchemy.engine.base.Engine (1625,)
2021-02-01 11:01:06,211 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,213 INFO sqlalchemy.engine.base.Engine (1626,)
2021-02-01 11:01:06,215 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,216 INFO sqlalchemy.engine.base.Engine (1627,)
2021-02-01 11:01:06,219 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,220 INFO sqlalchemy.engine.base.Engine (1628,)
2021-02-01 11:01:06,223 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,224 INFO sqlalchemy.engine.base.Engine (1629,)
2021-02-01 11:01:06,227 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,228 INFO sqlalchemy.engine.base.Engine (1630,)
2021-02-01 11:01:06,230 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,232 INFO sqlalchemy.engine.base.Engine (1631,)
2021-02-01 11:01:06,236 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,237 INFO sqlalchemy.engine.base.Engine (1632,)
2021-02-01 11:01:06,239 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,240 INFO sqlalchemy.engine.base.Engine (1633,)
2021-02-01 11:01:06,244 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,245 INFO sqlalchemy.engine.base.Engine (1634,)
2021-02-01 11:01:06,247 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,249 INFO sqlalchemy.engine.base.Engine (1635,)
2021-02-01 11:01:06,252 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,253 INFO sqlalchemy.engine.base.Engine (1636,)
2021-02-01 11:01:06,255 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,260 INFO sqlalchemy.engine.base.Engine (1637,)
2021-02-01 11:01:06,264 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,265 INFO sqlalchemy.engine.base.Engine (1638,)
2021-02-01 11:01:06,268 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:06,269 INFO sqlalchemy.engine.base.Engine (1639,)
2021-02-01 11:01:06,271 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,272 INFO sqlalchemy.engine.base.Engine (1640,)
2021-02-01 11:01:06,275 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,276 INFO sqlalchemy.engine.base.Engine (1641,)
2021-02-01 11:01:06,279 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,281 INFO sqlalchemy.engine.base.Engine (1642,)
2021-02-01 11:01:06,287 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,288 INFO sqlalchemy.engine.base.Engine (1643,)
2021-02-01 11:01:06,292 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,295 INFO sqlalchemy.engine.base.Engine (1644,)
2021-02-01 11:01:06,297 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,298 INFO sqlalchemy.engine.base.Engine (1645,)
2021-02-01 11:01:06,301 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,302 INFO sqlalchemy.engine.base.Engine (1646,)
2021-02-01 11:01:06,303 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,304 INFO sqlalchemy.engine.base.Engine (1647,)
2021-02-01 11:01:06,307 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,310 INFO sqlalchemy.engine.base.Engine (1648,)
2021-02-01 11:01:06,313 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,314 INFO sqlalchemy.engine.base.Engine (1649,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:06,439 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:06,443 INFO sqlalchemy.engine.base.Engine ('F34',)
2021-02-01 11:01:06,450 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:06,451 INFO sqlalchemy.engine.base.Engine ((1650, 14.3, 14.3, 14.3, 152892.8790000254, 122592.58713904768), (1651, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152892.8790000254, 122592.58713904768), (1652, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152892.8790000254, 122592.58713904768), (1653, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152892.8790000254, 122592.58713904768), (1654, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152892.8790000254, 122592.58713904768), (1655, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152892.8790000254, 122592.58713904768), (1656, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152892.8790000254, 122592.58713904768), (1657, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152892.8790000254, 122592.58713904768)  ... displaying 10 of 50 total bound parameter sets ...  (1698, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152892.8790000254, 122592.58713904768), (1699, 135.9, 135.9, 135.9, 152892.8790000254, 122592.58713904768))
2021-02-01 11:01:06,456 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:06,457 INFO sqlalchemy.engine.base.Engine ((825, 'F34', 0, 'Anhydrite', 1650, 1651), (826, 'F34', 1, 'Sandstone, grey, vf-f', 1652, 1653), (827, 'F34', 2, 'Anhydrite', 1654, 1655), (828, 'F34', 3, 'Dolomite', 1656, 1657), (829, 'F34', 4, 'Anhydrite', 1658, 1659), (830, 'F34', 5, 'Sandstone, grey, vf-f', 1660, 1661), (831, 'F34', 6, 'Siltstone, red', 1662, 1663), (832, 'F34', 7, 'Dolomite', 1664, 1665)  ... displaying 10 of 25 total bound parameter sets ...  (848, 'F34', 23, 'Limestone', 1696, 1697), (849, 'F34', 24, 'Volcanic', 1698, 1699))
2021-02-01 11:01:06,461 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:06,558 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:06,560 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:06,561 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:06,564 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:06,566 INFO sqlalchemy.engine.base.Engine ('F34',)
2021-02-01 11:01:06,569 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,570 INFO sqlalchemy.engine.base.Engine (1650,)
2021-02-01 11:01:06,573 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,574 INFO sqlalchemy.engine.base.Engine (1651,)
2021-02-01 11:01:06,576 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,579 INFO sqlalchemy.engine.base.Engine (1652,)

2021-02-01 11:01:06,581 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,582 INFO sqlalchemy.engine.base.Engine (1653,)
2021-02-01 11:01:06,585 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,589 INFO sqlalchemy.engine.base.Engine (1654,)
2021-02-01 11:01:06,592 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,593 INFO sqlalchemy.engine.base.Engine (1655,)
2021-02-01 11:01:06,596 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,597 INFO sqlalchemy.engine.base.Engine (1656,)
2021-02-01 11:01:06,599 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,600 INFO sqlalchemy.engine.base.Engine (1657,)
2021-02-01 11:01:06,603 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,604 INFO sqlalchemy.engine.base.Engine (1658,)
2021-02-01 11:01:06,606 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,607 INFO sqlalchemy.engine.base.Engine (1659,)
2021-02-01 11:01:06,610 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,612 INFO sqlalchemy.engine.base.Engine (1660,)
2021-02-01 11:01:06,615 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,616 INFO sqlalchemy.engine.base.Engine (1661,)
2021-02-01 11:01:06,618 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,618 INFO sqlalchemy.engine.base.Engine (1662,)
2021-02-01 11:01:06,620 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,622 INFO sqlalchemy.engine.base.Engine (1663,)
2021-02-01 11:01:06,624 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,625 INFO sqlalchemy.engine.base.Engine (1664,)
2021-02-01 11:01:06,628 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,629 INFO sqlalchemy.engine.base.Engine (1665,)
2021-02-01 11:01:06,631 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,635 INFO sqlalchemy.engine.base.Engine (1666,)
2021-02-01 11:01:06,639 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,640 INFO sqlalchemy.engine.base.Engine (1667,)
2021-02-01 11:01:06,643 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,645 INFO sqlalchemy.engine.base.Engine (1668,)
2021-02-01 11:01:06,651 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,651 INFO sqlalchemy.engine.base.Engine (1669,)
2021-02-01 11:01:06,654 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,655 INFO sqlalchemy.engine.base.Engine (1670,)
2021-02-01 11:01:06,656 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,658 INFO sqlalchemy.engine.base.Engine (1671,)
2021-02-01 11:01:06,659 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,662 INFO sqlalchemy.engine.base.Engine (1672,)
2021-02-01 11:01:06,666 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:06,667 INFO sqlalchemy.engine.base.Engine (1673,)
2021-02-01 11:01:06,669 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,670 INFO sqlalchemy.engine.base.Engine (1674,)
2021-02-01 11:01:06,672 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,673 INFO sqlalchemy.engine.base.Engine (1675,)
2021-02-01 11:01:06,676 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,677 INFO sqlalchemy.engine.base.Engine (1676,)
2021-02-01 11:01:06,683 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,686 INFO sqlalchemy.engine.base.Engine (1677,)
2021-02-01 11:01:06,689 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,693 INFO sqlalchemy.engine.base.Engine (1678,)
2021-02-01 11:01:06,695 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,699 INFO sqlalchemy.engine.base.Engine (1679,)
2021-02-01 11:01:06,702 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,704 INFO sqlalchemy.engine.base.Engine (1680,)
2021-02-01 11:01:06,706 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,707 INFO sqlalchemy.engine.base.Engine (1681,)
2021-02-01 11:01:06,710 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,711 INFO sqlalchemy.engine.base.Engine (1682,)
2021-02-01 11:01:06,714 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,715 INFO sqlalchemy.engine.base.Engine (1683,)
2021-02-01 11:01:06,718 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,718 INFO sqlalchemy.engine.base.Engine (1684,)
2021-02-01 11:01:06,721 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,722 INFO sqlalchemy.engine.base.Engine (1685,)
2021-02-01 11:01:06,724 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,726 INFO sqlalchemy.engine.base.Engine (1686,)
2021-02-01 11:01:06,728 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,729 INFO sqlalchemy.engine.base.Engine (1687,)
2021-02-01 11:01:06,732 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,734 INFO sqlalchemy.engine.base.Engine (1688,)
2021-02-01 11:01:06,736 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,739 INFO sqlalchemy.engine.base.Engine (1689,)
2021-02-01 11:01:06,742 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,743 INFO sqlalchemy.engine.base.Engine (1690,)
2021-02-01 11:01:06,746 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,747 INFO sqlalchemy.engine.base.Engine (1691,)
2021-02-01 11:01:06,750 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,751 INFO sqlalchemy.engine.base.Engine (1692,)
2021-02-01 11:01:06,753 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,756 INFO sqlalchemy.engine.base.Engine (1693,)
2021-02-01 11:01:06,760 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:06,761 INFO sqlalchemy.engine.base.Engine (1694,)
2021-02-01 11:01:06,762 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,764 INFO sqlalchemy.engine.base.Engine (1695,)
2021-02-01 11:01:06,767 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,768 INFO sqlalchemy.engine.base.Engine (1696,)
2021-02-01 11:01:06,769 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,771 INFO sqlalchemy.engine.base.Engine (1697,)
2021-02-01 11:01:06,773 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,774 INFO sqlalchemy.engine.base.Engine (1698,)
2021-02-01 11:01:06,779 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:06,781 INFO sqlalchemy.engine.base.Engine (1699,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:06,926 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:06,929 INFO sqlalchemy.engine.base.Engine ((1700, 14.3, 14.3, 14.3, 152885.19800002538, 122592.74513904564), (1701, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152885.19800002538, 122592.74513904564), (1702, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152885.19800002538, 122592.74513904564), (1703, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152885.19800002538, 122592.74513904564), (1704, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152885.19800002538, 122592.74513904564), (1705, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152885.19800002538, 122592.74513904564), (1706, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152885.19800002538, 122592.74513904564), (1707, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152885.19800002538, 122592.74513904564)  ... displaying 10 of 50 total bound parameter sets ...  (1748, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152885.19800002538, 122592.74513904564), (1749, 135.9, 135.9, 135.9, 152885.19800002538, 122592.74513904564))
2021-02-01 11:01:06,932 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:06,933 INFO sqlalchemy.engine.base.Engine ('F35',)
2021-02-01 11:01:06,936 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:06,937 INFO sqlalchemy.engine.base.Engine ((850, 'F35', 0, 'Anhydrite', 1700, 1701), (851, 'F35', 1, 'Sandstone, grey, vf-f', 1702, 1703), (852, 'F35', 2, 'Anhydrite', 1704, 1705), (853, 'F35', 3, 'Dolomite', 1706, 1707), (854, 'F35', 4, 'Anhydrite', 1708, 1709), (855, 'F35', 5, 'Sandstone, grey, vf-f', 1710, 1711), (856, 'F35', 6, 'Siltstone, red', 1712, 1713), (857, 'F35', 7, 'Dolomite', 1714, 1715)  ... displaying 10 of 25 total bound parameter sets ...  (873, 'F35', 23, 'Limestone', 1746, 1747), (874, 'F35', 24, 'Volcanic', 1748, 1749))
2021-02-01 11:01:06,942 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:07,086 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:07,088 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:07,089 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:07,093 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:07,095 INFO sqlalchemy.engine.base.Engine ('F35',)
2021-02-01 11:01:07,101 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,102 INFO sqlalchemy.engine.base.Engine (1700,)
2021-02-01 11:01:07,104 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,105 INFO sqlalchemy.engine.base.Engine (1701,)
2021-02-01 11:01:07,107 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,107 INFO sqlalchemy.engine.base.Engine (1702,)
2021-02-01 11:01:07,109 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,110 INFO sqlalchemy.engine.base.Engine (1703,)
2021-02-01 11:01:07,113 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,114 INFO sqlalchemy.engine.base.Engine (1704,)
2021-02-01 11:01:07,116 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,117 INFO sqlalchemy.engine.base.Engine (1705,)
2021-02-01 11:01:07,120 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,121 INFO sqlalchemy.engine.base.Engine (1706,)
2021-02-01 11:01:07,122 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,123 INFO sqlalchemy.engine.base.Engine (1707,)

2021-02-01 11:01:07,124 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,129 INFO sqlalchemy.engine.base.Engine (1708,)
2021-02-01 11:01:07,131 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,133 INFO sqlalchemy.engine.base.Engine (1709,)
2021-02-01 11:01:07,135 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,136 INFO sqlalchemy.engine.base.Engine (1710,)
2021-02-01 11:01:07,138 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,140 INFO sqlalchemy.engine.base.Engine (1711,)
2021-02-01 11:01:07,143 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,144 INFO sqlalchemy.engine.base.Engine (1712,)
2021-02-01 11:01:07,150 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,152 INFO sqlalchemy.engine.base.Engine (1713,)
2021-02-01 11:01:07,154 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,154 INFO sqlalchemy.engine.base.Engine (1714,)
2021-02-01 11:01:07,157 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,158 INFO sqlalchemy.engine.base.Engine (1715,)
2021-02-01 11:01:07,162 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,163 INFO sqlalchemy.engine.base.Engine (1716,)
2021-02-01 11:01:07,165 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,165 INFO sqlalchemy.engine.base.Engine (1717,)
2021-02-01 11:01:07,168 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,169 INFO sqlalchemy.engine.base.Engine (1718,)
2021-02-01 11:01:07,170 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,171 INFO sqlalchemy.engine.base.Engine (1719,)
2021-02-01 11:01:07,173 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,175 INFO sqlalchemy.engine.base.Engine (1720,)
2021-02-01 11:01:07,181 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,184 INFO sqlalchemy.engine.base.Engine (1721,)
2021-02-01 11:01:07,186 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,187 INFO sqlalchemy.engine.base.Engine (1722,)
2021-02-01 11:01:07,189 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,189 INFO sqlalchemy.engine.base.Engine (1723,)
2021-02-01 11:01:07,192 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,193 INFO sqlalchemy.engine.base.Engine (1724,)
2021-02-01 11:01:07,197 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,198 INFO sqlalchemy.engine.base.Engine (1725,)
2021-02-01 11:01:07,201 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,203 INFO sqlalchemy.engine.base.Engine (1726,)
2021-02-01 11:01:07,205 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,206 INFO sqlalchemy.engine.base.Engine (1727,)
2021-02-01 11:01:07,209 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:07,211 INFO sqlalchemy.engine.base.Engine (1728,)
2021-02-01 11:01:07,214 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,215 INFO sqlalchemy.engine.base.Engine (1729,)
2021-02-01 11:01:07,217 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,219 INFO sqlalchemy.engine.base.Engine (1730,)
2021-02-01 11:01:07,221 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,222 INFO sqlalchemy.engine.base.Engine (1731,)
2021-02-01 11:01:07,225 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,227 INFO sqlalchemy.engine.base.Engine (1732,)
2021-02-01 11:01:07,231 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,232 INFO sqlalchemy.engine.base.Engine (1733,)
2021-02-01 11:01:07,236 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,237 INFO sqlalchemy.engine.base.Engine (1734,)
2021-02-01 11:01:07,240 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,241 INFO sqlalchemy.engine.base.Engine (1735,)
2021-02-01 11:01:07,244 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,245 INFO sqlalchemy.engine.base.Engine (1736,)
2021-02-01 11:01:07,247 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,249 INFO sqlalchemy.engine.base.Engine (1737,)
2021-02-01 11:01:07,252 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,253 INFO sqlalchemy.engine.base.Engine (1738,)
2021-02-01 11:01:07,255 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,257 INFO sqlalchemy.engine.base.Engine (1739,)
2021-02-01 11:01:07,261 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,264 INFO sqlalchemy.engine.base.Engine (1740,)
2021-02-01 11:01:07,266 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,267 INFO sqlalchemy.engine.base.Engine (1741,)
2021-02-01 11:01:07,270 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,272 INFO sqlalchemy.engine.base.Engine (1742,)
2021-02-01 11:01:07,274 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,275 INFO sqlalchemy.engine.base.Engine (1743,)
2021-02-01 11:01:07,278 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,279 INFO sqlalchemy.engine.base.Engine (1744,)
2021-02-01 11:01:07,282 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,283 INFO sqlalchemy.engine.base.Engine (1745,)
2021-02-01 11:01:07,286 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,287 INFO sqlalchemy.engine.base.Engine (1746,)
2021-02-01 11:01:07,293 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,294 INFO sqlalchemy.engine.base.Engine (1747,)
2021-02-01 11:01:07,297 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,298 INFO sqlalchemy.engine.base.Engine (1748,)
2021-02-01 11:01:07,300 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:07,301 INFO sqlalchemy.engine.base.Engine (1749,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:07,418 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:07,422 INFO sqlalchemy.engine.base.Engine ('F36',)
2021-02-01 11:01:07,427 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:07,432 INFO sqlalchemy.engine.base.Engine ((1750, 14.3, 14.3, 14.3, 152888.16400002534, 122591.69413904753), (1751, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.16400002534, 122591.69413904753), (1752, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.16400002534, 122591.69413904753), (1753, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.16400002534, 122591.69413904753), (1754, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.16400002534, 122591.69413904753), (1755, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.16400002534, 122591.69413904753), (1756, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.16400002534, 122591.69413904753), (1757, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152888.16400002534, 122591.69413904753)  ... displaying 10 of 50 total bound parameter sets ...  (1798, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152888.16400002534, 122591.69413904753), (1799, 135.9, 135.9, 135.9, 152888.16400002534, 122591.69413904753))
2021-02-01 11:01:07,437 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:07,440 INFO sqlalchemy.engine.base.Engine ((875, 'F36', 0, 'Anhydrite', 1750, 1751), (876, 'F36', 1, 'Sandstone, grey, vf-f', 1752, 1753), (877, 'F36', 2, 'Anhydrite', 1754, 1755), (878, 'F36', 3, 'Dolomite', 1756, 1757), (879, 'F36', 4, 'Anhydrite', 1758, 1759), (880, 'F36', 5, 'Sandstone, grey, vf-f', 1760, 1761), (881, 'F36', 6, 'Siltstone, red', 1762, 1763), (882, 'F36', 7, 'Dolomite', 1764, 1765)  ... displaying 10 of 25 total bound parameter sets ...  (898, 'F36', 23, 'Limestone', 1796, 1797), (899, 'F36', 24, 'Volcanic', 1798, 1799))
2021-02-01 11:01:07,443 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:07,588 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:07,589 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:07,591 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:07,595 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:07,597 INFO sqlalchemy.engine.base.Engine ('F36',)
2021-02-01 11:01:07,600 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,601 INFO sqlalchemy.engine.base.Engine (1750,)
2021-02-01 11:01:07,603 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,604 INFO sqlalchemy.engine.base.Engine (1751,)
2021-02-01 11:01:07,607 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,608 INFO sqlalchemy.engine.base.Engine (1752,)
2021-02-01 11:01:07,613 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,615 INFO sqlalchemy.engine.base.Engine (1753,)
2021-02-01 11:01:07,617 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,618 INFO sqlalchemy.engine.base.Engine (1754,)
2021-02-01 11:01:07,620 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,621 INFO sqlalchemy.engine.base.Engine (1755,)
2021-02-01 11:01:07,625 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,626 INFO sqlalchemy.engine.base.Engine (1756,)
2021-02-01 11:01:07,631 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,632 INFO sqlalchemy.engine.base.Engine (1757,)
2021-02-01 11:01:07,635 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,636 INFO sqlalchemy.engine.base.Engine (1758,)
2021-02-01 11:01:07,639 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,641 INFO sqlalchemy.engine.base.Engine (1759,)
2021-02-01 11:01:07,646 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,647 INFO sqlalchemy.engine.base.Engine (1760,)
2021-02-01 11:01:07,649 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,650 INFO sqlalchemy.engine.base.Engine (1761,)
2021-02-01 11:01:07,655 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,655 INFO sqlalchemy.engine.base.Engine (1762,)

2021-02-01 11:01:07,660 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,661 INFO sqlalchemy.engine.base.Engine (1763,)
2021-02-01 11:01:07,662 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,663 INFO sqlalchemy.engine.base.Engine (1764,)
2021-02-01 11:01:07,665 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,666 INFO sqlalchemy.engine.base.Engine (1765,)
2021-02-01 11:01:07,668 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,670 INFO sqlalchemy.engine.base.Engine (1766,)
2021-02-01 11:01:07,674 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,675 INFO sqlalchemy.engine.base.Engine (1767,)
2021-02-01 11:01:07,677 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,678 INFO sqlalchemy.engine.base.Engine (1768,)
2021-02-01 11:01:07,681 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,682 INFO sqlalchemy.engine.base.Engine (1769,)
2021-02-01 11:01:07,684 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,685 INFO sqlalchemy.engine.base.Engine (1770,)
2021-02-01 11:01:07,687 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,688 INFO sqlalchemy.engine.base.Engine (1771,)
2021-02-01 11:01:07,693 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,693 INFO sqlalchemy.engine.base.Engine (1772,)
2021-02-01 11:01:07,696 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,697 INFO sqlalchemy.engine.base.Engine (1773,)
2021-02-01 11:01:07,699 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,700 INFO sqlalchemy.engine.base.Engine (1774,)
2021-02-01 11:01:07,703 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,704 INFO sqlalchemy.engine.base.Engine (1775,)
2021-02-01 11:01:07,706 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,707 INFO sqlalchemy.engine.base.Engine (1776,)
2021-02-01 11:01:07,710 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,711 INFO sqlalchemy.engine.base.Engine (1777,)
2021-02-01 11:01:07,714 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,716 INFO sqlalchemy.engine.base.Engine (1778,)
2021-02-01 11:01:07,718 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,719 INFO sqlalchemy.engine.base.Engine (1779,)
2021-02-01 11:01:07,721 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,722 INFO sqlalchemy.engine.base.Engine (1780,)
2021-02-01 11:01:07,724 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,726 INFO sqlalchemy.engine.base.Engine (1781,)
2021-02-01 11:01:07,728 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,729 INFO sqlalchemy.engine.base.Engine (1782,)
2021-02-01 11:01:07,732 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:07,734 INFO sqlalchemy.engine.base.Engine (1783,)
2021-02-01 11:01:07,738 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,740 INFO sqlalchemy.engine.base.Engine (1784,)
2021-02-01 11:01:07,742 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,743 INFO sqlalchemy.engine.base.Engine (1785,)
2021-02-01 11:01:07,745 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,746 INFO sqlalchemy.engine.base.Engine (1786,)
2021-02-01 11:01:07,748 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,749 INFO sqlalchemy.engine.base.Engine (1787,)
2021-02-01 11:01:07,752 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,753 INFO sqlalchemy.engine.base.Engine (1788,)
2021-02-01 11:01:07,756 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,757 INFO sqlalchemy.engine.base.Engine (1789,)
2021-02-01 11:01:07,763 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,765 INFO sqlalchemy.engine.base.Engine (1790,)
2021-02-01 11:01:07,768 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,769 INFO sqlalchemy.engine.base.Engine (1791,)
2021-02-01 11:01:07,771 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,772 INFO sqlalchemy.engine.base.Engine (1792,)
2021-02-01 11:01:07,775 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,778 INFO sqlalchemy.engine.base.Engine (1793,)
2021-02-01 11:01:07,781 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,783 INFO sqlalchemy.engine.base.Engine (1794,)
2021-02-01 11:01:07,786 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,788 INFO sqlalchemy.engine.base.Engine (1795,)
2021-02-01 11:01:07,791 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,792 INFO sqlalchemy.engine.base.Engine (1796,)
2021-02-01 11:01:07,794 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,797 INFO sqlalchemy.engine.base.Engine (1797,)
2021-02-01 11:01:07,801 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,803 INFO sqlalchemy.engine.base.Engine (1798,)
2021-02-01 11:01:07,805 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:07,807 INFO sqlalchemy.engine.base.Engine (1799,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:07,946 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:07,949 INFO sqlalchemy.engine.base.Engine ('F37',)
2021-02-01 11:01:07,953 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:07,954 INFO sqlalchemy.engine.base.Engine ((1800, 14.3, 14.3, 14.3, 152890.42400002544, 122593.64313904569), (1801, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152890.42400002544, 122593.64313904569), (1802, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152890.42400002544, 122593.64313904569), (1803, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152890.42400002544, 122593.64313904569), (1804, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152890.42400002544, 122593.64313904569), (1805, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152890.42400002544, 122593.64313904569), (1806, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152890.42400002544, 122593.64313904569), (1807, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152890.42400002544, 122593.64313904569)  ... displaying 10 of 50 total bound parameter sets ...  (1848, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152890.42400002544, 122593.64313904569), (1849, 135.9, 135.9, 135.9, 152890.42400002544, 122593.64313904569))
2021-02-01 11:01:07,960 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:07,961 INFO sqlalchemy.engine.base.Engine ((900, 'F37', 0, 'Anhydrite', 1800, 1801), (901, 'F37', 1, 'Sandstone, grey, vf-f', 1802, 1803), (902, 'F37', 2, 'Anhydrite', 1804, 1805), (903, 'F37', 3, 'Dolomite', 1806, 1807), (904, 'F37', 4, 'Anhydrite', 1808, 1809), (905, 'F37', 5, 'Sandstone, grey, vf-f', 1810, 1811), (906, 'F37', 6, 'Siltstone, red', 1812, 1813), (907, 'F37', 7, 'Dolomite', 1814, 1815)  ... displaying 10 of 25 total bound parameter sets ...  (923, 'F37', 23, 'Limestone', 1846, 1847), (924, 'F37', 24, 'Volcanic', 1848, 1849))

2021-02-01 11:01:07,965 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:08,088 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:08,089 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:08,093 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:08,096 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:08,097 INFO sqlalchemy.engine.base.Engine ('F37',)
2021-02-01 11:01:08,101 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,102 INFO sqlalchemy.engine.base.Engine (1800,)
2021-02-01 11:01:08,105 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,106 INFO sqlalchemy.engine.base.Engine (1801,)
2021-02-01 11:01:08,108 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,110 INFO sqlalchemy.engine.base.Engine (1802,)
2021-02-01 11:01:08,112 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,116 INFO sqlalchemy.engine.base.Engine (1803,)
2021-02-01 11:01:08,118 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,120 INFO sqlalchemy.engine.base.Engine (1804,)
2021-02-01 11:01:08,122 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,124 INFO sqlalchemy.engine.base.Engine (1805,)
2021-02-01 11:01:08,126 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,128 INFO sqlalchemy.engine.base.Engine (1806,)
2021-02-01 11:01:08,130 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,131 INFO sqlalchemy.engine.base.Engine (1807,)
2021-02-01 11:01:08,134 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,135 INFO sqlalchemy.engine.base.Engine (1808,)
2021-02-01 11:01:08,138 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,140 INFO sqlalchemy.engine.base.Engine (1809,)
2021-02-01 11:01:08,142 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,143 INFO sqlalchemy.engine.base.Engine (1810,)
2021-02-01 11:01:08,146 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,149 INFO sqlalchemy.engine.base.Engine (1811,)
2021-02-01 11:01:08,152 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,157 INFO sqlalchemy.engine.base.Engine (1812,)
2021-02-01 11:01:08,160 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,161 INFO sqlalchemy.engine.base.Engine (1813,)
2021-02-01 11:01:08,166 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,168 INFO sqlalchemy.engine.base.Engine (1814,)
2021-02-01 11:01:08,170 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,171 INFO sqlalchemy.engine.base.Engine (1815,)
2021-02-01 11:01:08,173 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,173 INFO sqlalchemy.engine.base.Engine (1816,)
2021-02-01 11:01:08,175 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,176 INFO sqlalchemy.engine.base.Engine (1817,)
2021-02-01 11:01:08,180 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:08,181 INFO sqlalchemy.engine.base.Engine (1818,)
2021-02-01 11:01:08,183 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,184 INFO sqlalchemy.engine.base.Engine (1819,)
2021-02-01 11:01:08,186 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,187 INFO sqlalchemy.engine.base.Engine (1820,)
2021-02-01 11:01:08,189 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,190 INFO sqlalchemy.engine.base.Engine (1821,)
2021-02-01 11:01:08,193 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,193 INFO sqlalchemy.engine.base.Engine (1822,)
2021-02-01 11:01:08,196 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,197 INFO sqlalchemy.engine.base.Engine (1823,)
2021-02-01 11:01:08,200 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,201 INFO sqlalchemy.engine.base.Engine (1824,)
2021-02-01 11:01:08,204 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,205 INFO sqlalchemy.engine.base.Engine (1825,)
2021-02-01 11:01:08,209 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,211 INFO sqlalchemy.engine.base.Engine (1826,)
2021-02-01 11:01:08,214 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,215 INFO sqlalchemy.engine.base.Engine (1827,)
2021-02-01 11:01:08,220 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,222 INFO sqlalchemy.engine.base.Engine (1828,)
2021-02-01 11:01:08,224 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,225 INFO sqlalchemy.engine.base.Engine (1829,)
2021-02-01 11:01:08,228 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,229 INFO sqlalchemy.engine.base.Engine (1830,)
2021-02-01 11:01:08,231 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,233 INFO sqlalchemy.engine.base.Engine (1831,)
2021-02-01 11:01:08,236 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,236 INFO sqlalchemy.engine.base.Engine (1832,)
2021-02-01 11:01:08,239 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,244 INFO sqlalchemy.engine.base.Engine (1833,)
2021-02-01 11:01:08,247 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,250 INFO sqlalchemy.engine.base.Engine (1834,)
2021-02-01 11:01:08,252 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,253 INFO sqlalchemy.engine.base.Engine (1835,)
2021-02-01 11:01:08,255 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,256 INFO sqlalchemy.engine.base.Engine (1836,)
2021-02-01 11:01:08,258 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,259 INFO sqlalchemy.engine.base.Engine (1837,)
2021-02-01 11:01:08,261 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,263 INFO sqlalchemy.engine.base.Engine (1838,)
2021-02-01 11:01:08,265 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:08,266 INFO sqlalchemy.engine.base.Engine (1839,)
2021-02-01 11:01:08,268 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,269 INFO sqlalchemy.engine.base.Engine (1840,)
2021-02-01 11:01:08,275 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,276 INFO sqlalchemy.engine.base.Engine (1841,)
2021-02-01 11:01:08,277 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,278 INFO sqlalchemy.engine.base.Engine (1842,)
2021-02-01 11:01:08,281 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,283 INFO sqlalchemy.engine.base.Engine (1843,)
2021-02-01 11:01:08,286 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,287 INFO sqlalchemy.engine.base.Engine (1844,)
2021-02-01 11:01:08,289 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,290 INFO sqlalchemy.engine.base.Engine (1845,)
2021-02-01 11:01:08,292 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,294 INFO sqlalchemy.engine.base.Engine (1846,)
2021-02-01 11:01:08,296 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,298 INFO sqlalchemy.engine.base.Engine (1847,)
2021-02-01 11:01:08,300 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,301 INFO sqlalchemy.engine.base.Engine (1848,)
2021-02-01 11:01:08,303 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,304 INFO sqlalchemy.engine.base.Engine (1849,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:08,420 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:08,422 INFO sqlalchemy.engine.base.Engine ('F38',)
2021-02-01 11:01:08,426 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:08,429 INFO sqlalchemy.engine.base.Engine ((1850, 14.3, 14.3, 14.3, 152888.12300002546, 122599.14613904712), (1851, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.12300002546, 122599.14613904712), (1852, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.12300002546, 122599.14613904712), (1853, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.12300002546, 122599.14613904712), (1854, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.12300002546, 122599.14613904712), (1855, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.12300002546, 122599.14613904712), (1856, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.12300002546, 122599.14613904712), (1857, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152888.12300002546, 122599.14613904712)  ... displaying 10 of 50 total bound parameter sets ...  (1898, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152888.12300002546, 122599.14613904712), (1899, 135.9, 135.9, 135.9, 152888.12300002546, 122599.14613904712))
2021-02-01 11:01:08,440 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:08,442 INFO sqlalchemy.engine.base.Engine ((925, 'F38', 0, 'Anhydrite', 1850, 1851), (926, 'F38', 1, 'Sandstone, grey, vf-f', 1852, 1853), (927, 'F38', 2, 'Anhydrite', 1854, 1855), (928, 'F38', 3, 'Dolomite', 1856, 1857), (929, 'F38', 4, 'Anhydrite', 1858, 1859), (930, 'F38', 5, 'Sandstone, grey, vf-f', 1860, 1861), (931, 'F38', 6, 'Siltstone, red', 1862, 1863), (932, 'F38', 7, 'Dolomite', 1864, 1865)  ... displaying 10 of 25 total bound parameter sets ...  (948, 'F38', 23, 'Limestone', 1896, 1897), (949, 'F38', 24, 'Volcanic', 1898, 1899))
2021-02-01 11:01:08,447 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:08,597 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:08,599 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:08,600 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:08,603 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:08,604 INFO sqlalchemy.engine.base.Engine ('F38',)
2021-02-01 11:01:08,606 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,607 INFO sqlalchemy.engine.base.Engine (1850,)
2021-02-01 11:01:08,609 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,610 INFO sqlalchemy.engine.base.Engine (1851,)
2021-02-01 11:01:08,611 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,612 INFO sqlalchemy.engine.base.Engine (1852,)

2021-02-01 11:01:08,613 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,614 INFO sqlalchemy.engine.base.Engine (1853,)
2021-02-01 11:01:08,616 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,617 INFO sqlalchemy.engine.base.Engine (1854,)
2021-02-01 11:01:08,618 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,620 INFO sqlalchemy.engine.base.Engine (1855,)
2021-02-01 11:01:08,621 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,622 INFO sqlalchemy.engine.base.Engine (1856,)
2021-02-01 11:01:08,625 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,625 INFO sqlalchemy.engine.base.Engine (1857,)
2021-02-01 11:01:08,627 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,629 INFO sqlalchemy.engine.base.Engine (1858,)
2021-02-01 11:01:08,630 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,631 INFO sqlalchemy.engine.base.Engine (1859,)
2021-02-01 11:01:08,633 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,634 INFO sqlalchemy.engine.base.Engine (1860,)
2021-02-01 11:01:08,636 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,636 INFO sqlalchemy.engine.base.Engine (1861,)
2021-02-01 11:01:08,640 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,643 INFO sqlalchemy.engine.base.Engine (1862,)
2021-02-01 11:01:08,647 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,648 INFO sqlalchemy.engine.base.Engine (1863,)
2021-02-01 11:01:08,653 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,654 INFO sqlalchemy.engine.base.Engine (1864,)
2021-02-01 11:01:08,660 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,661 INFO sqlalchemy.engine.base.Engine (1865,)
2021-02-01 11:01:08,664 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,665 INFO sqlalchemy.engine.base.Engine (1866,)
2021-02-01 11:01:08,671 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,672 INFO sqlalchemy.engine.base.Engine (1867,)
2021-02-01 11:01:08,674 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,676 INFO sqlalchemy.engine.base.Engine (1868,)
2021-02-01 11:01:08,679 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,680 INFO sqlalchemy.engine.base.Engine (1869,)
2021-02-01 11:01:08,682 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,684 INFO sqlalchemy.engine.base.Engine (1870,)
2021-02-01 11:01:08,686 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,688 INFO sqlalchemy.engine.base.Engine (1871,)
2021-02-01 11:01:08,694 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,695 INFO sqlalchemy.engine.base.Engine (1872,)
2021-02-01 11:01:08,698 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:08,700 INFO sqlalchemy.engine.base.Engine (1873,)
2021-02-01 11:01:08,703 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,704 INFO sqlalchemy.engine.base.Engine (1874,)
2021-02-01 11:01:08,706 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,709 INFO sqlalchemy.engine.base.Engine (1875,)
2021-02-01 11:01:08,712 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,713 INFO sqlalchemy.engine.base.Engine (1876,)
2021-02-01 11:01:08,719 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,721 INFO sqlalchemy.engine.base.Engine (1877,)
2021-02-01 11:01:08,723 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,725 INFO sqlalchemy.engine.base.Engine (1878,)
2021-02-01 11:01:08,727 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,730 INFO sqlalchemy.engine.base.Engine (1879,)
2021-02-01 11:01:08,732 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,733 INFO sqlalchemy.engine.base.Engine (1880,)
2021-02-01 11:01:08,736 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,737 INFO sqlalchemy.engine.base.Engine (1881,)
2021-02-01 11:01:08,740 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,741 INFO sqlalchemy.engine.base.Engine (1882,)
2021-02-01 11:01:08,743 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,744 INFO sqlalchemy.engine.base.Engine (1883,)
2021-02-01 11:01:08,748 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,749 INFO sqlalchemy.engine.base.Engine (1884,)
2021-02-01 11:01:08,751 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,753 INFO sqlalchemy.engine.base.Engine (1885,)
2021-02-01 11:01:08,756 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,757 INFO sqlalchemy.engine.base.Engine (1886,)
2021-02-01 11:01:08,759 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,761 INFO sqlalchemy.engine.base.Engine (1887,)
2021-02-01 11:01:08,764 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,765 INFO sqlalchemy.engine.base.Engine (1888,)
2021-02-01 11:01:08,769 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,771 INFO sqlalchemy.engine.base.Engine (1889,)
2021-02-01 11:01:08,773 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,774 INFO sqlalchemy.engine.base.Engine (1890,)
2021-02-01 11:01:08,776 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,777 INFO sqlalchemy.engine.base.Engine (1891,)
2021-02-01 11:01:08,779 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,780 INFO sqlalchemy.engine.base.Engine (1892,)
2021-02-01 11:01:08,787 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,788 INFO sqlalchemy.engine.base.Engine (1893,)
2021-02-01 11:01:08,791 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:08,793 INFO sqlalchemy.engine.base.Engine (1894,)
2021-02-01 11:01:08,797 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,799 INFO sqlalchemy.engine.base.Engine (1895,)
2021-02-01 11:01:08,801 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,802 INFO sqlalchemy.engine.base.Engine (1896,)
2021-02-01 11:01:08,804 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,805 INFO sqlalchemy.engine.base.Engine (1897,)
2021-02-01 11:01:08,809 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,812 INFO sqlalchemy.engine.base.Engine (1898,)
2021-02-01 11:01:08,816 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:08,817 INFO sqlalchemy.engine.base.Engine (1899,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:09,003 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:09,007 INFO sqlalchemy.engine.base.Engine ('F39',)
2021-02-01 11:01:09,011 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:09,013 INFO sqlalchemy.engine.base.Engine ((1900, 14.3, 14.3, 14.3, 152891.16600002546, 122597.62813904602), (1901, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152891.16600002546, 122597.62813904602), (1902, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152891.16600002546, 122597.62813904602), (1903, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152891.16600002546, 122597.62813904602), (1904, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152891.16600002546, 122597.62813904602), (1905, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152891.16600002546, 122597.62813904602), (1906, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152891.16600002546, 122597.62813904602), (1907, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152891.16600002546, 122597.62813904602)  ... displaying 10 of 50 total bound parameter sets ...  (1948, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152891.16600002546, 122597.62813904602), (1949, 135.9, 135.9, 135.9, 152891.16600002546, 122597.62813904602))
2021-02-01 11:01:09,018 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:09,020 INFO sqlalchemy.engine.base.Engine ((950, 'F39', 0, 'Anhydrite', 1900, 1901), (951, 'F39', 1, 'Sandstone, grey, vf-f', 1902, 1903), (952, 'F39', 2, 'Anhydrite', 1904, 1905), (953, 'F39', 3, 'Dolomite', 1906, 1907), (954, 'F39', 4, 'Anhydrite', 1908, 1909), (955, 'F39', 5, 'Sandstone, grey, vf-f', 1910, 1911), (956, 'F39', 6, 'Siltstone, red', 1912, 1913), (957, 'F39', 7, 'Dolomite', 1914, 1915)  ... displaying 10 of 25 total bound parameter sets ...  (973, 'F39', 23, 'Limestone', 1946, 1947), (974, 'F39', 24, 'Volcanic', 1948, 1949))
2021-02-01 11:01:09,027 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:09,106 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:09,108 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:09,109 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:09,113 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:09,114 INFO sqlalchemy.engine.base.Engine ('F39',)
2021-02-01 11:01:09,117 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,118 INFO sqlalchemy.engine.base.Engine (1900,)
2021-02-01 11:01:09,121 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,123 INFO sqlalchemy.engine.base.Engine (1901,)
2021-02-01 11:01:09,125 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,126 INFO sqlalchemy.engine.base.Engine (1902,)
2021-02-01 11:01:09,128 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,131 INFO sqlalchemy.engine.base.Engine (1903,)
2021-02-01 11:01:09,135 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,136 INFO sqlalchemy.engine.base.Engine (1904,)
2021-02-01 11:01:09,138 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,139 INFO sqlalchemy.engine.base.Engine (1905,)
2021-02-01 11:01:09,142 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,143 INFO sqlalchemy.engine.base.Engine (1906,)
2021-02-01 11:01:09,145 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,147 INFO sqlalchemy.engine.base.Engine (1907,)

2021-02-01 11:01:09,149 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,151 INFO sqlalchemy.engine.base.Engine (1908,)
2021-02-01 11:01:09,153 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,155 INFO sqlalchemy.engine.base.Engine (1909,)
2021-02-01 11:01:09,158 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,161 INFO sqlalchemy.engine.base.Engine (1910,)
2021-02-01 11:01:09,165 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,167 INFO sqlalchemy.engine.base.Engine (1911,)
2021-02-01 11:01:09,172 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,173 INFO sqlalchemy.engine.base.Engine (1912,)
2021-02-01 11:01:09,176 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,177 INFO sqlalchemy.engine.base.Engine (1913,)
2021-02-01 11:01:09,181 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,182 INFO sqlalchemy.engine.base.Engine (1914,)
2021-02-01 11:01:09,185 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,188 INFO sqlalchemy.engine.base.Engine (1915,)
2021-02-01 11:01:09,192 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,194 INFO sqlalchemy.engine.base.Engine (1916,)
2021-02-01 11:01:09,196 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,199 INFO sqlalchemy.engine.base.Engine (1917,)
2021-02-01 11:01:09,201 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,205 INFO sqlalchemy.engine.base.Engine (1918,)
2021-02-01 11:01:09,210 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,210 INFO sqlalchemy.engine.base.Engine (1919,)
2021-02-01 11:01:09,213 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,215 INFO sqlalchemy.engine.base.Engine (1920,)
2021-02-01 11:01:09,217 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,219 INFO sqlalchemy.engine.base.Engine (1921,)
2021-02-01 11:01:09,221 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,223 INFO sqlalchemy.engine.base.Engine (1922,)
2021-02-01 11:01:09,231 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,233 INFO sqlalchemy.engine.base.Engine (1923,)
2021-02-01 11:01:09,236 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,238 INFO sqlalchemy.engine.base.Engine (1924,)
2021-02-01 11:01:09,240 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,245 INFO sqlalchemy.engine.base.Engine (1925,)
2021-02-01 11:01:09,247 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,249 INFO sqlalchemy.engine.base.Engine (1926,)
2021-02-01 11:01:09,250 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,255 INFO sqlalchemy.engine.base.Engine (1927,)
2021-02-01 11:01:09,259 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:09,261 INFO sqlalchemy.engine.base.Engine (1928,)
2021-02-01 11:01:09,263 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,264 INFO sqlalchemy.engine.base.Engine (1929,)
2021-02-01 11:01:09,267 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,267 INFO sqlalchemy.engine.base.Engine (1930,)
2021-02-01 11:01:09,270 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,270 INFO sqlalchemy.engine.base.Engine (1931,)
2021-02-01 11:01:09,272 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,273 INFO sqlalchemy.engine.base.Engine (1932,)
2021-02-01 11:01:09,276 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,278 INFO sqlalchemy.engine.base.Engine (1933,)
2021-02-01 11:01:09,285 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,286 INFO sqlalchemy.engine.base.Engine (1934,)
2021-02-01 11:01:09,287 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,288 INFO sqlalchemy.engine.base.Engine (1935,)
2021-02-01 11:01:09,290 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,292 INFO sqlalchemy.engine.base.Engine (1936,)
2021-02-01 11:01:09,294 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,295 INFO sqlalchemy.engine.base.Engine (1937,)
2021-02-01 11:01:09,297 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,298 INFO sqlalchemy.engine.base.Engine (1938,)
2021-02-01 11:01:09,300 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,301 INFO sqlalchemy.engine.base.Engine (1939,)
2021-02-01 11:01:09,305 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,306 INFO sqlalchemy.engine.base.Engine (1940,)
2021-02-01 11:01:09,312 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,313 INFO sqlalchemy.engine.base.Engine (1941,)
2021-02-01 11:01:09,315 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,316 INFO sqlalchemy.engine.base.Engine (1942,)
2021-02-01 11:01:09,317 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,318 INFO sqlalchemy.engine.base.Engine (1943,)
2021-02-01 11:01:09,320 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,322 INFO sqlalchemy.engine.base.Engine (1944,)
2021-02-01 11:01:09,325 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,327 INFO sqlalchemy.engine.base.Engine (1945,)
2021-02-01 11:01:09,332 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,333 INFO sqlalchemy.engine.base.Engine (1946,)
2021-02-01 11:01:09,334 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,336 INFO sqlalchemy.engine.base.Engine (1947,)
2021-02-01 11:01:09,339 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,340 INFO sqlalchemy.engine.base.Engine (1948,)
2021-02-01 11:01:09,341 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:09,343 INFO sqlalchemy.engine.base.Engine (1949,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:09,514 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:09,516 INFO sqlalchemy.engine.base.Engine ((1950, 14.3, 14.3, 14.3, 152893.33600002548, 122595.9201390464), (1951, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152893.33600002548, 122595.9201390464), (1952, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152893.33600002548, 122595.9201390464), (1953, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152893.33600002548, 122595.9201390464), (1954, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152893.33600002548, 122595.9201390464), (1955, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152893.33600002548, 122595.9201390464), (1956, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152893.33600002548, 122595.9201390464), (1957, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152893.33600002548, 122595.9201390464)  ... displaying 10 of 50 total bound parameter sets ...  (1998, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152893.33600002548, 122595.9201390464), (1999, 135.9, 135.9, 135.9, 152893.33600002548, 122595.9201390464))
2021-02-01 11:01:09,518 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:09,520 INFO sqlalchemy.engine.base.Engine ('F40',)
2021-02-01 11:01:09,528 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:09,530 INFO sqlalchemy.engine.base.Engine ((975, 'F40', 0, 'Anhydrite', 1950, 1951), (976, 'F40', 1, 'Sandstone, grey, vf-f', 1952, 1953), (977, 'F40', 2, 'Anhydrite', 1954, 1955), (978, 'F40', 3, 'Dolomite', 1956, 1957), (979, 'F40', 4, 'Anhydrite', 1958, 1959), (980, 'F40', 5, 'Sandstone, grey, vf-f', 1960, 1961), (981, 'F40', 6, 'Siltstone, red', 1962, 1963), (982, 'F40', 7, 'Dolomite', 1964, 1965)  ... displaying 10 of 25 total bound parameter sets ...  (998, 'F40', 23, 'Limestone', 1996, 1997), (999, 'F40', 24, 'Volcanic', 1998, 1999))
2021-02-01 11:01:09,533 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:09,650 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:09,652 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:09,654 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:09,657 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:09,658 INFO sqlalchemy.engine.base.Engine ('F40',)
2021-02-01 11:01:09,664 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,665 INFO sqlalchemy.engine.base.Engine (1950,)
2021-02-01 11:01:09,667 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,668 INFO sqlalchemy.engine.base.Engine (1951,)
2021-02-01 11:01:09,670 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,672 INFO sqlalchemy.engine.base.Engine (1952,)
2021-02-01 11:01:09,675 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,676 INFO sqlalchemy.engine.base.Engine (1953,)
2021-02-01 11:01:09,680 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,682 INFO sqlalchemy.engine.base.Engine (1954,)
2021-02-01 11:01:09,684 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,684 INFO sqlalchemy.engine.base.Engine (1955,)
2021-02-01 11:01:09,686 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,687 INFO sqlalchemy.engine.base.Engine (1956,)
2021-02-01 11:01:09,688 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,689 INFO sqlalchemy.engine.base.Engine (1957,)
2021-02-01 11:01:09,691 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,693 INFO sqlalchemy.engine.base.Engine (1958,)
2021-02-01 11:01:09,696 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,697 INFO sqlalchemy.engine.base.Engine (1959,)
2021-02-01 11:01:09,702 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,703 INFO sqlalchemy.engine.base.Engine (1960,)
2021-02-01 11:01:09,705 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,706 INFO sqlalchemy.engine.base.Engine (1961,)
2021-02-01 11:01:09,707 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,709 INFO sqlalchemy.engine.base.Engine (1962,)

2021-02-01 11:01:09,711 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,712 INFO sqlalchemy.engine.base.Engine (1963,)
2021-02-01 11:01:09,716 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,719 INFO sqlalchemy.engine.base.Engine (1964,)
2021-02-01 11:01:09,721 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,722 INFO sqlalchemy.engine.base.Engine (1965,)
2021-02-01 11:01:09,724 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,726 INFO sqlalchemy.engine.base.Engine (1966,)
2021-02-01 11:01:09,728 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,730 INFO sqlalchemy.engine.base.Engine (1967,)
2021-02-01 11:01:09,733 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,734 INFO sqlalchemy.engine.base.Engine (1968,)
2021-02-01 11:01:09,737 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,738 INFO sqlalchemy.engine.base.Engine (1969,)
2021-02-01 11:01:09,741 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,742 INFO sqlalchemy.engine.base.Engine (1970,)
2021-02-01 11:01:09,745 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,747 INFO sqlalchemy.engine.base.Engine (1971,)
2021-02-01 11:01:09,751 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,752 INFO sqlalchemy.engine.base.Engine (1972,)
2021-02-01 11:01:09,754 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,755 INFO sqlalchemy.engine.base.Engine (1973,)
2021-02-01 11:01:09,758 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,759 INFO sqlalchemy.engine.base.Engine (1974,)
2021-02-01 11:01:09,761 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,767 INFO sqlalchemy.engine.base.Engine (1975,)
2021-02-01 11:01:09,772 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,774 INFO sqlalchemy.engine.base.Engine (1976,)
2021-02-01 11:01:09,776 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,779 INFO sqlalchemy.engine.base.Engine (1977,)
2021-02-01 11:01:09,782 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,783 INFO sqlalchemy.engine.base.Engine (1978,)
2021-02-01 11:01:09,786 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,787 INFO sqlalchemy.engine.base.Engine (1979,)
2021-02-01 11:01:09,789 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,791 INFO sqlalchemy.engine.base.Engine (1980,)
2021-02-01 11:01:09,794 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,797 INFO sqlalchemy.engine.base.Engine (1981,)
2021-02-01 11:01:09,799 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,801 INFO sqlalchemy.engine.base.Engine (1982,)
2021-02-01 11:01:09,805 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:09,806 INFO sqlalchemy.engine.base.Engine (1983,)
2021-02-01 11:01:09,809 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,810 INFO sqlalchemy.engine.base.Engine (1984,)
2021-02-01 11:01:09,812 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,813 INFO sqlalchemy.engine.base.Engine (1985,)
2021-02-01 11:01:09,817 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,818 INFO sqlalchemy.engine.base.Engine (1986,)
2021-02-01 11:01:09,820 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,821 INFO sqlalchemy.engine.base.Engine (1987,)
2021-02-01 11:01:09,823 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,824 INFO sqlalchemy.engine.base.Engine (1988,)
2021-02-01 11:01:09,828 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,833 INFO sqlalchemy.engine.base.Engine (1989,)
2021-02-01 11:01:09,835 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,836 INFO sqlalchemy.engine.base.Engine (1990,)
2021-02-01 11:01:09,838 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,839 INFO sqlalchemy.engine.base.Engine (1991,)
2021-02-01 11:01:09,841 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,842 INFO sqlalchemy.engine.base.Engine (1992,)
2021-02-01 11:01:09,844 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,845 INFO sqlalchemy.engine.base.Engine (1993,)
2021-02-01 11:01:09,850 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,853 INFO sqlalchemy.engine.base.Engine (1994,)
2021-02-01 11:01:09,855 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,856 INFO sqlalchemy.engine.base.Engine (1995,)
2021-02-01 11:01:09,858 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,861 INFO sqlalchemy.engine.base.Engine (1996,)
2021-02-01 11:01:09,864 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,867 INFO sqlalchemy.engine.base.Engine (1997,)
2021-02-01 11:01:09,869 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,869 INFO sqlalchemy.engine.base.Engine (1998,)
2021-02-01 11:01:09,871 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:09,873 INFO sqlalchemy.engine.base.Engine (1999,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:10,020 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:10,022 INFO sqlalchemy.engine.base.Engine ((2000, 14.3, 14.3, 14.3, 152895.43100002548, 122594.85713904814), (2001, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152895.43100002548, 122594.85713904814), (2002, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152895.43100002548, 122594.85713904814), (2003, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152895.43100002548, 122594.85713904814), (2004, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152895.43100002548, 122594.85713904814), (2005, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152895.43100002548, 122594.85713904814), (2006, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152895.43100002548, 122594.85713904814), (2007, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152895.43100002548, 122594.85713904814)  ... displaying 10 of 50 total bound parameter sets ...  (2048, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152895.43100002548, 122594.85713904814), (2049, 135.9, 135.9, 135.9, 152895.43100002548, 122594.85713904814))
2021-02-01 11:01:10,026 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:10,027 INFO sqlalchemy.engine.base.Engine ('F41',)
2021-02-01 11:01:10,032 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:10,034 INFO sqlalchemy.engine.base.Engine ((1000, 'F41', 0, 'Anhydrite', 2000, 2001), (1001, 'F41', 1, 'Sandstone, grey, vf-f', 2002, 2003), (1002, 'F41', 2, 'Anhydrite', 2004, 2005), (1003, 'F41', 3, 'Dolomite', 2006, 2007), (1004, 'F41', 4, 'Anhydrite', 2008, 2009), (1005, 'F41', 5, 'Sandstone, grey, vf-f', 2010, 2011), (1006, 'F41', 6, 'Siltstone, red', 2012, 2013), (1007, 'F41', 7, 'Dolomite', 2014, 2015)  ... displaying 10 of 25 total bound parameter sets ...  (1023, 'F41', 23, 'Limestone', 2046, 2047), (1024, 'F41', 24, 'Volcanic', 2048, 2049))

2021-02-01 11:01:10,037 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:10,266 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:10,267 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:10,268 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:10,272 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:10,273 INFO sqlalchemy.engine.base.Engine ('F41',)
2021-02-01 11:01:10,277 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,278 INFO sqlalchemy.engine.base.Engine (2000,)
2021-02-01 11:01:10,280 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,281 INFO sqlalchemy.engine.base.Engine (2001,)
2021-02-01 11:01:10,283 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,284 INFO sqlalchemy.engine.base.Engine (2002,)
2021-02-01 11:01:10,285 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,287 INFO sqlalchemy.engine.base.Engine (2003,)
2021-02-01 11:01:10,289 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,292 INFO sqlalchemy.engine.base.Engine (2004,)
2021-02-01 11:01:10,295 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,296 INFO sqlalchemy.engine.base.Engine (2005,)
2021-02-01 11:01:10,298 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,299 INFO sqlalchemy.engine.base.Engine (2006,)
2021-02-01 11:01:10,302 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,303 INFO sqlalchemy.engine.base.Engine (2007,)
2021-02-01 11:01:10,305 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,306 INFO sqlalchemy.engine.base.Engine (2008,)
2021-02-01 11:01:10,308 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,311 INFO sqlalchemy.engine.base.Engine (2009,)
2021-02-01 11:01:10,315 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,317 INFO sqlalchemy.engine.base.Engine (2010,)
2021-02-01 11:01:10,318 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,319 INFO sqlalchemy.engine.base.Engine (2011,)
2021-02-01 11:01:10,321 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,322 INFO sqlalchemy.engine.base.Engine (2012,)
2021-02-01 11:01:10,325 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,327 INFO sqlalchemy.engine.base.Engine (2013,)
2021-02-01 11:01:10,331 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,334 INFO sqlalchemy.engine.base.Engine (2014,)
2021-02-01 11:01:10,338 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,340 INFO sqlalchemy.engine.base.Engine (2015,)
2021-02-01 11:01:10,343 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,344 INFO sqlalchemy.engine.base.Engine (2016,)
2021-02-01 11:01:10,346 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,347 INFO sqlalchemy.engine.base.Engine (2017,)
2021-02-01 11:01:10,350 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:10,351 INFO sqlalchemy.engine.base.Engine (2018,)
2021-02-01 11:01:10,353 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,354 INFO sqlalchemy.engine.base.Engine (2019,)
2021-02-01 11:01:10,356 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,356 INFO sqlalchemy.engine.base.Engine (2020,)
2021-02-01 11:01:10,360 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,362 INFO sqlalchemy.engine.base.Engine (2021,)
2021-02-01 11:01:10,364 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,365 INFO sqlalchemy.engine.base.Engine (2022,)
2021-02-01 11:01:10,371 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,375 INFO sqlalchemy.engine.base.Engine (2023,)
2021-02-01 11:01:10,378 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,379 INFO sqlalchemy.engine.base.Engine (2024,)
2021-02-01 11:01:10,380 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,382 INFO sqlalchemy.engine.base.Engine (2025,)
2021-02-01 11:01:10,384 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,385 INFO sqlalchemy.engine.base.Engine (2026,)
2021-02-01 11:01:10,388 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,389 INFO sqlalchemy.engine.base.Engine (2027,)
2021-02-01 11:01:10,392 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,393 INFO sqlalchemy.engine.base.Engine (2028,)
2021-02-01 11:01:10,395 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,397 INFO sqlalchemy.engine.base.Engine (2029,)
2021-02-01 11:01:10,402 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,404 INFO sqlalchemy.engine.base.Engine (2030,)
2021-02-01 11:01:10,406 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,408 INFO sqlalchemy.engine.base.Engine (2031,)
2021-02-01 11:01:10,410 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,412 INFO sqlalchemy.engine.base.Engine (2032,)
2021-02-01 11:01:10,414 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,415 INFO sqlalchemy.engine.base.Engine (2033,)
2021-02-01 11:01:10,418 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,419 INFO sqlalchemy.engine.base.Engine (2034,)
2021-02-01 11:01:10,422 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,425 INFO sqlalchemy.engine.base.Engine (2035,)
2021-02-01 11:01:10,428 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,429 INFO sqlalchemy.engine.base.Engine (2036,)
2021-02-01 11:01:10,431 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,433 INFO sqlalchemy.engine.base.Engine (2037,)
2021-02-01 11:01:10,435 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,436 INFO sqlalchemy.engine.base.Engine (2038,)
2021-02-01 11:01:10,438 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:10,443 INFO sqlalchemy.engine.base.Engine (2039,)
2021-02-01 11:01:10,445 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,447 INFO sqlalchemy.engine.base.Engine (2040,)
2021-02-01 11:01:10,449 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,451 INFO sqlalchemy.engine.base.Engine (2041,)
2021-02-01 11:01:10,454 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,457 INFO sqlalchemy.engine.base.Engine (2042,)
2021-02-01 11:01:10,459 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,460 INFO sqlalchemy.engine.base.Engine (2043,)
2021-02-01 11:01:10,463 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,466 INFO sqlalchemy.engine.base.Engine (2044,)
2021-02-01 11:01:10,468 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,469 INFO sqlalchemy.engine.base.Engine (2045,)
2021-02-01 11:01:10,471 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,472 INFO sqlalchemy.engine.base.Engine (2046,)
2021-02-01 11:01:10,474 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,477 INFO sqlalchemy.engine.base.Engine (2047,)
2021-02-01 11:01:10,480 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,481 INFO sqlalchemy.engine.base.Engine (2048,)
2021-02-01 11:01:10,484 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,485 INFO sqlalchemy.engine.base.Engine (2049,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:10,616 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:10,617 INFO sqlalchemy.engine.base.Engine ((2050, 14.3, 14.3, 14.3, 152888.20900002544, 122596.492139047), (2051, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.20900002544, 122596.492139047), (2052, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.20900002544, 122596.492139047), (2053, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.20900002544, 122596.492139047), (2054, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.20900002544, 122596.492139047), (2055, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.20900002544, 122596.492139047), (2056, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.20900002544, 122596.492139047), (2057, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152888.20900002544, 122596.492139047)  ... displaying 10 of 50 total bound parameter sets ...  (2098, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152888.20900002544, 122596.492139047), (2099, 135.9, 135.9, 135.9, 152888.20900002544, 122596.492139047))
2021-02-01 11:01:10,620 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:10,623 INFO sqlalchemy.engine.base.Engine ('F42',)
2021-02-01 11:01:10,629 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:10,630 INFO sqlalchemy.engine.base.Engine ((1025, 'F42', 0, 'Anhydrite', 2050, 2051), (1026, 'F42', 1, 'Sandstone, grey, vf-f', 2052, 2053), (1027, 'F42', 2, 'Anhydrite', 2054, 2055), (1028, 'F42', 3, 'Dolomite', 2056, 2057), (1029, 'F42', 4, 'Anhydrite', 2058, 2059), (1030, 'F42', 5, 'Sandstone, grey, vf-f', 2060, 2061), (1031, 'F42', 6, 'Siltstone, red', 2062, 2063), (1032, 'F42', 7, 'Dolomite', 2064, 2065)  ... displaying 10 of 25 total bound parameter sets ...  (1048, 'F42', 23, 'Limestone', 2096, 2097), (1049, 'F42', 24, 'Volcanic', 2098, 2099))
2021-02-01 11:01:10,635 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:10,753 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:10,754 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:10,757 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:10,760 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:10,762 INFO sqlalchemy.engine.base.Engine ('F42',)
2021-02-01 11:01:10,765 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,767 INFO sqlalchemy.engine.base.Engine (2050,)
2021-02-01 11:01:10,769 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,771 INFO sqlalchemy.engine.base.Engine (2051,)
2021-02-01 11:01:10,773 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,775 INFO sqlalchemy.engine.base.Engine (2052,)

2021-02-01 11:01:10,777 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,778 INFO sqlalchemy.engine.base.Engine (2053,)
2021-02-01 11:01:10,781 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,786 INFO sqlalchemy.engine.base.Engine (2054,)
2021-02-01 11:01:10,788 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,790 INFO sqlalchemy.engine.base.Engine (2055,)
2021-02-01 11:01:10,792 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,794 INFO sqlalchemy.engine.base.Engine (2056,)
2021-02-01 11:01:10,796 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,797 INFO sqlalchemy.engine.base.Engine (2057,)
2021-02-01 11:01:10,799 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,800 INFO sqlalchemy.engine.base.Engine (2058,)
2021-02-01 11:01:10,802 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,804 INFO sqlalchemy.engine.base.Engine (2059,)
2021-02-01 11:01:10,806 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,807 INFO sqlalchemy.engine.base.Engine (2060,)
2021-02-01 11:01:10,809 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,810 INFO sqlalchemy.engine.base.Engine (2061,)
2021-02-01 11:01:10,815 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,818 INFO sqlalchemy.engine.base.Engine (2062,)
2021-02-01 11:01:10,821 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,822 INFO sqlalchemy.engine.base.Engine (2063,)
2021-02-01 11:01:10,824 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,827 INFO sqlalchemy.engine.base.Engine (2064,)
2021-02-01 11:01:10,833 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,834 INFO sqlalchemy.engine.base.Engine (2065,)
2021-02-01 11:01:10,837 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,838 INFO sqlalchemy.engine.base.Engine (2066,)
2021-02-01 11:01:10,840 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,843 INFO sqlalchemy.engine.base.Engine (2067,)
2021-02-01 11:01:10,846 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,847 INFO sqlalchemy.engine.base.Engine (2068,)
2021-02-01 11:01:10,849 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,850 INFO sqlalchemy.engine.base.Engine (2069,)
2021-02-01 11:01:10,853 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,854 INFO sqlalchemy.engine.base.Engine (2070,)
2021-02-01 11:01:10,859 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,860 INFO sqlalchemy.engine.base.Engine (2071,)
2021-02-01 11:01:10,862 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,864 INFO sqlalchemy.engine.base.Engine (2072,)
2021-02-01 11:01:10,867 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:10,869 INFO sqlalchemy.engine.base.Engine (2073,)
2021-02-01 11:01:10,873 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,874 INFO sqlalchemy.engine.base.Engine (2074,)
2021-02-01 11:01:10,878 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,879 INFO sqlalchemy.engine.base.Engine (2075,)
2021-02-01 11:01:10,882 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,883 INFO sqlalchemy.engine.base.Engine (2076,)
2021-02-01 11:01:10,886 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,887 INFO sqlalchemy.engine.base.Engine (2077,)
2021-02-01 11:01:10,890 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,891 INFO sqlalchemy.engine.base.Engine (2078,)
2021-02-01 11:01:10,893 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,894 INFO sqlalchemy.engine.base.Engine (2079,)
2021-02-01 11:01:10,897 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,898 INFO sqlalchemy.engine.base.Engine (2080,)
2021-02-01 11:01:10,907 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,908 INFO sqlalchemy.engine.base.Engine (2081,)
2021-02-01 11:01:10,910 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,911 INFO sqlalchemy.engine.base.Engine (2082,)
2021-02-01 11:01:10,914 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,915 INFO sqlalchemy.engine.base.Engine (2083,)
2021-02-01 11:01:10,918 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,919 INFO sqlalchemy.engine.base.Engine (2084,)
2021-02-01 11:01:10,922 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,922 INFO sqlalchemy.engine.base.Engine (2085,)
2021-02-01 11:01:10,926 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,928 INFO sqlalchemy.engine.base.Engine (2086,)
2021-02-01 11:01:10,930 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,931 INFO sqlalchemy.engine.base.Engine (2087,)
2021-02-01 11:01:10,934 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,935 INFO sqlalchemy.engine.base.Engine (2088,)
2021-02-01 11:01:10,938 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,943 INFO sqlalchemy.engine.base.Engine (2089,)
2021-02-01 11:01:10,947 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,948 INFO sqlalchemy.engine.base.Engine (2090,)
2021-02-01 11:01:10,950 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,951 INFO sqlalchemy.engine.base.Engine (2091,)
2021-02-01 11:01:10,953 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,954 INFO sqlalchemy.engine.base.Engine (2092,)
2021-02-01 11:01:10,955 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,957 INFO sqlalchemy.engine.base.Engine (2093,)
2021-02-01 11:01:10,960 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:10,961 INFO sqlalchemy.engine.base.Engine (2094,)
2021-02-01 11:01:10,963 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,967 INFO sqlalchemy.engine.base.Engine (2095,)
2021-02-01 11:01:10,970 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,971 INFO sqlalchemy.engine.base.Engine (2096,)
2021-02-01 11:01:10,973 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,974 INFO sqlalchemy.engine.base.Engine (2097,)
2021-02-01 11:01:10,976 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,978 INFO sqlalchemy.engine.base.Engine (2098,)
2021-02-01 11:01:10,981 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:10,981 INFO sqlalchemy.engine.base.Engine (2099,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:11,106 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:11,107 INFO sqlalchemy.engine.base.Engine ((2100, 14.3, 14.3, 14.3, 152891.32900002546, 122588.78113904875), (2101, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152891.32900002546, 122588.78113904875), (2102, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152891.32900002546, 122588.78113904875), (2103, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152891.32900002546, 122588.78113904875), (2104, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152891.32900002546, 122588.78113904875), (2105, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152891.32900002546, 122588.78113904875), (2106, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152891.32900002546, 122588.78113904875), (2107, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152891.32900002546, 122588.78113904875)  ... displaying 10 of 50 total bound parameter sets ...  (2148, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152891.32900002546, 122588.78113904875), (2149, 135.9, 135.9, 135.9, 152891.32900002546, 122588.78113904875))
2021-02-01 11:01:11,110 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:11,111 INFO sqlalchemy.engine.base.Engine ('F43',)
2021-02-01 11:01:11,115 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:11,116 INFO sqlalchemy.engine.base.Engine ((1050, 'F43', 0, 'Anhydrite', 2100, 2101), (1051, 'F43', 1, 'Sandstone, grey, vf-f', 2102, 2103), (1052, 'F43', 2, 'Anhydrite', 2104, 2105), (1053, 'F43', 3, 'Dolomite', 2106, 2107), (1054, 'F43', 4, 'Anhydrite', 2108, 2109), (1055, 'F43', 5, 'Sandstone, grey, vf-f', 2110, 2111), (1056, 'F43', 6, 'Siltstone, red', 2112, 2113), (1057, 'F43', 7, 'Dolomite', 2114, 2115)  ... displaying 10 of 25 total bound parameter sets ...  (1073, 'F43', 23, 'Limestone', 2146, 2147), (1074, 'F43', 24, 'Volcanic', 2148, 2149))
2021-02-01 11:01:11,119 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:11,261 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:11,263 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:11,264 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:11,269 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:11,270 INFO sqlalchemy.engine.base.Engine ('F43',)
2021-02-01 11:01:11,273 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,275 INFO sqlalchemy.engine.base.Engine (2100,)
2021-02-01 11:01:11,280 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,281 INFO sqlalchemy.engine.base.Engine (2101,)
2021-02-01 11:01:11,283 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,284 INFO sqlalchemy.engine.base.Engine (2102,)
2021-02-01 11:01:11,287 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,288 INFO sqlalchemy.engine.base.Engine (2103,)
2021-02-01 11:01:11,290 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,292 INFO sqlalchemy.engine.base.Engine (2104,)
2021-02-01 11:01:11,294 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,295 INFO sqlalchemy.engine.base.Engine (2105,)
2021-02-01 11:01:11,300 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,302 INFO sqlalchemy.engine.base.Engine (2106,)
2021-02-01 11:01:11,304 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,305 INFO sqlalchemy.engine.base.Engine (2107,)

2021-02-01 11:01:11,308 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,310 INFO sqlalchemy.engine.base.Engine (2108,)
2021-02-01 11:01:11,312 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,313 INFO sqlalchemy.engine.base.Engine (2109,)
2021-02-01 11:01:11,316 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,318 INFO sqlalchemy.engine.base.Engine (2110,)
2021-02-01 11:01:11,322 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,323 INFO sqlalchemy.engine.base.Engine (2111,)
2021-02-01 11:01:11,325 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,327 INFO sqlalchemy.engine.base.Engine (2112,)
2021-02-01 11:01:11,329 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,330 INFO sqlalchemy.engine.base.Engine (2113,)
2021-02-01 11:01:11,333 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,335 INFO sqlalchemy.engine.base.Engine (2114,)
2021-02-01 11:01:11,337 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,339 INFO sqlalchemy.engine.base.Engine (2115,)
2021-02-01 11:01:11,342 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,343 INFO sqlalchemy.engine.base.Engine (2116,)
2021-02-01 11:01:11,345 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,347 INFO sqlalchemy.engine.base.Engine (2117,)
2021-02-01 11:01:11,350 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,351 INFO sqlalchemy.engine.base.Engine (2118,)
2021-02-01 11:01:11,353 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,355 INFO sqlalchemy.engine.base.Engine (2119,)
2021-02-01 11:01:11,357 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,358 INFO sqlalchemy.engine.base.Engine (2120,)
2021-02-01 11:01:11,361 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,363 INFO sqlalchemy.engine.base.Engine (2121,)
2021-02-01 11:01:11,365 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,367 INFO sqlalchemy.engine.base.Engine (2122,)
2021-02-01 11:01:11,371 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,373 INFO sqlalchemy.engine.base.Engine (2123,)
2021-02-01 11:01:11,377 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,378 INFO sqlalchemy.engine.base.Engine (2124,)
2021-02-01 11:01:11,380 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,381 INFO sqlalchemy.engine.base.Engine (2125,)
2021-02-01 11:01:11,386 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,388 INFO sqlalchemy.engine.base.Engine (2126,)
2021-02-01 11:01:11,390 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,395 INFO sqlalchemy.engine.base.Engine (2127,)
2021-02-01 11:01:11,398 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:11,399 INFO sqlalchemy.engine.base.Engine (2128,)
2021-02-01 11:01:11,401 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,403 INFO sqlalchemy.engine.base.Engine (2129,)
2021-02-01 11:01:11,406 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,407 INFO sqlalchemy.engine.base.Engine (2130,)
2021-02-01 11:01:11,409 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,412 INFO sqlalchemy.engine.base.Engine (2131,)
2021-02-01 11:01:11,414 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,415 INFO sqlalchemy.engine.base.Engine (2132,)
2021-02-01 11:01:11,420 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,422 INFO sqlalchemy.engine.base.Engine (2133,)
2021-02-01 11:01:11,425 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,426 INFO sqlalchemy.engine.base.Engine (2134,)
2021-02-01 11:01:11,428 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,429 INFO sqlalchemy.engine.base.Engine (2135,)
2021-02-01 11:01:11,432 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,433 INFO sqlalchemy.engine.base.Engine (2136,)
2021-02-01 11:01:11,437 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,441 INFO sqlalchemy.engine.base.Engine (2137,)
2021-02-01 11:01:11,444 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,448 INFO sqlalchemy.engine.base.Engine (2138,)
2021-02-01 11:01:11,452 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,452 INFO sqlalchemy.engine.base.Engine (2139,)
2021-02-01 11:01:11,455 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,456 INFO sqlalchemy.engine.base.Engine (2140,)
2021-02-01 11:01:11,458 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,462 INFO sqlalchemy.engine.base.Engine (2141,)
2021-02-01 11:01:11,466 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,468 INFO sqlalchemy.engine.base.Engine (2142,)
2021-02-01 11:01:11,471 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,477 INFO sqlalchemy.engine.base.Engine (2143,)
2021-02-01 11:01:11,480 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,482 INFO sqlalchemy.engine.base.Engine (2144,)
2021-02-01 11:01:11,484 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,487 INFO sqlalchemy.engine.base.Engine (2145,)
2021-02-01 11:01:11,489 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,492 INFO sqlalchemy.engine.base.Engine (2146,)
2021-02-01 11:01:11,494 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,495 INFO sqlalchemy.engine.base.Engine (2147,)
2021-02-01 11:01:11,499 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,500 INFO sqlalchemy.engine.base.Engine (2148,)
2021-02-01 11:01:11,503 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:11,505 INFO sqlalchemy.engine.base.Engine (2149,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:11,638 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:11,639 INFO sqlalchemy.engine.base.Engine ('F44',)
2021-02-01 11:01:11,642 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:11,644 INFO sqlalchemy.engine.base.Engine ((2150, 14.3, 14.3, 14.3, 152889.47000002547, 122584.78213904797), (2151, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152889.47000002547, 122584.78213904797), (2152, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152889.47000002547, 122584.78213904797), (2153, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152889.47000002547, 122584.78213904797), (2154, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152889.47000002547, 122584.78213904797), (2155, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152889.47000002547, 122584.78213904797), (2156, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152889.47000002547, 122584.78213904797), (2157, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152889.47000002547, 122584.78213904797)  ... displaying 10 of 50 total bound parameter sets ...  (2198, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152889.47000002547, 122584.78213904797), (2199, 135.9, 135.9, 135.9, 152889.47000002547, 122584.78213904797))
2021-02-01 11:01:11,655 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:11,655 INFO sqlalchemy.engine.base.Engine ((1075, 'F44', 0, 'Anhydrite', 2150, 2151), (1076, 'F44', 1, 'Sandstone, grey, vf-f', 2152, 2153), (1077, 'F44', 2, 'Anhydrite', 2154, 2155), (1078, 'F44', 3, 'Dolomite', 2156, 2157), (1079, 'F44', 4, 'Anhydrite', 2158, 2159), (1080, 'F44', 5, 'Sandstone, grey, vf-f', 2160, 2161), (1081, 'F44', 6, 'Siltstone, red', 2162, 2163), (1082, 'F44', 7, 'Dolomite', 2164, 2165)  ... displaying 10 of 25 total bound parameter sets ...  (1098, 'F44', 23, 'Limestone', 2196, 2197), (1099, 'F44', 24, 'Volcanic', 2198, 2199))
2021-02-01 11:01:11,659 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:11,784 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:11,786 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:11,787 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:11,791 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:11,792 INFO sqlalchemy.engine.base.Engine ('F44',)
2021-02-01 11:01:11,795 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,798 INFO sqlalchemy.engine.base.Engine (2150,)
2021-02-01 11:01:11,801 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,802 INFO sqlalchemy.engine.base.Engine (2151,)
2021-02-01 11:01:11,804 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,805 INFO sqlalchemy.engine.base.Engine (2152,)
2021-02-01 11:01:11,808 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,810 INFO sqlalchemy.engine.base.Engine (2153,)
2021-02-01 11:01:11,812 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,814 INFO sqlalchemy.engine.base.Engine (2154,)
2021-02-01 11:01:11,816 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,817 INFO sqlalchemy.engine.base.Engine (2155,)
2021-02-01 11:01:11,818 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,820 INFO sqlalchemy.engine.base.Engine (2156,)
2021-02-01 11:01:11,822 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,823 INFO sqlalchemy.engine.base.Engine (2157,)
2021-02-01 11:01:11,825 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,827 INFO sqlalchemy.engine.base.Engine (2158,)
2021-02-01 11:01:11,829 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,831 INFO sqlalchemy.engine.base.Engine (2159,)
2021-02-01 11:01:11,836 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,837 INFO sqlalchemy.engine.base.Engine (2160,)
2021-02-01 11:01:11,840 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,842 INFO sqlalchemy.engine.base.Engine (2161,)
2021-02-01 11:01:11,844 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,846 INFO sqlalchemy.engine.base.Engine (2162,)

2021-02-01 11:01:11,848 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,849 INFO sqlalchemy.engine.base.Engine (2163,)
2021-02-01 11:01:11,851 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,852 INFO sqlalchemy.engine.base.Engine (2164,)
2021-02-01 11:01:11,853 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,855 INFO sqlalchemy.engine.base.Engine (2165,)
2021-02-01 11:01:11,858 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,859 INFO sqlalchemy.engine.base.Engine (2166,)
2021-02-01 11:01:11,861 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,862 INFO sqlalchemy.engine.base.Engine (2167,)
2021-02-01 11:01:11,866 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,867 INFO sqlalchemy.engine.base.Engine (2168,)
2021-02-01 11:01:11,870 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,871 INFO sqlalchemy.engine.base.Engine (2169,)
2021-02-01 11:01:11,873 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,874 INFO sqlalchemy.engine.base.Engine (2170,)
2021-02-01 11:01:11,876 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,877 INFO sqlalchemy.engine.base.Engine (2171,)
2021-02-01 11:01:11,880 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,882 INFO sqlalchemy.engine.base.Engine (2172,)
2021-02-01 11:01:11,884 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,885 INFO sqlalchemy.engine.base.Engine (2173,)
2021-02-01 11:01:11,887 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,891 INFO sqlalchemy.engine.base.Engine (2174,)
2021-02-01 11:01:11,893 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,895 INFO sqlalchemy.engine.base.Engine (2175,)
2021-02-01 11:01:11,898 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,899 INFO sqlalchemy.engine.base.Engine (2176,)
2021-02-01 11:01:11,901 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,902 INFO sqlalchemy.engine.base.Engine (2177,)
2021-02-01 11:01:11,904 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,905 INFO sqlalchemy.engine.base.Engine (2178,)
2021-02-01 11:01:11,906 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,909 INFO sqlalchemy.engine.base.Engine (2179,)
2021-02-01 11:01:11,913 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,915 INFO sqlalchemy.engine.base.Engine (2180,)
2021-02-01 11:01:11,918 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,919 INFO sqlalchemy.engine.base.Engine (2181,)
2021-02-01 11:01:11,922 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,922 INFO sqlalchemy.engine.base.Engine (2182,)
2021-02-01 11:01:11,925 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:11,928 INFO sqlalchemy.engine.base.Engine (2183,)
2021-02-01 11:01:11,930 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,932 INFO sqlalchemy.engine.base.Engine (2184,)
2021-02-01 11:01:11,935 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,936 INFO sqlalchemy.engine.base.Engine (2185,)
2021-02-01 11:01:11,938 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,942 INFO sqlalchemy.engine.base.Engine (2186,)
2021-02-01 11:01:11,948 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,949 INFO sqlalchemy.engine.base.Engine (2187,)
2021-02-01 11:01:11,952 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,953 INFO sqlalchemy.engine.base.Engine (2188,)
2021-02-01 11:01:11,955 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,957 INFO sqlalchemy.engine.base.Engine (2189,)
2021-02-01 11:01:11,964 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,967 INFO sqlalchemy.engine.base.Engine (2190,)
2021-02-01 11:01:11,970 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,971 INFO sqlalchemy.engine.base.Engine (2191,)
2021-02-01 11:01:11,979 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,981 INFO sqlalchemy.engine.base.Engine (2192,)
2021-02-01 11:01:11,983 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,984 INFO sqlalchemy.engine.base.Engine (2193,)
2021-02-01 11:01:11,987 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,988 INFO sqlalchemy.engine.base.Engine (2194,)
2021-02-01 11:01:11,990 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,991 INFO sqlalchemy.engine.base.Engine (2195,)
2021-02-01 11:01:11,993 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,996 INFO sqlalchemy.engine.base.Engine (2196,)
2021-02-01 11:01:11,997 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:11,998 INFO sqlalchemy.engine.base.Engine (2197,)
2021-02-01 11:01:12,001 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,002 INFO sqlalchemy.engine.base.Engine (2198,)
2021-02-01 11:01:12,003 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,005 INFO sqlalchemy.engine.base.Engine (2199,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:12,175 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:12,176 INFO sqlalchemy.engine.base.Engine ((2200, 14.3, 14.3, 14.3, 152887.75000002538, 122594.56613904705), (2201, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152887.75000002538, 122594.56613904705), (2202, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152887.75000002538, 122594.56613904705), (2203, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152887.75000002538, 122594.56613904705), (2204, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152887.75000002538, 122594.56613904705), (2205, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152887.75000002538, 122594.56613904705), (2206, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152887.75000002538, 122594.56613904705), (2207, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152887.75000002538, 122594.56613904705)  ... displaying 10 of 50 total bound parameter sets ...  (2248, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152887.75000002538, 122594.56613904705), (2249, 135.9, 135.9, 135.9, 152887.75000002538, 122594.56613904705))
2021-02-01 11:01:12,180 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:12,181 INFO sqlalchemy.engine.base.Engine ('F45',)
2021-02-01 11:01:12,187 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:12,188 INFO sqlalchemy.engine.base.Engine ((1100, 'F45', 0, 'Anhydrite', 2200, 2201), (1101, 'F45', 1, 'Sandstone, grey, vf-f', 2202, 2203), (1102, 'F45', 2, 'Anhydrite', 2204, 2205), (1103, 'F45', 3, 'Dolomite', 2206, 2207), (1104, 'F45', 4, 'Anhydrite', 2208, 2209), (1105, 'F45', 5, 'Sandstone, grey, vf-f', 2210, 2211), (1106, 'F45', 6, 'Siltstone, red', 2212, 2213), (1107, 'F45', 7, 'Dolomite', 2214, 2215)  ... displaying 10 of 25 total bound parameter sets ...  (1123, 'F45', 23, 'Limestone', 2246, 2247), (1124, 'F45', 24, 'Volcanic', 2248, 2249))

2021-02-01 11:01:12,194 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:12,283 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:12,285 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:12,286 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:12,289 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:12,291 INFO sqlalchemy.engine.base.Engine ('F45',)
2021-02-01 11:01:12,293 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,295 INFO sqlalchemy.engine.base.Engine (2200,)
2021-02-01 11:01:12,299 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,303 INFO sqlalchemy.engine.base.Engine (2201,)
2021-02-01 11:01:12,306 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,308 INFO sqlalchemy.engine.base.Engine (2202,)
2021-02-01 11:01:12,311 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,312 INFO sqlalchemy.engine.base.Engine (2203,)
2021-02-01 11:01:12,314 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,315 INFO sqlalchemy.engine.base.Engine (2204,)
2021-02-01 11:01:12,318 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,320 INFO sqlalchemy.engine.base.Engine (2205,)
2021-02-01 11:01:12,322 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,323 INFO sqlalchemy.engine.base.Engine (2206,)
2021-02-01 11:01:12,325 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,327 INFO sqlalchemy.engine.base.Engine (2207,)
2021-02-01 11:01:12,329 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,330 INFO sqlalchemy.engine.base.Engine (2208,)
2021-02-01 11:01:12,332 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,333 INFO sqlalchemy.engine.base.Engine (2209,)
2021-02-01 11:01:12,335 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,337 INFO sqlalchemy.engine.base.Engine (2210,)
2021-02-01 11:01:12,340 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,341 INFO sqlalchemy.engine.base.Engine (2211,)
2021-02-01 11:01:12,343 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,345 INFO sqlalchemy.engine.base.Engine (2212,)
2021-02-01 11:01:12,351 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,352 INFO sqlalchemy.engine.base.Engine (2213,)
2021-02-01 11:01:12,356 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,357 INFO sqlalchemy.engine.base.Engine (2214,)
2021-02-01 11:01:12,359 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,361 INFO sqlalchemy.engine.base.Engine (2215,)
2021-02-01 11:01:12,364 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,365 INFO sqlalchemy.engine.base.Engine (2216,)
2021-02-01 11:01:12,367 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,368 INFO sqlalchemy.engine.base.Engine (2217,)
2021-02-01 11:01:12,371 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:12,372 INFO sqlalchemy.engine.base.Engine (2218,)
2021-02-01 11:01:12,375 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,377 INFO sqlalchemy.engine.base.Engine (2219,)
2021-02-01 11:01:12,379 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,380 INFO sqlalchemy.engine.base.Engine (2220,)
2021-02-01 11:01:12,383 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,384 INFO sqlalchemy.engine.base.Engine (2221,)
2021-02-01 11:01:12,386 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,387 INFO sqlalchemy.engine.base.Engine (2222,)
2021-02-01 11:01:12,389 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,390 INFO sqlalchemy.engine.base.Engine (2223,)
2021-02-01 11:01:12,393 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,394 INFO sqlalchemy.engine.base.Engine (2224,)
2021-02-01 11:01:12,396 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,398 INFO sqlalchemy.engine.base.Engine (2225,)
2021-02-01 11:01:12,400 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,401 INFO sqlalchemy.engine.base.Engine (2226,)
2021-02-01 11:01:12,404 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,405 INFO sqlalchemy.engine.base.Engine (2227,)
2021-02-01 11:01:12,408 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,409 INFO sqlalchemy.engine.base.Engine (2228,)
2021-02-01 11:01:12,411 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,412 INFO sqlalchemy.engine.base.Engine (2229,)
2021-02-01 11:01:12,414 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,416 INFO sqlalchemy.engine.base.Engine (2230,)
2021-02-01 11:01:12,418 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,419 INFO sqlalchemy.engine.base.Engine (2231,)
2021-02-01 11:01:12,422 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,423 INFO sqlalchemy.engine.base.Engine (2232,)
2021-02-01 11:01:12,425 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,426 INFO sqlalchemy.engine.base.Engine (2233,)
2021-02-01 11:01:12,428 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,430 INFO sqlalchemy.engine.base.Engine (2234,)
2021-02-01 11:01:12,432 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,433 INFO sqlalchemy.engine.base.Engine (2235,)
2021-02-01 11:01:12,436 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,437 INFO sqlalchemy.engine.base.Engine (2236,)
2021-02-01 11:01:12,442 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,444 INFO sqlalchemy.engine.base.Engine (2237,)
2021-02-01 11:01:12,446 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,447 INFO sqlalchemy.engine.base.Engine (2238,)
2021-02-01 11:01:12,448 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:12,449 INFO sqlalchemy.engine.base.Engine (2239,)
2021-02-01 11:01:12,453 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,454 INFO sqlalchemy.engine.base.Engine (2240,)
2021-02-01 11:01:12,456 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,457 INFO sqlalchemy.engine.base.Engine (2241,)
2021-02-01 11:01:12,459 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,460 INFO sqlalchemy.engine.base.Engine (2242,)
2021-02-01 11:01:12,464 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,465 INFO sqlalchemy.engine.base.Engine (2243,)
2021-02-01 11:01:12,467 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,468 INFO sqlalchemy.engine.base.Engine (2244,)
2021-02-01 11:01:12,471 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,472 INFO sqlalchemy.engine.base.Engine (2245,)
2021-02-01 11:01:12,475 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,476 INFO sqlalchemy.engine.base.Engine (2246,)
2021-02-01 11:01:12,478 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,479 INFO sqlalchemy.engine.base.Engine (2247,)
2021-02-01 11:01:12,481 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,482 INFO sqlalchemy.engine.base.Engine (2248,)
2021-02-01 11:01:12,485 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,486 INFO sqlalchemy.engine.base.Engine (2249,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:12,676 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:12,677 INFO sqlalchemy.engine.base.Engine ('F46',)
2021-02-01 11:01:12,682 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:12,683 INFO sqlalchemy.engine.base.Engine ((2250, 14.3, 14.3, 14.3, 152885.1050000254, 122596.2951390464), (2251, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152885.1050000254, 122596.2951390464), (2252, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152885.1050000254, 122596.2951390464), (2253, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152885.1050000254, 122596.2951390464), (2254, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152885.1050000254, 122596.2951390464), (2255, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152885.1050000254, 122596.2951390464), (2256, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152885.1050000254, 122596.2951390464), (2257, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152885.1050000254, 122596.2951390464)  ... displaying 10 of 50 total bound parameter sets ...  (2298, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152885.1050000254, 122596.2951390464), (2299, 135.9, 135.9, 135.9, 152885.1050000254, 122596.2951390464))
2021-02-01 11:01:12,690 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:12,691 INFO sqlalchemy.engine.base.Engine ((1125, 'F46', 0, 'Anhydrite', 2250, 2251), (1126, 'F46', 1, 'Sandstone, grey, vf-f', 2252, 2253), (1127, 'F46', 2, 'Anhydrite', 2254, 2255), (1128, 'F46', 3, 'Dolomite', 2256, 2257), (1129, 'F46', 4, 'Anhydrite', 2258, 2259), (1130, 'F46', 5, 'Sandstone, grey, vf-f', 2260, 2261), (1131, 'F46', 6, 'Siltstone, red', 2262, 2263), (1132, 'F46', 7, 'Dolomite', 2264, 2265)  ... displaying 10 of 25 total bound parameter sets ...  (1148, 'F46', 23, 'Limestone', 2296, 2297), (1149, 'F46', 24, 'Volcanic', 2298, 2299))
2021-02-01 11:01:12,694 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:12,919 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:12,920 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:12,920 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:12,923 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:12,924 INFO sqlalchemy.engine.base.Engine ('F46',)
2021-02-01 11:01:12,928 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,930 INFO sqlalchemy.engine.base.Engine (2250,)
2021-02-01 11:01:12,933 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,934 INFO sqlalchemy.engine.base.Engine (2251,)
2021-02-01 11:01:12,937 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,938 INFO sqlalchemy.engine.base.Engine (2252,)

2021-02-01 11:01:12,941 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,942 INFO sqlalchemy.engine.base.Engine (2253,)
2021-02-01 11:01:12,945 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,946 INFO sqlalchemy.engine.base.Engine (2254,)
2021-02-01 11:01:12,949 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,950 INFO sqlalchemy.engine.base.Engine (2255,)
2021-02-01 11:01:12,952 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,954 INFO sqlalchemy.engine.base.Engine (2256,)
2021-02-01 11:01:12,956 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,957 INFO sqlalchemy.engine.base.Engine (2257,)
2021-02-01 11:01:12,960 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,961 INFO sqlalchemy.engine.base.Engine (2258,)
2021-02-01 11:01:12,963 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,965 INFO sqlalchemy.engine.base.Engine (2259,)
2021-02-01 11:01:12,968 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,969 INFO sqlalchemy.engine.base.Engine (2260,)
2021-02-01 11:01:12,971 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,972 INFO sqlalchemy.engine.base.Engine (2261,)
2021-02-01 11:01:12,975 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,976 INFO sqlalchemy.engine.base.Engine (2262,)
2021-02-01 11:01:12,979 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,980 INFO sqlalchemy.engine.base.Engine (2263,)
2021-02-01 11:01:12,984 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,986 INFO sqlalchemy.engine.base.Engine (2264,)
2021-02-01 11:01:12,988 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,989 INFO sqlalchemy.engine.base.Engine (2265,)
2021-02-01 11:01:12,992 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,993 INFO sqlalchemy.engine.base.Engine (2266,)
2021-02-01 11:01:12,996 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:12,997 INFO sqlalchemy.engine.base.Engine (2267,)
2021-02-01 11:01:12,999 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,000 INFO sqlalchemy.engine.base.Engine (2268,)
2021-02-01 11:01:13,003 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,004 INFO sqlalchemy.engine.base.Engine (2269,)
2021-02-01 11:01:13,007 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,008 INFO sqlalchemy.engine.base.Engine (2270,)
2021-02-01 11:01:13,010 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,012 INFO sqlalchemy.engine.base.Engine (2271,)
2021-02-01 11:01:13,014 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,016 INFO sqlalchemy.engine.base.Engine (2272,)
2021-02-01 11:01:13,022 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:13,026 INFO sqlalchemy.engine.base.Engine (2273,)
2021-02-01 11:01:13,028 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,029 INFO sqlalchemy.engine.base.Engine (2274,)
2021-02-01 11:01:13,032 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,033 INFO sqlalchemy.engine.base.Engine (2275,)
2021-02-01 11:01:13,035 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,037 INFO sqlalchemy.engine.base.Engine (2276,)
2021-02-01 11:01:13,040 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,041 INFO sqlalchemy.engine.base.Engine (2277,)
2021-02-01 11:01:13,044 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,045 INFO sqlalchemy.engine.base.Engine (2278,)
2021-02-01 11:01:13,048 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,049 INFO sqlalchemy.engine.base.Engine (2279,)
2021-02-01 11:01:13,052 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,053 INFO sqlalchemy.engine.base.Engine (2280,)
2021-02-01 11:01:13,056 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,057 INFO sqlalchemy.engine.base.Engine (2281,)
2021-02-01 11:01:13,062 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,063 INFO sqlalchemy.engine.base.Engine (2282,)
2021-02-01 11:01:13,065 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,066 INFO sqlalchemy.engine.base.Engine (2283,)
2021-02-01 11:01:13,069 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,070 INFO sqlalchemy.engine.base.Engine (2284,)
2021-02-01 11:01:13,072 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,073 INFO sqlalchemy.engine.base.Engine (2285,)
2021-02-01 11:01:13,076 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,077 INFO sqlalchemy.engine.base.Engine (2286,)
2021-02-01 11:01:13,079 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,080 INFO sqlalchemy.engine.base.Engine (2287,)
2021-02-01 11:01:13,083 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,084 INFO sqlalchemy.engine.base.Engine (2288,)
2021-02-01 11:01:13,087 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,088 INFO sqlalchemy.engine.base.Engine (2289,)
2021-02-01 11:01:13,091 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,092 INFO sqlalchemy.engine.base.Engine (2290,)
2021-02-01 11:01:13,094 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,095 INFO sqlalchemy.engine.base.Engine (2291,)
2021-02-01 11:01:13,098 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,099 INFO sqlalchemy.engine.base.Engine (2292,)
2021-02-01 11:01:13,101 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,103 INFO sqlalchemy.engine.base.Engine (2293,)
2021-02-01 11:01:13,106 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:13,107 INFO sqlalchemy.engine.base.Engine (2294,)
2021-02-01 11:01:13,110 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,111 INFO sqlalchemy.engine.base.Engine (2295,)
2021-02-01 11:01:13,113 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,114 INFO sqlalchemy.engine.base.Engine (2296,)
2021-02-01 11:01:13,117 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,118 INFO sqlalchemy.engine.base.Engine (2297,)
2021-02-01 11:01:13,120 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,123 INFO sqlalchemy.engine.base.Engine (2298,)
2021-02-01 11:01:13,127 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,128 INFO sqlalchemy.engine.base.Engine (2299,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:13,334 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:13,340 INFO sqlalchemy.engine.base.Engine ((2300, 14.3, 14.3, 14.3, 152892.8990000255, 122594.97613904813), (2301, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152892.8990000255, 122594.97613904813), (2302, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152892.8990000255, 122594.97613904813), (2303, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152892.8990000255, 122594.97613904813), (2304, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152892.8990000255, 122594.97613904813), (2305, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152892.8990000255, 122594.97613904813), (2306, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152892.8990000255, 122594.97613904813), (2307, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152892.8990000255, 122594.97613904813)  ... displaying 10 of 50 total bound parameter sets ...  (2348, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152892.8990000255, 122594.97613904813), (2349, 135.9, 135.9, 135.9, 152892.8990000255, 122594.97613904813))
2021-02-01 11:01:13,342 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:13,344 INFO sqlalchemy.engine.base.Engine ('F47',)
2021-02-01 11:01:13,349 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:13,350 INFO sqlalchemy.engine.base.Engine ((1150, 'F47', 0, 'Anhydrite', 2300, 2301), (1151, 'F47', 1, 'Sandstone, grey, vf-f', 2302, 2303), (1152, 'F47', 2, 'Anhydrite', 2304, 2305), (1153, 'F47', 3, 'Dolomite', 2306, 2307), (1154, 'F47', 4, 'Anhydrite', 2308, 2309), (1155, 'F47', 5, 'Sandstone, grey, vf-f', 2310, 2311), (1156, 'F47', 6, 'Siltstone, red', 2312, 2313), (1157, 'F47', 7, 'Dolomite', 2314, 2315)  ... displaying 10 of 25 total bound parameter sets ...  (1173, 'F47', 23, 'Limestone', 2346, 2347), (1174, 'F47', 24, 'Volcanic', 2348, 2349))
2021-02-01 11:01:13,355 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:13,522 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:13,524 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:13,525 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:13,528 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:13,529 INFO sqlalchemy.engine.base.Engine ('F47',)
2021-02-01 11:01:13,531 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,532 INFO sqlalchemy.engine.base.Engine (2300,)
2021-02-01 11:01:13,534 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,535 INFO sqlalchemy.engine.base.Engine (2301,)
2021-02-01 11:01:13,536 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,537 INFO sqlalchemy.engine.base.Engine (2302,)
2021-02-01 11:01:13,538 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,539 INFO sqlalchemy.engine.base.Engine (2303,)
2021-02-01 11:01:13,542 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,543 INFO sqlalchemy.engine.base.Engine (2304,)
2021-02-01 11:01:13,545 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,546 INFO sqlalchemy.engine.base.Engine (2305,)
2021-02-01 11:01:13,549 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,553 INFO sqlalchemy.engine.base.Engine (2306,)
2021-02-01 11:01:13,555 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,556 INFO sqlalchemy.engine.base.Engine (2307,)

2021-02-01 11:01:13,559 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,560 INFO sqlalchemy.engine.base.Engine (2308,)
2021-02-01 11:01:13,563 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,564 INFO sqlalchemy.engine.base.Engine (2309,)
2021-02-01 11:01:13,566 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,567 INFO sqlalchemy.engine.base.Engine (2310,)
2021-02-01 11:01:13,569 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,570 INFO sqlalchemy.engine.base.Engine (2311,)
2021-02-01 11:01:13,573 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,574 INFO sqlalchemy.engine.base.Engine (2312,)
2021-02-01 11:01:13,576 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,577 INFO sqlalchemy.engine.base.Engine (2313,)
2021-02-01 11:01:13,580 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,581 INFO sqlalchemy.engine.base.Engine (2314,)
2021-02-01 11:01:13,584 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,585 INFO sqlalchemy.engine.base.Engine (2315,)
2021-02-01 11:01:13,588 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,589 INFO sqlalchemy.engine.base.Engine (2316,)
2021-02-01 11:01:13,591 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,592 INFO sqlalchemy.engine.base.Engine (2317,)
2021-02-01 11:01:13,595 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,596 INFO sqlalchemy.engine.base.Engine (2318,)
2021-02-01 11:01:13,598 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,599 INFO sqlalchemy.engine.base.Engine (2319,)
2021-02-01 11:01:13,602 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,602 INFO sqlalchemy.engine.base.Engine (2320,)
2021-02-01 11:01:13,605 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,606 INFO sqlalchemy.engine.base.Engine (2321,)
2021-02-01 11:01:13,609 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,610 INFO sqlalchemy.engine.base.Engine (2322,)
2021-02-01 11:01:13,612 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,613 INFO sqlalchemy.engine.base.Engine (2323,)
2021-02-01 11:01:13,619 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,620 INFO sqlalchemy.engine.base.Engine (2324,)
2021-02-01 11:01:13,624 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,625 INFO sqlalchemy.engine.base.Engine (2325,)
2021-02-01 11:01:13,628 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,629 INFO sqlalchemy.engine.base.Engine (2326,)
2021-02-01 11:01:13,631 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,633 INFO sqlalchemy.engine.base.Engine (2327,)
2021-02-01 11:01:13,635 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:13,636 INFO sqlalchemy.engine.base.Engine (2328,)
2021-02-01 11:01:13,639 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,642 INFO sqlalchemy.engine.base.Engine (2329,)
2021-02-01 11:01:13,644 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,645 INFO sqlalchemy.engine.base.Engine (2330,)
2021-02-01 11:01:13,646 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,648 INFO sqlalchemy.engine.base.Engine (2331,)
2021-02-01 11:01:13,650 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,651 INFO sqlalchemy.engine.base.Engine (2332,)
2021-02-01 11:01:13,653 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,655 INFO sqlalchemy.engine.base.Engine (2333,)
2021-02-01 11:01:13,657 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,659 INFO sqlalchemy.engine.base.Engine (2334,)
2021-02-01 11:01:13,661 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,662 INFO sqlalchemy.engine.base.Engine (2335,)
2021-02-01 11:01:13,665 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,666 INFO sqlalchemy.engine.base.Engine (2336,)
2021-02-01 11:01:13,669 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,670 INFO sqlalchemy.engine.base.Engine (2337,)
2021-02-01 11:01:13,673 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,675 INFO sqlalchemy.engine.base.Engine (2338,)
2021-02-01 11:01:13,677 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,679 INFO sqlalchemy.engine.base.Engine (2339,)
2021-02-01 11:01:13,681 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,682 INFO sqlalchemy.engine.base.Engine (2340,)
2021-02-01 11:01:13,685 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,686 INFO sqlalchemy.engine.base.Engine (2341,)
2021-02-01 11:01:13,691 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,692 INFO sqlalchemy.engine.base.Engine (2342,)
2021-02-01 11:01:13,694 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,695 INFO sqlalchemy.engine.base.Engine (2343,)
2021-02-01 11:01:13,698 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,699 INFO sqlalchemy.engine.base.Engine (2344,)
2021-02-01 11:01:13,701 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,702 INFO sqlalchemy.engine.base.Engine (2345,)
2021-02-01 11:01:13,704 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,705 INFO sqlalchemy.engine.base.Engine (2346,)
2021-02-01 11:01:13,708 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,709 INFO sqlalchemy.engine.base.Engine (2347,)
2021-02-01 11:01:13,713 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:13,714 INFO sqlalchemy.engine.base.Engine (2348,)
2021-02-01 11:01:13,717 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:13,721 INFO sqlalchemy.engine.base.Engine (2349,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:13,900 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:13,901 INFO sqlalchemy.engine.base.Engine ((2350, 14.3, 14.3, 14.3, 152890.24100002553, 122596.46113904752), (2351, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152890.24100002553, 122596.46113904752), (2352, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152890.24100002553, 122596.46113904752), (2353, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152890.24100002553, 122596.46113904752), (2354, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152890.24100002553, 122596.46113904752), (2355, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152890.24100002553, 122596.46113904752), (2356, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152890.24100002553, 122596.46113904752), (2357, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152890.24100002553, 122596.46113904752)  ... displaying 10 of 50 total bound parameter sets ...  (2398, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152890.24100002553, 122596.46113904752), (2399, 135.9, 135.9, 135.9, 152890.24100002553, 122596.46113904752))
2021-02-01 11:01:13,903 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:13,904 INFO sqlalchemy.engine.base.Engine ('F48',)
2021-02-01 11:01:13,908 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:13,909 INFO sqlalchemy.engine.base.Engine ((1175, 'F48', 0, 'Anhydrite', 2350, 2351), (1176, 'F48', 1, 'Sandstone, grey, vf-f', 2352, 2353), (1177, 'F48', 2, 'Anhydrite', 2354, 2355), (1178, 'F48', 3, 'Dolomite', 2356, 2357), (1179, 'F48', 4, 'Anhydrite', 2358, 2359), (1180, 'F48', 5, 'Sandstone, grey, vf-f', 2360, 2361), (1181, 'F48', 6, 'Siltstone, red', 2362, 2363), (1182, 'F48', 7, 'Dolomite', 2364, 2365)  ... displaying 10 of 25 total bound parameter sets ...  (1198, 'F48', 23, 'Limestone', 2396, 2397), (1199, 'F48', 24, 'Volcanic', 2398, 2399))
2021-02-01 11:01:13,914 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:14,017 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:14,018 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:14,021 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:14,025 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:14,026 INFO sqlalchemy.engine.base.Engine ('F48',)
2021-02-01 11:01:14,030 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,031 INFO sqlalchemy.engine.base.Engine (2350,)
2021-02-01 11:01:14,032 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,033 INFO sqlalchemy.engine.base.Engine (2351,)
2021-02-01 11:01:14,035 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,035 INFO sqlalchemy.engine.base.Engine (2352,)
2021-02-01 11:01:14,037 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,039 INFO sqlalchemy.engine.base.Engine (2353,)
2021-02-01 11:01:14,043 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,045 INFO sqlalchemy.engine.base.Engine (2354,)
2021-02-01 11:01:14,048 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,049 INFO sqlalchemy.engine.base.Engine (2355,)
2021-02-01 11:01:14,053 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,054 INFO sqlalchemy.engine.base.Engine (2356,)
2021-02-01 11:01:14,059 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,062 INFO sqlalchemy.engine.base.Engine (2357,)
2021-02-01 11:01:14,064 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,065 INFO sqlalchemy.engine.base.Engine (2358,)
2021-02-01 11:01:14,068 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,069 INFO sqlalchemy.engine.base.Engine (2359,)
2021-02-01 11:01:14,071 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,073 INFO sqlalchemy.engine.base.Engine (2360,)
2021-02-01 11:01:14,074 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,079 INFO sqlalchemy.engine.base.Engine (2361,)
2021-02-01 11:01:14,082 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,083 INFO sqlalchemy.engine.base.Engine (2362,)

2021-02-01 11:01:14,085 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,087 INFO sqlalchemy.engine.base.Engine (2363,)
2021-02-01 11:01:14,090 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,091 INFO sqlalchemy.engine.base.Engine (2364,)
2021-02-01 11:01:14,093 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,094 INFO sqlalchemy.engine.base.Engine (2365,)
2021-02-01 11:01:14,097 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,098 INFO sqlalchemy.engine.base.Engine (2366,)
2021-02-01 11:01:14,101 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,102 INFO sqlalchemy.engine.base.Engine (2367,)
2021-02-01 11:01:14,105 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,106 INFO sqlalchemy.engine.base.Engine (2368,)
2021-02-01 11:01:14,108 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,109 INFO sqlalchemy.engine.base.Engine (2369,)
2021-02-01 11:01:14,113 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,114 INFO sqlalchemy.engine.base.Engine (2370,)
2021-02-01 11:01:14,117 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,118 INFO sqlalchemy.engine.base.Engine (2371,)
2021-02-01 11:01:14,120 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,121 INFO sqlalchemy.engine.base.Engine (2372,)
2021-02-01 11:01:14,124 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,125 INFO sqlalchemy.engine.base.Engine (2373,)
2021-02-01 11:01:14,127 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,128 INFO sqlalchemy.engine.base.Engine (2374,)
2021-02-01 11:01:14,131 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,132 INFO sqlalchemy.engine.base.Engine (2375,)
2021-02-01 11:01:14,135 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,137 INFO sqlalchemy.engine.base.Engine (2376,)
2021-02-01 11:01:14,140 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,141 INFO sqlalchemy.engine.base.Engine (2377,)
2021-02-01 11:01:14,147 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,149 INFO sqlalchemy.engine.base.Engine (2378,)
2021-02-01 11:01:14,151 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,152 INFO sqlalchemy.engine.base.Engine (2379,)
2021-02-01 11:01:14,155 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,157 INFO sqlalchemy.engine.base.Engine (2380,)
2021-02-01 11:01:14,160 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,161 INFO sqlalchemy.engine.base.Engine (2381,)
2021-02-01 11:01:14,163 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,166 INFO sqlalchemy.engine.base.Engine (2382,)
2021-02-01 11:01:14,169 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:14,170 INFO sqlalchemy.engine.base.Engine (2383,)
2021-02-01 11:01:14,172 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,174 INFO sqlalchemy.engine.base.Engine (2384,)
2021-02-01 11:01:14,176 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,177 INFO sqlalchemy.engine.base.Engine (2385,)
2021-02-01 11:01:14,181 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,183 INFO sqlalchemy.engine.base.Engine (2386,)
2021-02-01 11:01:14,187 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,190 INFO sqlalchemy.engine.base.Engine (2387,)
2021-02-01 11:01:14,193 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,195 INFO sqlalchemy.engine.base.Engine (2388,)
2021-02-01 11:01:14,196 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,198 INFO sqlalchemy.engine.base.Engine (2389,)
2021-02-01 11:01:14,200 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,201 INFO sqlalchemy.engine.base.Engine (2390,)
2021-02-01 11:01:14,203 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,205 INFO sqlalchemy.engine.base.Engine (2391,)
2021-02-01 11:01:14,209 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,210 INFO sqlalchemy.engine.base.Engine (2392,)
2021-02-01 11:01:14,213 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,216 INFO sqlalchemy.engine.base.Engine (2393,)
2021-02-01 11:01:14,218 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,219 INFO sqlalchemy.engine.base.Engine (2394,)
2021-02-01 11:01:14,221 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,222 INFO sqlalchemy.engine.base.Engine (2395,)
2021-02-01 11:01:14,225 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,226 INFO sqlalchemy.engine.base.Engine (2396,)
2021-02-01 11:01:14,228 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,231 INFO sqlalchemy.engine.base.Engine (2397,)
2021-02-01 11:01:14,234 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,235 INFO sqlalchemy.engine.base.Engine (2398,)
2021-02-01 11:01:14,237 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,237 INFO sqlalchemy.engine.base.Engine (2399,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:14,372 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:14,373 INFO sqlalchemy.engine.base.Engine ((2400, 14.3, 14.3, 14.3, 152887.63100002534, 122598.04613904748), (2401, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152887.63100002534, 122598.04613904748), (2402, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152887.63100002534, 122598.04613904748), (2403, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152887.63100002534, 122598.04613904748), (2404, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152887.63100002534, 122598.04613904748), (2405, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152887.63100002534, 122598.04613904748), (2406, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152887.63100002534, 122598.04613904748), (2407, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152887.63100002534, 122598.04613904748)  ... displaying 10 of 50 total bound parameter sets ...  (2448, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152887.63100002534, 122598.04613904748), (2449, 135.9, 135.9, 135.9, 152887.63100002534, 122598.04613904748))
2021-02-01 11:01:14,376 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:14,377 INFO sqlalchemy.engine.base.Engine ('F49',)
2021-02-01 11:01:14,381 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:14,382 INFO sqlalchemy.engine.base.Engine ((1200, 'F49', 0, 'Anhydrite', 2400, 2401), (1201, 'F49', 1, 'Sandstone, grey, vf-f', 2402, 2403), (1202, 'F49', 2, 'Anhydrite', 2404, 2405), (1203, 'F49', 3, 'Dolomite', 2406, 2407), (1204, 'F49', 4, 'Anhydrite', 2408, 2409), (1205, 'F49', 5, 'Sandstone, grey, vf-f', 2410, 2411), (1206, 'F49', 6, 'Siltstone, red', 2412, 2413), (1207, 'F49', 7, 'Dolomite', 2414, 2415)  ... displaying 10 of 25 total bound parameter sets ...  (1223, 'F49', 23, 'Limestone', 2446, 2447), (1224, 'F49', 24, 'Volcanic', 2448, 2449))

2021-02-01 11:01:14,385 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:14,511 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:14,516 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:14,524 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:14,529 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:14,530 INFO sqlalchemy.engine.base.Engine ('F49',)
2021-02-01 11:01:14,540 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,541 INFO sqlalchemy.engine.base.Engine (2400,)
2021-02-01 11:01:14,545 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,548 INFO sqlalchemy.engine.base.Engine (2401,)
2021-02-01 11:01:14,551 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,552 INFO sqlalchemy.engine.base.Engine (2402,)
2021-02-01 11:01:14,557 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,559 INFO sqlalchemy.engine.base.Engine (2403,)
2021-02-01 11:01:14,562 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,563 INFO sqlalchemy.engine.base.Engine (2404,)
2021-02-01 11:01:14,565 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,566 INFO sqlalchemy.engine.base.Engine (2405,)
2021-02-01 11:01:14,569 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,570 INFO sqlalchemy.engine.base.Engine (2406,)
2021-02-01 11:01:14,572 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,577 INFO sqlalchemy.engine.base.Engine (2407,)
2021-02-01 11:01:14,579 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,580 INFO sqlalchemy.engine.base.Engine (2408,)
2021-02-01 11:01:14,584 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,588 INFO sqlalchemy.engine.base.Engine (2409,)
2021-02-01 11:01:14,590 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,592 INFO sqlalchemy.engine.base.Engine (2410,)
2021-02-01 11:01:14,594 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,596 INFO sqlalchemy.engine.base.Engine (2411,)
2021-02-01 11:01:14,599 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,601 INFO sqlalchemy.engine.base.Engine (2412,)
2021-02-01 11:01:14,605 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,608 INFO sqlalchemy.engine.base.Engine (2413,)
2021-02-01 11:01:14,610 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,611 INFO sqlalchemy.engine.base.Engine (2414,)
2021-02-01 11:01:14,614 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,616 INFO sqlalchemy.engine.base.Engine (2415,)
2021-02-01 11:01:14,619 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,620 INFO sqlalchemy.engine.base.Engine (2416,)
2021-02-01 11:01:14,622 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,624 INFO sqlalchemy.engine.base.Engine (2417,)
2021-02-01 11:01:14,628 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:14,630 INFO sqlalchemy.engine.base.Engine (2418,)
2021-02-01 11:01:14,632 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,633 INFO sqlalchemy.engine.base.Engine (2419,)
2021-02-01 11:01:14,634 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,637 INFO sqlalchemy.engine.base.Engine (2420,)
2021-02-01 11:01:14,638 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,639 INFO sqlalchemy.engine.base.Engine (2421,)
2021-02-01 11:01:14,641 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,643 INFO sqlalchemy.engine.base.Engine (2422,)
2021-02-01 11:01:14,644 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,645 INFO sqlalchemy.engine.base.Engine (2423,)
2021-02-01 11:01:14,848 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,849 INFO sqlalchemy.engine.base.Engine (2424,)
2021-02-01 11:01:14,851 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,857 INFO sqlalchemy.engine.base.Engine (2425,)
2021-02-01 11:01:14,861 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,863 INFO sqlalchemy.engine.base.Engine (2426,)
2021-02-01 11:01:14,865 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,867 INFO sqlalchemy.engine.base.Engine (2427,)
2021-02-01 11:01:14,870 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,871 INFO sqlalchemy.engine.base.Engine (2428,)
2021-02-01 11:01:14,873 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,875 INFO sqlalchemy.engine.base.Engine (2429,)
2021-02-01 11:01:14,877 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,882 INFO sqlalchemy.engine.base.Engine (2430,)
2021-02-01 11:01:14,885 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,886 INFO sqlalchemy.engine.base.Engine (2431,)
2021-02-01 11:01:14,888 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,890 INFO sqlalchemy.engine.base.Engine (2432,)
2021-02-01 11:01:14,892 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,894 INFO sqlalchemy.engine.base.Engine (2433,)
2021-02-01 11:01:14,899 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,901 INFO sqlalchemy.engine.base.Engine (2434,)
2021-02-01 11:01:14,903 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,904 INFO sqlalchemy.engine.base.Engine (2435,)
2021-02-01 11:01:14,911 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,913 INFO sqlalchemy.engine.base.Engine (2436,)
2021-02-01 11:01:14,915 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,917 INFO sqlalchemy.engine.base.Engine (2437,)
2021-02-01 11:01:14,920 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,921 INFO sqlalchemy.engine.base.Engine (2438,)
2021-02-01 11:01:14,924 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:14,925 INFO sqlalchemy.engine.base.Engine (2439,)
2021-02-01 11:01:14,927 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,929 INFO sqlalchemy.engine.base.Engine (2440,)
2021-02-01 11:01:14,933 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,936 INFO sqlalchemy.engine.base.Engine (2441,)
2021-02-01 11:01:14,939 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,940 INFO sqlalchemy.engine.base.Engine (2442,)
2021-02-01 11:01:14,942 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,944 INFO sqlalchemy.engine.base.Engine (2443,)
2021-02-01 11:01:14,947 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,948 INFO sqlalchemy.engine.base.Engine (2444,)
2021-02-01 11:01:14,951 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,952 INFO sqlalchemy.engine.base.Engine (2445,)
2021-02-01 11:01:14,956 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,957 INFO sqlalchemy.engine.base.Engine (2446,)
2021-02-01 11:01:14,959 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,960 INFO sqlalchemy.engine.base.Engine (2447,)
2021-02-01 11:01:14,969 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,970 INFO sqlalchemy.engine.base.Engine (2448,)
2021-02-01 11:01:14,972 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:14,973 INFO sqlalchemy.engine.base.Engine (2449,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:15,128 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:15,131 INFO sqlalchemy.engine.base.Engine ((2450, 14.3, 14.3, 14.3, 152885.82300002544, 122597.76613904722), (2451, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152885.82300002544, 122597.76613904722), (2452, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152885.82300002544, 122597.76613904722), (2453, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152885.82300002544, 122597.76613904722), (2454, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152885.82300002544, 122597.76613904722), (2455, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152885.82300002544, 122597.76613904722), (2456, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152885.82300002544, 122597.76613904722), (2457, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152885.82300002544, 122597.76613904722)  ... displaying 10 of 50 total bound parameter sets ...  (2498, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152885.82300002544, 122597.76613904722), (2499, 135.9, 135.9, 135.9, 152885.82300002544, 122597.76613904722))
2021-02-01 11:01:15,134 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:15,136 INFO sqlalchemy.engine.base.Engine ('F50',)
2021-02-01 11:01:15,141 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:15,148 INFO sqlalchemy.engine.base.Engine ((1225, 'F50', 0, 'Anhydrite', 2450, 2451), (1226, 'F50', 1, 'Sandstone, grey, vf-f', 2452, 2453), (1227, 'F50', 2, 'Anhydrite', 2454, 2455), (1228, 'F50', 3, 'Dolomite', 2456, 2457), (1229, 'F50', 4, 'Anhydrite', 2458, 2459), (1230, 'F50', 5, 'Sandstone, grey, vf-f', 2460, 2461), (1231, 'F50', 6, 'Siltstone, red', 2462, 2463), (1232, 'F50', 7, 'Dolomite', 2464, 2465)  ... displaying 10 of 25 total bound parameter sets ...  (1248, 'F50', 23, 'Limestone', 2496, 2497), (1249, 'F50', 24, 'Volcanic', 2498, 2499))
2021-02-01 11:01:15,152 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:15,244 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:15,246 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:15,249 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:15,254 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:15,255 INFO sqlalchemy.engine.base.Engine ('F50',)
2021-02-01 11:01:15,258 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,259 INFO sqlalchemy.engine.base.Engine (2450,)
2021-02-01 11:01:15,262 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,263 INFO sqlalchemy.engine.base.Engine (2451,)
2021-02-01 11:01:15,265 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,266 INFO sqlalchemy.engine.base.Engine (2452,)

2021-02-01 11:01:15,268 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,269 INFO sqlalchemy.engine.base.Engine (2453,)
2021-02-01 11:01:15,271 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,273 INFO sqlalchemy.engine.base.Engine (2454,)
2021-02-01 11:01:15,275 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,276 INFO sqlalchemy.engine.base.Engine (2455,)
2021-02-01 11:01:15,278 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,282 INFO sqlalchemy.engine.base.Engine (2456,)
2021-02-01 11:01:15,284 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,286 INFO sqlalchemy.engine.base.Engine (2457,)
2021-02-01 11:01:15,291 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,293 INFO sqlalchemy.engine.base.Engine (2458,)
2021-02-01 11:01:15,296 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,297 INFO sqlalchemy.engine.base.Engine (2459,)
2021-02-01 11:01:15,300 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,301 INFO sqlalchemy.engine.base.Engine (2460,)
2021-02-01 11:01:15,304 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,305 INFO sqlalchemy.engine.base.Engine (2461,)
2021-02-01 11:01:15,308 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,309 INFO sqlalchemy.engine.base.Engine (2462,)
2021-02-01 11:01:15,311 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,316 INFO sqlalchemy.engine.base.Engine (2463,)
2021-02-01 11:01:15,319 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,321 INFO sqlalchemy.engine.base.Engine (2464,)
2021-02-01 11:01:15,323 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,324 INFO sqlalchemy.engine.base.Engine (2465,)
2021-02-01 11:01:15,326 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,328 INFO sqlalchemy.engine.base.Engine (2466,)
2021-02-01 11:01:15,330 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,331 INFO sqlalchemy.engine.base.Engine (2467,)
2021-02-01 11:01:15,334 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,336 INFO sqlalchemy.engine.base.Engine (2468,)
2021-02-01 11:01:15,338 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,340 INFO sqlalchemy.engine.base.Engine (2469,)
2021-02-01 11:01:15,342 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,344 INFO sqlalchemy.engine.base.Engine (2470,)
2021-02-01 11:01:15,346 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,347 INFO sqlalchemy.engine.base.Engine (2471,)
2021-02-01 11:01:15,350 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,352 INFO sqlalchemy.engine.base.Engine (2472,)
2021-02-01 11:01:15,354 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:15,359 INFO sqlalchemy.engine.base.Engine (2473,)
2021-02-01 11:01:15,365 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,366 INFO sqlalchemy.engine.base.Engine (2474,)
2021-02-01 11:01:15,369 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,371 INFO sqlalchemy.engine.base.Engine (2475,)
2021-02-01 11:01:15,373 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,374 INFO sqlalchemy.engine.base.Engine (2476,)
2021-02-01 11:01:15,377 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,378 INFO sqlalchemy.engine.base.Engine (2477,)
2021-02-01 11:01:15,380 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,385 INFO sqlalchemy.engine.base.Engine (2478,)
2021-02-01 11:01:15,387 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,389 INFO sqlalchemy.engine.base.Engine (2479,)
2021-02-01 11:01:15,392 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,396 INFO sqlalchemy.engine.base.Engine (2480,)
2021-02-01 11:01:15,398 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,399 INFO sqlalchemy.engine.base.Engine (2481,)
2021-02-01 11:01:15,402 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,403 INFO sqlalchemy.engine.base.Engine (2482,)
2021-02-01 11:01:15,405 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,406 INFO sqlalchemy.engine.base.Engine (2483,)
2021-02-01 11:01:15,409 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,413 INFO sqlalchemy.engine.base.Engine (2484,)
2021-02-01 11:01:15,415 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,418 INFO sqlalchemy.engine.base.Engine (2485,)
2021-02-01 11:01:15,421 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,422 INFO sqlalchemy.engine.base.Engine (2486,)
2021-02-01 11:01:15,425 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,426 INFO sqlalchemy.engine.base.Engine (2487,)
2021-02-01 11:01:15,429 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,430 INFO sqlalchemy.engine.base.Engine (2488,)
2021-02-01 11:01:15,432 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,434 INFO sqlalchemy.engine.base.Engine (2489,)
2021-02-01 11:01:15,438 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,439 INFO sqlalchemy.engine.base.Engine (2490,)
2021-02-01 11:01:15,441 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,442 INFO sqlalchemy.engine.base.Engine (2491,)
2021-02-01 11:01:15,444 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,445 INFO sqlalchemy.engine.base.Engine (2492,)
2021-02-01 11:01:15,448 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,449 INFO sqlalchemy.engine.base.Engine (2493,)
2021-02-01 11:01:15,452 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:15,453 INFO sqlalchemy.engine.base.Engine (2494,)
2021-02-01 11:01:15,457 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,458 INFO sqlalchemy.engine.base.Engine (2495,)
2021-02-01 11:01:15,461 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,463 INFO sqlalchemy.engine.base.Engine (2496,)
2021-02-01 11:01:15,467 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,468 INFO sqlalchemy.engine.base.Engine (2497,)
2021-02-01 11:01:15,471 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,472 INFO sqlalchemy.engine.base.Engine (2498,)
2021-02-01 11:01:15,475 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,476 INFO sqlalchemy.engine.base.Engine (2499,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:15,638 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:15,639 INFO sqlalchemy.engine.base.Engine ('F51',)
2021-02-01 11:01:15,643 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:15,652 INFO sqlalchemy.engine.base.Engine ((2500, 14.3, 14.3, 14.3, 152888.55700002538, 122593.31413904855), (2501, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.55700002538, 122593.31413904855), (2502, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.55700002538, 122593.31413904855), (2503, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.55700002538, 122593.31413904855), (2504, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.55700002538, 122593.31413904855), (2505, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.55700002538, 122593.31413904855), (2506, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.55700002538, 122593.31413904855), (2507, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152888.55700002538, 122593.31413904855)  ... displaying 10 of 50 total bound parameter sets ...  (2548, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152888.55700002538, 122593.31413904855), (2549, 135.9, 135.9, 135.9, 152888.55700002538, 122593.31413904855))
2021-02-01 11:01:15,662 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:15,663 INFO sqlalchemy.engine.base.Engine ((1250, 'F51', 0, 'Anhydrite', 2500, 2501), (1251, 'F51', 1, 'Sandstone, grey, vf-f', 2502, 2503), (1252, 'F51', 2, 'Anhydrite', 2504, 2505), (1253, 'F51', 3, 'Dolomite', 2506, 2507), (1254, 'F51', 4, 'Anhydrite', 2508, 2509), (1255, 'F51', 5, 'Sandstone, grey, vf-f', 2510, 2511), (1256, 'F51', 6, 'Siltstone, red', 2512, 2513), (1257, 'F51', 7, 'Dolomite', 2514, 2515)  ... displaying 10 of 25 total bound parameter sets ...  (1273, 'F51', 23, 'Limestone', 2546, 2547), (1274, 'F51', 24, 'Volcanic', 2548, 2549))
2021-02-01 11:01:15,674 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:15,834 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:15,836 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:15,837 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:15,841 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:15,843 INFO sqlalchemy.engine.base.Engine ('F51',)
2021-02-01 11:01:15,846 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,847 INFO sqlalchemy.engine.base.Engine (2500,)
2021-02-01 11:01:15,849 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,851 INFO sqlalchemy.engine.base.Engine (2501,)
2021-02-01 11:01:15,853 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,855 INFO sqlalchemy.engine.base.Engine (2502,)
2021-02-01 11:01:15,858 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,862 INFO sqlalchemy.engine.base.Engine (2503,)
2021-02-01 11:01:15,866 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,869 INFO sqlalchemy.engine.base.Engine (2504,)
2021-02-01 11:01:15,874 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,875 INFO sqlalchemy.engine.base.Engine (2505,)
2021-02-01 11:01:15,878 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,881 INFO sqlalchemy.engine.base.Engine (2506,)
2021-02-01 11:01:15,884 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,885 INFO sqlalchemy.engine.base.Engine (2507,)

2021-02-01 11:01:15,888 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,889 INFO sqlalchemy.engine.base.Engine (2508,)
2021-02-01 11:01:15,891 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,892 INFO sqlalchemy.engine.base.Engine (2509,)
2021-02-01 11:01:15,894 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,900 INFO sqlalchemy.engine.base.Engine (2510,)
2021-02-01 11:01:15,904 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,907 INFO sqlalchemy.engine.base.Engine (2511,)
2021-02-01 11:01:15,910 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,911 INFO sqlalchemy.engine.base.Engine (2512,)
2021-02-01 11:01:15,913 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,914 INFO sqlalchemy.engine.base.Engine (2513,)
2021-02-01 11:01:15,916 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,918 INFO sqlalchemy.engine.base.Engine (2514,)
2021-02-01 11:01:15,920 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,920 INFO sqlalchemy.engine.base.Engine (2515,)
2021-02-01 11:01:15,924 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,926 INFO sqlalchemy.engine.base.Engine (2516,)
2021-02-01 11:01:15,928 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,929 INFO sqlalchemy.engine.base.Engine (2517,)
2021-02-01 11:01:15,933 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,935 INFO sqlalchemy.engine.base.Engine (2518,)
2021-02-01 11:01:15,937 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,939 INFO sqlalchemy.engine.base.Engine (2519,)
2021-02-01 11:01:15,941 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,943 INFO sqlalchemy.engine.base.Engine (2520,)
2021-02-01 11:01:15,948 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,950 INFO sqlalchemy.engine.base.Engine (2521,)
2021-02-01 11:01:15,952 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,954 INFO sqlalchemy.engine.base.Engine (2522,)
2021-02-01 11:01:15,956 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,958 INFO sqlalchemy.engine.base.Engine (2523,)
2021-02-01 11:01:15,960 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,961 INFO sqlalchemy.engine.base.Engine (2524,)
2021-02-01 11:01:15,967 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,968 INFO sqlalchemy.engine.base.Engine (2525,)
2021-02-01 11:01:15,972 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,974 INFO sqlalchemy.engine.base.Engine (2526,)
2021-02-01 11:01:15,977 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,979 INFO sqlalchemy.engine.base.Engine (2527,)
2021-02-01 11:01:15,982 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:15,985 INFO sqlalchemy.engine.base.Engine (2528,)
2021-02-01 11:01:15,987 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,989 INFO sqlalchemy.engine.base.Engine (2529,)
2021-02-01 11:01:15,992 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,993 INFO sqlalchemy.engine.base.Engine (2530,)
2021-02-01 11:01:15,997 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:15,998 INFO sqlalchemy.engine.base.Engine (2531,)
2021-02-01 11:01:16,002 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,003 INFO sqlalchemy.engine.base.Engine (2532,)
2021-02-01 11:01:16,005 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,007 INFO sqlalchemy.engine.base.Engine (2533,)
2021-02-01 11:01:16,009 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,011 INFO sqlalchemy.engine.base.Engine (2534,)
2021-02-01 11:01:16,015 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,016 INFO sqlalchemy.engine.base.Engine (2535,)
2021-02-01 11:01:16,018 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,019 INFO sqlalchemy.engine.base.Engine (2536,)
2021-02-01 11:01:16,024 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,025 INFO sqlalchemy.engine.base.Engine (2537,)
2021-02-01 11:01:16,028 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,029 INFO sqlalchemy.engine.base.Engine (2538,)
2021-02-01 11:01:16,033 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,035 INFO sqlalchemy.engine.base.Engine (2539,)
2021-02-01 11:01:16,037 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,038 INFO sqlalchemy.engine.base.Engine (2540,)
2021-02-01 11:01:16,041 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,043 INFO sqlalchemy.engine.base.Engine (2541,)
2021-02-01 11:01:16,048 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,049 INFO sqlalchemy.engine.base.Engine (2542,)
2021-02-01 11:01:16,052 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,053 INFO sqlalchemy.engine.base.Engine (2543,)
2021-02-01 11:01:16,055 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,056 INFO sqlalchemy.engine.base.Engine (2544,)
2021-02-01 11:01:16,059 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,060 INFO sqlalchemy.engine.base.Engine (2545,)
2021-02-01 11:01:16,062 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,064 INFO sqlalchemy.engine.base.Engine (2546,)
2021-02-01 11:01:16,066 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,069 INFO sqlalchemy.engine.base.Engine (2547,)
2021-02-01 11:01:16,072 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,073 INFO sqlalchemy.engine.base.Engine (2548,)
2021-02-01 11:01:16,075 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:16,076 INFO sqlalchemy.engine.base.Engine (2549,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:16,238 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:16,242 INFO sqlalchemy.engine.base.Engine ((2550, 14.3, 14.3, 14.3, 152891.79100002546, 122586.1501390487), (2551, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152891.79100002546, 122586.1501390487), (2552, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152891.79100002546, 122586.1501390487), (2553, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152891.79100002546, 122586.1501390487), (2554, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152891.79100002546, 122586.1501390487), (2555, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152891.79100002546, 122586.1501390487), (2556, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152891.79100002546, 122586.1501390487), (2557, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152891.79100002546, 122586.1501390487)  ... displaying 10 of 50 total bound parameter sets ...  (2598, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152891.79100002546, 122586.1501390487), (2599, 135.9, 135.9, 135.9, 152891.79100002546, 122586.1501390487))
2021-02-01 11:01:16,246 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:16,247 INFO sqlalchemy.engine.base.Engine ('F52',)
2021-02-01 11:01:16,251 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:16,256 INFO sqlalchemy.engine.base.Engine ((1275, 'F52', 0, 'Anhydrite', 2550, 2551), (1276, 'F52', 1, 'Sandstone, grey, vf-f', 2552, 2553), (1277, 'F52', 2, 'Anhydrite', 2554, 2555), (1278, 'F52', 3, 'Dolomite', 2556, 2557), (1279, 'F52', 4, 'Anhydrite', 2558, 2559), (1280, 'F52', 5, 'Sandstone, grey, vf-f', 2560, 2561), (1281, 'F52', 6, 'Siltstone, red', 2562, 2563), (1282, 'F52', 7, 'Dolomite', 2564, 2565)  ... displaying 10 of 25 total bound parameter sets ...  (1298, 'F52', 23, 'Limestone', 2596, 2597), (1299, 'F52', 24, 'Volcanic', 2598, 2599))
2021-02-01 11:01:16,260 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:16,353 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:16,355 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:16,357 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:16,359 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:16,361 INFO sqlalchemy.engine.base.Engine ('F52',)
2021-02-01 11:01:16,363 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,365 INFO sqlalchemy.engine.base.Engine (2550,)
2021-02-01 11:01:16,367 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,368 INFO sqlalchemy.engine.base.Engine (2551,)
2021-02-01 11:01:16,371 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,372 INFO sqlalchemy.engine.base.Engine (2552,)
2021-02-01 11:01:16,374 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,376 INFO sqlalchemy.engine.base.Engine (2553,)
2021-02-01 11:01:16,379 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,380 INFO sqlalchemy.engine.base.Engine (2554,)
2021-02-01 11:01:16,382 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,384 INFO sqlalchemy.engine.base.Engine (2555,)
2021-02-01 11:01:16,389 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,391 INFO sqlalchemy.engine.base.Engine (2556,)
2021-02-01 11:01:16,394 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,395 INFO sqlalchemy.engine.base.Engine (2557,)
2021-02-01 11:01:16,398 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,399 INFO sqlalchemy.engine.base.Engine (2558,)
2021-02-01 11:01:16,402 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,403 INFO sqlalchemy.engine.base.Engine (2559,)
2021-02-01 11:01:16,405 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,406 INFO sqlalchemy.engine.base.Engine (2560,)
2021-02-01 11:01:16,409 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,410 INFO sqlalchemy.engine.base.Engine (2561,)
2021-02-01 11:01:16,412 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,413 INFO sqlalchemy.engine.base.Engine (2562,)

2021-02-01 11:01:16,416 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,417 INFO sqlalchemy.engine.base.Engine (2563,)
2021-02-01 11:01:16,419 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,420 INFO sqlalchemy.engine.base.Engine (2564,)
2021-02-01 11:01:16,426 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,428 INFO sqlalchemy.engine.base.Engine (2565,)
2021-02-01 11:01:16,430 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,431 INFO sqlalchemy.engine.base.Engine (2566,)
2021-02-01 11:01:16,435 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,436 INFO sqlalchemy.engine.base.Engine (2567,)
2021-02-01 11:01:16,439 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,440 INFO sqlalchemy.engine.base.Engine (2568,)
2021-02-01 11:01:16,442 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,444 INFO sqlalchemy.engine.base.Engine (2569,)
2021-02-01 11:01:16,447 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,448 INFO sqlalchemy.engine.base.Engine (2570,)
2021-02-01 11:01:16,450 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,452 INFO sqlalchemy.engine.base.Engine (2571,)
2021-02-01 11:01:16,454 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,458 INFO sqlalchemy.engine.base.Engine (2572,)
2021-02-01 11:01:16,461 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,462 INFO sqlalchemy.engine.base.Engine (2573,)
2021-02-01 11:01:16,465 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,466 INFO sqlalchemy.engine.base.Engine (2574,)
2021-02-01 11:01:16,469 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,470 INFO sqlalchemy.engine.base.Engine (2575,)
2021-02-01 11:01:16,472 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,473 INFO sqlalchemy.engine.base.Engine (2576,)
2021-02-01 11:01:16,476 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,477 INFO sqlalchemy.engine.base.Engine (2577,)
2021-02-01 11:01:16,481 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,484 INFO sqlalchemy.engine.base.Engine (2578,)
2021-02-01 11:01:16,486 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,487 INFO sqlalchemy.engine.base.Engine (2579,)
2021-02-01 11:01:16,490 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,491 INFO sqlalchemy.engine.base.Engine (2580,)
2021-02-01 11:01:16,493 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,495 INFO sqlalchemy.engine.base.Engine (2581,)
2021-02-01 11:01:16,496 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,498 INFO sqlalchemy.engine.base.Engine (2582,)
2021-02-01 11:01:16,500 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:16,501 INFO sqlalchemy.engine.base.Engine (2583,)
2021-02-01 11:01:16,505 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,506 INFO sqlalchemy.engine.base.Engine (2584,)
2021-02-01 11:01:16,508 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,509 INFO sqlalchemy.engine.base.Engine (2585,)
2021-02-01 11:01:16,511 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,514 INFO sqlalchemy.engine.base.Engine (2586,)
2021-02-01 11:01:16,517 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,517 INFO sqlalchemy.engine.base.Engine (2587,)
2021-02-01 11:01:16,519 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,521 INFO sqlalchemy.engine.base.Engine (2588,)
2021-02-01 11:01:16,525 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,527 INFO sqlalchemy.engine.base.Engine (2589,)
2021-02-01 11:01:16,530 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,531 INFO sqlalchemy.engine.base.Engine (2590,)
2021-02-01 11:01:16,533 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,534 INFO sqlalchemy.engine.base.Engine (2591,)
2021-02-01 11:01:16,536 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,537 INFO sqlalchemy.engine.base.Engine (2592,)
2021-02-01 11:01:16,540 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,541 INFO sqlalchemy.engine.base.Engine (2593,)
2021-02-01 11:01:16,544 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,546 INFO sqlalchemy.engine.base.Engine (2594,)
2021-02-01 11:01:16,548 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,550 INFO sqlalchemy.engine.base.Engine (2595,)
2021-02-01 11:01:16,555 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,561 INFO sqlalchemy.engine.base.Engine (2596,)
2021-02-01 11:01:16,564 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,565 INFO sqlalchemy.engine.base.Engine (2597,)
2021-02-01 11:01:16,569 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,570 INFO sqlalchemy.engine.base.Engine (2598,)
2021-02-01 11:01:16,573 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,574 INFO sqlalchemy.engine.base.Engine (2599,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:16,737 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:16,739 INFO sqlalchemy.engine.base.Engine ((2600, 14.3, 14.3, 14.3, 152879.13500002536, 122580.17613904734), (2601, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152879.13500002536, 122580.17613904734), (2602, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152879.13500002536, 122580.17613904734), (2603, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152879.13500002536, 122580.17613904734), (2604, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152879.13500002536, 122580.17613904734), (2605, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152879.13500002536, 122580.17613904734), (2606, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152879.13500002536, 122580.17613904734), (2607, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152879.13500002536, 122580.17613904734)  ... displaying 10 of 50 total bound parameter sets ...  (2648, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152879.13500002536, 122580.17613904734), (2649, 135.9, 135.9, 135.9, 152879.13500002536, 122580.17613904734))
2021-02-01 11:01:16,741 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:16,743 INFO sqlalchemy.engine.base.Engine ('F53',)
2021-02-01 11:01:16,747 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:16,749 INFO sqlalchemy.engine.base.Engine ((1300, 'F53', 0, 'Anhydrite', 2600, 2601), (1301, 'F53', 1, 'Sandstone, grey, vf-f', 2602, 2603), (1302, 'F53', 2, 'Anhydrite', 2604, 2605), (1303, 'F53', 3, 'Dolomite', 2606, 2607), (1304, 'F53', 4, 'Anhydrite', 2608, 2609), (1305, 'F53', 5, 'Sandstone, grey, vf-f', 2610, 2611), (1306, 'F53', 6, 'Siltstone, red', 2612, 2613), (1307, 'F53', 7, 'Dolomite', 2614, 2615)  ... displaying 10 of 25 total bound parameter sets ...  (1323, 'F53', 23, 'Limestone', 2646, 2647), (1324, 'F53', 24, 'Volcanic', 2648, 2649))

2021-02-01 11:01:16,754 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:16,866 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:16,868 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:16,879 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:16,886 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:16,896 INFO sqlalchemy.engine.base.Engine ('F53',)
2021-02-01 11:01:16,898 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,899 INFO sqlalchemy.engine.base.Engine (2600,)
2021-02-01 11:01:16,902 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,903 INFO sqlalchemy.engine.base.Engine (2601,)
2021-02-01 11:01:16,905 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,908 INFO sqlalchemy.engine.base.Engine (2602,)
2021-02-01 11:01:16,911 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,911 INFO sqlalchemy.engine.base.Engine (2603,)
2021-02-01 11:01:16,914 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,916 INFO sqlalchemy.engine.base.Engine (2604,)
2021-02-01 11:01:16,919 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,921 INFO sqlalchemy.engine.base.Engine (2605,)
2021-02-01 11:01:16,924 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,925 INFO sqlalchemy.engine.base.Engine (2606,)
2021-02-01 11:01:16,927 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,928 INFO sqlalchemy.engine.base.Engine (2607,)
2021-02-01 11:01:16,930 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,931 INFO sqlalchemy.engine.base.Engine (2608,)
2021-02-01 11:01:16,935 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,937 INFO sqlalchemy.engine.base.Engine (2609,)
2021-02-01 11:01:16,939 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,941 INFO sqlalchemy.engine.base.Engine (2610,)
2021-02-01 11:01:16,944 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,946 INFO sqlalchemy.engine.base.Engine (2611,)
2021-02-01 11:01:16,951 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,952 INFO sqlalchemy.engine.base.Engine (2612,)
2021-02-01 11:01:16,955 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,956 INFO sqlalchemy.engine.base.Engine (2613,)
2021-02-01 11:01:16,959 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,960 INFO sqlalchemy.engine.base.Engine (2614,)
2021-02-01 11:01:16,963 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,963 INFO sqlalchemy.engine.base.Engine (2615,)
2021-02-01 11:01:16,966 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,967 INFO sqlalchemy.engine.base.Engine (2616,)
2021-02-01 11:01:16,969 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,970 INFO sqlalchemy.engine.base.Engine (2617,)
2021-02-01 11:01:16,973 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:16,973 INFO sqlalchemy.engine.base.Engine (2618,)
2021-02-01 11:01:16,976 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,977 INFO sqlalchemy.engine.base.Engine (2619,)
2021-02-01 11:01:16,984 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,986 INFO sqlalchemy.engine.base.Engine (2620,)
2021-02-01 11:01:16,988 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,989 INFO sqlalchemy.engine.base.Engine (2621,)
2021-02-01 11:01:16,992 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,993 INFO sqlalchemy.engine.base.Engine (2622,)
2021-02-01 11:01:16,995 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:16,998 INFO sqlalchemy.engine.base.Engine (2623,)
2021-02-01 11:01:17,001 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,001 INFO sqlalchemy.engine.base.Engine (2624,)
2021-02-01 11:01:17,004 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,005 INFO sqlalchemy.engine.base.Engine (2625,)
2021-02-01 11:01:17,008 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,009 INFO sqlalchemy.engine.base.Engine (2626,)
2021-02-01 11:01:17,011 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,012 INFO sqlalchemy.engine.base.Engine (2627,)
2021-02-01 11:01:17,014 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,016 INFO sqlalchemy.engine.base.Engine (2628,)
2021-02-01 11:01:17,019 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,021 INFO sqlalchemy.engine.base.Engine (2629,)
2021-02-01 11:01:17,025 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,025 INFO sqlalchemy.engine.base.Engine (2630,)
2021-02-01 11:01:17,028 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,029 INFO sqlalchemy.engine.base.Engine (2631,)
2021-02-01 11:01:17,034 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,036 INFO sqlalchemy.engine.base.Engine (2632,)
2021-02-01 11:01:17,038 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,039 INFO sqlalchemy.engine.base.Engine (2633,)
2021-02-01 11:01:17,042 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,043 INFO sqlalchemy.engine.base.Engine (2634,)
2021-02-01 11:01:17,050 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,051 INFO sqlalchemy.engine.base.Engine (2635,)
2021-02-01 11:01:17,054 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,055 INFO sqlalchemy.engine.base.Engine (2636,)
2021-02-01 11:01:17,057 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,058 INFO sqlalchemy.engine.base.Engine (2637,)
2021-02-01 11:01:17,061 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,062 INFO sqlalchemy.engine.base.Engine (2638,)
2021-02-01 11:01:17,064 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:17,067 INFO sqlalchemy.engine.base.Engine (2639,)
2021-02-01 11:01:17,069 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,070 INFO sqlalchemy.engine.base.Engine (2640,)
2021-02-01 11:01:17,072 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,073 INFO sqlalchemy.engine.base.Engine (2641,)
2021-02-01 11:01:17,076 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,077 INFO sqlalchemy.engine.base.Engine (2642,)
2021-02-01 11:01:17,079 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,081 INFO sqlalchemy.engine.base.Engine (2643,)
2021-02-01 11:01:17,083 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,084 INFO sqlalchemy.engine.base.Engine (2644,)
2021-02-01 11:01:17,087 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,088 INFO sqlalchemy.engine.base.Engine (2645,)
2021-02-01 11:01:17,091 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,092 INFO sqlalchemy.engine.base.Engine (2646,)
2021-02-01 11:01:17,094 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,095 INFO sqlalchemy.engine.base.Engine (2647,)
2021-02-01 11:01:17,098 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,100 INFO sqlalchemy.engine.base.Engine (2648,)
2021-02-01 11:01:17,103 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,104 INFO sqlalchemy.engine.base.Engine (2649,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:17,276 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:17,281 INFO sqlalchemy.engine.base.Engine ((2650, 14.3, 14.3, 14.3, 152882.02200002535, 122579.22513904703), (2651, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152882.02200002535, 122579.22513904703), (2652, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152882.02200002535, 122579.22513904703), (2653, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152882.02200002535, 122579.22513904703), (2654, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152882.02200002535, 122579.22513904703), (2655, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152882.02200002535, 122579.22513904703), (2656, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152882.02200002535, 122579.22513904703), (2657, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152882.02200002535, 122579.22513904703)  ... displaying 10 of 50 total bound parameter sets ...  (2698, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152882.02200002535, 122579.22513904703), (2699, 135.9, 135.9, 135.9, 152882.02200002535, 122579.22513904703))
2021-02-01 11:01:17,291 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:17,296 INFO sqlalchemy.engine.base.Engine ('F54',)
2021-02-01 11:01:17,300 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:17,302 INFO sqlalchemy.engine.base.Engine ((1325, 'F54', 0, 'Anhydrite', 2650, 2651), (1326, 'F54', 1, 'Sandstone, grey, vf-f', 2652, 2653), (1327, 'F54', 2, 'Anhydrite', 2654, 2655), (1328, 'F54', 3, 'Dolomite', 2656, 2657), (1329, 'F54', 4, 'Anhydrite', 2658, 2659), (1330, 'F54', 5, 'Sandstone, grey, vf-f', 2660, 2661), (1331, 'F54', 6, 'Siltstone, red', 2662, 2663), (1332, 'F54', 7, 'Dolomite', 2664, 2665)  ... displaying 10 of 25 total bound parameter sets ...  (1348, 'F54', 23, 'Limestone', 2696, 2697), (1349, 'F54', 24, 'Volcanic', 2698, 2699))
2021-02-01 11:01:17,306 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:17,429 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:17,430 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:17,437 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:17,440 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:17,441 INFO sqlalchemy.engine.base.Engine ('F54',)
2021-02-01 11:01:17,446 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,447 INFO sqlalchemy.engine.base.Engine (2650,)
2021-02-01 11:01:17,450 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,451 INFO sqlalchemy.engine.base.Engine (2651,)
2021-02-01 11:01:17,453 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,454 INFO sqlalchemy.engine.base.Engine (2652,)

2021-02-01 11:01:17,457 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,459 INFO sqlalchemy.engine.base.Engine (2653,)
2021-02-01 11:01:17,462 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,463 INFO sqlalchemy.engine.base.Engine (2654,)
2021-02-01 11:01:17,465 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,467 INFO sqlalchemy.engine.base.Engine (2655,)
2021-02-01 11:01:17,469 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,473 INFO sqlalchemy.engine.base.Engine (2656,)
2021-02-01 11:01:17,475 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,476 INFO sqlalchemy.engine.base.Engine (2657,)
2021-02-01 11:01:17,478 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,480 INFO sqlalchemy.engine.base.Engine (2658,)
2021-02-01 11:01:17,483 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,484 INFO sqlalchemy.engine.base.Engine (2659,)
2021-02-01 11:01:17,486 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,487 INFO sqlalchemy.engine.base.Engine (2660,)
2021-02-01 11:01:17,490 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,491 INFO sqlalchemy.engine.base.Engine (2661,)
2021-02-01 11:01:17,494 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,497 INFO sqlalchemy.engine.base.Engine (2662,)
2021-02-01 11:01:17,500 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,503 INFO sqlalchemy.engine.base.Engine (2663,)
2021-02-01 11:01:17,505 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,507 INFO sqlalchemy.engine.base.Engine (2664,)
2021-02-01 11:01:17,509 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,511 INFO sqlalchemy.engine.base.Engine (2665,)
2021-02-01 11:01:17,517 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,519 INFO sqlalchemy.engine.base.Engine (2666,)
2021-02-01 11:01:17,520 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,522 INFO sqlalchemy.engine.base.Engine (2667,)
2021-02-01 11:01:17,524 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,525 INFO sqlalchemy.engine.base.Engine (2668,)
2021-02-01 11:01:17,527 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,529 INFO sqlalchemy.engine.base.Engine (2669,)
2021-02-01 11:01:17,531 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,532 INFO sqlalchemy.engine.base.Engine (2670,)
2021-02-01 11:01:17,534 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,538 INFO sqlalchemy.engine.base.Engine (2671,)
2021-02-01 11:01:17,540 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,542 INFO sqlalchemy.engine.base.Engine (2672,)
2021-02-01 11:01:17,544 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:17,545 INFO sqlalchemy.engine.base.Engine (2673,)
2021-02-01 11:01:17,548 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,549 INFO sqlalchemy.engine.base.Engine (2674,)
2021-02-01 11:01:17,551 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,552 INFO sqlalchemy.engine.base.Engine (2675,)
2021-02-01 11:01:17,553 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,557 INFO sqlalchemy.engine.base.Engine (2676,)
2021-02-01 11:01:17,559 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,560 INFO sqlalchemy.engine.base.Engine (2677,)
2021-02-01 11:01:17,562 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,563 INFO sqlalchemy.engine.base.Engine (2678,)
2021-02-01 11:01:17,564 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,565 INFO sqlalchemy.engine.base.Engine (2679,)
2021-02-01 11:01:17,567 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,570 INFO sqlalchemy.engine.base.Engine (2680,)
2021-02-01 11:01:17,573 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,574 INFO sqlalchemy.engine.base.Engine (2681,)
2021-02-01 11:01:17,576 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,577 INFO sqlalchemy.engine.base.Engine (2682,)
2021-02-01 11:01:17,580 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,581 INFO sqlalchemy.engine.base.Engine (2683,)
2021-02-01 11:01:17,583 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,588 INFO sqlalchemy.engine.base.Engine (2684,)
2021-02-01 11:01:17,590 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,591 INFO sqlalchemy.engine.base.Engine (2685,)
2021-02-01 11:01:17,593 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,594 INFO sqlalchemy.engine.base.Engine (2686,)
2021-02-01 11:01:17,596 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,599 INFO sqlalchemy.engine.base.Engine (2687,)
2021-02-01 11:01:17,603 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,604 INFO sqlalchemy.engine.base.Engine (2688,)
2021-02-01 11:01:17,606 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,607 INFO sqlalchemy.engine.base.Engine (2689,)
2021-02-01 11:01:17,609 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,610 INFO sqlalchemy.engine.base.Engine (2690,)
2021-02-01 11:01:17,612 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,613 INFO sqlalchemy.engine.base.Engine (2691,)
2021-02-01 11:01:17,614 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,615 INFO sqlalchemy.engine.base.Engine (2692,)
2021-02-01 11:01:17,618 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,619 INFO sqlalchemy.engine.base.Engine (2693,)
2021-02-01 11:01:17,623 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:17,627 INFO sqlalchemy.engine.base.Engine (2694,)
2021-02-01 11:01:17,628 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,633 INFO sqlalchemy.engine.base.Engine (2695,)
2021-02-01 11:01:17,635 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,636 INFO sqlalchemy.engine.base.Engine (2696,)
2021-02-01 11:01:17,637 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,638 INFO sqlalchemy.engine.base.Engine (2697,)
2021-02-01 11:01:17,640 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,641 INFO sqlalchemy.engine.base.Engine (2698,)
2021-02-01 11:01:17,643 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,644 INFO sqlalchemy.engine.base.Engine (2699,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:17,789 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:17,792 INFO sqlalchemy.engine.base.Engine ('F55',)
2021-02-01 11:01:17,797 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:17,799 INFO sqlalchemy.engine.base.Engine ((2700, 14.3, 14.3, 14.3, 152895.35400002546, 122593.7011390468), (2701, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152895.35400002546, 122593.7011390468), (2702, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152895.35400002546, 122593.7011390468), (2703, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152895.35400002546, 122593.7011390468), (2704, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152895.35400002546, 122593.7011390468), (2705, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152895.35400002546, 122593.7011390468), (2706, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152895.35400002546, 122593.7011390468), (2707, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152895.35400002546, 122593.7011390468)  ... displaying 10 of 50 total bound parameter sets ...  (2748, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152895.35400002546, 122593.7011390468), (2749, 135.9, 135.9, 135.9, 152895.35400002546, 122593.7011390468))
2021-02-01 11:01:17,810 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:17,812 INFO sqlalchemy.engine.base.Engine ((1350, 'F55', 0, 'Anhydrite', 2700, 2701), (1351, 'F55', 1, 'Sandstone, grey, vf-f', 2702, 2703), (1352, 'F55', 2, 'Anhydrite', 2704, 2705), (1353, 'F55', 3, 'Dolomite', 2706, 2707), (1354, 'F55', 4, 'Anhydrite', 2708, 2709), (1355, 'F55', 5, 'Sandstone, grey, vf-f', 2710, 2711), (1356, 'F55', 6, 'Siltstone, red', 2712, 2713), (1357, 'F55', 7, 'Dolomite', 2714, 2715)  ... displaying 10 of 25 total bound parameter sets ...  (1373, 'F55', 23, 'Limestone', 2746, 2747), (1374, 'F55', 24, 'Volcanic', 2748, 2749))
2021-02-01 11:01:17,815 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:17,921 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:17,923 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:17,924 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:17,927 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:17,929 INFO sqlalchemy.engine.base.Engine ('F55',)
2021-02-01 11:01:17,931 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,933 INFO sqlalchemy.engine.base.Engine (2700,)
2021-02-01 11:01:17,935 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,936 INFO sqlalchemy.engine.base.Engine (2701,)
2021-02-01 11:01:17,938 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,941 INFO sqlalchemy.engine.base.Engine (2702,)
2021-02-01 11:01:17,942 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,944 INFO sqlalchemy.engine.base.Engine (2703,)
2021-02-01 11:01:17,946 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,947 INFO sqlalchemy.engine.base.Engine (2704,)
2021-02-01 11:01:17,949 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,950 INFO sqlalchemy.engine.base.Engine (2705,)
2021-02-01 11:01:17,952 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,957 INFO sqlalchemy.engine.base.Engine (2706,)
2021-02-01 11:01:17,961 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,965 INFO sqlalchemy.engine.base.Engine (2707,)

2021-02-01 11:01:17,970 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,971 INFO sqlalchemy.engine.base.Engine (2708,)
2021-02-01 11:01:17,973 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,974 INFO sqlalchemy.engine.base.Engine (2709,)
2021-02-01 11:01:17,977 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,979 INFO sqlalchemy.engine.base.Engine (2710,)
2021-02-01 11:01:17,981 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,982 INFO sqlalchemy.engine.base.Engine (2711,)
2021-02-01 11:01:17,987 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,989 INFO sqlalchemy.engine.base.Engine (2712,)
2021-02-01 11:01:17,996 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:17,998 INFO sqlalchemy.engine.base.Engine (2713,)
2021-02-01 11:01:18,000 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,001 INFO sqlalchemy.engine.base.Engine (2714,)
2021-02-01 11:01:18,004 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,005 INFO sqlalchemy.engine.base.Engine (2715,)
2021-02-01 11:01:18,010 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,012 INFO sqlalchemy.engine.base.Engine (2716,)
2021-02-01 11:01:18,015 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,016 INFO sqlalchemy.engine.base.Engine (2717,)
2021-02-01 11:01:18,022 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,024 INFO sqlalchemy.engine.base.Engine (2718,)
2021-02-01 11:01:18,026 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,027 INFO sqlalchemy.engine.base.Engine (2719,)
2021-02-01 11:01:18,028 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,033 INFO sqlalchemy.engine.base.Engine (2720,)
2021-02-01 11:01:18,035 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,036 INFO sqlalchemy.engine.base.Engine (2721,)
2021-02-01 11:01:18,040 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,041 INFO sqlalchemy.engine.base.Engine (2722,)
2021-02-01 11:01:18,044 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,046 INFO sqlalchemy.engine.base.Engine (2723,)
2021-02-01 11:01:18,055 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,056 INFO sqlalchemy.engine.base.Engine (2724,)
2021-02-01 11:01:18,062 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,065 INFO sqlalchemy.engine.base.Engine (2725,)
2021-02-01 11:01:18,070 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,071 INFO sqlalchemy.engine.base.Engine (2726,)
2021-02-01 11:01:18,075 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,077 INFO sqlalchemy.engine.base.Engine (2727,)
2021-02-01 11:01:18,081 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:18,083 INFO sqlalchemy.engine.base.Engine (2728,)
2021-02-01 11:01:18,085 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,087 INFO sqlalchemy.engine.base.Engine (2729,)
2021-02-01 11:01:18,090 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,092 INFO sqlalchemy.engine.base.Engine (2730,)
2021-02-01 11:01:18,094 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,095 INFO sqlalchemy.engine.base.Engine (2731,)
2021-02-01 11:01:18,098 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,100 INFO sqlalchemy.engine.base.Engine (2732,)
2021-02-01 11:01:18,102 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,104 INFO sqlalchemy.engine.base.Engine (2733,)
2021-02-01 11:01:18,106 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,110 INFO sqlalchemy.engine.base.Engine (2734,)
2021-02-01 11:01:18,113 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,115 INFO sqlalchemy.engine.base.Engine (2735,)
2021-02-01 11:01:18,118 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,119 INFO sqlalchemy.engine.base.Engine (2736,)
2021-02-01 11:01:18,120 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,121 INFO sqlalchemy.engine.base.Engine (2737,)
2021-02-01 11:01:18,125 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,127 INFO sqlalchemy.engine.base.Engine (2738,)
2021-02-01 11:01:18,129 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,130 INFO sqlalchemy.engine.base.Engine (2739,)
2021-02-01 11:01:18,138 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,140 INFO sqlalchemy.engine.base.Engine (2740,)
2021-02-01 11:01:18,143 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,144 INFO sqlalchemy.engine.base.Engine (2741,)
2021-02-01 11:01:18,147 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,148 INFO sqlalchemy.engine.base.Engine (2742,)
2021-02-01 11:01:18,152 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,154 INFO sqlalchemy.engine.base.Engine (2743,)
2021-02-01 11:01:18,156 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,158 INFO sqlalchemy.engine.base.Engine (2744,)
2021-02-01 11:01:18,163 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,167 INFO sqlalchemy.engine.base.Engine (2745,)
2021-02-01 11:01:18,169 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,170 INFO sqlalchemy.engine.base.Engine (2746,)
2021-02-01 11:01:18,173 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,175 INFO sqlalchemy.engine.base.Engine (2747,)
2021-02-01 11:01:18,177 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,178 INFO sqlalchemy.engine.base.Engine (2748,)
2021-02-01 11:01:18,181 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:18,182 INFO sqlalchemy.engine.base.Engine (2749,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:18,335 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:18,336 INFO sqlalchemy.engine.base.Engine ((2750, 14.3, 14.3, 14.3, 152882.76500002542, 122591.41413904633), (2751, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152882.76500002542, 122591.41413904633), (2752, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152882.76500002542, 122591.41413904633), (2753, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152882.76500002542, 122591.41413904633), (2754, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152882.76500002542, 122591.41413904633), (2755, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152882.76500002542, 122591.41413904633), (2756, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152882.76500002542, 122591.41413904633), (2757, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152882.76500002542, 122591.41413904633)  ... displaying 10 of 50 total bound parameter sets ...  (2798, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152882.76500002542, 122591.41413904633), (2799, 135.9, 135.9, 135.9, 152882.76500002542, 122591.41413904633))
2021-02-01 11:01:18,340 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:18,341 INFO sqlalchemy.engine.base.Engine ('F56',)
2021-02-01 11:01:18,348 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:18,351 INFO sqlalchemy.engine.base.Engine ((1375, 'F56', 0, 'Anhydrite', 2750, 2751), (1376, 'F56', 1, 'Sandstone, grey, vf-f', 2752, 2753), (1377, 'F56', 2, 'Anhydrite', 2754, 2755), (1378, 'F56', 3, 'Dolomite', 2756, 2757), (1379, 'F56', 4, 'Anhydrite', 2758, 2759), (1380, 'F56', 5, 'Sandstone, grey, vf-f', 2760, 2761), (1381, 'F56', 6, 'Siltstone, red', 2762, 2763), (1382, 'F56', 7, 'Dolomite', 2764, 2765)  ... displaying 10 of 25 total bound parameter sets ...  (1398, 'F56', 23, 'Limestone', 2796, 2797), (1399, 'F56', 24, 'Volcanic', 2798, 2799))
2021-02-01 11:01:18,356 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:18,426 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:18,435 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:18,438 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:18,442 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:18,443 INFO sqlalchemy.engine.base.Engine ('F56',)
2021-02-01 11:01:18,446 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,447 INFO sqlalchemy.engine.base.Engine (2750,)
2021-02-01 11:01:18,449 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,451 INFO sqlalchemy.engine.base.Engine (2751,)
2021-02-01 11:01:18,454 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,456 INFO sqlalchemy.engine.base.Engine (2752,)
2021-02-01 11:01:18,458 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,460 INFO sqlalchemy.engine.base.Engine (2753,)
2021-02-01 11:01:18,462 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,464 INFO sqlalchemy.engine.base.Engine (2754,)
2021-02-01 11:01:18,467 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,469 INFO sqlalchemy.engine.base.Engine (2755,)
2021-02-01 11:01:18,471 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,473 INFO sqlalchemy.engine.base.Engine (2756,)
2021-02-01 11:01:18,475 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,478 INFO sqlalchemy.engine.base.Engine (2757,)
2021-02-01 11:01:18,485 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,486 INFO sqlalchemy.engine.base.Engine (2758,)
2021-02-01 11:01:18,487 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,488 INFO sqlalchemy.engine.base.Engine (2759,)
2021-02-01 11:01:18,490 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,491 INFO sqlalchemy.engine.base.Engine (2760,)
2021-02-01 11:01:18,493 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,493 INFO sqlalchemy.engine.base.Engine (2761,)
2021-02-01 11:01:18,495 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,496 INFO sqlalchemy.engine.base.Engine (2762,)

2021-02-01 11:01:18,500 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,501 INFO sqlalchemy.engine.base.Engine (2763,)
2021-02-01 11:01:18,505 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,516 INFO sqlalchemy.engine.base.Engine (2764,)
2021-02-01 11:01:18,517 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,518 INFO sqlalchemy.engine.base.Engine (2765,)
2021-02-01 11:01:18,520 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,529 INFO sqlalchemy.engine.base.Engine (2766,)
2021-02-01 11:01:18,530 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,531 INFO sqlalchemy.engine.base.Engine (2767,)
2021-02-01 11:01:18,534 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,536 INFO sqlalchemy.engine.base.Engine (2768,)
2021-02-01 11:01:18,538 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,539 INFO sqlalchemy.engine.base.Engine (2769,)
2021-02-01 11:01:18,540 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,541 INFO sqlalchemy.engine.base.Engine (2770,)
2021-02-01 11:01:18,542 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,546 INFO sqlalchemy.engine.base.Engine (2771,)
2021-02-01 11:01:18,552 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,555 INFO sqlalchemy.engine.base.Engine (2772,)
2021-02-01 11:01:18,556 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,558 INFO sqlalchemy.engine.base.Engine (2773,)
2021-02-01 11:01:18,560 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,563 INFO sqlalchemy.engine.base.Engine (2774,)
2021-02-01 11:01:18,566 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,567 INFO sqlalchemy.engine.base.Engine (2775,)
2021-02-01 11:01:18,572 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,574 INFO sqlalchemy.engine.base.Engine (2776,)
2021-02-01 11:01:18,577 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,578 INFO sqlalchemy.engine.base.Engine (2777,)
2021-02-01 11:01:18,579 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,581 INFO sqlalchemy.engine.base.Engine (2778,)
2021-02-01 11:01:18,583 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,584 INFO sqlalchemy.engine.base.Engine (2779,)
2021-02-01 11:01:18,586 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,586 INFO sqlalchemy.engine.base.Engine (2780,)
2021-02-01 11:01:18,588 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,589 INFO sqlalchemy.engine.base.Engine (2781,)
2021-02-01 11:01:18,591 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,592 INFO sqlalchemy.engine.base.Engine (2782,)
2021-02-01 11:01:18,594 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:18,595 INFO sqlalchemy.engine.base.Engine (2783,)
2021-02-01 11:01:18,596 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,597 INFO sqlalchemy.engine.base.Engine (2784,)
2021-02-01 11:01:18,600 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,601 INFO sqlalchemy.engine.base.Engine (2785,)
2021-02-01 11:01:18,603 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,604 INFO sqlalchemy.engine.base.Engine (2786,)
2021-02-01 11:01:18,606 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,606 INFO sqlalchemy.engine.base.Engine (2787,)
2021-02-01 11:01:18,609 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,610 INFO sqlalchemy.engine.base.Engine (2788,)
2021-02-01 11:01:18,612 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,613 INFO sqlalchemy.engine.base.Engine (2789,)
2021-02-01 11:01:18,615 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,615 INFO sqlalchemy.engine.base.Engine (2790,)
2021-02-01 11:01:18,617 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,618 INFO sqlalchemy.engine.base.Engine (2791,)
2021-02-01 11:01:18,621 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,622 INFO sqlalchemy.engine.base.Engine (2792,)
2021-02-01 11:01:18,624 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,625 INFO sqlalchemy.engine.base.Engine (2793,)
2021-02-01 11:01:18,627 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,628 INFO sqlalchemy.engine.base.Engine (2794,)
2021-02-01 11:01:18,630 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,631 INFO sqlalchemy.engine.base.Engine (2795,)
2021-02-01 11:01:18,633 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,634 INFO sqlalchemy.engine.base.Engine (2796,)
2021-02-01 11:01:18,636 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,637 INFO sqlalchemy.engine.base.Engine (2797,)
2021-02-01 11:01:18,640 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,641 INFO sqlalchemy.engine.base.Engine (2798,)
2021-02-01 11:01:18,643 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,645 INFO sqlalchemy.engine.base.Engine (2799,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:18,800 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:18,803 INFO sqlalchemy.engine.base.Engine ((2800, 14.3, 14.3, 14.3, 152888.10200002545, 122583.96013904642), (2801, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.10200002545, 122583.96013904642), (2802, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.10200002545, 122583.96013904642), (2803, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.10200002545, 122583.96013904642), (2804, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.10200002545, 122583.96013904642), (2805, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.10200002545, 122583.96013904642), (2806, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.10200002545, 122583.96013904642), (2807, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152888.10200002545, 122583.96013904642)  ... displaying 10 of 50 total bound parameter sets ...  (2848, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152888.10200002545, 122583.96013904642), (2849, 135.9, 135.9, 135.9, 152888.10200002545, 122583.96013904642))
2021-02-01 11:01:18,805 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:18,806 INFO sqlalchemy.engine.base.Engine ('F57',)
2021-02-01 11:01:18,810 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:18,811 INFO sqlalchemy.engine.base.Engine ((1400, 'F57', 0, 'Anhydrite', 2800, 2801), (1401, 'F57', 1, 'Sandstone, grey, vf-f', 2802, 2803), (1402, 'F57', 2, 'Anhydrite', 2804, 2805), (1403, 'F57', 3, 'Dolomite', 2806, 2807), (1404, 'F57', 4, 'Anhydrite', 2808, 2809), (1405, 'F57', 5, 'Sandstone, grey, vf-f', 2810, 2811), (1406, 'F57', 6, 'Siltstone, red', 2812, 2813), (1407, 'F57', 7, 'Dolomite', 2814, 2815)  ... displaying 10 of 25 total bound parameter sets ...  (1423, 'F57', 23, 'Limestone', 2846, 2847), (1424, 'F57', 24, 'Volcanic', 2848, 2849))

2021-02-01 11:01:18,817 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:18,930 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:18,932 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:18,939 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:18,942 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:18,944 INFO sqlalchemy.engine.base.Engine ('F57',)
2021-02-01 11:01:18,947 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,948 INFO sqlalchemy.engine.base.Engine (2800,)
2021-02-01 11:01:18,950 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,952 INFO sqlalchemy.engine.base.Engine (2801,)
2021-02-01 11:01:18,954 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,959 INFO sqlalchemy.engine.base.Engine (2802,)
2021-02-01 11:01:18,960 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,961 INFO sqlalchemy.engine.base.Engine (2803,)
2021-02-01 11:01:18,964 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,966 INFO sqlalchemy.engine.base.Engine (2804,)
2021-02-01 11:01:18,969 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,970 INFO sqlalchemy.engine.base.Engine (2805,)
2021-02-01 11:01:18,973 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,974 INFO sqlalchemy.engine.base.Engine (2806,)
2021-02-01 11:01:18,977 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,978 INFO sqlalchemy.engine.base.Engine (2807,)
2021-02-01 11:01:18,982 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,984 INFO sqlalchemy.engine.base.Engine (2808,)
2021-02-01 11:01:18,986 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,988 INFO sqlalchemy.engine.base.Engine (2809,)
2021-02-01 11:01:18,990 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,992 INFO sqlalchemy.engine.base.Engine (2810,)
2021-02-01 11:01:18,997 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:18,999 INFO sqlalchemy.engine.base.Engine (2811,)
2021-02-01 11:01:19,002 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,003 INFO sqlalchemy.engine.base.Engine (2812,)
2021-02-01 11:01:19,005 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,007 INFO sqlalchemy.engine.base.Engine (2813,)
2021-02-01 11:01:19,009 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,010 INFO sqlalchemy.engine.base.Engine (2814,)
2021-02-01 11:01:19,013 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,014 INFO sqlalchemy.engine.base.Engine (2815,)
2021-02-01 11:01:19,019 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,021 INFO sqlalchemy.engine.base.Engine (2816,)
2021-02-01 11:01:19,023 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,025 INFO sqlalchemy.engine.base.Engine (2817,)
2021-02-01 11:01:19,027 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:19,028 INFO sqlalchemy.engine.base.Engine (2818,)
2021-02-01 11:01:19,030 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,031 INFO sqlalchemy.engine.base.Engine (2819,)
2021-02-01 11:01:19,033 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,037 INFO sqlalchemy.engine.base.Engine (2820,)
2021-02-01 11:01:19,039 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,040 INFO sqlalchemy.engine.base.Engine (2821,)
2021-02-01 11:01:19,042 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,046 INFO sqlalchemy.engine.base.Engine (2822,)
2021-02-01 11:01:19,048 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,049 INFO sqlalchemy.engine.base.Engine (2823,)
2021-02-01 11:01:19,054 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,055 INFO sqlalchemy.engine.base.Engine (2824,)
2021-02-01 11:01:19,058 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,059 INFO sqlalchemy.engine.base.Engine (2825,)
2021-02-01 11:01:19,061 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,062 INFO sqlalchemy.engine.base.Engine (2826,)
2021-02-01 11:01:19,065 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,066 INFO sqlalchemy.engine.base.Engine (2827,)
2021-02-01 11:01:19,068 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,070 INFO sqlalchemy.engine.base.Engine (2828,)
2021-02-01 11:01:19,072 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,073 INFO sqlalchemy.engine.base.Engine (2829,)
2021-02-01 11:01:19,079 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,080 INFO sqlalchemy.engine.base.Engine (2830,)
2021-02-01 11:01:19,082 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,083 INFO sqlalchemy.engine.base.Engine (2831,)
2021-02-01 11:01:19,085 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,086 INFO sqlalchemy.engine.base.Engine (2832,)
2021-02-01 11:01:19,089 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,091 INFO sqlalchemy.engine.base.Engine (2833,)
2021-02-01 11:01:19,095 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,097 INFO sqlalchemy.engine.base.Engine (2834,)
2021-02-01 11:01:19,100 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,101 INFO sqlalchemy.engine.base.Engine (2835,)
2021-02-01 11:01:19,106 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,108 INFO sqlalchemy.engine.base.Engine (2836,)
2021-02-01 11:01:19,110 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,111 INFO sqlalchemy.engine.base.Engine (2837,)
2021-02-01 11:01:19,114 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,116 INFO sqlalchemy.engine.base.Engine (2838,)
2021-02-01 11:01:19,118 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:19,119 INFO sqlalchemy.engine.base.Engine (2839,)
2021-02-01 11:01:19,125 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,126 INFO sqlalchemy.engine.base.Engine (2840,)
2021-02-01 11:01:19,128 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,131 INFO sqlalchemy.engine.base.Engine (2841,)
2021-02-01 11:01:19,133 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,134 INFO sqlalchemy.engine.base.Engine (2842,)
2021-02-01 11:01:19,136 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,138 INFO sqlalchemy.engine.base.Engine (2843,)
2021-02-01 11:01:19,141 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,143 INFO sqlalchemy.engine.base.Engine (2844,)
2021-02-01 11:01:19,146 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,147 INFO sqlalchemy.engine.base.Engine (2845,)
2021-02-01 11:01:19,152 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,153 INFO sqlalchemy.engine.base.Engine (2846,)
2021-02-01 11:01:19,155 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,156 INFO sqlalchemy.engine.base.Engine (2847,)
2021-02-01 11:01:19,158 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,159 INFO sqlalchemy.engine.base.Engine (2848,)
2021-02-01 11:01:19,161 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,164 INFO sqlalchemy.engine.base.Engine (2849,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:19,299 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:19,303 INFO sqlalchemy.engine.base.Engine ((2850, 14.3, 14.3, 14.3, 152891.5540000255, 122584.95313904715), (2851, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152891.5540000255, 122584.95313904715), (2852, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152891.5540000255, 122584.95313904715), (2853, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152891.5540000255, 122584.95313904715), (2854, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152891.5540000255, 122584.95313904715), (2855, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152891.5540000255, 122584.95313904715), (2856, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152891.5540000255, 122584.95313904715), (2857, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152891.5540000255, 122584.95313904715)  ... displaying 10 of 50 total bound parameter sets ...  (2898, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152891.5540000255, 122584.95313904715), (2899, 135.9, 135.9, 135.9, 152891.5540000255, 122584.95313904715))
2021-02-01 11:01:19,306 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:19,307 INFO sqlalchemy.engine.base.Engine ('F58',)
2021-02-01 11:01:19,312 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:19,313 INFO sqlalchemy.engine.base.Engine ((1425, 'F58', 0, 'Anhydrite', 2850, 2851), (1426, 'F58', 1, 'Sandstone, grey, vf-f', 2852, 2853), (1427, 'F58', 2, 'Anhydrite', 2854, 2855), (1428, 'F58', 3, 'Dolomite', 2856, 2857), (1429, 'F58', 4, 'Anhydrite', 2858, 2859), (1430, 'F58', 5, 'Sandstone, grey, vf-f', 2860, 2861), (1431, 'F58', 6, 'Siltstone, red', 2862, 2863), (1432, 'F58', 7, 'Dolomite', 2864, 2865)  ... displaying 10 of 25 total bound parameter sets ...  (1448, 'F58', 23, 'Limestone', 2896, 2897), (1449, 'F58', 24, 'Volcanic', 2898, 2899))
2021-02-01 11:01:19,318 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:19,439 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:19,441 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:19,443 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:19,447 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:19,448 INFO sqlalchemy.engine.base.Engine ('F58',)
2021-02-01 11:01:19,452 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,454 INFO sqlalchemy.engine.base.Engine (2850,)
2021-02-01 11:01:19,457 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,458 INFO sqlalchemy.engine.base.Engine (2851,)
2021-02-01 11:01:19,460 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,464 INFO sqlalchemy.engine.base.Engine (2852,)

2021-02-01 11:01:19,466 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,468 INFO sqlalchemy.engine.base.Engine (2853,)
2021-02-01 11:01:19,473 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,475 INFO sqlalchemy.engine.base.Engine (2854,)
2021-02-01 11:01:19,477 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,479 INFO sqlalchemy.engine.base.Engine (2855,)
2021-02-01 11:01:19,482 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,483 INFO sqlalchemy.engine.base.Engine (2856,)
2021-02-01 11:01:19,485 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,486 INFO sqlalchemy.engine.base.Engine (2857,)
2021-02-01 11:01:19,489 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,490 INFO sqlalchemy.engine.base.Engine (2858,)
2021-02-01 11:01:19,492 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,494 INFO sqlalchemy.engine.base.Engine (2859,)
2021-02-01 11:01:19,497 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,499 INFO sqlalchemy.engine.base.Engine (2860,)
2021-02-01 11:01:19,501 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,504 INFO sqlalchemy.engine.base.Engine (2861,)
2021-02-01 11:01:19,507 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,509 INFO sqlalchemy.engine.base.Engine (2862,)
2021-02-01 11:01:19,511 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,512 INFO sqlalchemy.engine.base.Engine (2863,)
2021-02-01 11:01:19,514 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,516 INFO sqlalchemy.engine.base.Engine (2864,)
2021-02-01 11:01:19,518 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,520 INFO sqlalchemy.engine.base.Engine (2865,)
2021-02-01 11:01:19,523 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,524 INFO sqlalchemy.engine.base.Engine (2866,)
2021-02-01 11:01:19,528 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,530 INFO sqlalchemy.engine.base.Engine (2867,)
2021-02-01 11:01:19,536 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,537 INFO sqlalchemy.engine.base.Engine (2868,)
2021-02-01 11:01:19,539 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,541 INFO sqlalchemy.engine.base.Engine (2869,)
2021-02-01 11:01:19,543 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,544 INFO sqlalchemy.engine.base.Engine (2870,)
2021-02-01 11:01:19,546 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,548 INFO sqlalchemy.engine.base.Engine (2871,)
2021-02-01 11:01:19,550 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,556 INFO sqlalchemy.engine.base.Engine (2872,)
2021-02-01 11:01:19,558 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:19,559 INFO sqlalchemy.engine.base.Engine (2873,)
2021-02-01 11:01:19,563 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,564 INFO sqlalchemy.engine.base.Engine (2874,)
2021-02-01 11:01:19,566 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,568 INFO sqlalchemy.engine.base.Engine (2875,)
2021-02-01 11:01:19,570 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,571 INFO sqlalchemy.engine.base.Engine (2876,)
2021-02-01 11:01:19,574 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,575 INFO sqlalchemy.engine.base.Engine (2877,)
2021-02-01 11:01:19,578 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,581 INFO sqlalchemy.engine.base.Engine (2878,)
2021-02-01 11:01:19,583 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,585 INFO sqlalchemy.engine.base.Engine (2879,)
2021-02-01 11:01:19,587 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,588 INFO sqlalchemy.engine.base.Engine (2880,)
2021-02-01 11:01:19,590 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,592 INFO sqlalchemy.engine.base.Engine (2881,)
2021-02-01 11:01:19,594 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,595 INFO sqlalchemy.engine.base.Engine (2882,)
2021-02-01 11:01:19,598 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,604 INFO sqlalchemy.engine.base.Engine (2883,)
2021-02-01 11:01:19,606 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,608 INFO sqlalchemy.engine.base.Engine (2884,)
2021-02-01 11:01:19,611 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,616 INFO sqlalchemy.engine.base.Engine (2885,)
2021-02-01 11:01:19,618 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,619 INFO sqlalchemy.engine.base.Engine (2886,)
2021-02-01 11:01:19,623 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,625 INFO sqlalchemy.engine.base.Engine (2887,)
2021-02-01 11:01:19,628 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,629 INFO sqlalchemy.engine.base.Engine (2888,)
2021-02-01 11:01:19,632 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,633 INFO sqlalchemy.engine.base.Engine (2889,)
2021-02-01 11:01:19,636 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,639 INFO sqlalchemy.engine.base.Engine (2890,)
2021-02-01 11:01:19,643 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,645 INFO sqlalchemy.engine.base.Engine (2891,)
2021-02-01 11:01:19,649 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,650 INFO sqlalchemy.engine.base.Engine (2892,)
2021-02-01 11:01:19,652 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,653 INFO sqlalchemy.engine.base.Engine (2893,)
2021-02-01 11:01:19,655 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"

WHERE "Positions".id = ?
2021-02-01 11:01:19,656 INFO sqlalchemy.engine.base.Engine (2894,)
2021-02-01 11:01:19,660 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,661 INFO sqlalchemy.engine.base.Engine (2895,)
2021-02-01 11:01:19,666 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,669 INFO sqlalchemy.engine.base.Engine (2896,)
2021-02-01 11:01:19,672 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,672 INFO sqlalchemy.engine.base.Engine (2897,)
2021-02-01 11:01:19,675 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,677 INFO sqlalchemy.engine.base.Engine (2898,)
2021-02-01 11:01:19,680 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,681 INFO sqlalchemy.engine.base.Engine (2899,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:19,818 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:19,820 INFO sqlalchemy.engine.base.Engine ((2900, 14.3, 14.3, 14.3, 152880.74000002534, 122586.3991390476), (2901, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152880.74000002534, 122586.3991390476), (2902, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152880.74000002534, 122586.3991390476), (2903, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152880.74000002534, 122586.3991390476), (2904, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152880.74000002534, 122586.3991390476), (2905, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152880.74000002534, 122586.3991390476), (2906, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152880.74000002534, 122586.3991390476), (2907, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152880.74000002534, 122586.3991390476)  ... displaying 10 of 50 total bound parameter sets ...  (2948, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152880.74000002534, 122586.3991390476), (2949, 135.9, 135.9, 135.9, 152880.74000002534, 122586.3991390476))
2021-02-01 11:01:19,823 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:19,824 INFO sqlalchemy.engine.base.Engine ('F59',)
2021-02-01 11:01:19,829 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:19,838 INFO sqlalchemy.engine.base.Engine ((1450, 'F59', 0, 'Anhydrite', 2900, 2901), (1451, 'F59', 1, 'Sandstone, grey, vf-f', 2902, 2903), (1452, 'F59', 2, 'Anhydrite', 2904, 2905), (1453, 'F59', 3, 'Dolomite', 2906, 2907), (1454, 'F59', 4, 'Anhydrite', 2908, 2909), (1455, 'F59', 5, 'Sandstone, grey, vf-f', 2910, 2911), (1456, 'F59', 6, 'Siltstone, red', 2912, 2913), (1457, 'F59', 7, 'Dolomite', 2914, 2915)  ... displaying 10 of 25 total bound parameter sets ...  (1473, 'F59', 23, 'Limestone', 2946, 2947), (1474, 'F59', 24, 'Volcanic', 2948, 2949))
2021-02-01 11:01:19,840 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:19,936 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:19,937 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:19,942 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:19,947 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:19,948 INFO sqlalchemy.engine.base.Engine ('F59',)
2021-02-01 11:01:19,952 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,953 INFO sqlalchemy.engine.base.Engine (2900,)
2021-02-01 11:01:19,955 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,956 INFO sqlalchemy.engine.base.Engine (2901,)
2021-02-01 11:01:19,959 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,960 INFO sqlalchemy.engine.base.Engine (2902,)
2021-02-01 11:01:19,963 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,964 INFO sqlalchemy.engine.base.Engine (2903,)
2021-02-01 11:01:19,967 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,968 INFO sqlalchemy.engine.base.Engine (2904,)
2021-02-01 11:01:19,970 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,972 INFO sqlalchemy.engine.base.Engine (2905,)
2021-02-01 11:01:19,978 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,979 INFO sqlalchemy.engine.base.Engine (2906,)
2021-02-01 11:01:19,982 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:19,983 INFO sqlalchemy.engine.base.Engine (2907,)
2021-02-01 11:01:19,986 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,988 INFO sqlalchemy.engine.base.Engine (2908,)
2021-02-01 11:01:19,990 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,992 INFO sqlalchemy.engine.base.Engine (2909,)
2021-02-01 11:01:19,994 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:19,996 INFO sqlalchemy.engine.base.Engine (2910,)
2021-02-01 11:01:19,998 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,008 INFO sqlalchemy.engine.base.Engine (2911,)
2021-02-01 11:01:20,010 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,011 INFO sqlalchemy.engine.base.Engine (2912,)
2021-02-01 11:01:20,014 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,015 INFO sqlalchemy.engine.base.Engine (2913,)
2021-02-01 11:01:20,017 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,021 INFO sqlalchemy.engine.base.Engine (2914,)
2021-02-01 11:01:20,023 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,025 INFO sqlalchemy.engine.base.Engine (2915,)
2021-02-01 11:01:20,030 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,031 INFO sqlalchemy.engine.base.Engine (2916,)
2021-02-01 11:01:20,033 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,035 INFO sqlalchemy.engine.base.Engine (2917,)
2021-02-01 11:01:20,037 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,038 INFO sqlalchemy.engine.base.Engine (2918,)
2021-02-01 11:01:20,040 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,041 INFO sqlalchemy.engine.base.Engine (2919,)
2021-02-01 11:01:20,044 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,049 INFO sqlalchemy.engine.base.Engine (2920,)
2021-02-01 11:01:20,054 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,055 INFO sqlalchemy.engine.base.Engine (2921,)
2021-02-01 11:01:20,058 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,059 INFO sqlalchemy.engine.base.Engine (2922,)
2021-02-01 11:01:20,061 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,062 INFO sqlalchemy.engine.base.Engine (2923,)
2021-02-01 11:01:20,066 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,067 INFO sqlalchemy.engine.base.Engine (2924,)
2021-02-01 11:01:20,070 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,072 INFO sqlalchemy.engine.base.Engine (2925,)
2021-02-01 11:01:20,074 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,075 INFO sqlalchemy.engine.base.Engine (2926,)
2021-02-01 11:01:20,078 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,079 INFO sqlalchemy.engine.base.Engine (2927,)
2021-02-01 11:01:20,080 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:20,084 INFO sqlalchemy.engine.base.Engine (2928,)
2021-02-01 11:01:20,088 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,090 INFO sqlalchemy.engine.base.Engine (2929,)
2021-02-01 11:01:20,096 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,097 INFO sqlalchemy.engine.base.Engine (2930,)
2021-02-01 11:01:20,099 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,100 INFO sqlalchemy.engine.base.Engine (2931,)
2021-02-01 11:01:20,103 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,104 INFO sqlalchemy.engine.base.Engine (2932,)
2021-02-01 11:01:20,105 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,106 INFO sqlalchemy.engine.base.Engine (2933,)
2021-02-01 11:01:20,110 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,111 INFO sqlalchemy.engine.base.Engine (2934,)
2021-02-01 11:01:20,113 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,114 INFO sqlalchemy.engine.base.Engine (2935,)
2021-02-01 11:01:20,116 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,117 INFO sqlalchemy.engine.base.Engine (2936,)
2021-02-01 11:01:20,120 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,121 INFO sqlalchemy.engine.base.Engine (2937,)
2021-02-01 11:01:20,123 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,126 INFO sqlalchemy.engine.base.Engine (2938,)
2021-02-01 11:01:20,129 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,131 INFO sqlalchemy.engine.base.Engine (2939,)
2021-02-01 11:01:20,134 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,135 INFO sqlalchemy.engine.base.Engine (2940,)
2021-02-01 11:01:20,140 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,142 INFO sqlalchemy.engine.base.Engine (2941,)
2021-02-01 11:01:20,144 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,145 INFO sqlalchemy.engine.base.Engine (2942,)
2021-02-01 11:01:20,147 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,148 INFO sqlalchemy.engine.base.Engine (2943,)
2021-02-01 11:01:20,150 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,153 INFO sqlalchemy.engine.base.Engine (2944,)
2021-02-01 11:01:20,155 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,157 INFO sqlalchemy.engine.base.Engine (2945,)
2021-02-01 11:01:20,160 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,161 INFO sqlalchemy.engine.base.Engine (2946,)
2021-02-01 11:01:20,163 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,166 INFO sqlalchemy.engine.base.Engine (2947,)
2021-02-01 11:01:20,169 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,174 INFO sqlalchemy.engine.base.Engine (2948,)
2021-02-01 11:01:20,177 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:20,178 INFO sqlalchemy.engine.base.Engine (2949,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:20,316 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:20,318 INFO sqlalchemy.engine.base.Engine ('F60',)
2021-02-01 11:01:20,321 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:20,323 INFO sqlalchemy.engine.base.Engine ((2950, 14.3, 14.3, 14.3, 152893.9330000255, 122594.96413904615), (2951, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152893.9330000255, 122594.96413904615), (2952, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152893.9330000255, 122594.96413904615), (2953, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152893.9330000255, 122594.96413904615), (2954, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152893.9330000255, 122594.96413904615), (2955, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152893.9330000255, 122594.96413904615), (2956, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152893.9330000255, 122594.96413904615), (2957, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152893.9330000255, 122594.96413904615)  ... displaying 10 of 50 total bound parameter sets ...  (2998, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152893.9330000255, 122594.96413904615), (2999, 135.9, 135.9, 135.9, 152893.9330000255, 122594.96413904615))
2021-02-01 11:01:20,327 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:20,328 INFO sqlalchemy.engine.base.Engine ((1475, 'F60', 0, 'Anhydrite', 2950, 2951), (1476, 'F60', 1, 'Sandstone, grey, vf-f', 2952, 2953), (1477, 'F60', 2, 'Anhydrite', 2954, 2955), (1478, 'F60', 3, 'Dolomite', 2956, 2957), (1479, 'F60', 4, 'Anhydrite', 2958, 2959), (1480, 'F60', 5, 'Sandstone, grey, vf-f', 2960, 2961), (1481, 'F60', 6, 'Siltstone, red', 2962, 2963), (1482, 'F60', 7, 'Dolomite', 2964, 2965)  ... displaying 10 of 25 total bound parameter sets ...  (1498, 'F60', 23, 'Limestone', 2996, 2997), (1499, 'F60', 24, 'Volcanic', 2998, 2999))
2021-02-01 11:01:20,331 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:20,442 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:20,444 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:20,445 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:20,449 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:20,450 INFO sqlalchemy.engine.base.Engine ('F60',)
2021-02-01 11:01:20,453 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,455 INFO sqlalchemy.engine.base.Engine (2950,)
2021-02-01 11:01:20,460 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,461 INFO sqlalchemy.engine.base.Engine (2951,)
2021-02-01 11:01:20,463 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,464 INFO sqlalchemy.engine.base.Engine (2952,)
2021-02-01 11:01:20,467 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,468 INFO sqlalchemy.engine.base.Engine (2953,)
2021-02-01 11:01:20,470 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,473 INFO sqlalchemy.engine.base.Engine (2954,)
2021-02-01 11:01:20,475 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,476 INFO sqlalchemy.engine.base.Engine (2955,)
2021-02-01 11:01:20,479 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,484 INFO sqlalchemy.engine.base.Engine (2956,)
2021-02-01 11:01:20,486 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,487 INFO sqlalchemy.engine.base.Engine (2957,)
2021-02-01 11:01:20,489 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,490 INFO sqlalchemy.engine.base.Engine (2958,)
2021-02-01 11:01:20,492 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,493 INFO sqlalchemy.engine.base.Engine (2959,)
2021-02-01 11:01:20,496 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,497 INFO sqlalchemy.engine.base.Engine (2960,)
2021-02-01 11:01:20,503 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,505 INFO sqlalchemy.engine.base.Engine (2961,)
2021-02-01 11:01:20,507 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,509 INFO sqlalchemy.engine.base.Engine (2962,)

2021-02-01 11:01:20,513 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,514 INFO sqlalchemy.engine.base.Engine (2963,)
2021-02-01 11:01:20,516 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,516 INFO sqlalchemy.engine.base.Engine (2964,)
2021-02-01 11:01:20,519 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,520 INFO sqlalchemy.engine.base.Engine (2965,)
2021-02-01 11:01:20,525 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,526 INFO sqlalchemy.engine.base.Engine (2966,)
2021-02-01 11:01:20,529 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,530 INFO sqlalchemy.engine.base.Engine (2967,)
2021-02-01 11:01:20,533 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,534 INFO sqlalchemy.engine.base.Engine (2968,)
2021-02-01 11:01:20,536 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,537 INFO sqlalchemy.engine.base.Engine (2969,)
2021-02-01 11:01:20,539 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,541 INFO sqlalchemy.engine.base.Engine (2970,)
2021-02-01 11:01:20,544 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,546 INFO sqlalchemy.engine.base.Engine (2971,)
2021-02-01 11:01:20,550 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,551 INFO sqlalchemy.engine.base.Engine (2972,)
2021-02-01 11:01:20,553 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,557 INFO sqlalchemy.engine.base.Engine (2973,)
2021-02-01 11:01:20,562 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,564 INFO sqlalchemy.engine.base.Engine (2974,)
2021-02-01 11:01:20,566 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,567 INFO sqlalchemy.engine.base.Engine (2975,)
2021-02-01 11:01:20,569 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,576 INFO sqlalchemy.engine.base.Engine (2976,)
2021-02-01 11:01:20,581 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,582 INFO sqlalchemy.engine.base.Engine (2977,)
2021-02-01 11:01:20,585 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,586 INFO sqlalchemy.engine.base.Engine (2978,)
2021-02-01 11:01:20,591 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,593 INFO sqlalchemy.engine.base.Engine (2979,)
2021-02-01 11:01:20,595 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,598 INFO sqlalchemy.engine.base.Engine (2980,)
2021-02-01 11:01:20,600 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,602 INFO sqlalchemy.engine.base.Engine (2981,)
2021-02-01 11:01:20,604 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,605 INFO sqlalchemy.engine.base.Engine (2982,)
2021-02-01 11:01:20,608 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:20,609 INFO sqlalchemy.engine.base.Engine (2983,)
2021-02-01 11:01:20,614 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,617 INFO sqlalchemy.engine.base.Engine (2984,)
2021-02-01 11:01:20,618 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,620 INFO sqlalchemy.engine.base.Engine (2985,)
2021-02-01 11:01:20,623 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,625 INFO sqlalchemy.engine.base.Engine (2986,)
2021-02-01 11:01:20,627 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,628 INFO sqlalchemy.engine.base.Engine (2987,)
2021-02-01 11:01:20,633 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,634 INFO sqlalchemy.engine.base.Engine (2988,)
2021-02-01 11:01:20,637 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,638 INFO sqlalchemy.engine.base.Engine (2989,)
2021-02-01 11:01:20,640 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,640 INFO sqlalchemy.engine.base.Engine (2990,)
2021-02-01 11:01:20,642 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,644 INFO sqlalchemy.engine.base.Engine (2991,)
2021-02-01 11:01:20,646 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,647 INFO sqlalchemy.engine.base.Engine (2992,)
2021-02-01 11:01:20,649 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,650 INFO sqlalchemy.engine.base.Engine (2993,)
2021-02-01 11:01:20,652 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,652 INFO sqlalchemy.engine.base.Engine (2994,)
2021-02-01 11:01:20,655 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,656 INFO sqlalchemy.engine.base.Engine (2995,)
2021-02-01 11:01:20,659 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,660 INFO sqlalchemy.engine.base.Engine (2996,)
2021-02-01 11:01:20,664 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,666 INFO sqlalchemy.engine.base.Engine (2997,)
2021-02-01 11:01:20,668 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,669 INFO sqlalchemy.engine.base.Engine (2998,)
2021-02-01 11:01:20,671 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,672 INFO sqlalchemy.engine.base.Engine (2999,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:20,804 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:20,805 INFO sqlalchemy.engine.base.Engine ((3000, 14.3, 14.3, 14.3, 152887.10600002544, 122593.01613904722), (3001, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152887.10600002544, 122593.01613904722), (3002, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152887.10600002544, 122593.01613904722), (3003, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152887.10600002544, 122593.01613904722), (3004, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152887.10600002544, 122593.01613904722), (3005, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152887.10600002544, 122593.01613904722), (3006, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152887.10600002544, 122593.01613904722), (3007, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152887.10600002544, 122593.01613904722)  ... displaying 10 of 50 total bound parameter sets ...  (3048, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152887.10600002544, 122593.01613904722), (3049, 135.9, 135.9, 135.9, 152887.10600002544, 122593.01613904722))
2021-02-01 11:01:20,808 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:20,812 INFO sqlalchemy.engine.base.Engine ('F61',)
2021-02-01 11:01:20,817 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:20,818 INFO sqlalchemy.engine.base.Engine ((1500, 'F61', 0, 'Anhydrite', 3000, 3001), (1501, 'F61', 1, 'Sandstone, grey, vf-f', 3002, 3003), (1502, 'F61', 2, 'Anhydrite', 3004, 3005), (1503, 'F61', 3, 'Dolomite', 3006, 3007), (1504, 'F61', 4, 'Anhydrite', 3008, 3009), (1505, 'F61', 5, 'Sandstone, grey, vf-f', 3010, 3011), (1506, 'F61', 6, 'Siltstone, red', 3012, 3013), (1507, 'F61', 7, 'Dolomite', 3014, 3015)  ... displaying 10 of 25 total bound parameter sets ...  (1523, 'F61', 23, 'Limestone', 3046, 3047), (1524, 'F61', 24, 'Volcanic', 3048, 3049))

2021-02-01 11:01:20,822 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:20,919 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:20,920 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:20,922 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:20,926 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:20,927 INFO sqlalchemy.engine.base.Engine ('F61',)
2021-02-01 11:01:20,930 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,932 INFO sqlalchemy.engine.base.Engine (3000,)
2021-02-01 11:01:20,935 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,937 INFO sqlalchemy.engine.base.Engine (3001,)
2021-02-01 11:01:20,939 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,941 INFO sqlalchemy.engine.base.Engine (3002,)
2021-02-01 11:01:20,945 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,949 INFO sqlalchemy.engine.base.Engine (3003,)
2021-02-01 11:01:20,951 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,952 INFO sqlalchemy.engine.base.Engine (3004,)
2021-02-01 11:01:20,955 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,956 INFO sqlalchemy.engine.base.Engine (3005,)
2021-02-01 11:01:20,958 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,961 INFO sqlalchemy.engine.base.Engine (3006,)
2021-02-01 11:01:20,962 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,963 INFO sqlalchemy.engine.base.Engine (3007,)
2021-02-01 11:01:20,965 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,966 INFO sqlalchemy.engine.base.Engine (3008,)
2021-02-01 11:01:20,968 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,969 INFO sqlalchemy.engine.base.Engine (3009,)
2021-02-01 11:01:20,971 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,972 INFO sqlalchemy.engine.base.Engine (3010,)
2021-02-01 11:01:20,974 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,976 INFO sqlalchemy.engine.base.Engine (3011,)
2021-02-01 11:01:20,979 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,981 INFO sqlalchemy.engine.base.Engine (3012,)
2021-02-01 11:01:20,982 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,983 INFO sqlalchemy.engine.base.Engine (3013,)
2021-02-01 11:01:20,986 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,987 INFO sqlalchemy.engine.base.Engine (3014,)
2021-02-01 11:01:20,989 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,993 INFO sqlalchemy.engine.base.Engine (3015,)
2021-02-01 11:01:20,998 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:20,999 INFO sqlalchemy.engine.base.Engine (3016,)
2021-02-01 11:01:21,002 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,003 INFO sqlalchemy.engine.base.Engine (3017,)
2021-02-01 11:01:21,005 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"

WHERE "Positions".id = ?
2021-02-01 11:01:21,007 INFO sqlalchemy.engine.base.Engine (3018,)
2021-02-01 11:01:21,009 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,010 INFO sqlalchemy.engine.base.Engine (3019,)
2021-02-01 11:01:21,012 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,014 INFO sqlalchemy.engine.base.Engine (3020,)
2021-02-01 11:01:21,016 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,017 INFO sqlalchemy.engine.base.Engine (3021,)
2021-02-01 11:01:21,020 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,021 INFO sqlalchemy.engine.base.Engine (3022,)
2021-02-01 11:01:21,024 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,026 INFO sqlalchemy.engine.base.Engine (3023,)
2021-02-01 11:01:21,030 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,032 INFO sqlalchemy.engine.base.Engine (3024,)
2021-02-01 11:01:21,037 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,038 INFO sqlalchemy.engine.base.Engine (3025,)
2021-02-01 11:01:21,040 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,042 INFO sqlalchemy.engine.base.Engine (3026,)
2021-02-01 11:01:21,045 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,045 INFO sqlalchemy.engine.base.Engine (3027,)
2021-02-01 11:01:21,048 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,049 INFO sqlalchemy.engine.base.Engine (3028,)
2021-02-01 11:01:21,053 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,054 INFO sqlalchemy.engine.base.Engine (3029,)
2021-02-01 11:01:21,057 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,058 INFO sqlalchemy.engine.base.Engine (3030,)
2021-02-01 11:01:21,063 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,065 INFO sqlalchemy.engine.base.Engine (3031,)
2021-02-01 11:01:21,067 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,068 INFO sqlalchemy.engine.base.Engine (3032,)
2021-02-01 11:01:21,070 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,071 INFO sqlalchemy.engine.base.Engine (3033,)
2021-02-01 11:01:21,073 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,074 INFO sqlalchemy.engine.base.Engine (3034,)
2021-02-01 11:01:21,081 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,082 INFO sqlalchemy.engine.base.Engine (3035,)
2021-02-01 11:01:21,087 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,091 INFO sqlalchemy.engine.base.Engine (3036,)
2021-02-01 11:01:21,094 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,095 INFO sqlalchemy.engine.base.Engine (3037,)
2021-02-01 11:01:21,097 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,099 INFO sqlalchemy.engine.base.Engine (3038,)
2021-02-01 11:01:21,101 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:21,102 INFO sqlalchemy.engine.base.Engine (3039,)
2021-02-01 11:01:21,104 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,105 INFO sqlalchemy.engine.base.Engine (3040,)
2021-02-01 11:01:21,108 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,109 INFO sqlalchemy.engine.base.Engine (3041,)
2021-02-01 11:01:21,111 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,112 INFO sqlalchemy.engine.base.Engine (3042,)
2021-02-01 11:01:21,115 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,116 INFO sqlalchemy.engine.base.Engine (3043,)
2021-02-01 11:01:21,119 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,120 INFO sqlalchemy.engine.base.Engine (3044,)
2021-02-01 11:01:21,122 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,124 INFO sqlalchemy.engine.base.Engine (3045,)
2021-02-01 11:01:21,126 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,127 INFO sqlalchemy.engine.base.Engine (3046,)
2021-02-01 11:01:21,132 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,133 INFO sqlalchemy.engine.base.Engine (3047,)
2021-02-01 11:01:21,135 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,136 INFO sqlalchemy.engine.base.Engine (3048,)
2021-02-01 11:01:21,138 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,139 INFO sqlalchemy.engine.base.Engine (3049,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:21,288 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:21,289 INFO sqlalchemy.engine.base.Engine ('F62',)
2021-02-01 11:01:21,296 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:21,297 INFO sqlalchemy.engine.base.Engine ((3050, 14.3, 14.3, 14.3, 152891.63200002545, 122591.38213904668), (3051, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152891.63200002545, 122591.38213904668), (3052, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152891.63200002545, 122591.38213904668), (3053, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152891.63200002545, 122591.38213904668), (3054, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152891.63200002545, 122591.38213904668), (3055, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152891.63200002545, 122591.38213904668), (3056, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152891.63200002545, 122591.38213904668), (3057, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152891.63200002545, 122591.38213904668)  ... displaying 10 of 50 total bound parameter sets ...  (3098, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152891.63200002545, 122591.38213904668), (3099, 135.9, 135.9, 135.9, 152891.63200002545, 122591.38213904668))
2021-02-01 11:01:21,302 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:21,312 INFO sqlalchemy.engine.base.Engine ((1525, 'F62', 0, 'Anhydrite', 3050, 3051), (1526, 'F62', 1, 'Sandstone, grey, vf-f', 3052, 3053), (1527, 'F62', 2, 'Anhydrite', 3054, 3055), (1528, 'F62', 3, 'Dolomite', 3056, 3057), (1529, 'F62', 4, 'Anhydrite', 3058, 3059), (1530, 'F62', 5, 'Sandstone, grey, vf-f', 3060, 3061), (1531, 'F62', 6, 'Siltstone, red', 3062, 3063), (1532, 'F62', 7, 'Dolomite', 3064, 3065)  ... displaying 10 of 25 total bound parameter sets ...  (1548, 'F62', 23, 'Limestone', 3096, 3097), (1549, 'F62', 24, 'Volcanic', 3098, 3099))
2021-02-01 11:01:21,315 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:21,435 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:21,436 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:21,437 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:21,441 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:21,442 INFO sqlalchemy.engine.base.Engine ('F62',)
2021-02-01 11:01:21,446 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,447 INFO sqlalchemy.engine.base.Engine (3050,)
2021-02-01 11:01:21,449 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,450 INFO sqlalchemy.engine.base.Engine (3051,)
2021-02-01 11:01:21,456 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,457 INFO sqlalchemy.engine.base.Engine (3052,)

2021-02-01 11:01:21,460 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,461 INFO sqlalchemy.engine.base.Engine (3053,)
2021-02-01 11:01:21,463 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,465 INFO sqlalchemy.engine.base.Engine (3054,)
2021-02-01 11:01:21,467 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,468 INFO sqlalchemy.engine.base.Engine (3055,)
2021-02-01 11:01:21,470 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,471 INFO sqlalchemy.engine.base.Engine (3056,)
2021-02-01 11:01:21,473 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,474 INFO sqlalchemy.engine.base.Engine (3057,)
2021-02-01 11:01:21,477 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,478 INFO sqlalchemy.engine.base.Engine (3058,)
2021-02-01 11:01:21,481 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,482 INFO sqlalchemy.engine.base.Engine (3059,)
2021-02-01 11:01:21,484 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,485 INFO sqlalchemy.engine.base.Engine (3060,)
2021-02-01 11:01:21,489 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,490 INFO sqlalchemy.engine.base.Engine (3061,)
2021-02-01 11:01:21,493 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,496 INFO sqlalchemy.engine.base.Engine (3062,)
2021-02-01 11:01:21,498 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,499 INFO sqlalchemy.engine.base.Engine (3063,)
2021-02-01 11:01:21,501 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,504 INFO sqlalchemy.engine.base.Engine (3064,)
2021-02-01 11:01:21,507 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,509 INFO sqlalchemy.engine.base.Engine (3065,)
2021-02-01 11:01:21,511 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,517 INFO sqlalchemy.engine.base.Engine (3066,)
2021-02-01 11:01:21,520 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,521 INFO sqlalchemy.engine.base.Engine (3067,)
2021-02-01 11:01:21,523 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,525 INFO sqlalchemy.engine.base.Engine (3068,)
2021-02-01 11:01:21,526 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,528 INFO sqlalchemy.engine.base.Engine (3069,)
2021-02-01 11:01:21,530 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,532 INFO sqlalchemy.engine.base.Engine (3070,)
2021-02-01 11:01:21,533 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,534 INFO sqlalchemy.engine.base.Engine (3071,)
2021-02-01 11:01:21,536 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,539 INFO sqlalchemy.engine.base.Engine (3072,)
2021-02-01 11:01:21,541 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:21,542 INFO sqlalchemy.engine.base.Engine (3073,)
2021-02-01 11:01:21,544 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,547 INFO sqlalchemy.engine.base.Engine (3074,)
2021-02-01 11:01:21,550 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,551 INFO sqlalchemy.engine.base.Engine (3075,)
2021-02-01 11:01:21,553 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,554 INFO sqlalchemy.engine.base.Engine (3076,)
2021-02-01 11:01:21,556 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,557 INFO sqlalchemy.engine.base.Engine (3077,)
2021-02-01 11:01:21,559 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,560 INFO sqlalchemy.engine.base.Engine (3078,)
2021-02-01 11:01:21,562 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,563 INFO sqlalchemy.engine.base.Engine (3079,)
2021-02-01 11:01:21,566 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,567 INFO sqlalchemy.engine.base.Engine (3080,)
2021-02-01 11:01:21,568 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,569 INFO sqlalchemy.engine.base.Engine (3081,)
2021-02-01 11:01:21,571 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,572 INFO sqlalchemy.engine.base.Engine (3082,)
2021-02-01 11:01:21,575 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,582 INFO sqlalchemy.engine.base.Engine (3083,)
2021-02-01 11:01:21,583 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,585 INFO sqlalchemy.engine.base.Engine (3084,)
2021-02-01 11:01:21,589 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,590 INFO sqlalchemy.engine.base.Engine (3085,)
2021-02-01 11:01:21,592 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,593 INFO sqlalchemy.engine.base.Engine (3086,)
2021-02-01 11:01:21,594 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,595 INFO sqlalchemy.engine.base.Engine (3087,)
2021-02-01 11:01:21,597 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,598 INFO sqlalchemy.engine.base.Engine (3088,)
2021-02-01 11:01:21,600 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,601 INFO sqlalchemy.engine.base.Engine (3089,)
2021-02-01 11:01:21,603 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,604 INFO sqlalchemy.engine.base.Engine (3090,)
2021-02-01 11:01:21,606 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,607 INFO sqlalchemy.engine.base.Engine (3091,)
2021-02-01 11:01:21,609 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,610 INFO sqlalchemy.engine.base.Engine (3092,)
2021-02-01 11:01:21,611 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,614 INFO sqlalchemy.engine.base.Engine (3093,)
2021-02-01 11:01:21,618 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:21,619 INFO sqlalchemy.engine.base.Engine (3094,)
2021-02-01 11:01:21,620 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,622 INFO sqlalchemy.engine.base.Engine (3095,)
2021-02-01 11:01:21,624 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,625 INFO sqlalchemy.engine.base.Engine (3096,)
2021-02-01 11:01:21,627 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,628 INFO sqlalchemy.engine.base.Engine (3097,)
2021-02-01 11:01:21,629 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,630 INFO sqlalchemy.engine.base.Engine (3098,)
2021-02-01 11:01:21,632 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,633 INFO sqlalchemy.engine.base.Engine (3099,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:21,788 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:21,790 INFO sqlalchemy.engine.base.Engine ('F63',)
2021-02-01 11:01:21,794 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:21,796 INFO sqlalchemy.engine.base.Engine ((3100, 14.3, 14.3, 14.3, 152880.26600002535, 122582.55413904414), (3101, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152880.26600002535, 122582.55413904414), (3102, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152880.26600002535, 122582.55413904414), (3103, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152880.26600002535, 122582.55413904414), (3104, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152880.26600002535, 122582.55413904414), (3105, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152880.26600002535, 122582.55413904414), (3106, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152880.26600002535, 122582.55413904414), (3107, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152880.26600002535, 122582.55413904414)  ... displaying 10 of 50 total bound parameter sets ...  (3148, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152880.26600002535, 122582.55413904414), (3149, 135.9, 135.9, 135.9, 152880.26600002535, 122582.55413904414))
2021-02-01 11:01:21,801 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:21,802 INFO sqlalchemy.engine.base.Engine ((1550, 'F63', 0, 'Anhydrite', 3100, 3101), (1551, 'F63', 1, 'Sandstone, grey, vf-f', 3102, 3103), (1552, 'F63', 2, 'Anhydrite', 3104, 3105), (1553, 'F63', 3, 'Dolomite', 3106, 3107), (1554, 'F63', 4, 'Anhydrite', 3108, 3109), (1555, 'F63', 5, 'Sandstone, grey, vf-f', 3110, 3111), (1556, 'F63', 6, 'Siltstone, red', 3112, 3113), (1557, 'F63', 7, 'Dolomite', 3114, 3115)  ... displaying 10 of 25 total bound parameter sets ...  (1573, 'F63', 23, 'Limestone', 3146, 3147), (1574, 'F63', 24, 'Volcanic', 3148, 3149))
2021-02-01 11:01:21,809 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:21,929 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:21,930 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:21,931 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:21,935 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:21,936 INFO sqlalchemy.engine.base.Engine ('F63',)
2021-02-01 11:01:21,939 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,939 INFO sqlalchemy.engine.base.Engine (3100,)
2021-02-01 11:01:21,941 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,943 INFO sqlalchemy.engine.base.Engine (3101,)
2021-02-01 11:01:21,945 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,949 INFO sqlalchemy.engine.base.Engine (3102,)
2021-02-01 11:01:21,951 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,953 INFO sqlalchemy.engine.base.Engine (3103,)
2021-02-01 11:01:21,956 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,957 INFO sqlalchemy.engine.base.Engine (3104,)
2021-02-01 11:01:21,958 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,960 INFO sqlalchemy.engine.base.Engine (3105,)
2021-02-01 11:01:21,963 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,964 INFO sqlalchemy.engine.base.Engine (3106,)
2021-02-01 11:01:21,966 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,968 INFO sqlalchemy.engine.base.Engine (3107,)

2021-02-01 11:01:21,970 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,972 INFO sqlalchemy.engine.base.Engine (3108,)
2021-02-01 11:01:21,974 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,976 INFO sqlalchemy.engine.base.Engine (3109,)
2021-02-01 11:01:21,980 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,981 INFO sqlalchemy.engine.base.Engine (3110,)
2021-02-01 11:01:21,985 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,987 INFO sqlalchemy.engine.base.Engine (3111,)
2021-02-01 11:01:21,990 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,991 INFO sqlalchemy.engine.base.Engine (3112,)
2021-02-01 11:01:21,993 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,995 INFO sqlalchemy.engine.base.Engine (3113,)
2021-02-01 11:01:21,997 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:21,999 INFO sqlalchemy.engine.base.Engine (3114,)
2021-02-01 11:01:22,003 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,005 INFO sqlalchemy.engine.base.Engine (3115,)
2021-02-01 11:01:22,007 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,009 INFO sqlalchemy.engine.base.Engine (3116,)
2021-02-01 11:01:22,012 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,012 INFO sqlalchemy.engine.base.Engine (3117,)
2021-02-01 11:01:22,015 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,016 INFO sqlalchemy.engine.base.Engine (3118,)
2021-02-01 11:01:22,018 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,019 INFO sqlalchemy.engine.base.Engine (3119,)
2021-02-01 11:01:22,021 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,023 INFO sqlalchemy.engine.base.Engine (3120,)
2021-02-01 11:01:22,027 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,028 INFO sqlalchemy.engine.base.Engine (3121,)
2021-02-01 11:01:22,030 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,035 INFO sqlalchemy.engine.base.Engine (3122,)
2021-02-01 11:01:22,037 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,038 INFO sqlalchemy.engine.base.Engine (3123,)
2021-02-01 11:01:22,042 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,043 INFO sqlalchemy.engine.base.Engine (3124,)
2021-02-01 11:01:22,045 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,046 INFO sqlalchemy.engine.base.Engine (3125,)
2021-02-01 11:01:22,049 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,053 INFO sqlalchemy.engine.base.Engine (3126,)
2021-02-01 11:01:22,055 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,056 INFO sqlalchemy.engine.base.Engine (3127,)
2021-02-01 11:01:22,058 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:22,060 INFO sqlalchemy.engine.base.Engine (3128,)
2021-02-01 11:01:22,062 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,063 INFO sqlalchemy.engine.base.Engine (3129,)
2021-02-01 11:01:22,066 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,067 INFO sqlalchemy.engine.base.Engine (3130,)
2021-02-01 11:01:22,070 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,071 INFO sqlalchemy.engine.base.Engine (3131,)
2021-02-01 11:01:22,073 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,075 INFO sqlalchemy.engine.base.Engine (3132,)
2021-02-01 11:01:22,077 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,079 INFO sqlalchemy.engine.base.Engine (3133,)
2021-02-01 11:01:22,081 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,082 INFO sqlalchemy.engine.base.Engine (3134,)
2021-02-01 11:01:22,085 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,086 INFO sqlalchemy.engine.base.Engine (3135,)
2021-02-01 11:01:22,091 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,092 INFO sqlalchemy.engine.base.Engine (3136,)
2021-02-01 11:01:22,094 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,097 INFO sqlalchemy.engine.base.Engine (3137,)
2021-02-01 11:01:22,099 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,103 INFO sqlalchemy.engine.base.Engine (3138,)
2021-02-01 11:01:22,106 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,107 INFO sqlalchemy.engine.base.Engine (3139,)
2021-02-01 11:01:22,108 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,111 INFO sqlalchemy.engine.base.Engine (3140,)
2021-02-01 11:01:22,117 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,121 INFO sqlalchemy.engine.base.Engine (3141,)
2021-02-01 11:01:22,123 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,124 INFO sqlalchemy.engine.base.Engine (3142,)
2021-02-01 11:01:22,127 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,129 INFO sqlalchemy.engine.base.Engine (3143,)
2021-02-01 11:01:22,130 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,132 INFO sqlalchemy.engine.base.Engine (3144,)
2021-02-01 11:01:22,134 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,137 INFO sqlalchemy.engine.base.Engine (3145,)
2021-02-01 11:01:22,143 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,145 INFO sqlalchemy.engine.base.Engine (3146,)
2021-02-01 11:01:22,147 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,148 INFO sqlalchemy.engine.base.Engine (3147,)
2021-02-01 11:01:22,151 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,154 INFO sqlalchemy.engine.base.Engine (3148,)
2021-02-01 11:01:22,159 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:22,160 INFO sqlalchemy.engine.base.Engine (3149,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:22,288 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:22,290 INFO sqlalchemy.engine.base.Engine ('F64',)
2021-02-01 11:01:22,294 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:22,302 INFO sqlalchemy.engine.base.Engine ((3150, 14.3, 14.3, 14.3, 152867.45209745006, 122588.87729745824), (3151, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152867.45209745006, 122588.87729745824), (3152, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152867.45209745006, 122588.87729745824), (3153, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152867.45209745006, 122588.87729745824), (3154, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152867.45209745006, 122588.87729745824), (3155, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152867.45209745006, 122588.87729745824), (3156, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152867.45209745006, 122588.87729745824), (3157, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152867.45209745006, 122588.87729745824)  ... displaying 10 of 50 total bound parameter sets ...  (3198, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152867.45209745006, 122588.87729745824), (3199, 135.9, 135.9, 135.9, 152867.45209745006, 122588.87729745824))
2021-02-01 11:01:22,312 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:22,313 INFO sqlalchemy.engine.base.Engine ((1575, 'F64', 0, 'Anhydrite', 3150, 3151), (1576, 'F64', 1, 'Sandstone, grey, vf-f', 3152, 3153), (1577, 'F64', 2, 'Anhydrite', 3154, 3155), (1578, 'F64', 3, 'Dolomite', 3156, 3157), (1579, 'F64', 4, 'Anhydrite', 3158, 3159), (1580, 'F64', 5, 'Sandstone, grey, vf-f', 3160, 3161), (1581, 'F64', 6, 'Siltstone, red', 3162, 3163), (1582, 'F64', 7, 'Dolomite', 3164, 3165)  ... displaying 10 of 25 total bound parameter sets ...  (1598, 'F64', 23, 'Limestone', 3196, 3197), (1599, 'F64', 24, 'Volcanic', 3198, 3199))
2021-02-01 11:01:22,317 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:22,410 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:22,412 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:22,413 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:22,415 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:22,417 INFO sqlalchemy.engine.base.Engine ('F64',)
2021-02-01 11:01:22,423 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,424 INFO sqlalchemy.engine.base.Engine (3150,)
2021-02-01 11:01:22,427 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,428 INFO sqlalchemy.engine.base.Engine (3151,)
2021-02-01 11:01:22,431 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,432 INFO sqlalchemy.engine.base.Engine (3152,)
2021-02-01 11:01:22,435 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,436 INFO sqlalchemy.engine.base.Engine (3153,)
2021-02-01 11:01:22,438 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,439 INFO sqlalchemy.engine.base.Engine (3154,)
2021-02-01 11:01:22,443 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,445 INFO sqlalchemy.engine.base.Engine (3155,)
2021-02-01 11:01:22,448 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,449 INFO sqlalchemy.engine.base.Engine (3156,)
2021-02-01 11:01:22,452 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,453 INFO sqlalchemy.engine.base.Engine (3157,)
2021-02-01 11:01:22,455 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,457 INFO sqlalchemy.engine.base.Engine (3158,)
2021-02-01 11:01:22,459 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,461 INFO sqlalchemy.engine.base.Engine (3159,)
2021-02-01 11:01:22,466 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,470 INFO sqlalchemy.engine.base.Engine (3160,)
2021-02-01 11:01:22,473 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,475 INFO sqlalchemy.engine.base.Engine (3161,)
2021-02-01 11:01:22,478 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,481 INFO sqlalchemy.engine.base.Engine (3162,)

2021-02-01 11:01:22,484 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,486 INFO sqlalchemy.engine.base.Engine (3163,)
2021-02-01 11:01:22,490 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,491 INFO sqlalchemy.engine.base.Engine (3164,)
2021-02-01 11:01:22,493 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,495 INFO sqlalchemy.engine.base.Engine (3165,)
2021-02-01 11:01:22,497 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,499 INFO sqlalchemy.engine.base.Engine (3166,)
2021-02-01 11:01:22,501 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,502 INFO sqlalchemy.engine.base.Engine (3167,)
2021-02-01 11:01:22,505 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,506 INFO sqlalchemy.engine.base.Engine (3168,)
2021-02-01 11:01:22,508 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,510 INFO sqlalchemy.engine.base.Engine (3169,)
2021-02-01 11:01:22,521 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,522 INFO sqlalchemy.engine.base.Engine (3170,)
2021-02-01 11:01:22,526 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,529 INFO sqlalchemy.engine.base.Engine (3171,)
2021-02-01 11:01:22,533 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,534 INFO sqlalchemy.engine.base.Engine (3172,)
2021-02-01 11:01:22,536 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,538 INFO sqlalchemy.engine.base.Engine (3173,)
2021-02-01 11:01:22,541 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,543 INFO sqlalchemy.engine.base.Engine (3174,)
2021-02-01 11:01:22,545 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,546 INFO sqlalchemy.engine.base.Engine (3175,)
2021-02-01 11:01:22,548 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,550 INFO sqlalchemy.engine.base.Engine (3176,)
2021-02-01 11:01:22,553 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,554 INFO sqlalchemy.engine.base.Engine (3177,)
2021-02-01 11:01:22,557 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,559 INFO sqlalchemy.engine.base.Engine (3178,)
2021-02-01 11:01:22,561 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,562 INFO sqlalchemy.engine.base.Engine (3179,)
2021-02-01 11:01:22,565 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,569 INFO sqlalchemy.engine.base.Engine (3180,)
2021-02-01 11:01:22,572 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,573 INFO sqlalchemy.engine.base.Engine (3181,)
2021-02-01 11:01:22,576 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,577 INFO sqlalchemy.engine.base.Engine (3182,)
2021-02-01 11:01:22,579 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:22,581 INFO sqlalchemy.engine.base.Engine (3183,)
2021-02-01 11:01:22,583 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,584 INFO sqlalchemy.engine.base.Engine (3184,)
2021-02-01 11:01:22,587 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,591 INFO sqlalchemy.engine.base.Engine (3185,)
2021-02-01 11:01:22,593 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,594 INFO sqlalchemy.engine.base.Engine (3186,)
2021-02-01 11:01:22,595 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,596 INFO sqlalchemy.engine.base.Engine (3187,)
2021-02-01 11:01:22,599 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,600 INFO sqlalchemy.engine.base.Engine (3188,)
2021-02-01 11:01:22,602 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,603 INFO sqlalchemy.engine.base.Engine (3189,)
2021-02-01 11:01:22,606 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,607 INFO sqlalchemy.engine.base.Engine (3190,)
2021-02-01 11:01:22,609 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,610 INFO sqlalchemy.engine.base.Engine (3191,)
2021-02-01 11:01:22,612 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,613 INFO sqlalchemy.engine.base.Engine (3192,)
2021-02-01 11:01:22,616 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,618 INFO sqlalchemy.engine.base.Engine (3193,)
2021-02-01 11:01:22,622 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,623 INFO sqlalchemy.engine.base.Engine (3194,)
2021-02-01 11:01:22,625 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,626 INFO sqlalchemy.engine.base.Engine (3195,)
2021-02-01 11:01:22,629 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,630 INFO sqlalchemy.engine.base.Engine (3196,)
2021-02-01 11:01:22,632 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,634 INFO sqlalchemy.engine.base.Engine (3197,)
2021-02-01 11:01:22,636 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,640 INFO sqlalchemy.engine.base.Engine (3198,)
2021-02-01 11:01:22,647 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,648 INFO sqlalchemy.engine.base.Engine (3199,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:22,833 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:22,834 INFO sqlalchemy.engine.base.Engine ((3200, 14.3, 14.3, 14.3, 152876.61200002534, 122584.35813904832), (3201, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152876.61200002534, 122584.35813904832), (3202, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152876.61200002534, 122584.35813904832), (3203, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152876.61200002534, 122584.35813904832), (3204, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152876.61200002534, 122584.35813904832), (3205, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152876.61200002534, 122584.35813904832), (3206, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152876.61200002534, 122584.35813904832), (3207, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152876.61200002534, 122584.35813904832)  ... displaying 10 of 50 total bound parameter sets ...  (3248, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152876.61200002534, 122584.35813904832), (3249, 135.9, 135.9, 135.9, 152876.61200002534, 122584.35813904832))
2021-02-01 11:01:22,837 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:22,838 INFO sqlalchemy.engine.base.Engine ('F65',)
2021-02-01 11:01:22,844 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:22,845 INFO sqlalchemy.engine.base.Engine ((1600, 'F65', 0, 'Anhydrite', 3200, 3201), (1601, 'F65', 1, 'Sandstone, grey, vf-f', 3202, 3203), (1602, 'F65', 2, 'Anhydrite', 3204, 3205), (1603, 'F65', 3, 'Dolomite', 3206, 3207), (1604, 'F65', 4, 'Anhydrite', 3208, 3209), (1605, 'F65', 5, 'Sandstone, grey, vf-f', 3210, 3211), (1606, 'F65', 6, 'Siltstone, red', 3212, 3213), (1607, 'F65', 7, 'Dolomite', 3214, 3215)  ... displaying 10 of 25 total bound parameter sets ...  (1623, 'F65', 23, 'Limestone', 3246, 3247), (1624, 'F65', 24, 'Volcanic', 3248, 3249))

2021-02-01 11:01:22,849 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:22,964 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:22,966 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:22,973 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:22,978 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:22,979 INFO sqlalchemy.engine.base.Engine ('F65',)
2021-02-01 11:01:22,982 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,983 INFO sqlalchemy.engine.base.Engine (3200,)
2021-02-01 11:01:22,986 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,988 INFO sqlalchemy.engine.base.Engine (3201,)
2021-02-01 11:01:22,990 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,992 INFO sqlalchemy.engine.base.Engine (3202,)
2021-02-01 11:01:22,995 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:22,999 INFO sqlalchemy.engine.base.Engine (3203,)
2021-02-01 11:01:23,002 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,003 INFO sqlalchemy.engine.base.Engine (3204,)
2021-02-01 11:01:23,005 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,007 INFO sqlalchemy.engine.base.Engine (3205,)
2021-02-01 11:01:23,009 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,010 INFO sqlalchemy.engine.base.Engine (3206,)
2021-02-01 11:01:23,012 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,013 INFO sqlalchemy.engine.base.Engine (3207,)
2021-02-01 11:01:23,015 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,016 INFO sqlalchemy.engine.base.Engine (3208,)
2021-02-01 11:01:23,018 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,021 INFO sqlalchemy.engine.base.Engine (3209,)
2021-02-01 11:01:23,026 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,027 INFO sqlalchemy.engine.base.Engine (3210,)
2021-02-01 11:01:23,030 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,031 INFO sqlalchemy.engine.base.Engine (3211,)
2021-02-01 11:01:23,033 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,034 INFO sqlalchemy.engine.base.Engine (3212,)
2021-02-01 11:01:23,036 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,038 INFO sqlalchemy.engine.base.Engine (3213,)
2021-02-01 11:01:23,040 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,042 INFO sqlalchemy.engine.base.Engine (3214,)
2021-02-01 11:01:23,044 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,047 INFO sqlalchemy.engine.base.Engine (3215,)
2021-02-01 11:01:23,051 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,053 INFO sqlalchemy.engine.base.Engine (3216,)
2021-02-01 11:01:23,056 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,057 INFO sqlalchemy.engine.base.Engine (3217,)
2021-02-01 11:01:23,060 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:23,062 INFO sqlalchemy.engine.base.Engine (3218,)
2021-02-01 11:01:23,064 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,065 INFO sqlalchemy.engine.base.Engine (3219,)
2021-02-01 11:01:23,069 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,070 INFO sqlalchemy.engine.base.Engine (3220,)
2021-02-01 11:01:23,072 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,074 INFO sqlalchemy.engine.base.Engine (3221,)
2021-02-01 11:01:23,076 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,078 INFO sqlalchemy.engine.base.Engine (3222,)
2021-02-01 11:01:23,080 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,082 INFO sqlalchemy.engine.base.Engine (3223,)
2021-02-01 11:01:23,085 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,086 INFO sqlalchemy.engine.base.Engine (3224,)
2021-02-01 11:01:23,089 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,090 INFO sqlalchemy.engine.base.Engine (3225,)
2021-02-01 11:01:23,097 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,098 INFO sqlalchemy.engine.base.Engine (3226,)
2021-02-01 11:01:23,100 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,102 INFO sqlalchemy.engine.base.Engine (3227,)
2021-02-01 11:01:23,104 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,105 INFO sqlalchemy.engine.base.Engine (3228,)
2021-02-01 11:01:23,107 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,108 INFO sqlalchemy.engine.base.Engine (3229,)
2021-02-01 11:01:23,111 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,111 INFO sqlalchemy.engine.base.Engine (3230,)
2021-02-01 11:01:23,114 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,116 INFO sqlalchemy.engine.base.Engine (3231,)
2021-02-01 11:01:23,119 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,119 INFO sqlalchemy.engine.base.Engine (3232,)
2021-02-01 11:01:23,124 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,125 INFO sqlalchemy.engine.base.Engine (3233,)
2021-02-01 11:01:23,128 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,129 INFO sqlalchemy.engine.base.Engine (3234,)
2021-02-01 11:01:23,132 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,133 INFO sqlalchemy.engine.base.Engine (3235,)
2021-02-01 11:01:23,135 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,136 INFO sqlalchemy.engine.base.Engine (3236,)
2021-02-01 11:01:23,138 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,139 INFO sqlalchemy.engine.base.Engine (3237,)
2021-02-01 11:01:23,141 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,142 INFO sqlalchemy.engine.base.Engine (3238,)
2021-02-01 11:01:23,149 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:23,152 INFO sqlalchemy.engine.base.Engine (3239,)
2021-02-01 11:01:23,157 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,159 INFO sqlalchemy.engine.base.Engine (3240,)
2021-02-01 11:01:23,161 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,162 INFO sqlalchemy.engine.base.Engine (3241,)
2021-02-01 11:01:23,165 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,166 INFO sqlalchemy.engine.base.Engine (3242,)
2021-02-01 11:01:23,168 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,169 INFO sqlalchemy.engine.base.Engine (3243,)
2021-02-01 11:01:23,172 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,173 INFO sqlalchemy.engine.base.Engine (3244,)
2021-02-01 11:01:23,176 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,177 INFO sqlalchemy.engine.base.Engine (3245,)
2021-02-01 11:01:23,180 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,182 INFO sqlalchemy.engine.base.Engine (3246,)
2021-02-01 11:01:23,184 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,187 INFO sqlalchemy.engine.base.Engine (3247,)
2021-02-01 11:01:23,190 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,191 INFO sqlalchemy.engine.base.Engine (3248,)
2021-02-01 11:01:23,193 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,196 INFO sqlalchemy.engine.base.Engine (3249,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:23,383 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:23,384 INFO sqlalchemy.engine.base.Engine ((3250, 14.3, 14.3, 14.3, 152889.81200002544, 122581.22613904813), (3251, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152889.81200002544, 122581.22613904813), (3252, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152889.81200002544, 122581.22613904813), (3253, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152889.81200002544, 122581.22613904813), (3254, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152889.81200002544, 122581.22613904813), (3255, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152889.81200002544, 122581.22613904813), (3256, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152889.81200002544, 122581.22613904813), (3257, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152889.81200002544, 122581.22613904813)  ... displaying 10 of 50 total bound parameter sets ...  (3298, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152889.81200002544, 122581.22613904813), (3299, 135.9, 135.9, 135.9, 152889.81200002544, 122581.22613904813))
2021-02-01 11:01:23,387 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:23,388 INFO sqlalchemy.engine.base.Engine ('F66',)
2021-02-01 11:01:23,394 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:23,401 INFO sqlalchemy.engine.base.Engine ((1625, 'F66', 0, 'Anhydrite', 3250, 3251), (1626, 'F66', 1, 'Sandstone, grey, vf-f', 3252, 3253), (1627, 'F66', 2, 'Anhydrite', 3254, 3255), (1628, 'F66', 3, 'Dolomite', 3256, 3257), (1629, 'F66', 4, 'Anhydrite', 3258, 3259), (1630, 'F66', 5, 'Sandstone, grey, vf-f', 3260, 3261), (1631, 'F66', 6, 'Siltstone, red', 3262, 3263), (1632, 'F66', 7, 'Dolomite', 3264, 3265)  ... displaying 10 of 25 total bound parameter sets ...  (1648, 'F66', 23, 'Limestone', 3296, 3297), (1649, 'F66', 24, 'Volcanic', 3298, 3299))
2021-02-01 11:01:23,404 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:23,520 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:23,522 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:23,523 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:23,527 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:23,529 INFO sqlalchemy.engine.base.Engine ('F66',)
2021-02-01 11:01:23,534 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,536 INFO sqlalchemy.engine.base.Engine (3250,)
2021-02-01 11:01:23,538 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,539 INFO sqlalchemy.engine.base.Engine (3251,)
2021-02-01 11:01:23,541 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,542 INFO sqlalchemy.engine.base.Engine (3252,)

2021-02-01 11:01:23,545 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,545 INFO sqlalchemy.engine.base.Engine (3253,)
2021-02-01 11:01:23,549 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,550 INFO sqlalchemy.engine.base.Engine (3254,)
2021-02-01 11:01:23,553 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,554 INFO sqlalchemy.engine.base.Engine (3255,)
2021-02-01 11:01:23,556 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,557 INFO sqlalchemy.engine.base.Engine (3256,)
2021-02-01 11:01:23,559 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,560 INFO sqlalchemy.engine.base.Engine (3257,)
2021-02-01 11:01:23,564 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,567 INFO sqlalchemy.engine.base.Engine (3258,)
2021-02-01 11:01:23,571 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,572 INFO sqlalchemy.engine.base.Engine (3259,)
2021-02-01 11:01:23,574 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,575 INFO sqlalchemy.engine.base.Engine (3260,)
2021-02-01 11:01:23,577 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,578 INFO sqlalchemy.engine.base.Engine (3261,)
2021-02-01 11:01:23,579 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,580 INFO sqlalchemy.engine.base.Engine (3262,)
2021-02-01 11:01:23,582 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,583 INFO sqlalchemy.engine.base.Engine (3263,)
2021-02-01 11:01:23,586 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,587 INFO sqlalchemy.engine.base.Engine (3264,)
2021-02-01 11:01:23,588 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,589 INFO sqlalchemy.engine.base.Engine (3265,)
2021-02-01 11:01:23,593 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,594 INFO sqlalchemy.engine.base.Engine (3266,)
2021-02-01 11:01:23,600 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,601 INFO sqlalchemy.engine.base.Engine (3267,)
2021-02-01 11:01:23,603 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,604 INFO sqlalchemy.engine.base.Engine (3268,)
2021-02-01 11:01:23,607 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,608 INFO sqlalchemy.engine.base.Engine (3269,)
2021-02-01 11:01:23,610 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,611 INFO sqlalchemy.engine.base.Engine (3270,)
2021-02-01 11:01:23,613 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,615 INFO sqlalchemy.engine.base.Engine (3271,)
2021-02-01 11:01:23,616 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,617 INFO sqlalchemy.engine.base.Engine (3272,)
2021-02-01 11:01:23,620 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:23,621 INFO sqlalchemy.engine.base.Engine (3273,)
2021-02-01 11:01:23,623 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,625 INFO sqlalchemy.engine.base.Engine (3274,)
2021-02-01 11:01:23,629 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,630 INFO sqlalchemy.engine.base.Engine (3275,)
2021-02-01 11:01:23,635 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,636 INFO sqlalchemy.engine.base.Engine (3276,)
2021-02-01 11:01:23,638 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,639 INFO sqlalchemy.engine.base.Engine (3277,)
2021-02-01 11:01:23,641 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,642 INFO sqlalchemy.engine.base.Engine (3278,)
2021-02-01 11:01:23,644 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,646 INFO sqlalchemy.engine.base.Engine (3279,)
2021-02-01 11:01:23,649 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,650 INFO sqlalchemy.engine.base.Engine (3280,)
2021-02-01 11:01:23,653 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,654 INFO sqlalchemy.engine.base.Engine (3281,)
2021-02-01 11:01:23,656 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,657 INFO sqlalchemy.engine.base.Engine (3282,)
2021-02-01 11:01:23,659 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,660 INFO sqlalchemy.engine.base.Engine (3283,)
2021-02-01 11:01:23,663 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,664 INFO sqlalchemy.engine.base.Engine (3284,)
2021-02-01 11:01:23,666 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,667 INFO sqlalchemy.engine.base.Engine (3285,)
2021-02-01 11:01:23,673 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,674 INFO sqlalchemy.engine.base.Engine (3286,)
2021-02-01 11:01:23,676 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,677 INFO sqlalchemy.engine.base.Engine (3287,)
2021-02-01 11:01:23,680 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,682 INFO sqlalchemy.engine.base.Engine (3288,)
2021-02-01 11:01:23,685 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,686 INFO sqlalchemy.engine.base.Engine (3289,)
2021-02-01 11:01:23,689 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,691 INFO sqlalchemy.engine.base.Engine (3290,)
2021-02-01 11:01:23,694 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,696 INFO sqlalchemy.engine.base.Engine (3291,)
2021-02-01 11:01:23,699 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,700 INFO sqlalchemy.engine.base.Engine (3292,)
2021-02-01 11:01:23,703 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,706 INFO sqlalchemy.engine.base.Engine (3293,)
2021-02-01 11:01:23,709 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:23,710 INFO sqlalchemy.engine.base.Engine (3294,)
2021-02-01 11:01:23,712 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,714 INFO sqlalchemy.engine.base.Engine (3295,)
2021-02-01 11:01:23,719 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,721 INFO sqlalchemy.engine.base.Engine (3296,)
2021-02-01 11:01:23,724 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,725 INFO sqlalchemy.engine.base.Engine (3297,)
2021-02-01 11:01:23,727 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,729 INFO sqlalchemy.engine.base.Engine (3298,)
2021-02-01 11:01:23,731 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:23,732 INFO sqlalchemy.engine.base.Engine (3299,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:23,911 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:23,917 INFO sqlalchemy.engine.base.Engine ((3300, 14.3, 14.3, 14.3, 152887.3020000254, 122579.5511390455), (3301, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152887.3020000254, 122579.5511390455), (3302, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152887.3020000254, 122579.5511390455), (3303, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152887.3020000254, 122579.5511390455), (3304, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152887.3020000254, 122579.5511390455), (3305, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152887.3020000254, 122579.5511390455), (3306, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152887.3020000254, 122579.5511390455), (3307, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152887.3020000254, 122579.5511390455)  ... displaying 10 of 50 total bound parameter sets ...  (3348, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152887.3020000254, 122579.5511390455), (3349, 135.9, 135.9, 135.9, 152887.3020000254, 122579.5511390455))
2021-02-01 11:01:23,920 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:23,921 INFO sqlalchemy.engine.base.Engine ('F67',)
2021-02-01 11:01:23,928 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:23,930 INFO sqlalchemy.engine.base.Engine ((1650, 'F67', 0, 'Anhydrite', 3300, 3301), (1651, 'F67', 1, 'Sandstone, grey, vf-f', 3302, 3303), (1652, 'F67', 2, 'Anhydrite', 3304, 3305), (1653, 'F67', 3, 'Dolomite', 3306, 3307), (1654, 'F67', 4, 'Anhydrite', 3308, 3309), (1655, 'F67', 5, 'Sandstone, grey, vf-f', 3310, 3311), (1656, 'F67', 6, 'Siltstone, red', 3312, 3313), (1657, 'F67', 7, 'Dolomite', 3314, 3315)  ... displaying 10 of 25 total bound parameter sets ...  (1673, 'F67', 23, 'Limestone', 3346, 3347), (1674, 'F67', 24, 'Volcanic', 3348, 3349))
2021-02-01 11:01:23,934 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:24,124 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:24,125 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:24,127 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:24,130 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:24,132 INFO sqlalchemy.engine.base.Engine ('F67',)
2021-02-01 11:01:24,136 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,137 INFO sqlalchemy.engine.base.Engine (3300,)
2021-02-01 11:01:24,140 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,141 INFO sqlalchemy.engine.base.Engine (3301,)
2021-02-01 11:01:24,143 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,144 INFO sqlalchemy.engine.base.Engine (3302,)
2021-02-01 11:01:24,147 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,149 INFO sqlalchemy.engine.base.Engine (3303,)
2021-02-01 11:01:24,154 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,155 INFO sqlalchemy.engine.base.Engine (3304,)
2021-02-01 11:01:24,158 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,159 INFO sqlalchemy.engine.base.Engine (3305,)
2021-02-01 11:01:24,162 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,164 INFO sqlalchemy.engine.base.Engine (3306,)
2021-02-01 11:01:24,167 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,168 INFO sqlalchemy.engine.base.Engine (3307,)

2021-02-01 11:01:24,170 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,171 INFO sqlalchemy.engine.base.Engine (3308,)
2021-02-01 11:01:24,174 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,175 INFO sqlalchemy.engine.base.Engine (3309,)
2021-02-01 11:01:24,178 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,179 INFO sqlalchemy.engine.base.Engine (3310,)
2021-02-01 11:01:24,184 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,186 INFO sqlalchemy.engine.base.Engine (3311,)
2021-02-01 11:01:24,188 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,190 INFO sqlalchemy.engine.base.Engine (3312,)
2021-02-01 11:01:24,192 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,193 INFO sqlalchemy.engine.base.Engine (3313,)
2021-02-01 11:01:24,196 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,197 INFO sqlalchemy.engine.base.Engine (3314,)
2021-02-01 11:01:24,200 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,202 INFO sqlalchemy.engine.base.Engine (3315,)
2021-02-01 11:01:24,205 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,206 INFO sqlalchemy.engine.base.Engine (3316,)
2021-02-01 11:01:24,213 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,214 INFO sqlalchemy.engine.base.Engine (3317,)
2021-02-01 11:01:24,217 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,218 INFO sqlalchemy.engine.base.Engine (3318,)
2021-02-01 11:01:24,221 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,224 INFO sqlalchemy.engine.base.Engine (3319,)
2021-02-01 11:01:24,228 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,229 INFO sqlalchemy.engine.base.Engine (3320,)
2021-02-01 11:01:24,231 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,233 INFO sqlalchemy.engine.base.Engine (3321,)
2021-02-01 11:01:24,239 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,240 INFO sqlalchemy.engine.base.Engine (3322,)
2021-02-01 11:01:24,243 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,246 INFO sqlalchemy.engine.base.Engine (3323,)
2021-02-01 11:01:24,249 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,251 INFO sqlalchemy.engine.base.Engine (3324,)
2021-02-01 11:01:24,253 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,255 INFO sqlalchemy.engine.base.Engine (3325,)
2021-02-01 11:01:24,258 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,259 INFO sqlalchemy.engine.base.Engine (3326,)
2021-02-01 11:01:24,262 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,263 INFO sqlalchemy.engine.base.Engine (3327,)
2021-02-01 11:01:24,265 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:24,267 INFO sqlalchemy.engine.base.Engine (3328,)
2021-02-01 11:01:24,269 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,270 INFO sqlalchemy.engine.base.Engine (3329,)
2021-02-01 11:01:24,273 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,274 INFO sqlalchemy.engine.base.Engine (3330,)
2021-02-01 11:01:24,277 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,277 INFO sqlalchemy.engine.base.Engine (3331,)
2021-02-01 11:01:24,283 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,284 INFO sqlalchemy.engine.base.Engine (3332,)
2021-02-01 11:01:24,287 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,289 INFO sqlalchemy.engine.base.Engine (3333,)
2021-02-01 11:01:24,291 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,293 INFO sqlalchemy.engine.base.Engine (3334,)
2021-02-01 11:01:24,296 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,297 INFO sqlalchemy.engine.base.Engine (3335,)
2021-02-01 11:01:24,301 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,304 INFO sqlalchemy.engine.base.Engine (3336,)
2021-02-01 11:01:24,307 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,307 INFO sqlalchemy.engine.base.Engine (3337,)
2021-02-01 11:01:24,310 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,311 INFO sqlalchemy.engine.base.Engine (3338,)
2021-02-01 11:01:24,314 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,316 INFO sqlalchemy.engine.base.Engine (3339,)
2021-02-01 11:01:24,318 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,319 INFO sqlalchemy.engine.base.Engine (3340,)
2021-02-01 11:01:24,322 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,323 INFO sqlalchemy.engine.base.Engine (3341,)
2021-02-01 11:01:24,326 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,327 INFO sqlalchemy.engine.base.Engine (3342,)
2021-02-01 11:01:24,329 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,331 INFO sqlalchemy.engine.base.Engine (3343,)
2021-02-01 11:01:24,333 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,335 INFO sqlalchemy.engine.base.Engine (3344,)
2021-02-01 11:01:24,337 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,338 INFO sqlalchemy.engine.base.Engine (3345,)
2021-02-01 11:01:24,341 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,343 INFO sqlalchemy.engine.base.Engine (3346,)
2021-02-01 11:01:24,345 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,347 INFO sqlalchemy.engine.base.Engine (3347,)
2021-02-01 11:01:24,350 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,351 INFO sqlalchemy.engine.base.Engine (3348,)
2021-02-01 11:01:24,355 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"

WHERE "Positions".id = ?
2021-02-01 11:01:24,359 INFO sqlalchemy.engine.base.Engine (3349,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:24,497 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:24,502 INFO sqlalchemy.engine.base.Engine ((3350, 14.3, 14.3, 14.3, 152884.5820000254, 122580.77813904732), (3351, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152884.5820000254, 122580.77813904732), (3352, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152884.5820000254, 122580.77813904732), (3353, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152884.5820000254, 122580.77813904732), (3354, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152884.5820000254, 122580.77813904732), (3355, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152884.5820000254, 122580.77813904732), (3356, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152884.5820000254, 122580.77813904732), (3357, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152884.5820000254, 122580.77813904732)  ... displaying 10 of 50 total bound parameter sets ...  (3398, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152884.5820000254, 122580.77813904732), (3399, 135.9, 135.9, 135.9, 152884.5820000254, 122580.77813904732))
2021-02-01 11:01:24,504 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:24,505 INFO sqlalchemy.engine.base.Engine ('F68',)
2021-02-01 11:01:24,509 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:24,515 INFO sqlalchemy.engine.base.Engine ((1675, 'F68', 0, 'Anhydrite', 3350, 3351), (1676, 'F68', 1, 'Sandstone, grey, vf-f', 3352, 3353), (1677, 'F68', 2, 'Anhydrite', 3354, 3355), (1678, 'F68', 3, 'Dolomite', 3356, 3357), (1679, 'F68', 4, 'Anhydrite', 3358, 3359), (1680, 'F68', 5, 'Sandstone, grey, vf-f', 3360, 3361), (1681, 'F68', 6, 'Siltstone, red', 3362, 3363), (1682, 'F68', 7, 'Dolomite', 3364, 3365)  ... displaying 10 of 25 total bound parameter sets ...  (1698, 'F68', 23, 'Limestone', 3396, 3397), (1699, 'F68', 24, 'Volcanic', 3398, 3399))
2021-02-01 11:01:24,518 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:24,819 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:24,820 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:24,822 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:24,825 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:24,827 INFO sqlalchemy.engine.base.Engine ('F68',)
2021-02-01 11:01:24,829 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,830 INFO sqlalchemy.engine.base.Engine (3350,)
2021-02-01 11:01:24,833 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,834 INFO sqlalchemy.engine.base.Engine (3351,)
2021-02-01 11:01:24,838 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,839 INFO sqlalchemy.engine.base.Engine (3352,)
2021-02-01 11:01:24,841 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,844 INFO sqlalchemy.engine.base.Engine (3353,)
2021-02-01 11:01:24,847 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,848 INFO sqlalchemy.engine.base.Engine (3354,)
2021-02-01 11:01:24,851 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,852 INFO sqlalchemy.engine.base.Engine (3355,)
2021-02-01 11:01:24,854 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,856 INFO sqlalchemy.engine.base.Engine (3356,)
2021-02-01 11:01:24,859 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,860 INFO sqlalchemy.engine.base.Engine (3357,)
2021-02-01 11:01:24,862 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,863 INFO sqlalchemy.engine.base.Engine (3358,)
2021-02-01 11:01:24,869 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,871 INFO sqlalchemy.engine.base.Engine (3359,)
2021-02-01 11:01:24,873 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,874 INFO sqlalchemy.engine.base.Engine (3360,)
2021-02-01 11:01:24,876 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,877 INFO sqlalchemy.engine.base.Engine (3361,)
2021-02-01 11:01:24,881 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:24,882 INFO sqlalchemy.engine.base.Engine (3362,)
2021-02-01 11:01:24,884 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,885 INFO sqlalchemy.engine.base.Engine (3363,)
2021-02-01 11:01:24,891 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,893 INFO sqlalchemy.engine.base.Engine (3364,)
2021-02-01 11:01:24,895 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,896 INFO sqlalchemy.engine.base.Engine (3365,)
2021-02-01 11:01:24,899 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,901 INFO sqlalchemy.engine.base.Engine (3366,)
2021-02-01 11:01:24,902 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,903 INFO sqlalchemy.engine.base.Engine (3367,)
2021-02-01 11:01:24,907 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,908 INFO sqlalchemy.engine.base.Engine (3368,)
2021-02-01 11:01:24,911 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,912 INFO sqlalchemy.engine.base.Engine (3369,)
2021-02-01 11:01:24,915 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,916 INFO sqlalchemy.engine.base.Engine (3370,)
2021-02-01 11:01:24,919 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,920 INFO sqlalchemy.engine.base.Engine (3371,)
2021-02-01 11:01:24,923 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,924 INFO sqlalchemy.engine.base.Engine (3372,)
2021-02-01 11:01:24,927 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,928 INFO sqlalchemy.engine.base.Engine (3373,)
2021-02-01 11:01:24,931 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,933 INFO sqlalchemy.engine.base.Engine (3374,)
2021-02-01 11:01:24,934 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,937 INFO sqlalchemy.engine.base.Engine (3375,)
2021-02-01 11:01:24,940 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,941 INFO sqlalchemy.engine.base.Engine (3376,)
2021-02-01 11:01:24,944 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,945 INFO sqlalchemy.engine.base.Engine (3377,)
2021-02-01 11:01:24,948 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,949 INFO sqlalchemy.engine.base.Engine (3378,)
2021-02-01 11:01:24,951 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,953 INFO sqlalchemy.engine.base.Engine (3379,)
2021-02-01 11:01:24,955 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,956 INFO sqlalchemy.engine.base.Engine (3380,)
2021-02-01 11:01:24,958 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,960 INFO sqlalchemy.engine.base.Engine (3381,)
2021-02-01 11:01:24,963 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,964 INFO sqlalchemy.engine.base.Engine (3382,)
2021-02-01 11:01:24,967 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:24,968 INFO sqlalchemy.engine.base.Engine (3383,)
2021-02-01 11:01:24,971 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,974 INFO sqlalchemy.engine.base.Engine (3384,)
2021-02-01 11:01:24,977 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,978 INFO sqlalchemy.engine.base.Engine (3385,)
2021-02-01 11:01:24,981 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,982 INFO sqlalchemy.engine.base.Engine (3386,)
2021-02-01 11:01:24,985 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,986 INFO sqlalchemy.engine.base.Engine (3387,)
2021-02-01 11:01:24,988 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,991 INFO sqlalchemy.engine.base.Engine (3388,)
2021-02-01 11:01:24,993 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,994 INFO sqlalchemy.engine.base.Engine (3389,)
2021-02-01 11:01:24,996 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:24,999 INFO sqlalchemy.engine.base.Engine (3390,)
2021-02-01 11:01:25,001 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,002 INFO sqlalchemy.engine.base.Engine (3391,)
2021-02-01 11:01:25,006 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,007 INFO sqlalchemy.engine.base.Engine (3392,)
2021-02-01 11:01:25,010 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,014 INFO sqlalchemy.engine.base.Engine (3393,)
2021-02-01 11:01:25,016 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,017 INFO sqlalchemy.engine.base.Engine (3394,)
2021-02-01 11:01:25,020 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,020 INFO sqlalchemy.engine.base.Engine (3395,)
2021-02-01 11:01:25,023 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,024 INFO sqlalchemy.engine.base.Engine (3396,)
2021-02-01 11:01:25,026 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,027 INFO sqlalchemy.engine.base.Engine (3397,)
2021-02-01 11:01:25,029 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,030 INFO sqlalchemy.engine.base.Engine (3398,)
2021-02-01 11:01:25,032 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,033 INFO sqlalchemy.engine.base.Engine (3399,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:25,186 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:25,187 INFO sqlalchemy.engine.base.Engine ('F69',)
2021-02-01 11:01:25,190 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:25,191 INFO sqlalchemy.engine.base.Engine ((3400, 14.3, 14.3, 14.3, 152884.69700002536, 122577.76113904732), (3401, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152884.69700002536, 122577.76113904732), (3402, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152884.69700002536, 122577.76113904732), (3403, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152884.69700002536, 122577.76113904732), (3404, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152884.69700002536, 122577.76113904732), (3405, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152884.69700002536, 122577.76113904732), (3406, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152884.69700002536, 122577.76113904732), (3407, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152884.69700002536, 122577.76113904732)  ... displaying 10 of 50 total bound parameter sets ...  (3448, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152884.69700002536, 122577.76113904732), (3449, 135.9, 135.9, 135.9, 152884.69700002536, 122577.76113904732))
2021-02-01 11:01:25,196 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:25,199 INFO sqlalchemy.engine.base.Engine ((1700, 'F69', 0, 'Anhydrite', 3400, 3401), (1701, 'F69', 1, 'Sandstone, grey, vf-f', 3402, 3403), (1702, 'F69', 2, 'Anhydrite', 3404, 3405), (1703, 'F69', 3, 'Dolomite', 3406, 3407), (1704, 'F69', 4, 'Anhydrite', 3408, 3409), (1705, 'F69', 5, 'Sandstone, grey, vf-f', 3410, 3411), (1706, 'F69', 6, 'Siltstone, red', 3412, 3413), (1707, 'F69', 7, 'Dolomite', 3414, 3415)  ... displaying 10 of 25 total bound parameter sets ...  (1723, 'F69', 23, 'Limestone', 3446, 3447), (1724, 'F69', 24, 'Volcanic', 3448, 3449))

2021-02-01 11:01:25,204 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:25,420 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:25,422 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:25,423 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:25,427 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:25,428 INFO sqlalchemy.engine.base.Engine ('F69',)
2021-02-01 11:01:25,433 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,434 INFO sqlalchemy.engine.base.Engine (3400,)
2021-02-01 11:01:25,440 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,443 INFO sqlalchemy.engine.base.Engine (3401,)
2021-02-01 11:01:25,446 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,447 INFO sqlalchemy.engine.base.Engine (3402,)
2021-02-01 11:01:25,450 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,451 INFO sqlalchemy.engine.base.Engine (3403,)
2021-02-01 11:01:25,453 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,455 INFO sqlalchemy.engine.base.Engine (3404,)
2021-02-01 11:01:25,457 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,458 INFO sqlalchemy.engine.base.Engine (3405,)
2021-02-01 11:01:25,461 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,462 INFO sqlalchemy.engine.base.Engine (3406,)
2021-02-01 11:01:25,464 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,466 INFO sqlalchemy.engine.base.Engine (3407,)
2021-02-01 11:01:25,468 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,470 INFO sqlalchemy.engine.base.Engine (3408,)
2021-02-01 11:01:25,474 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,475 INFO sqlalchemy.engine.base.Engine (3409,)
2021-02-01 11:01:25,477 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,479 INFO sqlalchemy.engine.base.Engine (3410,)
2021-02-01 11:01:25,482 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,483 INFO sqlalchemy.engine.base.Engine (3411,)
2021-02-01 11:01:25,487 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,489 INFO sqlalchemy.engine.base.Engine (3412,)
2021-02-01 11:01:25,492 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,493 INFO sqlalchemy.engine.base.Engine (3413,)
2021-02-01 11:01:25,496 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,497 INFO sqlalchemy.engine.base.Engine (3414,)
2021-02-01 11:01:25,500 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,501 INFO sqlalchemy.engine.base.Engine (3415,)
2021-02-01 11:01:25,507 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,508 INFO sqlalchemy.engine.base.Engine (3416,)
2021-02-01 11:01:25,510 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,511 INFO sqlalchemy.engine.base.Engine (3417,)
2021-02-01 11:01:25,514 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:25,515 INFO sqlalchemy.engine.base.Engine (3418,)
2021-02-01 11:01:25,518 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,519 INFO sqlalchemy.engine.base.Engine (3419,)
2021-02-01 11:01:25,522 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,523 INFO sqlalchemy.engine.base.Engine (3420,)
2021-02-01 11:01:25,525 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,526 INFO sqlalchemy.engine.base.Engine (3421,)
2021-02-01 11:01:25,529 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,531 INFO sqlalchemy.engine.base.Engine (3422,)
2021-02-01 11:01:25,535 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,535 INFO sqlalchemy.engine.base.Engine (3423,)
2021-02-01 11:01:25,538 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,540 INFO sqlalchemy.engine.base.Engine (3424,)
2021-02-01 11:01:25,542 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,546 INFO sqlalchemy.engine.base.Engine (3425,)
2021-02-01 11:01:25,549 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,550 INFO sqlalchemy.engine.base.Engine (3426,)
2021-02-01 11:01:25,552 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,553 INFO sqlalchemy.engine.base.Engine (3427,)
2021-02-01 11:01:25,556 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,557 INFO sqlalchemy.engine.base.Engine (3428,)
2021-02-01 11:01:25,559 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,560 INFO sqlalchemy.engine.base.Engine (3429,)
2021-02-01 11:01:25,564 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,565 INFO sqlalchemy.engine.base.Engine (3430,)
2021-02-01 11:01:25,568 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,569 INFO sqlalchemy.engine.base.Engine (3431,)
2021-02-01 11:01:25,572 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,573 INFO sqlalchemy.engine.base.Engine (3432,)
2021-02-01 11:01:25,575 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,576 INFO sqlalchemy.engine.base.Engine (3433,)
2021-02-01 11:01:25,579 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,581 INFO sqlalchemy.engine.base.Engine (3434,)
2021-02-01 11:01:25,583 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,585 INFO sqlalchemy.engine.base.Engine (3435,)
2021-02-01 11:01:25,588 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,589 INFO sqlalchemy.engine.base.Engine (3436,)
2021-02-01 11:01:25,591 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,592 INFO sqlalchemy.engine.base.Engine (3437,)
2021-02-01 11:01:25,596 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,599 INFO sqlalchemy.engine.base.Engine (3438,)
2021-02-01 11:01:25,601 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:25,602 INFO sqlalchemy.engine.base.Engine (3439,)
2021-02-01 11:01:25,607 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,609 INFO sqlalchemy.engine.base.Engine (3440,)
2021-02-01 11:01:25,613 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,614 INFO sqlalchemy.engine.base.Engine (3441,)
2021-02-01 11:01:25,617 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,618 INFO sqlalchemy.engine.base.Engine (3442,)
2021-02-01 11:01:25,620 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,621 INFO sqlalchemy.engine.base.Engine (3443,)
2021-02-01 11:01:25,624 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,625 INFO sqlalchemy.engine.base.Engine (3444,)
2021-02-01 11:01:25,630 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,631 INFO sqlalchemy.engine.base.Engine (3445,)
2021-02-01 11:01:25,634 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,635 INFO sqlalchemy.engine.base.Engine (3446,)
2021-02-01 11:01:25,638 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,639 INFO sqlalchemy.engine.base.Engine (3447,)
2021-02-01 11:01:25,642 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,643 INFO sqlalchemy.engine.base.Engine (3448,)
2021-02-01 11:01:25,645 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:25,646 INFO sqlalchemy.engine.base.Engine (3449,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:25,801 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:25,805 INFO sqlalchemy.engine.base.Engine ((3450, 14.3, 14.3, 14.3, 152887.41200002545, 122576.40913904553), (3451, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152887.41200002545, 122576.40913904553), (3452, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152887.41200002545, 122576.40913904553), (3453, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152887.41200002545, 122576.40913904553), (3454, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152887.41200002545, 122576.40913904553), (3455, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152887.41200002545, 122576.40913904553), (3456, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152887.41200002545, 122576.40913904553), (3457, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152887.41200002545, 122576.40913904553)  ... displaying 10 of 50 total bound parameter sets ...  (3498, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152887.41200002545, 122576.40913904553), (3499, 135.9, 135.9, 135.9, 152887.41200002545, 122576.40913904553))
2021-02-01 11:01:25,810 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:25,811 INFO sqlalchemy.engine.base.Engine ('F70',)
2021-02-01 11:01:25,822 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:25,825 INFO sqlalchemy.engine.base.Engine ((1725, 'F70', 0, 'Anhydrite', 3450, 3451), (1726, 'F70', 1, 'Sandstone, grey, vf-f', 3452, 3453), (1727, 'F70', 2, 'Anhydrite', 3454, 3455), (1728, 'F70', 3, 'Dolomite', 3456, 3457), (1729, 'F70', 4, 'Anhydrite', 3458, 3459), (1730, 'F70', 5, 'Sandstone, grey, vf-f', 3460, 3461), (1731, 'F70', 6, 'Siltstone, red', 3462, 3463), (1732, 'F70', 7, 'Dolomite', 3464, 3465)  ... displaying 10 of 25 total bound parameter sets ...  (1748, 'F70', 23, 'Limestone', 3496, 3497), (1749, 'F70', 24, 'Volcanic', 3498, 3499))
2021-02-01 11:01:25,835 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:26,175 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:26,177 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:26,178 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:26,181 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:26,182 INFO sqlalchemy.engine.base.Engine ('F70',)
2021-02-01 11:01:26,185 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,186 INFO sqlalchemy.engine.base.Engine (3450,)
2021-02-01 11:01:26,188 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,189 INFO sqlalchemy.engine.base.Engine (3451,)
2021-02-01 11:01:26,192 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,192 INFO sqlalchemy.engine.base.Engine (3452,)

2021-02-01 11:01:26,198 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,199 INFO sqlalchemy.engine.base.Engine (3453,)
2021-02-01 11:01:26,202 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,206 INFO sqlalchemy.engine.base.Engine (3454,)
2021-02-01 11:01:26,211 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,212 INFO sqlalchemy.engine.base.Engine (3455,)
2021-02-01 11:01:26,214 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,215 INFO sqlalchemy.engine.base.Engine (3456,)
2021-02-01 11:01:26,217 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,218 INFO sqlalchemy.engine.base.Engine (3457,)
2021-02-01 11:01:26,220 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,220 INFO sqlalchemy.engine.base.Engine (3458,)
2021-02-01 11:01:26,222 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,223 INFO sqlalchemy.engine.base.Engine (3459,)
2021-02-01 11:01:26,226 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,227 INFO sqlalchemy.engine.base.Engine (3460,)
2021-02-01 11:01:26,229 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,230 INFO sqlalchemy.engine.base.Engine (3461,)
2021-02-01 11:01:26,233 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,236 INFO sqlalchemy.engine.base.Engine (3462,)
2021-02-01 11:01:26,239 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,240 INFO sqlalchemy.engine.base.Engine (3463,)
2021-02-01 11:01:26,242 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,244 INFO sqlalchemy.engine.base.Engine (3464,)
2021-02-01 11:01:26,246 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,250 INFO sqlalchemy.engine.base.Engine (3465,)
2021-02-01 11:01:26,254 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,255 INFO sqlalchemy.engine.base.Engine (3466,)
2021-02-01 11:01:26,258 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,259 INFO sqlalchemy.engine.base.Engine (3467,)
2021-02-01 11:01:26,262 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,263 INFO sqlalchemy.engine.base.Engine (3468,)
2021-02-01 11:01:26,265 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,266 INFO sqlalchemy.engine.base.Engine (3469,)
2021-02-01 11:01:26,270 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,270 INFO sqlalchemy.engine.base.Engine (3470,)
2021-02-01 11:01:26,272 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,273 INFO sqlalchemy.engine.base.Engine (3471,)
2021-02-01 11:01:26,276 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,279 INFO sqlalchemy.engine.base.Engine (3472,)
2021-02-01 11:01:26,281 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:26,283 INFO sqlalchemy.engine.base.Engine (3473,)
2021-02-01 11:01:26,285 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,287 INFO sqlalchemy.engine.base.Engine (3474,)
2021-02-01 11:01:26,289 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,291 INFO sqlalchemy.engine.base.Engine (3475,)
2021-02-01 11:01:26,296 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,297 INFO sqlalchemy.engine.base.Engine (3476,)
2021-02-01 11:01:26,300 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,301 INFO sqlalchemy.engine.base.Engine (3477,)
2021-02-01 11:01:26,303 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,305 INFO sqlalchemy.engine.base.Engine (3478,)
2021-02-01 11:01:26,307 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,308 INFO sqlalchemy.engine.base.Engine (3479,)
2021-02-01 11:01:26,311 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,312 INFO sqlalchemy.engine.base.Engine (3480,)
2021-02-01 11:01:26,314 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,316 INFO sqlalchemy.engine.base.Engine (3481,)
2021-02-01 11:01:26,318 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,320 INFO sqlalchemy.engine.base.Engine (3482,)
2021-02-01 11:01:26,323 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,324 INFO sqlalchemy.engine.base.Engine (3483,)
2021-02-01 11:01:26,332 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,334 INFO sqlalchemy.engine.base.Engine (3484,)
2021-02-01 11:01:26,337 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,338 INFO sqlalchemy.engine.base.Engine (3485,)
2021-02-01 11:01:26,340 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,342 INFO sqlalchemy.engine.base.Engine (3486,)
2021-02-01 11:01:26,344 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,345 INFO sqlalchemy.engine.base.Engine (3487,)
2021-02-01 11:01:26,348 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,349 INFO sqlalchemy.engine.base.Engine (3488,)
2021-02-01 11:01:26,352 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,353 INFO sqlalchemy.engine.base.Engine (3489,)
2021-02-01 11:01:26,355 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,357 INFO sqlalchemy.engine.base.Engine (3490,)
2021-02-01 11:01:26,360 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,361 INFO sqlalchemy.engine.base.Engine (3491,)
2021-02-01 11:01:26,364 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,365 INFO sqlalchemy.engine.base.Engine (3492,)
2021-02-01 11:01:26,371 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,372 INFO sqlalchemy.engine.base.Engine (3493,)
2021-02-01 11:01:26,374 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:26,375 INFO sqlalchemy.engine.base.Engine (3494,)
2021-02-01 11:01:26,378 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,380 INFO sqlalchemy.engine.base.Engine (3495,)
2021-02-01 11:01:26,383 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,385 INFO sqlalchemy.engine.base.Engine (3496,)
2021-02-01 11:01:26,387 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,389 INFO sqlalchemy.engine.base.Engine (3497,)
2021-02-01 11:01:26,391 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,392 INFO sqlalchemy.engine.base.Engine (3498,)
2021-02-01 11:01:26,395 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:26,396 INFO sqlalchemy.engine.base.Engine (3499,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:26,572 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:26,575 INFO sqlalchemy.engine.base.Engine ('F71',)
2021-02-01 11:01:26,583 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:26,594 INFO sqlalchemy.engine.base.Engine ((3500, 14.3, 14.3, 14.3, 152885.5410000254, 122579.35213904643), (3501, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152885.5410000254, 122579.35213904643), (3502, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152885.5410000254, 122579.35213904643), (3503, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152885.5410000254, 122579.35213904643), (3504, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152885.5410000254, 122579.35213904643), (3505, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152885.5410000254, 122579.35213904643), (3506, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152885.5410000254, 122579.35213904643), (3507, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152885.5410000254, 122579.35213904643)  ... displaying 10 of 50 total bound parameter sets ...  (3548, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152885.5410000254, 122579.35213904643), (3549, 135.9, 135.9, 135.9, 152885.5410000254, 122579.35213904643))
2021-02-01 11:01:26,601 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:26,604 INFO sqlalchemy.engine.base.Engine ((1750, 'F71', 0, 'Anhydrite', 3500, 3501), (1751, 'F71', 1, 'Sandstone, grey, vf-f', 3502, 3503), (1752, 'F71', 2, 'Anhydrite', 3504, 3505), (1753, 'F71', 3, 'Dolomite', 3506, 3507), (1754, 'F71', 4, 'Anhydrite', 3508, 3509), (1755, 'F71', 5, 'Sandstone, grey, vf-f', 3510, 3511), (1756, 'F71', 6, 'Siltstone, red', 3512, 3513), (1757, 'F71', 7, 'Dolomite', 3514, 3515)  ... displaying 10 of 25 total bound parameter sets ...  (1773, 'F71', 23, 'Limestone', 3546, 3547), (1774, 'F71', 24, 'Volcanic', 3548, 3549))
2021-02-01 11:01:26,610 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:27,054 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:27,056 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:27,057 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:27,062 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:27,064 INFO sqlalchemy.engine.base.Engine ('F71',)
2021-02-01 11:01:27,067 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,069 INFO sqlalchemy.engine.base.Engine (3500,)
2021-02-01 11:01:27,071 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,072 INFO sqlalchemy.engine.base.Engine (3501,)
2021-02-01 11:01:27,074 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,075 INFO sqlalchemy.engine.base.Engine (3502,)
2021-02-01 11:01:27,077 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,078 INFO sqlalchemy.engine.base.Engine (3503,)
2021-02-01 11:01:27,081 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,082 INFO sqlalchemy.engine.base.Engine (3504,)
2021-02-01 11:01:27,085 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,086 INFO sqlalchemy.engine.base.Engine (3505,)
2021-02-01 11:01:27,088 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,090 INFO sqlalchemy.engine.base.Engine (3506,)
2021-02-01 11:01:27,092 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,093 INFO sqlalchemy.engine.base.Engine (3507,)

2021-02-01 11:01:27,096 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,099 INFO sqlalchemy.engine.base.Engine (3508,)
2021-02-01 11:01:27,102 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,103 INFO sqlalchemy.engine.base.Engine (3509,)
2021-02-01 11:01:27,105 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,107 INFO sqlalchemy.engine.base.Engine (3510,)
2021-02-01 11:01:27,112 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,113 INFO sqlalchemy.engine.base.Engine (3511,)
2021-02-01 11:01:27,117 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,119 INFO sqlalchemy.engine.base.Engine (3512,)
2021-02-01 11:01:27,121 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,124 INFO sqlalchemy.engine.base.Engine (3513,)
2021-02-01 11:01:27,127 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,129 INFO sqlalchemy.engine.base.Engine (3514,)
2021-02-01 11:01:27,132 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,136 INFO sqlalchemy.engine.base.Engine (3515,)
2021-02-01 11:01:27,139 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,140 INFO sqlalchemy.engine.base.Engine (3516,)
2021-02-01 11:01:27,143 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,144 INFO sqlalchemy.engine.base.Engine (3517,)
2021-02-01 11:01:27,146 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,148 INFO sqlalchemy.engine.base.Engine (3518,)
2021-02-01 11:01:27,150 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,151 INFO sqlalchemy.engine.base.Engine (3519,)
2021-02-01 11:01:27,153 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,154 INFO sqlalchemy.engine.base.Engine (3520,)
2021-02-01 11:01:27,156 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,158 INFO sqlalchemy.engine.base.Engine (3521,)
2021-02-01 11:01:27,161 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,162 INFO sqlalchemy.engine.base.Engine (3522,)
2021-02-01 11:01:27,164 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,167 INFO sqlalchemy.engine.base.Engine (3523,)
2021-02-01 11:01:27,170 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,171 INFO sqlalchemy.engine.base.Engine (3524,)
2021-02-01 11:01:27,173 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,174 INFO sqlalchemy.engine.base.Engine (3525,)
2021-02-01 11:01:27,177 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,181 INFO sqlalchemy.engine.base.Engine (3526,)
2021-02-01 11:01:27,183 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,184 INFO sqlalchemy.engine.base.Engine (3527,)
2021-02-01 11:01:27,186 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:27,187 INFO sqlalchemy.engine.base.Engine (3528,)
2021-02-01 11:01:27,191 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,192 INFO sqlalchemy.engine.base.Engine (3529,)
2021-02-01 11:01:27,194 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,198 INFO sqlalchemy.engine.base.Engine (3530,)
2021-02-01 11:01:27,199 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,201 INFO sqlalchemy.engine.base.Engine (3531,)
2021-02-01 11:01:27,203 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,204 INFO sqlalchemy.engine.base.Engine (3532,)
2021-02-01 11:01:27,207 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,208 INFO sqlalchemy.engine.base.Engine (3533,)
2021-02-01 11:01:27,210 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,213 INFO sqlalchemy.engine.base.Engine (3534,)
2021-02-01 11:01:27,217 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,218 INFO sqlalchemy.engine.base.Engine (3535,)
2021-02-01 11:01:27,220 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,222 INFO sqlalchemy.engine.base.Engine (3536,)
2021-02-01 11:01:27,224 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,226 INFO sqlalchemy.engine.base.Engine (3537,)
2021-02-01 11:01:27,229 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,230 INFO sqlalchemy.engine.base.Engine (3538,)
2021-02-01 11:01:27,232 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,233 INFO sqlalchemy.engine.base.Engine (3539,)
2021-02-01 11:01:27,236 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,237 INFO sqlalchemy.engine.base.Engine (3540,)
2021-02-01 11:01:27,239 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,240 INFO sqlalchemy.engine.base.Engine (3541,)
2021-02-01 11:01:27,243 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,245 INFO sqlalchemy.engine.base.Engine (3542,)
2021-02-01 11:01:27,250 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,251 INFO sqlalchemy.engine.base.Engine (3543,)
2021-02-01 11:01:27,253 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,255 INFO sqlalchemy.engine.base.Engine (3544,)
2021-02-01 11:01:27,260 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,261 INFO sqlalchemy.engine.base.Engine (3545,)
2021-02-01 11:01:27,263 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,266 INFO sqlalchemy.engine.base.Engine (3546,)
2021-02-01 11:01:27,269 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,271 INFO sqlalchemy.engine.base.Engine (3547,)
2021-02-01 11:01:27,273 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,278 INFO sqlalchemy.engine.base.Engine (3548,)
2021-02-01 11:01:27,280 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:27,281 INFO sqlalchemy.engine.base.Engine (3549,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:27,481 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:27,486 INFO sqlalchemy.engine.base.Engine ('F72',)
2021-02-01 11:01:27,490 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:27,492 INFO sqlalchemy.engine.base.Engine ((3550, 14.3, 14.3, 14.3, 152888.36700002544, 122577.94413904753), (3551, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.36700002544, 122577.94413904753), (3552, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.36700002544, 122577.94413904753), (3553, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.36700002544, 122577.94413904753), (3554, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.36700002544, 122577.94413904753), (3555, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.36700002544, 122577.94413904753), (3556, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.36700002544, 122577.94413904753), (3557, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152888.36700002544, 122577.94413904753)  ... displaying 10 of 50 total bound parameter sets ...  (3598, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152888.36700002544, 122577.94413904753), (3599, 135.9, 135.9, 135.9, 152888.36700002544, 122577.94413904753))
2021-02-01 11:01:27,501 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:27,502 INFO sqlalchemy.engine.base.Engine ((1775, 'F72', 0, 'Anhydrite', 3550, 3551), (1776, 'F72', 1, 'Sandstone, grey, vf-f', 3552, 3553), (1777, 'F72', 2, 'Anhydrite', 3554, 3555), (1778, 'F72', 3, 'Dolomite', 3556, 3557), (1779, 'F72', 4, 'Anhydrite', 3558, 3559), (1780, 'F72', 5, 'Sandstone, grey, vf-f', 3560, 3561), (1781, 'F72', 6, 'Siltstone, red', 3562, 3563), (1782, 'F72', 7, 'Dolomite', 3564, 3565)  ... displaying 10 of 25 total bound parameter sets ...  (1798, 'F72', 23, 'Limestone', 3596, 3597), (1799, 'F72', 24, 'Volcanic', 3598, 3599))
2021-02-01 11:01:27,507 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:27,770 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:27,772 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:27,773 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:27,775 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:27,777 INFO sqlalchemy.engine.base.Engine ('F72',)
2021-02-01 11:01:27,779 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,780 INFO sqlalchemy.engine.base.Engine (3550,)
2021-02-01 11:01:27,783 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,784 INFO sqlalchemy.engine.base.Engine (3551,)
2021-02-01 11:01:27,787 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,789 INFO sqlalchemy.engine.base.Engine (3552,)
2021-02-01 11:01:27,791 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,793 INFO sqlalchemy.engine.base.Engine (3553,)
2021-02-01 11:01:27,795 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,797 INFO sqlalchemy.engine.base.Engine (3554,)
2021-02-01 11:01:27,799 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,801 INFO sqlalchemy.engine.base.Engine (3555,)
2021-02-01 11:01:27,802 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,804 INFO sqlalchemy.engine.base.Engine (3556,)
2021-02-01 11:01:27,805 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,807 INFO sqlalchemy.engine.base.Engine (3557,)
2021-02-01 11:01:27,809 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,810 INFO sqlalchemy.engine.base.Engine (3558,)
2021-02-01 11:01:27,815 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,817 INFO sqlalchemy.engine.base.Engine (3559,)
2021-02-01 11:01:27,819 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,821 INFO sqlalchemy.engine.base.Engine (3560,)
2021-02-01 11:01:27,823 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,824 INFO sqlalchemy.engine.base.Engine (3561,)
2021-02-01 11:01:27,827 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,828 INFO sqlalchemy.engine.base.Engine (3562,)

2021-02-01 11:01:27,830 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,831 INFO sqlalchemy.engine.base.Engine (3563,)
2021-02-01 11:01:27,833 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,835 INFO sqlalchemy.engine.base.Engine (3564,)
2021-02-01 11:01:27,836 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,838 INFO sqlalchemy.engine.base.Engine (3565,)
2021-02-01 11:01:27,839 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,841 INFO sqlalchemy.engine.base.Engine (3566,)
2021-02-01 11:01:27,843 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,844 INFO sqlalchemy.engine.base.Engine (3567,)
2021-02-01 11:01:27,846 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,848 INFO sqlalchemy.engine.base.Engine (3568,)
2021-02-01 11:01:27,849 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,850 INFO sqlalchemy.engine.base.Engine (3569,)
2021-02-01 11:01:27,852 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,854 INFO sqlalchemy.engine.base.Engine (3570,)
2021-02-01 11:01:27,856 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,857 INFO sqlalchemy.engine.base.Engine (3571,)
2021-02-01 11:01:27,859 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,861 INFO sqlalchemy.engine.base.Engine (3572,)
2021-02-01 11:01:27,863 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,865 INFO sqlalchemy.engine.base.Engine (3573,)
2021-02-01 11:01:27,867 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,868 INFO sqlalchemy.engine.base.Engine (3574,)
2021-02-01 11:01:27,871 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,872 INFO sqlalchemy.engine.base.Engine (3575,)
2021-02-01 11:01:27,876 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,877 INFO sqlalchemy.engine.base.Engine (3576,)
2021-02-01 11:01:27,880 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,881 INFO sqlalchemy.engine.base.Engine (3577,)
2021-02-01 11:01:27,883 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,884 INFO sqlalchemy.engine.base.Engine (3578,)
2021-02-01 11:01:27,887 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,888 INFO sqlalchemy.engine.base.Engine (3579,)
2021-02-01 11:01:27,890 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,891 INFO sqlalchemy.engine.base.Engine (3580,)
2021-02-01 11:01:27,894 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,895 INFO sqlalchemy.engine.base.Engine (3581,)
2021-02-01 11:01:27,898 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,899 INFO sqlalchemy.engine.base.Engine (3582,)
2021-02-01 11:01:27,903 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:27,904 INFO sqlalchemy.engine.base.Engine (3583,)
2021-02-01 11:01:27,907 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,908 INFO sqlalchemy.engine.base.Engine (3584,)
2021-02-01 11:01:27,910 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,911 INFO sqlalchemy.engine.base.Engine (3585,)
2021-02-01 11:01:27,914 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,915 INFO sqlalchemy.engine.base.Engine (3586,)
2021-02-01 11:01:27,918 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,919 INFO sqlalchemy.engine.base.Engine (3587,)
2021-02-01 11:01:27,921 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,923 INFO sqlalchemy.engine.base.Engine (3588,)
2021-02-01 11:01:27,925 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,926 INFO sqlalchemy.engine.base.Engine (3589,)
2021-02-01 11:01:27,928 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,929 INFO sqlalchemy.engine.base.Engine (3590,)
2021-02-01 11:01:27,933 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,937 INFO sqlalchemy.engine.base.Engine (3591,)
2021-02-01 11:01:27,939 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,940 INFO sqlalchemy.engine.base.Engine (3592,)
2021-02-01 11:01:27,943 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,944 INFO sqlalchemy.engine.base.Engine (3593,)
2021-02-01 11:01:27,946 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,947 INFO sqlalchemy.engine.base.Engine (3594,)
2021-02-01 11:01:27,950 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,951 INFO sqlalchemy.engine.base.Engine (3595,)
2021-02-01 11:01:27,956 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,957 INFO sqlalchemy.engine.base.Engine (3596,)
2021-02-01 11:01:27,959 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,960 INFO sqlalchemy.engine.base.Engine (3597,)
2021-02-01 11:01:27,963 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,964 INFO sqlalchemy.engine.base.Engine (3598,)
2021-02-01 11:01:27,966 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:27,967 INFO sqlalchemy.engine.base.Engine (3599,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:28,117 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:28,118 INFO sqlalchemy.engine.base.Engine ((3600, 14.3, 14.3, 14.3, 152888.55500002546, 122581.87813904787), (3601, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.55500002546, 122581.87813904787), (3602, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.55500002546, 122581.87813904787), (3603, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.55500002546, 122581.87813904787), (3604, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.55500002546, 122581.87813904787), (3605, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.55500002546, 122581.87813904787), (3606, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.55500002546, 122581.87813904787), (3607, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152888.55500002546, 122581.87813904787)  ... displaying 10 of 50 total bound parameter sets ...  (3648, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152888.55500002546, 122581.87813904787), (3649, 135.9, 135.9, 135.9, 152888.55500002546, 122581.87813904787))
2021-02-01 11:01:28,120 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:28,121 INFO sqlalchemy.engine.base.Engine ('F73',)
2021-02-01 11:01:28,125 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:28,126 INFO sqlalchemy.engine.base.Engine ((1800, 'F73', 0, 'Anhydrite', 3600, 3601), (1801, 'F73', 1, 'Sandstone, grey, vf-f', 3602, 3603), (1802, 'F73', 2, 'Anhydrite', 3604, 3605), (1803, 'F73', 3, 'Dolomite', 3606, 3607), (1804, 'F73', 4, 'Anhydrite', 3608, 3609), (1805, 'F73', 5, 'Sandstone, grey, vf-f', 3610, 3611), (1806, 'F73', 6, 'Siltstone, red', 3612, 3613), (1807, 'F73', 7, 'Dolomite', 3614, 3615)  ... displaying 10 of 25 total bound parameter sets ...  (1823, 'F73', 23, 'Limestone', 3646, 3647), (1824, 'F73', 24, 'Volcanic', 3648, 3649))

2021-02-01 11:01:28,133 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:28,472 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:28,474 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:28,475 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:28,479 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:28,482 INFO sqlalchemy.engine.base.Engine ('F73',)
2021-02-01 11:01:28,486 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,491 INFO sqlalchemy.engine.base.Engine (3600,)
2021-02-01 11:01:28,493 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,494 INFO sqlalchemy.engine.base.Engine (3601,)
2021-02-01 11:01:28,498 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,502 INFO sqlalchemy.engine.base.Engine (3602,)
2021-02-01 11:01:28,504 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,505 INFO sqlalchemy.engine.base.Engine (3603,)
2021-02-01 11:01:28,508 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,509 INFO sqlalchemy.engine.base.Engine (3604,)
2021-02-01 11:01:28,511 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,513 INFO sqlalchemy.engine.base.Engine (3605,)
2021-02-01 11:01:28,516 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,516 INFO sqlalchemy.engine.base.Engine (3606,)
2021-02-01 11:01:28,521 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,522 INFO sqlalchemy.engine.base.Engine (3607,)
2021-02-01 11:01:28,524 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,525 INFO sqlalchemy.engine.base.Engine (3608,)
2021-02-01 11:01:28,527 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,528 INFO sqlalchemy.engine.base.Engine (3609,)
2021-02-01 11:01:28,530 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,532 INFO sqlalchemy.engine.base.Engine (3610,)
2021-02-01 11:01:28,534 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,535 INFO sqlalchemy.engine.base.Engine (3611,)
2021-02-01 11:01:28,537 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,539 INFO sqlalchemy.engine.base.Engine (3612,)
2021-02-01 11:01:28,543 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,546 INFO sqlalchemy.engine.base.Engine (3613,)
2021-02-01 11:01:28,548 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,550 INFO sqlalchemy.engine.base.Engine (3614,)
2021-02-01 11:01:28,552 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,553 INFO sqlalchemy.engine.base.Engine (3615,)
2021-02-01 11:01:28,555 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,557 INFO sqlalchemy.engine.base.Engine (3616,)
2021-02-01 11:01:28,559 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,564 INFO sqlalchemy.engine.base.Engine (3617,)
2021-02-01 11:01:28,566 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:28,567 INFO sqlalchemy.engine.base.Engine (3618,)
2021-02-01 11:01:28,569 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,570 INFO sqlalchemy.engine.base.Engine (3619,)
2021-02-01 11:01:28,574 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,575 INFO sqlalchemy.engine.base.Engine (3620,)
2021-02-01 11:01:28,579 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,580 INFO sqlalchemy.engine.base.Engine (3621,)
2021-02-01 11:01:28,583 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,584 INFO sqlalchemy.engine.base.Engine (3622,)
2021-02-01 11:01:28,587 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,588 INFO sqlalchemy.engine.base.Engine (3623,)
2021-02-01 11:01:28,590 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,591 INFO sqlalchemy.engine.base.Engine (3624,)
2021-02-01 11:01:28,594 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,596 INFO sqlalchemy.engine.base.Engine (3625,)
2021-02-01 11:01:28,599 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,601 INFO sqlalchemy.engine.base.Engine (3626,)
2021-02-01 11:01:28,603 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,606 INFO sqlalchemy.engine.base.Engine (3627,)
2021-02-01 11:01:28,610 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,611 INFO sqlalchemy.engine.base.Engine (3628,)
2021-02-01 11:01:28,614 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,615 INFO sqlalchemy.engine.base.Engine (3629,)
2021-02-01 11:01:28,617 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,618 INFO sqlalchemy.engine.base.Engine (3630,)
2021-02-01 11:01:28,620 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,621 INFO sqlalchemy.engine.base.Engine (3631,)
2021-02-01 11:01:28,623 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,625 INFO sqlalchemy.engine.base.Engine (3632,)
2021-02-01 11:01:28,627 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,628 INFO sqlalchemy.engine.base.Engine (3633,)
2021-02-01 11:01:28,631 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,634 INFO sqlalchemy.engine.base.Engine (3634,)
2021-02-01 11:01:28,636 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,639 INFO sqlalchemy.engine.base.Engine (3635,)
2021-02-01 11:01:28,643 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,644 INFO sqlalchemy.engine.base.Engine (3636,)
2021-02-01 11:01:28,645 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,646 INFO sqlalchemy.engine.base.Engine (3637,)
2021-02-01 11:01:28,648 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,649 INFO sqlalchemy.engine.base.Engine (3638,)
2021-02-01 11:01:28,651 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:28,654 INFO sqlalchemy.engine.base.Engine (3639,)
2021-02-01 11:01:28,657 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,658 INFO sqlalchemy.engine.base.Engine (3640,)
2021-02-01 11:01:28,661 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,662 INFO sqlalchemy.engine.base.Engine (3641,)
2021-02-01 11:01:28,664 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,667 INFO sqlalchemy.engine.base.Engine (3642,)
2021-02-01 11:01:28,670 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,672 INFO sqlalchemy.engine.base.Engine (3643,)
2021-02-01 11:01:28,674 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,676 INFO sqlalchemy.engine.base.Engine (3644,)
2021-02-01 11:01:28,679 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,682 INFO sqlalchemy.engine.base.Engine (3645,)
2021-02-01 11:01:28,685 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,686 INFO sqlalchemy.engine.base.Engine (3646,)
2021-02-01 11:01:28,688 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,690 INFO sqlalchemy.engine.base.Engine (3647,)
2021-02-01 11:01:28,693 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,694 INFO sqlalchemy.engine.base.Engine (3648,)
2021-02-01 11:01:28,696 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:28,698 INFO sqlalchemy.engine.base.Engine (3649,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:28,877 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:28,878 INFO sqlalchemy.engine.base.Engine ((3650, 14.3, 14.3, 14.3, 152886.29900002538, 122580.93113904724), (3651, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152886.29900002538, 122580.93113904724), (3652, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152886.29900002538, 122580.93113904724), (3653, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152886.29900002538, 122580.93113904724), (3654, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152886.29900002538, 122580.93113904724), (3655, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152886.29900002538, 122580.93113904724), (3656, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152886.29900002538, 122580.93113904724), (3657, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152886.29900002538, 122580.93113904724)  ... displaying 10 of 50 total bound parameter sets ...  (3698, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152886.29900002538, 122580.93113904724), (3699, 135.9, 135.9, 135.9, 152886.29900002538, 122580.93113904724))
2021-02-01 11:01:28,882 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:28,884 INFO sqlalchemy.engine.base.Engine ('F74',)
2021-02-01 11:01:28,888 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:28,890 INFO sqlalchemy.engine.base.Engine ((1825, 'F74', 0, 'Anhydrite', 3650, 3651), (1826, 'F74', 1, 'Sandstone, grey, vf-f', 3652, 3653), (1827, 'F74', 2, 'Anhydrite', 3654, 3655), (1828, 'F74', 3, 'Dolomite', 3656, 3657), (1829, 'F74', 4, 'Anhydrite', 3658, 3659), (1830, 'F74', 5, 'Sandstone, grey, vf-f', 3660, 3661), (1831, 'F74', 6, 'Siltstone, red', 3662, 3663), (1832, 'F74', 7, 'Dolomite', 3664, 3665)  ... displaying 10 of 25 total bound parameter sets ...  (1848, 'F74', 23, 'Limestone', 3696, 3697), (1849, 'F74', 24, 'Volcanic', 3698, 3699))
2021-02-01 11:01:28,895 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:29,060 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:29,062 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:29,064 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:29,068 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:29,072 INFO sqlalchemy.engine.base.Engine ('F74',)
2021-02-01 11:01:29,078 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,079 INFO sqlalchemy.engine.base.Engine (3650,)
2021-02-01 11:01:29,085 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,090 INFO sqlalchemy.engine.base.Engine (3651,)
2021-02-01 11:01:29,094 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,097 INFO sqlalchemy.engine.base.Engine (3652,)

2021-02-01 11:01:29,099 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,101 INFO sqlalchemy.engine.base.Engine (3653,)
2021-02-01 11:01:29,104 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,109 INFO sqlalchemy.engine.base.Engine (3654,)
2021-02-01 11:01:29,111 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,112 INFO sqlalchemy.engine.base.Engine (3655,)
2021-02-01 11:01:29,115 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,116 INFO sqlalchemy.engine.base.Engine (3656,)
2021-02-01 11:01:29,118 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,119 INFO sqlalchemy.engine.base.Engine (3657,)
2021-02-01 11:01:29,121 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,125 INFO sqlalchemy.engine.base.Engine (3658,)
2021-02-01 11:01:29,127 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,130 INFO sqlalchemy.engine.base.Engine (3659,)
2021-02-01 11:01:29,132 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,135 INFO sqlalchemy.engine.base.Engine (3660,)
2021-02-01 11:01:29,136 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,137 INFO sqlalchemy.engine.base.Engine (3661,)
2021-02-01 11:01:29,144 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,147 INFO sqlalchemy.engine.base.Engine (3662,)
2021-02-01 11:01:29,149 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,151 INFO sqlalchemy.engine.base.Engine (3663,)
2021-02-01 11:01:29,153 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,155 INFO sqlalchemy.engine.base.Engine (3664,)
2021-02-01 11:01:29,157 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,158 INFO sqlalchemy.engine.base.Engine (3665,)
2021-02-01 11:01:29,160 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,165 INFO sqlalchemy.engine.base.Engine (3666,)
2021-02-01 11:01:29,167 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,168 INFO sqlalchemy.engine.base.Engine (3667,)
2021-02-01 11:01:29,170 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,173 INFO sqlalchemy.engine.base.Engine (3668,)
2021-02-01 11:01:29,175 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,176 INFO sqlalchemy.engine.base.Engine (3669,)
2021-02-01 11:01:29,182 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,192 INFO sqlalchemy.engine.base.Engine (3670,)
2021-02-01 11:01:29,194 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,195 INFO sqlalchemy.engine.base.Engine (3671,)
2021-02-01 11:01:29,197 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,198 INFO sqlalchemy.engine.base.Engine (3672,)
2021-02-01 11:01:29,202 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:29,206 INFO sqlalchemy.engine.base.Engine (3673,)
2021-02-01 11:01:29,208 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,210 INFO sqlalchemy.engine.base.Engine (3674,)
2021-02-01 11:01:29,213 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,214 INFO sqlalchemy.engine.base.Engine (3675,)
2021-02-01 11:01:29,227 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,228 INFO sqlalchemy.engine.base.Engine (3676,)
2021-02-01 11:01:29,230 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,231 INFO sqlalchemy.engine.base.Engine (3677,)
2021-02-01 11:01:29,237 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,239 INFO sqlalchemy.engine.base.Engine (3678,)
2021-02-01 11:01:29,241 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,242 INFO sqlalchemy.engine.base.Engine (3679,)
2021-02-01 11:01:29,245 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,246 INFO sqlalchemy.engine.base.Engine (3680,)
2021-02-01 11:01:29,249 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,250 INFO sqlalchemy.engine.base.Engine (3681,)
2021-02-01 11:01:29,253 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,255 INFO sqlalchemy.engine.base.Engine (3682,)
2021-02-01 11:01:29,258 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,259 INFO sqlalchemy.engine.base.Engine (3683,)
2021-02-01 11:01:29,262 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,263 INFO sqlalchemy.engine.base.Engine (3684,)
2021-02-01 11:01:29,269 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,271 INFO sqlalchemy.engine.base.Engine (3685,)
2021-02-01 11:01:29,273 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,277 INFO sqlalchemy.engine.base.Engine (3686,)
2021-02-01 11:01:29,281 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,282 INFO sqlalchemy.engine.base.Engine (3687,)
2021-02-01 11:01:29,284 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,286 INFO sqlalchemy.engine.base.Engine (3688,)
2021-02-01 11:01:29,290 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,293 INFO sqlalchemy.engine.base.Engine (3689,)
2021-02-01 11:01:29,296 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,298 INFO sqlalchemy.engine.base.Engine (3690,)
2021-02-01 11:01:29,300 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,301 INFO sqlalchemy.engine.base.Engine (3691,)
2021-02-01 11:01:29,304 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,305 INFO sqlalchemy.engine.base.Engine (3692,)
2021-02-01 11:01:29,308 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,310 INFO sqlalchemy.engine.base.Engine (3693,)
2021-02-01 11:01:29,313 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:29,314 INFO sqlalchemy.engine.base.Engine (3694,)
2021-02-01 11:01:29,316 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,317 INFO sqlalchemy.engine.base.Engine (3695,)
2021-02-01 11:01:29,320 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,321 INFO sqlalchemy.engine.base.Engine (3696,)
2021-02-01 11:01:29,323 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,324 INFO sqlalchemy.engine.base.Engine (3697,)
2021-02-01 11:01:29,328 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,334 INFO sqlalchemy.engine.base.Engine (3698,)
2021-02-01 11:01:29,336 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,339 INFO sqlalchemy.engine.base.Engine (3699,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:29,526 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:29,528 INFO sqlalchemy.engine.base.Engine ((3700, 14.3, 14.3, 14.3, 152888.50000002538, 122580.49013904762), (3701, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.50000002538, 122580.49013904762), (3702, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.50000002538, 122580.49013904762), (3703, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.50000002538, 122580.49013904762), (3704, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.50000002538, 122580.49013904762), (3705, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.50000002538, 122580.49013904762), (3706, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.50000002538, 122580.49013904762), (3707, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152888.50000002538, 122580.49013904762)  ... displaying 10 of 50 total bound parameter sets ...  (3748, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152888.50000002538, 122580.49013904762), (3749, 135.9, 135.9, 135.9, 152888.50000002538, 122580.49013904762))
2021-02-01 11:01:29,531 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:29,532 INFO sqlalchemy.engine.base.Engine ('F75',)
2021-02-01 11:01:29,536 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:29,537 INFO sqlalchemy.engine.base.Engine ((1850, 'F75', 0, 'Anhydrite', 3700, 3701), (1851, 'F75', 1, 'Sandstone, grey, vf-f', 3702, 3703), (1852, 'F75', 2, 'Anhydrite', 3704, 3705), (1853, 'F75', 3, 'Dolomite', 3706, 3707), (1854, 'F75', 4, 'Anhydrite', 3708, 3709), (1855, 'F75', 5, 'Sandstone, grey, vf-f', 3710, 3711), (1856, 'F75', 6, 'Siltstone, red', 3712, 3713), (1857, 'F75', 7, 'Dolomite', 3714, 3715)  ... displaying 10 of 25 total bound parameter sets ...  (1873, 'F75', 23, 'Limestone', 3746, 3747), (1874, 'F75', 24, 'Volcanic', 3748, 3749))
2021-02-01 11:01:29,540 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:29,866 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:29,867 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:29,868 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:29,873 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:29,874 INFO sqlalchemy.engine.base.Engine ('F75',)
2021-02-01 11:01:29,877 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,878 INFO sqlalchemy.engine.base.Engine (3700,)
2021-02-01 11:01:29,880 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,882 INFO sqlalchemy.engine.base.Engine (3701,)
2021-02-01 11:01:29,884 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,886 INFO sqlalchemy.engine.base.Engine (3702,)
2021-02-01 11:01:29,888 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,889 INFO sqlalchemy.engine.base.Engine (3703,)
2021-02-01 11:01:29,891 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,893 INFO sqlalchemy.engine.base.Engine (3704,)
2021-02-01 11:01:29,900 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,901 INFO sqlalchemy.engine.base.Engine (3705,)
2021-02-01 11:01:29,905 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,907 INFO sqlalchemy.engine.base.Engine (3706,)
2021-02-01 11:01:29,909 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,910 INFO sqlalchemy.engine.base.Engine (3707,)

2021-02-01 11:01:29,912 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,915 INFO sqlalchemy.engine.base.Engine (3708,)
2021-02-01 11:01:29,917 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,921 INFO sqlalchemy.engine.base.Engine (3709,)
2021-02-01 11:01:29,924 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,926 INFO sqlalchemy.engine.base.Engine (3710,)
2021-02-01 11:01:29,928 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,929 INFO sqlalchemy.engine.base.Engine (3711,)
2021-02-01 11:01:29,931 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,933 INFO sqlalchemy.engine.base.Engine (3712,)
2021-02-01 11:01:29,935 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,936 INFO sqlalchemy.engine.base.Engine (3713,)
2021-02-01 11:01:29,938 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,939 INFO sqlalchemy.engine.base.Engine (3714,)
2021-02-01 11:01:29,941 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,944 INFO sqlalchemy.engine.base.Engine (3715,)
2021-02-01 11:01:29,949 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,950 INFO sqlalchemy.engine.base.Engine (3716,)
2021-02-01 11:01:29,951 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,952 INFO sqlalchemy.engine.base.Engine (3717,)
2021-02-01 11:01:29,954 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,955 INFO sqlalchemy.engine.base.Engine (3718,)
2021-02-01 11:01:29,957 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,958 INFO sqlalchemy.engine.base.Engine (3719,)
2021-02-01 11:01:29,960 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,963 INFO sqlalchemy.engine.base.Engine (3720,)
2021-02-01 11:01:29,965 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,968 INFO sqlalchemy.engine.base.Engine (3721,)
2021-02-01 11:01:29,972 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,973 INFO sqlalchemy.engine.base.Engine (3722,)
2021-02-01 11:01:29,975 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,977 INFO sqlalchemy.engine.base.Engine (3723,)
2021-02-01 11:01:29,979 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,980 INFO sqlalchemy.engine.base.Engine (3724,)
2021-02-01 11:01:29,982 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,983 INFO sqlalchemy.engine.base.Engine (3725,)
2021-02-01 11:01:29,987 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,994 INFO sqlalchemy.engine.base.Engine (3726,)
2021-02-01 11:01:29,996 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:29,996 INFO sqlalchemy.engine.base.Engine (3727,)
2021-02-01 11:01:29,999 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:30,000 INFO sqlalchemy.engine.base.Engine (3728,)
2021-02-01 11:01:30,002 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,003 INFO sqlalchemy.engine.base.Engine (3729,)
2021-02-01 11:01:30,005 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,006 INFO sqlalchemy.engine.base.Engine (3730,)
2021-02-01 11:01:30,008 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,008 INFO sqlalchemy.engine.base.Engine (3731,)
2021-02-01 11:01:30,011 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,017 INFO sqlalchemy.engine.base.Engine (3732,)
2021-02-01 11:01:30,019 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,020 INFO sqlalchemy.engine.base.Engine (3733,)
2021-02-01 11:01:30,022 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,023 INFO sqlalchemy.engine.base.Engine (3734,)
2021-02-01 11:01:30,025 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,027 INFO sqlalchemy.engine.base.Engine (3735,)
2021-02-01 11:01:30,029 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,030 INFO sqlalchemy.engine.base.Engine (3736,)
2021-02-01 11:01:30,032 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,033 INFO sqlalchemy.engine.base.Engine (3737,)
2021-02-01 11:01:30,035 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,036 INFO sqlalchemy.engine.base.Engine (3738,)
2021-02-01 11:01:30,037 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,038 INFO sqlalchemy.engine.base.Engine (3739,)
2021-02-01 11:01:30,040 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,041 INFO sqlalchemy.engine.base.Engine (3740,)
2021-02-01 11:01:30,043 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,044 INFO sqlalchemy.engine.base.Engine (3741,)
2021-02-01 11:01:30,046 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,053 INFO sqlalchemy.engine.base.Engine (3742,)
2021-02-01 11:01:30,057 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,058 INFO sqlalchemy.engine.base.Engine (3743,)
2021-02-01 11:01:30,060 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,060 INFO sqlalchemy.engine.base.Engine (3744,)
2021-02-01 11:01:30,062 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,064 INFO sqlalchemy.engine.base.Engine (3745,)
2021-02-01 11:01:30,067 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,068 INFO sqlalchemy.engine.base.Engine (3746,)
2021-02-01 11:01:30,074 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,076 INFO sqlalchemy.engine.base.Engine (3747,)
2021-02-01 11:01:30,080 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,083 INFO sqlalchemy.engine.base.Engine (3748,)
2021-02-01 11:01:30,085 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:30,086 INFO sqlalchemy.engine.base.Engine (3749,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:30,302 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:30,303 INFO sqlalchemy.engine.base.Engine ('F76',)
2021-02-01 11:01:30,307 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:30,309 INFO sqlalchemy.engine.base.Engine ((3750, 14.3, 14.3, 14.3, 152886.46500002546, 122577.9491390474), (3751, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152886.46500002546, 122577.9491390474), (3752, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152886.46500002546, 122577.9491390474), (3753, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152886.46500002546, 122577.9491390474), (3754, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152886.46500002546, 122577.9491390474), (3755, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152886.46500002546, 122577.9491390474), (3756, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152886.46500002546, 122577.9491390474), (3757, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152886.46500002546, 122577.9491390474)  ... displaying 10 of 50 total bound parameter sets ...  (3798, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152886.46500002546, 122577.9491390474), (3799, 135.9, 135.9, 135.9, 152886.46500002546, 122577.9491390474))
2021-02-01 11:01:30,322 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:30,323 INFO sqlalchemy.engine.base.Engine ((1875, 'F76', 0, 'Anhydrite', 3750, 3751), (1876, 'F76', 1, 'Sandstone, grey, vf-f', 3752, 3753), (1877, 'F76', 2, 'Anhydrite', 3754, 3755), (1878, 'F76', 3, 'Dolomite', 3756, 3757), (1879, 'F76', 4, 'Anhydrite', 3758, 3759), (1880, 'F76', 5, 'Sandstone, grey, vf-f', 3760, 3761), (1881, 'F76', 6, 'Siltstone, red', 3762, 3763), (1882, 'F76', 7, 'Dolomite', 3764, 3765)  ... displaying 10 of 25 total bound parameter sets ...  (1898, 'F76', 23, 'Limestone', 3796, 3797), (1899, 'F76', 24, 'Volcanic', 3798, 3799))
2021-02-01 11:01:30,331 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:30,408 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:30,411 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:30,414 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:30,427 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:30,428 INFO sqlalchemy.engine.base.Engine ('F76',)
2021-02-01 11:01:30,434 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,436 INFO sqlalchemy.engine.base.Engine (3750,)
2021-02-01 11:01:30,446 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,447 INFO sqlalchemy.engine.base.Engine (3751,)
2021-02-01 11:01:30,450 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,451 INFO sqlalchemy.engine.base.Engine (3752,)
2021-02-01 11:01:30,453 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,454 INFO sqlalchemy.engine.base.Engine (3753,)
2021-02-01 11:01:30,456 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,457 INFO sqlalchemy.engine.base.Engine (3754,)
2021-02-01 11:01:30,459 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,460 INFO sqlalchemy.engine.base.Engine (3755,)
2021-02-01 11:01:30,464 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,466 INFO sqlalchemy.engine.base.Engine (3756,)
2021-02-01 11:01:30,469 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,470 INFO sqlalchemy.engine.base.Engine (3757,)
2021-02-01 11:01:30,472 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,474 INFO sqlalchemy.engine.base.Engine (3758,)
2021-02-01 11:01:30,478 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,480 INFO sqlalchemy.engine.base.Engine (3759,)
2021-02-01 11:01:30,483 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,484 INFO sqlalchemy.engine.base.Engine (3760,)
2021-02-01 11:01:30,487 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,488 INFO sqlalchemy.engine.base.Engine (3761,)
2021-02-01 11:01:30,492 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,493 INFO sqlalchemy.engine.base.Engine (3762,)

2021-02-01 11:01:30,495 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,496 INFO sqlalchemy.engine.base.Engine (3763,)
2021-02-01 11:01:30,501 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,503 INFO sqlalchemy.engine.base.Engine (3764,)
2021-02-01 11:01:30,505 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,506 INFO sqlalchemy.engine.base.Engine (3765,)
2021-02-01 11:01:30,509 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,511 INFO sqlalchemy.engine.base.Engine (3766,)
2021-02-01 11:01:30,514 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,516 INFO sqlalchemy.engine.base.Engine (3767,)
2021-02-01 11:01:30,521 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,522 INFO sqlalchemy.engine.base.Engine (3768,)
2021-02-01 11:01:30,525 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,527 INFO sqlalchemy.engine.base.Engine (3769,)
2021-02-01 11:01:30,529 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,531 INFO sqlalchemy.engine.base.Engine (3770,)
2021-02-01 11:01:30,533 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,537 INFO sqlalchemy.engine.base.Engine (3771,)
2021-02-01 11:01:30,539 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,540 INFO sqlalchemy.engine.base.Engine (3772,)
2021-02-01 11:01:30,542 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,543 INFO sqlalchemy.engine.base.Engine (3773,)
2021-02-01 11:01:30,545 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,548 INFO sqlalchemy.engine.base.Engine (3774,)
2021-02-01 11:01:30,549 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,551 INFO sqlalchemy.engine.base.Engine (3775,)
2021-02-01 11:01:30,553 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,555 INFO sqlalchemy.engine.base.Engine (3776,)
2021-02-01 11:01:30,557 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,559 INFO sqlalchemy.engine.base.Engine (3777,)
2021-02-01 11:01:30,561 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,565 INFO sqlalchemy.engine.base.Engine (3778,)
2021-02-01 11:01:30,568 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,570 INFO sqlalchemy.engine.base.Engine (3779,)
2021-02-01 11:01:30,572 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,573 INFO sqlalchemy.engine.base.Engine (3780,)
2021-02-01 11:01:30,575 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,577 INFO sqlalchemy.engine.base.Engine (3781,)
2021-02-01 11:01:30,579 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,581 INFO sqlalchemy.engine.base.Engine (3782,)
2021-02-01 11:01:30,582 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:30,584 INFO sqlalchemy.engine.base.Engine (3783,)
2021-02-01 11:01:30,588 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,591 INFO sqlalchemy.engine.base.Engine (3784,)
2021-02-01 11:01:30,593 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,594 INFO sqlalchemy.engine.base.Engine (3785,)
2021-02-01 11:01:30,597 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,598 INFO sqlalchemy.engine.base.Engine (3786,)
2021-02-01 11:01:30,602 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,603 INFO sqlalchemy.engine.base.Engine (3787,)
2021-02-01 11:01:30,609 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,610 INFO sqlalchemy.engine.base.Engine (3788,)
2021-02-01 11:01:30,614 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,618 INFO sqlalchemy.engine.base.Engine (3789,)
2021-02-01 11:01:30,622 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,623 INFO sqlalchemy.engine.base.Engine (3790,)
2021-02-01 11:01:30,625 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,629 INFO sqlalchemy.engine.base.Engine (3791,)
2021-02-01 11:01:30,633 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,635 INFO sqlalchemy.engine.base.Engine (3792,)
2021-02-01 11:01:30,638 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,640 INFO sqlalchemy.engine.base.Engine (3793,)
2021-02-01 11:01:30,642 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,643 INFO sqlalchemy.engine.base.Engine (3794,)
2021-02-01 11:01:30,646 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,652 INFO sqlalchemy.engine.base.Engine (3795,)
2021-02-01 11:01:30,655 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,657 INFO sqlalchemy.engine.base.Engine (3796,)
2021-02-01 11:01:30,660 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,661 INFO sqlalchemy.engine.base.Engine (3797,)
2021-02-01 11:01:30,664 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,665 INFO sqlalchemy.engine.base.Engine (3798,)
2021-02-01 11:01:30,667 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,668 INFO sqlalchemy.engine.base.Engine (3799,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:30,833 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:30,836 INFO sqlalchemy.engine.base.Engine ((3800, 14.3, 14.3, 14.3, 152888.05000002545, 122581.03613904586), (3801, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.05000002545, 122581.03613904586), (3802, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.05000002545, 122581.03613904586), (3803, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.05000002545, 122581.03613904586), (3804, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.05000002545, 122581.03613904586), (3805, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.05000002545, 122581.03613904586), (3806, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.05000002545, 122581.03613904586), (3807, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152888.05000002545, 122581.03613904586)  ... displaying 10 of 50 total bound parameter sets ...  (3848, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152888.05000002545, 122581.03613904586), (3849, 135.9, 135.9, 135.9, 152888.05000002545, 122581.03613904586))
2021-02-01 11:01:30,840 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:30,841 INFO sqlalchemy.engine.base.Engine ('F77',)
2021-02-01 11:01:30,848 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:30,849 INFO sqlalchemy.engine.base.Engine ((1900, 'F77', 0, 'Anhydrite', 3800, 3801), (1901, 'F77', 1, 'Sandstone, grey, vf-f', 3802, 3803), (1902, 'F77', 2, 'Anhydrite', 3804, 3805), (1903, 'F77', 3, 'Dolomite', 3806, 3807), (1904, 'F77', 4, 'Anhydrite', 3808, 3809), (1905, 'F77', 5, 'Sandstone, grey, vf-f', 3810, 3811), (1906, 'F77', 6, 'Siltstone, red', 3812, 3813), (1907, 'F77', 7, 'Dolomite', 3814, 3815)  ... displaying 10 of 25 total bound parameter sets ...  (1923, 'F77', 23, 'Limestone', 3846, 3847), (1924, 'F77', 24, 'Volcanic', 3848, 3849))

2021-02-01 11:01:30,855 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:30,982 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:30,983 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:30,984 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:30,989 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:30,991 INFO sqlalchemy.engine.base.Engine ('F77',)
2021-02-01 11:01:30,994 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:30,998 INFO sqlalchemy.engine.base.Engine (3800,)
2021-02-01 11:01:31,000 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,001 INFO sqlalchemy.engine.base.Engine (3801,)
2021-02-01 11:01:31,006 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,007 INFO sqlalchemy.engine.base.Engine (3802,)
2021-02-01 11:01:31,010 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,011 INFO sqlalchemy.engine.base.Engine (3803,)
2021-02-01 11:01:31,014 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,015 INFO sqlalchemy.engine.base.Engine (3804,)
2021-02-01 11:01:31,018 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,019 INFO sqlalchemy.engine.base.Engine (3805,)
2021-02-01 11:01:31,022 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,023 INFO sqlalchemy.engine.base.Engine (3806,)
2021-02-01 11:01:31,026 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,027 INFO sqlalchemy.engine.base.Engine (3807,)
2021-02-01 11:01:31,030 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,031 INFO sqlalchemy.engine.base.Engine (3808,)
2021-02-01 11:01:31,035 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,037 INFO sqlalchemy.engine.base.Engine (3809,)
2021-02-01 11:01:31,040 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,041 INFO sqlalchemy.engine.base.Engine (3810,)
2021-02-01 11:01:31,043 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,045 INFO sqlalchemy.engine.base.Engine (3811,)
2021-02-01 11:01:31,049 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,052 INFO sqlalchemy.engine.base.Engine (3812,)
2021-02-01 11:01:31,055 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,056 INFO sqlalchemy.engine.base.Engine (3813,)
2021-02-01 11:01:31,062 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,063 INFO sqlalchemy.engine.base.Engine (3814,)
2021-02-01 11:01:31,068 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,069 INFO sqlalchemy.engine.base.Engine (3815,)
2021-02-01 11:01:31,072 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,073 INFO sqlalchemy.engine.base.Engine (3816,)
2021-02-01 11:01:31,075 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,076 INFO sqlalchemy.engine.base.Engine (3817,)
2021-02-01 11:01:31,080 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:31,082 INFO sqlalchemy.engine.base.Engine (3818,)
2021-02-01 11:01:31,085 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,091 INFO sqlalchemy.engine.base.Engine (3819,)
2021-02-01 11:01:31,094 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,096 INFO sqlalchemy.engine.base.Engine (3820,)
2021-02-01 11:01:31,098 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,099 INFO sqlalchemy.engine.base.Engine (3821,)
2021-02-01 11:01:31,102 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,103 INFO sqlalchemy.engine.base.Engine (3822,)
2021-02-01 11:01:31,105 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,106 INFO sqlalchemy.engine.base.Engine (3823,)
2021-02-01 11:01:31,110 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,114 INFO sqlalchemy.engine.base.Engine (3824,)
2021-02-01 11:01:31,116 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,118 INFO sqlalchemy.engine.base.Engine (3825,)
2021-02-01 11:01:31,120 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,122 INFO sqlalchemy.engine.base.Engine (3826,)
2021-02-01 11:01:31,124 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,126 INFO sqlalchemy.engine.base.Engine (3827,)
2021-02-01 11:01:31,128 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,130 INFO sqlalchemy.engine.base.Engine (3828,)
2021-02-01 11:01:31,136 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,137 INFO sqlalchemy.engine.base.Engine (3829,)
2021-02-01 11:01:31,140 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,141 INFO sqlalchemy.engine.base.Engine (3830,)
2021-02-01 11:01:31,144 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,146 INFO sqlalchemy.engine.base.Engine (3831,)
2021-02-01 11:01:31,148 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,149 INFO sqlalchemy.engine.base.Engine (3832,)
2021-02-01 11:01:31,151 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,153 INFO sqlalchemy.engine.base.Engine (3833,)
2021-02-01 11:01:31,157 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,158 INFO sqlalchemy.engine.base.Engine (3834,)
2021-02-01 11:01:31,161 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,162 INFO sqlalchemy.engine.base.Engine (3835,)
2021-02-01 11:01:31,164 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,165 INFO sqlalchemy.engine.base.Engine (3836,)
2021-02-01 11:01:31,167 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,168 INFO sqlalchemy.engine.base.Engine (3837,)
2021-02-01 11:01:31,170 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,175 INFO sqlalchemy.engine.base.Engine (3838,)
2021-02-01 11:01:31,178 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:31,180 INFO sqlalchemy.engine.base.Engine (3839,)
2021-02-01 11:01:31,185 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,186 INFO sqlalchemy.engine.base.Engine (3840,)
2021-02-01 11:01:31,189 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,190 INFO sqlalchemy.engine.base.Engine (3841,)
2021-02-01 11:01:31,193 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,194 INFO sqlalchemy.engine.base.Engine (3842,)
2021-02-01 11:01:31,196 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,198 INFO sqlalchemy.engine.base.Engine (3843,)
2021-02-01 11:01:31,201 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,205 INFO sqlalchemy.engine.base.Engine (3844,)
2021-02-01 11:01:31,208 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,209 INFO sqlalchemy.engine.base.Engine (3845,)
2021-02-01 11:01:31,212 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,213 INFO sqlalchemy.engine.base.Engine (3846,)
2021-02-01 11:01:31,216 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,217 INFO sqlalchemy.engine.base.Engine (3847,)
2021-02-01 11:01:31,219 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,221 INFO sqlalchemy.engine.base.Engine (3848,)
2021-02-01 11:01:31,223 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,224 INFO sqlalchemy.engine.base.Engine (3849,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:31,401 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:31,402 INFO sqlalchemy.engine.base.Engine ('F78',)
2021-02-01 11:01:31,409 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:31,413 INFO sqlalchemy.engine.base.Engine ((3850, 14.3, 14.3, 14.3, 152885.90100002542, 122581.71113904846), (3851, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152885.90100002542, 122581.71113904846), (3852, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152885.90100002542, 122581.71113904846), (3853, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152885.90100002542, 122581.71113904846), (3854, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152885.90100002542, 122581.71113904846), (3855, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152885.90100002542, 122581.71113904846), (3856, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152885.90100002542, 122581.71113904846), (3857, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152885.90100002542, 122581.71113904846)  ... displaying 10 of 50 total bound parameter sets ...  (3898, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152885.90100002542, 122581.71113904846), (3899, 135.9, 135.9, 135.9, 152885.90100002542, 122581.71113904846))
2021-02-01 11:01:31,420 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:31,421 INFO sqlalchemy.engine.base.Engine ((1925, 'F78', 0, 'Anhydrite', 3850, 3851), (1926, 'F78', 1, 'Sandstone, grey, vf-f', 3852, 3853), (1927, 'F78', 2, 'Anhydrite', 3854, 3855), (1928, 'F78', 3, 'Dolomite', 3856, 3857), (1929, 'F78', 4, 'Anhydrite', 3858, 3859), (1930, 'F78', 5, 'Sandstone, grey, vf-f', 3860, 3861), (1931, 'F78', 6, 'Siltstone, red', 3862, 3863), (1932, 'F78', 7, 'Dolomite', 3864, 3865)  ... displaying 10 of 25 total bound parameter sets ...  (1948, 'F78', 23, 'Limestone', 3896, 3897), (1949, 'F78', 24, 'Volcanic', 3898, 3899))
2021-02-01 11:01:31,425 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:31,516 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:31,518 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:31,522 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:31,528 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:31,530 INFO sqlalchemy.engine.base.Engine ('F78',)
2021-02-01 11:01:31,540 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,542 INFO sqlalchemy.engine.base.Engine (3850,)
2021-02-01 11:01:31,545 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,555 INFO sqlalchemy.engine.base.Engine (3851,)
2021-02-01 11:01:31,557 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,558 INFO sqlalchemy.engine.base.Engine (3852,)

2021-02-01 11:01:31,560 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,562 INFO sqlalchemy.engine.base.Engine (3853,)
2021-02-01 11:01:31,566 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,568 INFO sqlalchemy.engine.base.Engine (3854,)
2021-02-01 11:01:31,570 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,572 INFO sqlalchemy.engine.base.Engine (3855,)
2021-02-01 11:01:31,575 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,577 INFO sqlalchemy.engine.base.Engine (3856,)
2021-02-01 11:01:31,580 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,581 INFO sqlalchemy.engine.base.Engine (3857,)
2021-02-01 11:01:31,583 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,584 INFO sqlalchemy.engine.base.Engine (3858,)
2021-02-01 11:01:31,587 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,588 INFO sqlalchemy.engine.base.Engine (3859,)
2021-02-01 11:01:31,590 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,591 INFO sqlalchemy.engine.base.Engine (3860,)
2021-02-01 11:01:31,594 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,598 INFO sqlalchemy.engine.base.Engine (3861,)
2021-02-01 11:01:31,601 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,603 INFO sqlalchemy.engine.base.Engine (3862,)
2021-02-01 11:01:31,606 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,607 INFO sqlalchemy.engine.base.Engine (3863,)
2021-02-01 11:01:31,611 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,613 INFO sqlalchemy.engine.base.Engine (3864,)
2021-02-01 11:01:31,615 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,618 INFO sqlalchemy.engine.base.Engine (3865,)
2021-02-01 11:01:31,622 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,625 INFO sqlalchemy.engine.base.Engine (3866,)
2021-02-01 11:01:31,627 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,629 INFO sqlalchemy.engine.base.Engine (3867,)
2021-02-01 11:01:31,631 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,632 INFO sqlalchemy.engine.base.Engine (3868,)
2021-02-01 11:01:31,635 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,636 INFO sqlalchemy.engine.base.Engine (3869,)
2021-02-01 11:01:31,640 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,642 INFO sqlalchemy.engine.base.Engine (3870,)
2021-02-01 11:01:31,644 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,647 INFO sqlalchemy.engine.base.Engine (3871,)
2021-02-01 11:01:31,650 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,652 INFO sqlalchemy.engine.base.Engine (3872,)
2021-02-01 11:01:31,654 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:31,655 INFO sqlalchemy.engine.base.Engine (3873,)
2021-02-01 11:01:31,658 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,659 INFO sqlalchemy.engine.base.Engine (3874,)
2021-02-01 11:01:31,661 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,662 INFO sqlalchemy.engine.base.Engine (3875,)
2021-02-01 11:01:31,665 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,666 INFO sqlalchemy.engine.base.Engine (3876,)
2021-02-01 11:01:31,669 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,670 INFO sqlalchemy.engine.base.Engine (3877,)
2021-02-01 11:01:31,672 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,673 INFO sqlalchemy.engine.base.Engine (3878,)
2021-02-01 11:01:31,675 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,678 INFO sqlalchemy.engine.base.Engine (3879,)
2021-02-01 11:01:31,682 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,683 INFO sqlalchemy.engine.base.Engine (3880,)
2021-02-01 11:01:31,685 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,686 INFO sqlalchemy.engine.base.Engine (3881,)
2021-02-01 11:01:31,687 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,688 INFO sqlalchemy.engine.base.Engine (3882,)
2021-02-01 11:01:31,690 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,691 INFO sqlalchemy.engine.base.Engine (3883,)
2021-02-01 11:01:31,693 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,695 INFO sqlalchemy.engine.base.Engine (3884,)
2021-02-01 11:01:31,699 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,700 INFO sqlalchemy.engine.base.Engine (3885,)
2021-02-01 11:01:31,704 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,709 INFO sqlalchemy.engine.base.Engine (3886,)
2021-02-01 11:01:31,711 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,713 INFO sqlalchemy.engine.base.Engine (3887,)
2021-02-01 11:01:31,716 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,718 INFO sqlalchemy.engine.base.Engine (3888,)
2021-02-01 11:01:31,720 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,721 INFO sqlalchemy.engine.base.Engine (3889,)
2021-02-01 11:01:31,724 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,725 INFO sqlalchemy.engine.base.Engine (3890,)
2021-02-01 11:01:31,728 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,729 INFO sqlalchemy.engine.base.Engine (3891,)
2021-02-01 11:01:31,732 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,732 INFO sqlalchemy.engine.base.Engine (3892,)
2021-02-01 11:01:31,735 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,735 INFO sqlalchemy.engine.base.Engine (3893,)
2021-02-01 11:01:31,738 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:31,739 INFO sqlalchemy.engine.base.Engine (3894,)
2021-02-01 11:01:31,741 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,742 INFO sqlalchemy.engine.base.Engine (3895,)
2021-02-01 11:01:31,744 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,745 INFO sqlalchemy.engine.base.Engine (3896,)
2021-02-01 11:01:31,747 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,749 INFO sqlalchemy.engine.base.Engine (3897,)
2021-02-01 11:01:31,751 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,752 INFO sqlalchemy.engine.base.Engine (3898,)
2021-02-01 11:01:31,753 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:31,754 INFO sqlalchemy.engine.base.Engine (3899,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:31,940 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:31,944 INFO sqlalchemy.engine.base.Engine ((3900, 14.3, 14.3, 14.3, 152886.0900000254, 122578.42713904569), (3901, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152886.0900000254, 122578.42713904569), (3902, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152886.0900000254, 122578.42713904569), (3903, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152886.0900000254, 122578.42713904569), (3904, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152886.0900000254, 122578.42713904569), (3905, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152886.0900000254, 122578.42713904569), (3906, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152886.0900000254, 122578.42713904569), (3907, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152886.0900000254, 122578.42713904569)  ... displaying 10 of 50 total bound parameter sets ...  (3948, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152886.0900000254, 122578.42713904569), (3949, 135.9, 135.9, 135.9, 152886.0900000254, 122578.42713904569))
2021-02-01 11:01:31,947 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:31,948 INFO sqlalchemy.engine.base.Engine ('F79',)
2021-02-01 11:01:31,954 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:31,955 INFO sqlalchemy.engine.base.Engine ((1950, 'F79', 0, 'Anhydrite', 3900, 3901), (1951, 'F79', 1, 'Sandstone, grey, vf-f', 3902, 3903), (1952, 'F79', 2, 'Anhydrite', 3904, 3905), (1953, 'F79', 3, 'Dolomite', 3906, 3907), (1954, 'F79', 4, 'Anhydrite', 3908, 3909), (1955, 'F79', 5, 'Sandstone, grey, vf-f', 3910, 3911), (1956, 'F79', 6, 'Siltstone, red', 3912, 3913), (1957, 'F79', 7, 'Dolomite', 3914, 3915)  ... displaying 10 of 25 total bound parameter sets ...  (1973, 'F79', 23, 'Limestone', 3946, 3947), (1974, 'F79', 24, 'Volcanic', 3948, 3949))
2021-02-01 11:01:31,963 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:32,059 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:32,062 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:32,063 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:32,066 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:32,068 INFO sqlalchemy.engine.base.Engine ('F79',)
2021-02-01 11:01:32,071 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,073 INFO sqlalchemy.engine.base.Engine (3900,)
2021-02-01 11:01:32,075 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,077 INFO sqlalchemy.engine.base.Engine (3901,)
2021-02-01 11:01:32,080 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,081 INFO sqlalchemy.engine.base.Engine (3902,)
2021-02-01 11:01:32,083 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,086 INFO sqlalchemy.engine.base.Engine (3903,)
2021-02-01 11:01:32,088 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,089 INFO sqlalchemy.engine.base.Engine (3904,)
2021-02-01 11:01:32,090 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,098 INFO sqlalchemy.engine.base.Engine (3905,)
2021-02-01 11:01:32,106 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,113 INFO sqlalchemy.engine.base.Engine (3906,)
2021-02-01 11:01:32,116 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,117 INFO sqlalchemy.engine.base.Engine (3907,)

2021-02-01 11:01:32,119 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,120 INFO sqlalchemy.engine.base.Engine (3908,)
2021-02-01 11:01:32,123 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,124 INFO sqlalchemy.engine.base.Engine (3909,)
2021-02-01 11:01:32,127 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,128 INFO sqlalchemy.engine.base.Engine (3910,)
2021-02-01 11:01:32,131 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,132 INFO sqlalchemy.engine.base.Engine (3911,)
2021-02-01 11:01:32,134 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,135 INFO sqlalchemy.engine.base.Engine (3912,)
2021-02-01 11:01:32,137 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,139 INFO sqlalchemy.engine.base.Engine (3913,)
2021-02-01 11:01:32,141 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,142 INFO sqlalchemy.engine.base.Engine (3914,)
2021-02-01 11:01:32,144 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,147 INFO sqlalchemy.engine.base.Engine (3915,)
2021-02-01 11:01:32,153 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,154 INFO sqlalchemy.engine.base.Engine (3916,)
2021-02-01 11:01:32,157 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,159 INFO sqlalchemy.engine.base.Engine (3917,)
2021-02-01 11:01:32,161 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,163 INFO sqlalchemy.engine.base.Engine (3918,)
2021-02-01 11:01:32,167 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,169 INFO sqlalchemy.engine.base.Engine (3919,)
2021-02-01 11:01:32,171 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,172 INFO sqlalchemy.engine.base.Engine (3920,)
2021-02-01 11:01:32,174 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,175 INFO sqlalchemy.engine.base.Engine (3921,)
2021-02-01 11:01:32,178 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,183 INFO sqlalchemy.engine.base.Engine (3922,)
2021-02-01 11:01:32,190 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,191 INFO sqlalchemy.engine.base.Engine (3923,)
2021-02-01 11:01:32,196 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,197 INFO sqlalchemy.engine.base.Engine (3924,)
2021-02-01 11:01:32,199 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,200 INFO sqlalchemy.engine.base.Engine (3925,)
2021-02-01 11:01:32,202 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,203 INFO sqlalchemy.engine.base.Engine (3926,)
2021-02-01 11:01:32,206 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,207 INFO sqlalchemy.engine.base.Engine (3927,)
2021-02-01 11:01:32,209 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:32,211 INFO sqlalchemy.engine.base.Engine (3928,)
2021-02-01 11:01:32,213 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,215 INFO sqlalchemy.engine.base.Engine (3929,)
2021-02-01 11:01:32,217 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,218 INFO sqlalchemy.engine.base.Engine (3930,)
2021-02-01 11:01:32,220 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,221 INFO sqlalchemy.engine.base.Engine (3931,)
2021-02-01 11:01:32,223 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,226 INFO sqlalchemy.engine.base.Engine (3932,)
2021-02-01 11:01:32,228 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,229 INFO sqlalchemy.engine.base.Engine (3933,)
2021-02-01 11:01:32,231 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,232 INFO sqlalchemy.engine.base.Engine (3934,)
2021-02-01 11:01:32,234 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,236 INFO sqlalchemy.engine.base.Engine (3935,)
2021-02-01 11:01:32,238 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,239 INFO sqlalchemy.engine.base.Engine (3936,)
2021-02-01 11:01:32,241 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,242 INFO sqlalchemy.engine.base.Engine (3937,)
2021-02-01 11:01:32,244 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,245 INFO sqlalchemy.engine.base.Engine (3938,)
2021-02-01 11:01:32,247 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,247 INFO sqlalchemy.engine.base.Engine (3939,)
2021-02-01 11:01:32,249 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,251 INFO sqlalchemy.engine.base.Engine (3940,)
2021-02-01 11:01:32,253 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,253 INFO sqlalchemy.engine.base.Engine (3941,)
2021-02-01 11:01:32,259 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,261 INFO sqlalchemy.engine.base.Engine (3942,)
2021-02-01 11:01:32,263 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,265 INFO sqlalchemy.engine.base.Engine (3943,)
2021-02-01 11:01:32,268 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,269 INFO sqlalchemy.engine.base.Engine (3944,)
2021-02-01 11:01:32,271 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,272 INFO sqlalchemy.engine.base.Engine (3945,)
2021-02-01 11:01:32,274 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,277 INFO sqlalchemy.engine.base.Engine (3946,)
2021-02-01 11:01:32,279 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,281 INFO sqlalchemy.engine.base.Engine (3947,)
2021-02-01 11:01:32,282 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,284 INFO sqlalchemy.engine.base.Engine (3948,)
2021-02-01 11:01:32,287 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:32,288 INFO sqlalchemy.engine.base.Engine (3949,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:32,449 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:32,454 INFO sqlalchemy.engine.base.Engine ((3950, 14.3, 14.3, 14.3, 152883.68000002546, 122577.58713904768), (3951, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152883.68000002546, 122577.58713904768), (3952, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152883.68000002546, 122577.58713904768), (3953, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152883.68000002546, 122577.58713904768), (3954, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152883.68000002546, 122577.58713904768), (3955, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152883.68000002546, 122577.58713904768), (3956, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152883.68000002546, 122577.58713904768), (3957, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152883.68000002546, 122577.58713904768)  ... displaying 10 of 50 total bound parameter sets ...  (3998, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152883.68000002546, 122577.58713904768), (3999, 135.9, 135.9, 135.9, 152883.68000002546, 122577.58713904768))
2021-02-01 11:01:32,460 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:32,461 INFO sqlalchemy.engine.base.Engine ('F80',)
2021-02-01 11:01:32,466 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:32,467 INFO sqlalchemy.engine.base.Engine ((1975, 'F80', 0, 'Anhydrite', 3950, 3951), (1976, 'F80', 1, 'Sandstone, grey, vf-f', 3952, 3953), (1977, 'F80', 2, 'Anhydrite', 3954, 3955), (1978, 'F80', 3, 'Dolomite', 3956, 3957), (1979, 'F80', 4, 'Anhydrite', 3958, 3959), (1980, 'F80', 5, 'Sandstone, grey, vf-f', 3960, 3961), (1981, 'F80', 6, 'Siltstone, red', 3962, 3963), (1982, 'F80', 7, 'Dolomite', 3964, 3965)  ... displaying 10 of 25 total bound parameter sets ...  (1998, 'F80', 23, 'Limestone', 3996, 3997), (1999, 'F80', 24, 'Volcanic', 3998, 3999))
2021-02-01 11:01:32,477 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:32,570 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:32,572 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:32,574 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:32,578 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:32,579 INFO sqlalchemy.engine.base.Engine ('F80',)
2021-02-01 11:01:32,582 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,583 INFO sqlalchemy.engine.base.Engine (3950,)
2021-02-01 11:01:32,586 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,588 INFO sqlalchemy.engine.base.Engine (3951,)
2021-02-01 11:01:32,590 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,591 INFO sqlalchemy.engine.base.Engine (3952,)
2021-02-01 11:01:32,593 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,595 INFO sqlalchemy.engine.base.Engine (3953,)
2021-02-01 11:01:32,597 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,598 INFO sqlalchemy.engine.base.Engine (3954,)
2021-02-01 11:01:32,601 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,602 INFO sqlalchemy.engine.base.Engine (3955,)
2021-02-01 11:01:32,604 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,606 INFO sqlalchemy.engine.base.Engine (3956,)
2021-02-01 11:01:32,608 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,609 INFO sqlalchemy.engine.base.Engine (3957,)
2021-02-01 11:01:32,611 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,613 INFO sqlalchemy.engine.base.Engine (3958,)
2021-02-01 11:01:32,615 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,616 INFO sqlalchemy.engine.base.Engine (3959,)
2021-02-01 11:01:32,618 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,620 INFO sqlalchemy.engine.base.Engine (3960,)
2021-02-01 11:01:32,624 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,625 INFO sqlalchemy.engine.base.Engine (3961,)
2021-02-01 11:01:32,627 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,629 INFO sqlalchemy.engine.base.Engine (3962,)

2021-02-01 11:01:32,631 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,632 INFO sqlalchemy.engine.base.Engine (3963,)
2021-02-01 11:01:32,634 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,637 INFO sqlalchemy.engine.base.Engine (3964,)
2021-02-01 11:01:32,640 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,641 INFO sqlalchemy.engine.base.Engine (3965,)
2021-02-01 11:01:32,643 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,646 INFO sqlalchemy.engine.base.Engine (3966,)
2021-02-01 11:01:32,649 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,650 INFO sqlalchemy.engine.base.Engine (3967,)
2021-02-01 11:01:32,652 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,654 INFO sqlalchemy.engine.base.Engine (3968,)
2021-02-01 11:01:32,656 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,658 INFO sqlalchemy.engine.base.Engine (3969,)
2021-02-01 11:01:32,667 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,668 INFO sqlalchemy.engine.base.Engine (3970,)
2021-02-01 11:01:32,670 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,672 INFO sqlalchemy.engine.base.Engine (3971,)
2021-02-01 11:01:32,675 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,677 INFO sqlalchemy.engine.base.Engine (3972,)
2021-02-01 11:01:32,681 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,682 INFO sqlalchemy.engine.base.Engine (3973,)
2021-02-01 11:01:32,684 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,688 INFO sqlalchemy.engine.base.Engine (3974,)
2021-02-01 11:01:32,692 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,693 INFO sqlalchemy.engine.base.Engine (3975,)
2021-02-01 11:01:32,696 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,697 INFO sqlalchemy.engine.base.Engine (3976,)
2021-02-01 11:01:32,699 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,700 INFO sqlalchemy.engine.base.Engine (3977,)
2021-02-01 11:01:32,703 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,705 INFO sqlalchemy.engine.base.Engine (3978,)
2021-02-01 11:01:32,707 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,711 INFO sqlalchemy.engine.base.Engine (3979,)
2021-02-01 11:01:32,716 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,719 INFO sqlalchemy.engine.base.Engine (3980,)
2021-02-01 11:01:32,720 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,724 INFO sqlalchemy.engine.base.Engine (3981,)
2021-02-01 11:01:32,727 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,728 INFO sqlalchemy.engine.base.Engine (3982,)
2021-02-01 11:01:32,730 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:32,732 INFO sqlalchemy.engine.base.Engine (3983,)
2021-02-01 11:01:32,734 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,735 INFO sqlalchemy.engine.base.Engine (3984,)
2021-02-01 11:01:32,738 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,742 INFO sqlalchemy.engine.base.Engine (3985,)
2021-02-01 11:01:32,746 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,748 INFO sqlalchemy.engine.base.Engine (3986,)
2021-02-01 11:01:32,750 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,751 INFO sqlalchemy.engine.base.Engine (3987,)
2021-02-01 11:01:32,753 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,755 INFO sqlalchemy.engine.base.Engine (3988,)
2021-02-01 11:01:32,757 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,758 INFO sqlalchemy.engine.base.Engine (3989,)
2021-02-01 11:01:32,760 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,761 INFO sqlalchemy.engine.base.Engine (3990,)
2021-02-01 11:01:32,763 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,765 INFO sqlalchemy.engine.base.Engine (3991,)
2021-02-01 11:01:32,769 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,770 INFO sqlalchemy.engine.base.Engine (3992,)
2021-02-01 11:01:32,773 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,774 INFO sqlalchemy.engine.base.Engine (3993,)
2021-02-01 11:01:32,776 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,777 INFO sqlalchemy.engine.base.Engine (3994,)
2021-02-01 11:01:32,780 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,781 INFO sqlalchemy.engine.base.Engine (3995,)
2021-02-01 11:01:32,784 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,786 INFO sqlalchemy.engine.base.Engine (3996,)
2021-02-01 11:01:32,788 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,789 INFO sqlalchemy.engine.base.Engine (3997,)
2021-02-01 11:01:32,791 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,792 INFO sqlalchemy.engine.base.Engine (3998,)
2021-02-01 11:01:32,796 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:32,797 INFO sqlalchemy.engine.base.Engine (3999,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:32,932 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:32,934 INFO sqlalchemy.engine.base.Engine ('F81',)
2021-02-01 11:01:32,938 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:32,944 INFO sqlalchemy.engine.base.Engine ((4000, 14.3, 14.3, 14.3, 152884.2410000254, 122576.7521390468), (4001, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152884.2410000254, 122576.7521390468), (4002, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152884.2410000254, 122576.7521390468), (4003, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152884.2410000254, 122576.7521390468), (4004, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152884.2410000254, 122576.7521390468), (4005, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152884.2410000254, 122576.7521390468), (4006, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152884.2410000254, 122576.7521390468), (4007, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152884.2410000254, 122576.7521390468)  ... displaying 10 of 50 total bound parameter sets ...  (4048, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152884.2410000254, 122576.7521390468), (4049, 135.9, 135.9, 135.9, 152884.2410000254, 122576.7521390468))
2021-02-01 11:01:32,953 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:32,954 INFO sqlalchemy.engine.base.Engine ((2000, 'F81', 0, 'Anhydrite', 4000, 4001), (2001, 'F81', 1, 'Sandstone, grey, vf-f', 4002, 4003), (2002, 'F81', 2, 'Anhydrite', 4004, 4005), (2003, 'F81', 3, 'Dolomite', 4006, 4007), (2004, 'F81', 4, 'Anhydrite', 4008, 4009), (2005, 'F81', 5, 'Sandstone, grey, vf-f', 4010, 4011), (2006, 'F81', 6, 'Siltstone, red', 4012, 4013), (2007, 'F81', 7, 'Dolomite', 4014, 4015)  ... displaying 10 of 25 total bound parameter sets ...  (2023, 'F81', 23, 'Limestone', 4046, 4047), (2024, 'F81', 24, 'Volcanic', 4048, 4049))

2021-02-01 11:01:32,957 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:33,058 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:33,061 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:33,064 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:33,070 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:33,072 INFO sqlalchemy.engine.base.Engine ('F81',)
2021-02-01 11:01:33,080 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,081 INFO sqlalchemy.engine.base.Engine (4000,)
2021-02-01 11:01:33,084 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,085 INFO sqlalchemy.engine.base.Engine (4001,)
2021-02-01 11:01:33,090 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,091 INFO sqlalchemy.engine.base.Engine (4002,)
2021-02-01 11:01:33,094 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,096 INFO sqlalchemy.engine.base.Engine (4003,)
2021-02-01 11:01:33,099 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,100 INFO sqlalchemy.engine.base.Engine (4004,)
2021-02-01 11:01:33,102 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,103 INFO sqlalchemy.engine.base.Engine (4005,)
2021-02-01 11:01:33,108 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,110 INFO sqlalchemy.engine.base.Engine (4006,)
2021-02-01 11:01:33,113 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,119 INFO sqlalchemy.engine.base.Engine (4007,)
2021-02-01 11:01:33,123 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,124 INFO sqlalchemy.engine.base.Engine (4008,)
2021-02-01 11:01:33,125 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,126 INFO sqlalchemy.engine.base.Engine (4009,)
2021-02-01 11:01:33,128 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,129 INFO sqlalchemy.engine.base.Engine (4010,)
2021-02-01 11:01:33,134 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,135 INFO sqlalchemy.engine.base.Engine (4011,)
2021-02-01 11:01:33,138 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,139 INFO sqlalchemy.engine.base.Engine (4012,)
2021-02-01 11:01:33,144 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,147 INFO sqlalchemy.engine.base.Engine (4013,)
2021-02-01 11:01:33,150 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,152 INFO sqlalchemy.engine.base.Engine (4014,)
2021-02-01 11:01:33,154 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,156 INFO sqlalchemy.engine.base.Engine (4015,)
2021-02-01 11:01:33,159 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,160 INFO sqlalchemy.engine.base.Engine (4016,)
2021-02-01 11:01:33,166 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,167 INFO sqlalchemy.engine.base.Engine (4017,)
2021-02-01 11:01:33,169 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:33,170 INFO sqlalchemy.engine.base.Engine (4018,)
2021-02-01 11:01:33,172 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,174 INFO sqlalchemy.engine.base.Engine (4019,)
2021-02-01 11:01:33,176 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,177 INFO sqlalchemy.engine.base.Engine (4020,)
2021-02-01 11:01:33,180 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,182 INFO sqlalchemy.engine.base.Engine (4021,)
2021-02-01 11:01:33,184 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,185 INFO sqlalchemy.engine.base.Engine (4022,)
2021-02-01 11:01:33,187 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,188 INFO sqlalchemy.engine.base.Engine (4023,)
2021-02-01 11:01:33,191 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,192 INFO sqlalchemy.engine.base.Engine (4024,)
2021-02-01 11:01:33,195 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,196 INFO sqlalchemy.engine.base.Engine (4025,)
2021-02-01 11:01:33,198 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,199 INFO sqlalchemy.engine.base.Engine (4026,)
2021-02-01 11:01:33,201 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,202 INFO sqlalchemy.engine.base.Engine (4027,)
2021-02-01 11:01:33,205 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,207 INFO sqlalchemy.engine.base.Engine (4028,)
2021-02-01 11:01:33,209 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,210 INFO sqlalchemy.engine.base.Engine (4029,)
2021-02-01 11:01:33,213 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,214 INFO sqlalchemy.engine.base.Engine (4030,)
2021-02-01 11:01:33,216 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,217 INFO sqlalchemy.engine.base.Engine (4031,)
2021-02-01 11:01:33,220 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,220 INFO sqlalchemy.engine.base.Engine (4032,)
2021-02-01 11:01:33,222 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,223 INFO sqlalchemy.engine.base.Engine (4033,)
2021-02-01 11:01:33,226 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,226 INFO sqlalchemy.engine.base.Engine (4034,)
2021-02-01 11:01:33,229 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,230 INFO sqlalchemy.engine.base.Engine (4035,)
2021-02-01 11:01:33,233 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,234 INFO sqlalchemy.engine.base.Engine (4036,)
2021-02-01 11:01:33,236 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,237 INFO sqlalchemy.engine.base.Engine (4037,)
2021-02-01 11:01:33,241 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,242 INFO sqlalchemy.engine.base.Engine (4038,)
2021-02-01 11:01:33,244 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:33,245 INFO sqlalchemy.engine.base.Engine (4039,)
2021-02-01 11:01:33,249 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,251 INFO sqlalchemy.engine.base.Engine (4040,)
2021-02-01 11:01:33,254 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,257 INFO sqlalchemy.engine.base.Engine (4041,)
2021-02-01 11:01:33,262 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,263 INFO sqlalchemy.engine.base.Engine (4042,)
2021-02-01 11:01:33,265 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,267 INFO sqlalchemy.engine.base.Engine (4043,)
2021-02-01 11:01:33,271 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,272 INFO sqlalchemy.engine.base.Engine (4044,)
2021-02-01 11:01:33,274 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,275 INFO sqlalchemy.engine.base.Engine (4045,)
2021-02-01 11:01:33,279 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,281 INFO sqlalchemy.engine.base.Engine (4046,)
2021-02-01 11:01:33,283 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,284 INFO sqlalchemy.engine.base.Engine (4047,)
2021-02-01 11:01:33,287 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,288 INFO sqlalchemy.engine.base.Engine (4048,)
2021-02-01 11:01:33,290 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,293 INFO sqlalchemy.engine.base.Engine (4049,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:33,422 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:33,423 INFO sqlalchemy.engine.base.Engine ((4050, 14.3, 14.3, 14.3, 152888.63600002538, 122578.79613904748), (4051, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.63600002538, 122578.79613904748), (4052, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152888.63600002538, 122578.79613904748), (4053, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.63600002538, 122578.79613904748), (4054, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152888.63600002538, 122578.79613904748), (4055, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.63600002538, 122578.79613904748), (4056, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152888.63600002538, 122578.79613904748), (4057, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152888.63600002538, 122578.79613904748)  ... displaying 10 of 50 total bound parameter sets ...  (4098, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152888.63600002538, 122578.79613904748), (4099, 135.9, 135.9, 135.9, 152888.63600002538, 122578.79613904748))
2021-02-01 11:01:33,426 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:33,428 INFO sqlalchemy.engine.base.Engine ('F82',)
2021-02-01 11:01:33,435 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:33,436 INFO sqlalchemy.engine.base.Engine ((2025, 'F82', 0, 'Anhydrite', 4050, 4051), (2026, 'F82', 1, 'Sandstone, grey, vf-f', 4052, 4053), (2027, 'F82', 2, 'Anhydrite', 4054, 4055), (2028, 'F82', 3, 'Dolomite', 4056, 4057), (2029, 'F82', 4, 'Anhydrite', 4058, 4059), (2030, 'F82', 5, 'Sandstone, grey, vf-f', 4060, 4061), (2031, 'F82', 6, 'Siltstone, red', 4062, 4063), (2032, 'F82', 7, 'Dolomite', 4064, 4065)  ... displaying 10 of 25 total bound parameter sets ...  (2048, 'F82', 23, 'Limestone', 4096, 4097), (2049, 'F82', 24, 'Volcanic', 4098, 4099))
2021-02-01 11:01:33,441 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:33,586 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:33,588 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:33,590 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:33,594 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:33,595 INFO sqlalchemy.engine.base.Engine ('F82',)
2021-02-01 11:01:33,601 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,603 INFO sqlalchemy.engine.base.Engine (4050,)
2021-02-01 11:01:33,605 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,607 INFO sqlalchemy.engine.base.Engine (4051,)
2021-02-01 11:01:33,609 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,611 INFO sqlalchemy.engine.base.Engine (4052,)

2021-02-01 11:01:33,613 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,617 INFO sqlalchemy.engine.base.Engine (4053,)
2021-02-01 11:01:33,620 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,621 INFO sqlalchemy.engine.base.Engine (4054,)
2021-02-01 11:01:33,624 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,625 INFO sqlalchemy.engine.base.Engine (4055,)
2021-02-01 11:01:33,629 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,630 INFO sqlalchemy.engine.base.Engine (4056,)
2021-02-01 11:01:33,633 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,634 INFO sqlalchemy.engine.base.Engine (4057,)
2021-02-01 11:01:33,637 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,640 INFO sqlalchemy.engine.base.Engine (4058,)
2021-02-01 11:01:33,642 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,643 INFO sqlalchemy.engine.base.Engine (4059,)
2021-02-01 11:01:33,648 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,649 INFO sqlalchemy.engine.base.Engine (4060,)
2021-02-01 11:01:33,652 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,654 INFO sqlalchemy.engine.base.Engine (4061,)
2021-02-01 11:01:33,658 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,659 INFO sqlalchemy.engine.base.Engine (4062,)
2021-02-01 11:01:33,661 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,663 INFO sqlalchemy.engine.base.Engine (4063,)
2021-02-01 11:01:33,666 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,668 INFO sqlalchemy.engine.base.Engine (4064,)
2021-02-01 11:01:33,671 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,673 INFO sqlalchemy.engine.base.Engine (4065,)
2021-02-01 11:01:33,677 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,678 INFO sqlalchemy.engine.base.Engine (4066,)
2021-02-01 11:01:33,682 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,684 INFO sqlalchemy.engine.base.Engine (4067,)
2021-02-01 11:01:33,686 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,687 INFO sqlalchemy.engine.base.Engine (4068,)
2021-02-01 11:01:33,689 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,690 INFO sqlalchemy.engine.base.Engine (4069,)
2021-02-01 11:01:33,693 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,694 INFO sqlalchemy.engine.base.Engine (4070,)
2021-02-01 11:01:33,697 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,698 INFO sqlalchemy.engine.base.Engine (4071,)
2021-02-01 11:01:33,700 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,701 INFO sqlalchemy.engine.base.Engine (4072,)
2021-02-01 11:01:33,704 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:33,705 INFO sqlalchemy.engine.base.Engine (4073,)
2021-02-01 11:01:33,708 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,709 INFO sqlalchemy.engine.base.Engine (4074,)
2021-02-01 11:01:33,712 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,714 INFO sqlalchemy.engine.base.Engine (4075,)
2021-02-01 11:01:33,716 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,717 INFO sqlalchemy.engine.base.Engine (4076,)
2021-02-01 11:01:33,720 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,721 INFO sqlalchemy.engine.base.Engine (4077,)
2021-02-01 11:01:33,724 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,725 INFO sqlalchemy.engine.base.Engine (4078,)
2021-02-01 11:01:33,727 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,729 INFO sqlalchemy.engine.base.Engine (4079,)
2021-02-01 11:01:33,731 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,734 INFO sqlalchemy.engine.base.Engine (4080,)
2021-02-01 11:01:33,736 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,737 INFO sqlalchemy.engine.base.Engine (4081,)
2021-02-01 11:01:33,739 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,741 INFO sqlalchemy.engine.base.Engine (4082,)
2021-02-01 11:01:33,743 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,744 INFO sqlalchemy.engine.base.Engine (4083,)
2021-02-01 11:01:33,748 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,752 INFO sqlalchemy.engine.base.Engine (4084,)
2021-02-01 11:01:33,755 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,756 INFO sqlalchemy.engine.base.Engine (4085,)
2021-02-01 11:01:33,758 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,759 INFO sqlalchemy.engine.base.Engine (4086,)
2021-02-01 11:01:33,762 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,764 INFO sqlalchemy.engine.base.Engine (4087,)
2021-02-01 11:01:33,767 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,768 INFO sqlalchemy.engine.base.Engine (4088,)
2021-02-01 11:01:33,770 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,772 INFO sqlalchemy.engine.base.Engine (4089,)
2021-02-01 11:01:33,774 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,776 INFO sqlalchemy.engine.base.Engine (4090,)
2021-02-01 11:01:33,780 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,782 INFO sqlalchemy.engine.base.Engine (4091,)
2021-02-01 11:01:33,785 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,787 INFO sqlalchemy.engine.base.Engine (4092,)
2021-02-01 11:01:33,789 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,791 INFO sqlalchemy.engine.base.Engine (4093,)
2021-02-01 11:01:33,793 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:33,795 INFO sqlalchemy.engine.base.Engine (4094,)
2021-02-01 11:01:33,798 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,799 INFO sqlalchemy.engine.base.Engine (4095,)
2021-02-01 11:01:33,803 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,804 INFO sqlalchemy.engine.base.Engine (4096,)
2021-02-01 11:01:33,807 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,808 INFO sqlalchemy.engine.base.Engine (4097,)
2021-02-01 11:01:33,811 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,812 INFO sqlalchemy.engine.base.Engine (4098,)
2021-02-01 11:01:33,815 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:33,816 INFO sqlalchemy.engine.base.Engine (4099,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:33,964 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:33,966 INFO sqlalchemy.engine.base.Engine ('F83',)
2021-02-01 11:01:33,970 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:33,971 INFO sqlalchemy.engine.base.Engine ((4100, 14.3, 14.3, 14.3, 152887.36800002542, 122581.0071390476), (4101, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152887.36800002542, 122581.0071390476), (4102, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152887.36800002542, 122581.0071390476), (4103, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152887.36800002542, 122581.0071390476), (4104, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152887.36800002542, 122581.0071390476), (4105, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152887.36800002542, 122581.0071390476), (4106, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152887.36800002542, 122581.0071390476), (4107, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152887.36800002542, 122581.0071390476)  ... displaying 10 of 50 total bound parameter sets ...  (4148, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152887.36800002542, 122581.0071390476), (4149, 135.9, 135.9, 135.9, 152887.36800002542, 122581.0071390476))
2021-02-01 11:01:33,983 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:33,985 INFO sqlalchemy.engine.base.Engine ((2050, 'F83', 0, 'Anhydrite', 4100, 4101), (2051, 'F83', 1, 'Sandstone, grey, vf-f', 4102, 4103), (2052, 'F83', 2, 'Anhydrite', 4104, 4105), (2053, 'F83', 3, 'Dolomite', 4106, 4107), (2054, 'F83', 4, 'Anhydrite', 4108, 4109), (2055, 'F83', 5, 'Sandstone, grey, vf-f', 4110, 4111), (2056, 'F83', 6, 'Siltstone, red', 4112, 4113), (2057, 'F83', 7, 'Dolomite', 4114, 4115)  ... displaying 10 of 25 total bound parameter sets ...  (2073, 'F83', 23, 'Limestone', 4146, 4147), (2074, 'F83', 24, 'Volcanic', 4148, 4149))
2021-02-01 11:01:33,993 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:34,102 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:34,103 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:34,104 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:34,108 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:34,110 INFO sqlalchemy.engine.base.Engine ('F83',)
2021-02-01 11:01:34,115 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,116 INFO sqlalchemy.engine.base.Engine (4100,)
2021-02-01 11:01:34,119 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,120 INFO sqlalchemy.engine.base.Engine (4101,)
2021-02-01 11:01:34,122 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,123 INFO sqlalchemy.engine.base.Engine (4102,)
2021-02-01 11:01:34,125 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,127 INFO sqlalchemy.engine.base.Engine (4103,)
2021-02-01 11:01:34,132 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,135 INFO sqlalchemy.engine.base.Engine (4104,)
2021-02-01 11:01:34,138 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,139 INFO sqlalchemy.engine.base.Engine (4105,)
2021-02-01 11:01:34,143 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,144 INFO sqlalchemy.engine.base.Engine (4106,)
2021-02-01 11:01:34,147 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,148 INFO sqlalchemy.engine.base.Engine (4107,)

2021-02-01 11:01:34,155 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,156 INFO sqlalchemy.engine.base.Engine (4108,)
2021-02-01 11:01:34,159 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,160 INFO sqlalchemy.engine.base.Engine (4109,)
2021-02-01 11:01:34,162 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,164 INFO sqlalchemy.engine.base.Engine (4110,)
2021-02-01 11:01:34,167 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,168 INFO sqlalchemy.engine.base.Engine (4111,)
2021-02-01 11:01:34,173 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,174 INFO sqlalchemy.engine.base.Engine (4112,)
2021-02-01 11:01:34,177 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,178 INFO sqlalchemy.engine.base.Engine (4113,)
2021-02-01 11:01:34,180 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,182 INFO sqlalchemy.engine.base.Engine (4114,)
2021-02-01 11:01:34,187 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,191 INFO sqlalchemy.engine.base.Engine (4115,)
2021-02-01 11:01:34,194 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,195 INFO sqlalchemy.engine.base.Engine (4116,)
2021-02-01 11:01:34,198 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,199 INFO sqlalchemy.engine.base.Engine (4117,)
2021-02-01 11:01:34,205 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,206 INFO sqlalchemy.engine.base.Engine (4118,)
2021-02-01 11:01:34,208 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,210 INFO sqlalchemy.engine.base.Engine (4119,)
2021-02-01 11:01:34,212 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,214 INFO sqlalchemy.engine.base.Engine (4120,)
2021-02-01 11:01:34,216 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,217 INFO sqlalchemy.engine.base.Engine (4121,)
2021-02-01 11:01:34,221 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,222 INFO sqlalchemy.engine.base.Engine (4122,)
2021-02-01 11:01:34,225 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,226 INFO sqlalchemy.engine.base.Engine (4123,)
2021-02-01 11:01:34,229 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,231 INFO sqlalchemy.engine.base.Engine (4124,)
2021-02-01 11:01:34,236 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,238 INFO sqlalchemy.engine.base.Engine (4125,)
2021-02-01 11:01:34,240 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,241 INFO sqlalchemy.engine.base.Engine (4126,)
2021-02-01 11:01:34,244 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,245 INFO sqlalchemy.engine.base.Engine (4127,)
2021-02-01 11:01:34,248 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:34,249 INFO sqlalchemy.engine.base.Engine (4128,)
2021-02-01 11:01:34,252 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,253 INFO sqlalchemy.engine.base.Engine (4129,)
2021-02-01 11:01:34,256 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,257 INFO sqlalchemy.engine.base.Engine (4130,)
2021-02-01 11:01:34,259 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,261 INFO sqlalchemy.engine.base.Engine (4131,)
2021-02-01 11:01:34,265 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,266 INFO sqlalchemy.engine.base.Engine (4132,)
2021-02-01 11:01:34,273 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,274 INFO sqlalchemy.engine.base.Engine (4133,)
2021-02-01 11:01:34,277 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,279 INFO sqlalchemy.engine.base.Engine (4134,)
2021-02-01 11:01:34,282 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,284 INFO sqlalchemy.engine.base.Engine (4135,)
2021-02-01 11:01:34,286 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,287 INFO sqlalchemy.engine.base.Engine (4136,)
2021-02-01 11:01:34,290 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,291 INFO sqlalchemy.engine.base.Engine (4137,)
2021-02-01 11:01:34,294 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,296 INFO sqlalchemy.engine.base.Engine (4138,)
2021-02-01 11:01:34,298 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,299 INFO sqlalchemy.engine.base.Engine (4139,)
2021-02-01 11:01:34,301 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,303 INFO sqlalchemy.engine.base.Engine (4140,)
2021-02-01 11:01:34,305 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,306 INFO sqlalchemy.engine.base.Engine (4141,)
2021-02-01 11:01:34,309 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,312 INFO sqlalchemy.engine.base.Engine (4142,)
2021-02-01 11:01:34,315 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,316 INFO sqlalchemy.engine.base.Engine (4143,)
2021-02-01 11:01:34,318 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,320 INFO sqlalchemy.engine.base.Engine (4144,)
2021-02-01 11:01:34,324 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,325 INFO sqlalchemy.engine.base.Engine (4145,)
2021-02-01 11:01:34,328 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,329 INFO sqlalchemy.engine.base.Engine (4146,)
2021-02-01 11:01:34,332 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,334 INFO sqlalchemy.engine.base.Engine (4147,)
2021-02-01 11:01:34,337 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,338 INFO sqlalchemy.engine.base.Engine (4148,)
2021-02-01 11:01:34,340 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:34,342 INFO sqlalchemy.engine.base.Engine (4149,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:34,470 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:34,472 INFO sqlalchemy.engine.base.Engine ('F84',)
2021-02-01 11:01:34,477 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:34,478 INFO sqlalchemy.engine.base.Engine ((4150, 14.3, 14.3, 14.3, 152893.12600002546, 122602.45613904766), (4151, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152893.12600002546, 122602.45613904766), (4152, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152893.12600002546, 122602.45613904766), (4153, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152893.12600002546, 122602.45613904766), (4154, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152893.12600002546, 122602.45613904766), (4155, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152893.12600002546, 122602.45613904766), (4156, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152893.12600002546, 122602.45613904766), (4157, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152893.12600002546, 122602.45613904766)  ... displaying 10 of 50 total bound parameter sets ...  (4198, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152893.12600002546, 122602.45613904766), (4199, 135.9, 135.9, 135.9, 152893.12600002546, 122602.45613904766))
2021-02-01 11:01:34,487 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:34,488 INFO sqlalchemy.engine.base.Engine ((2075, 'F84', 0, 'Anhydrite', 4150, 4151), (2076, 'F84', 1, 'Sandstone, grey, vf-f', 4152, 4153), (2077, 'F84', 2, 'Anhydrite', 4154, 4155), (2078, 'F84', 3, 'Dolomite', 4156, 4157), (2079, 'F84', 4, 'Anhydrite', 4158, 4159), (2080, 'F84', 5, 'Sandstone, grey, vf-f', 4160, 4161), (2081, 'F84', 6, 'Siltstone, red', 4162, 4163), (2082, 'F84', 7, 'Dolomite', 4164, 4165)  ... displaying 10 of 25 total bound parameter sets ...  (2098, 'F84', 23, 'Limestone', 4196, 4197), (2099, 'F84', 24, 'Volcanic', 4198, 4199))
2021-02-01 11:01:34,491 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:34,791 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:34,792 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:34,794 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:34,801 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:34,802 INFO sqlalchemy.engine.base.Engine ('F84',)
2021-02-01 11:01:34,806 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,807 INFO sqlalchemy.engine.base.Engine (4150,)
2021-02-01 11:01:34,810 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,811 INFO sqlalchemy.engine.base.Engine (4151,)
2021-02-01 11:01:34,814 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,815 INFO sqlalchemy.engine.base.Engine (4152,)
2021-02-01 11:01:34,818 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,821 INFO sqlalchemy.engine.base.Engine (4153,)
2021-02-01 11:01:34,824 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,827 INFO sqlalchemy.engine.base.Engine (4154,)
2021-02-01 11:01:34,830 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,833 INFO sqlalchemy.engine.base.Engine (4155,)
2021-02-01 11:01:34,837 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,838 INFO sqlalchemy.engine.base.Engine (4156,)
2021-02-01 11:01:34,840 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,841 INFO sqlalchemy.engine.base.Engine (4157,)
2021-02-01 11:01:34,843 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,845 INFO sqlalchemy.engine.base.Engine (4158,)
2021-02-01 11:01:34,847 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,848 INFO sqlalchemy.engine.base.Engine (4159,)
2021-02-01 11:01:34,850 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,854 INFO sqlalchemy.engine.base.Engine (4160,)
2021-02-01 11:01:34,856 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,857 INFO sqlalchemy.engine.base.Engine (4161,)
2021-02-01 11:01:34,860 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,861 INFO sqlalchemy.engine.base.Engine (4162,)

2021-02-01 11:01:34,866 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,867 INFO sqlalchemy.engine.base.Engine (4163,)
2021-02-01 11:01:34,869 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,871 INFO sqlalchemy.engine.base.Engine (4164,)
2021-02-01 11:01:34,874 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,875 INFO sqlalchemy.engine.base.Engine (4165,)
2021-02-01 11:01:34,877 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,878 INFO sqlalchemy.engine.base.Engine (4166,)
2021-02-01 11:01:34,881 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,882 INFO sqlalchemy.engine.base.Engine (4167,)
2021-02-01 11:01:34,884 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,886 INFO sqlalchemy.engine.base.Engine (4168,)
2021-02-01 11:01:34,888 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,889 INFO sqlalchemy.engine.base.Engine (4169,)
2021-02-01 11:01:34,891 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,892 INFO sqlalchemy.engine.base.Engine (4170,)
2021-02-01 11:01:34,898 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,899 INFO sqlalchemy.engine.base.Engine (4171,)
2021-02-01 11:01:34,902 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,903 INFO sqlalchemy.engine.base.Engine (4172,)
2021-02-01 11:01:34,906 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,907 INFO sqlalchemy.engine.base.Engine (4173,)
2021-02-01 11:01:34,910 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,911 INFO sqlalchemy.engine.base.Engine (4174,)
2021-02-01 11:01:34,914 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,915 INFO sqlalchemy.engine.base.Engine (4175,)
2021-02-01 11:01:34,920 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,922 INFO sqlalchemy.engine.base.Engine (4176,)
2021-02-01 11:01:34,924 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,925 INFO sqlalchemy.engine.base.Engine (4177,)
2021-02-01 11:01:34,927 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,931 INFO sqlalchemy.engine.base.Engine (4178,)
2021-02-01 11:01:34,934 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,935 INFO sqlalchemy.engine.base.Engine (4179,)
2021-02-01 11:01:34,937 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,939 INFO sqlalchemy.engine.base.Engine (4180,)
2021-02-01 11:01:34,942 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,943 INFO sqlalchemy.engine.base.Engine (4181,)
2021-02-01 11:01:34,946 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,947 INFO sqlalchemy.engine.base.Engine (4182,)
2021-02-01 11:01:34,949 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:34,952 INFO sqlalchemy.engine.base.Engine (4183,)
2021-02-01 11:01:34,956 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,957 INFO sqlalchemy.engine.base.Engine (4184,)
2021-02-01 11:01:34,960 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,961 INFO sqlalchemy.engine.base.Engine (4185,)
2021-02-01 11:01:34,963 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,964 INFO sqlalchemy.engine.base.Engine (4186,)
2021-02-01 11:01:34,965 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,966 INFO sqlalchemy.engine.base.Engine (4187,)
2021-02-01 11:01:34,968 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,969 INFO sqlalchemy.engine.base.Engine (4188,)
2021-02-01 11:01:34,970 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,972 INFO sqlalchemy.engine.base.Engine (4189,)
2021-02-01 11:01:34,976 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,978 INFO sqlalchemy.engine.base.Engine (4190,)
2021-02-01 11:01:34,981 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,982 INFO sqlalchemy.engine.base.Engine (4191,)
2021-02-01 11:01:34,984 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,985 INFO sqlalchemy.engine.base.Engine (4192,)
2021-02-01 11:01:34,988 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,990 INFO sqlalchemy.engine.base.Engine (4193,)
2021-02-01 11:01:34,992 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:34,994 INFO sqlalchemy.engine.base.Engine (4194,)
2021-02-01 11:01:34,999 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,002 INFO sqlalchemy.engine.base.Engine (4195,)
2021-02-01 11:01:35,004 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,006 INFO sqlalchemy.engine.base.Engine (4196,)
2021-02-01 11:01:35,009 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,010 INFO sqlalchemy.engine.base.Engine (4197,)
2021-02-01 11:01:35,013 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,015 INFO sqlalchemy.engine.base.Engine (4198,)
2021-02-01 11:01:35,018 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,019 INFO sqlalchemy.engine.base.Engine (4199,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:35,202 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:35,206 INFO sqlalchemy.engine.base.Engine ('F85',)
2021-02-01 11:01:35,210 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:35,211 INFO sqlalchemy.engine.base.Engine ((4200, 14.3, 14.3, 14.3, 152889.30100002539, 122592.51713904738), (4201, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152889.30100002539, 122592.51713904738), (4202, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152889.30100002539, 122592.51713904738), (4203, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152889.30100002539, 122592.51713904738), (4204, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152889.30100002539, 122592.51713904738), (4205, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152889.30100002539, 122592.51713904738), (4206, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152889.30100002539, 122592.51713904738), (4207, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152889.30100002539, 122592.51713904738)  ... displaying 10 of 50 total bound parameter sets ...  (4248, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152889.30100002539, 122592.51713904738), (4249, 135.9, 135.9, 135.9, 152889.30100002539, 122592.51713904738))
2021-02-01 11:01:35,218 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:35,220 INFO sqlalchemy.engine.base.Engine ((2100, 'F85', 0, 'Anhydrite', 4200, 4201), (2101, 'F85', 1, 'Sandstone, grey, vf-f', 4202, 4203), (2102, 'F85', 2, 'Anhydrite', 4204, 4205), (2103, 'F85', 3, 'Dolomite', 4206, 4207), (2104, 'F85', 4, 'Anhydrite', 4208, 4209), (2105, 'F85', 5, 'Sandstone, grey, vf-f', 4210, 4211), (2106, 'F85', 6, 'Siltstone, red', 4212, 4213), (2107, 'F85', 7, 'Dolomite', 4214, 4215)  ... displaying 10 of 25 total bound parameter sets ...  (2123, 'F85', 23, 'Limestone', 4246, 4247), (2124, 'F85', 24, 'Volcanic', 4248, 4249))

2021-02-01 11:01:35,224 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:35,374 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:35,376 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:35,377 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:35,383 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:35,386 INFO sqlalchemy.engine.base.Engine ('F85',)
2021-02-01 11:01:35,389 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,390 INFO sqlalchemy.engine.base.Engine (4200,)
2021-02-01 11:01:35,393 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,394 INFO sqlalchemy.engine.base.Engine (4201,)
2021-02-01 11:01:35,397 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,398 INFO sqlalchemy.engine.base.Engine (4202,)
2021-02-01 11:01:35,401 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,402 INFO sqlalchemy.engine.base.Engine (4203,)
2021-02-01 11:01:35,405 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,406 INFO sqlalchemy.engine.base.Engine (4204,)
2021-02-01 11:01:35,409 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,411 INFO sqlalchemy.engine.base.Engine (4205,)
2021-02-01 11:01:35,414 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,415 INFO sqlalchemy.engine.base.Engine (4206,)
2021-02-01 11:01:35,421 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,422 INFO sqlalchemy.engine.base.Engine (4207,)
2021-02-01 11:01:35,425 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,426 INFO sqlalchemy.engine.base.Engine (4208,)
2021-02-01 11:01:35,429 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,430 INFO sqlalchemy.engine.base.Engine (4209,)
2021-02-01 11:01:35,433 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,435 INFO sqlalchemy.engine.base.Engine (4210,)
2021-02-01 11:01:35,438 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,442 INFO sqlalchemy.engine.base.Engine (4211,)
2021-02-01 11:01:35,445 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,446 INFO sqlalchemy.engine.base.Engine (4212,)
2021-02-01 11:01:35,449 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,450 INFO sqlalchemy.engine.base.Engine (4213,)
2021-02-01 11:01:35,453 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,455 INFO sqlalchemy.engine.base.Engine (4214,)
2021-02-01 11:01:35,457 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,459 INFO sqlalchemy.engine.base.Engine (4215,)
2021-02-01 11:01:35,462 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,468 INFO sqlalchemy.engine.base.Engine (4216,)
2021-02-01 11:01:35,470 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,471 INFO sqlalchemy.engine.base.Engine (4217,)
2021-02-01 11:01:35,475 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:35,477 INFO sqlalchemy.engine.base.Engine (4218,)
2021-02-01 11:01:35,482 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,483 INFO sqlalchemy.engine.base.Engine (4219,)
2021-02-01 11:01:35,485 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,486 INFO sqlalchemy.engine.base.Engine (4220,)
2021-02-01 11:01:35,488 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,489 INFO sqlalchemy.engine.base.Engine (4221,)
2021-02-01 11:01:35,491 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,492 INFO sqlalchemy.engine.base.Engine (4222,)
2021-02-01 11:01:35,497 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,499 INFO sqlalchemy.engine.base.Engine (4223,)
2021-02-01 11:01:35,502 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,503 INFO sqlalchemy.engine.base.Engine (4224,)
2021-02-01 11:01:35,506 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,508 INFO sqlalchemy.engine.base.Engine (4225,)
2021-02-01 11:01:35,510 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,512 INFO sqlalchemy.engine.base.Engine (4226,)
2021-02-01 11:01:35,514 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,515 INFO sqlalchemy.engine.base.Engine (4227,)
2021-02-01 11:01:35,517 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,519 INFO sqlalchemy.engine.base.Engine (4228,)
2021-02-01 11:01:35,523 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,525 INFO sqlalchemy.engine.base.Engine (4229,)
2021-02-01 11:01:35,528 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,529 INFO sqlalchemy.engine.base.Engine (4230,)
2021-02-01 11:01:35,532 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,533 INFO sqlalchemy.engine.base.Engine (4231,)
2021-02-01 11:01:35,536 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,537 INFO sqlalchemy.engine.base.Engine (4232,)
2021-02-01 11:01:35,540 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,541 INFO sqlalchemy.engine.base.Engine (4233,)
2021-02-01 11:01:35,543 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,546 INFO sqlalchemy.engine.base.Engine (4234,)
2021-02-01 11:01:35,548 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,549 INFO sqlalchemy.engine.base.Engine (4235,)
2021-02-01 11:01:35,552 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,553 INFO sqlalchemy.engine.base.Engine (4236,)
2021-02-01 11:01:35,555 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,556 INFO sqlalchemy.engine.base.Engine (4237,)
2021-02-01 11:01:35,559 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,561 INFO sqlalchemy.engine.base.Engine (4238,)
2021-02-01 11:01:35,565 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:35,565 INFO sqlalchemy.engine.base.Engine (4239,)
2021-02-01 11:01:35,571 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,572 INFO sqlalchemy.engine.base.Engine (4240,)
2021-02-01 11:01:35,573 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,574 INFO sqlalchemy.engine.base.Engine (4241,)
2021-02-01 11:01:35,577 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,578 INFO sqlalchemy.engine.base.Engine (4242,)
2021-02-01 11:01:35,582 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,583 INFO sqlalchemy.engine.base.Engine (4243,)
2021-02-01 11:01:35,586 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,587 INFO sqlalchemy.engine.base.Engine (4244,)
2021-02-01 11:01:35,589 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,591 INFO sqlalchemy.engine.base.Engine (4245,)
2021-02-01 11:01:35,594 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,595 INFO sqlalchemy.engine.base.Engine (4246,)
2021-02-01 11:01:35,599 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,601 INFO sqlalchemy.engine.base.Engine (4247,)
2021-02-01 11:01:35,604 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,605 INFO sqlalchemy.engine.base.Engine (4248,)
2021-02-01 11:01:35,608 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,611 INFO sqlalchemy.engine.base.Engine (4249,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:35,794 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:35,796 INFO sqlalchemy.engine.base.Engine ('F86',)
2021-02-01 11:01:35,800 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:35,801 INFO sqlalchemy.engine.base.Engine ((4250, 14.3, 14.3, 14.3, 152889.53400002542, 122591.68613904806), (4251, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152889.53400002542, 122591.68613904806), (4252, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152889.53400002542, 122591.68613904806), (4253, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152889.53400002542, 122591.68613904806), (4254, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152889.53400002542, 122591.68613904806), (4255, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152889.53400002542, 122591.68613904806), (4256, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152889.53400002542, 122591.68613904806), (4257, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152889.53400002542, 122591.68613904806)  ... displaying 10 of 50 total bound parameter sets ...  (4298, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152889.53400002542, 122591.68613904806), (4299, 135.9, 135.9, 135.9, 152889.53400002542, 122591.68613904806))
2021-02-01 11:01:35,804 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:35,805 INFO sqlalchemy.engine.base.Engine ((2125, 'F86', 0, 'Anhydrite', 4250, 4251), (2126, 'F86', 1, 'Sandstone, grey, vf-f', 4252, 4253), (2127, 'F86', 2, 'Anhydrite', 4254, 4255), (2128, 'F86', 3, 'Dolomite', 4256, 4257), (2129, 'F86', 4, 'Anhydrite', 4258, 4259), (2130, 'F86', 5, 'Sandstone, grey, vf-f', 4260, 4261), (2131, 'F86', 6, 'Siltstone, red', 4262, 4263), (2132, 'F86', 7, 'Dolomite', 4264, 4265)  ... displaying 10 of 25 total bound parameter sets ...  (2148, 'F86', 23, 'Limestone', 4296, 4297), (2149, 'F86', 24, 'Volcanic', 4298, 4299))
2021-02-01 11:01:35,808 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:35,923 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:35,925 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:35,926 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:35,935 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:35,940 INFO sqlalchemy.engine.base.Engine ('F86',)
2021-02-01 11:01:35,944 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,949 INFO sqlalchemy.engine.base.Engine (4250,)
2021-02-01 11:01:35,954 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,956 INFO sqlalchemy.engine.base.Engine (4251,)
2021-02-01 11:01:35,959 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,960 INFO sqlalchemy.engine.base.Engine (4252,)

2021-02-01 11:01:35,963 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,967 INFO sqlalchemy.engine.base.Engine (4253,)
2021-02-01 11:01:35,970 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,971 INFO sqlalchemy.engine.base.Engine (4254,)
2021-02-01 11:01:35,973 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,974 INFO sqlalchemy.engine.base.Engine (4255,)
2021-02-01 11:01:35,979 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,980 INFO sqlalchemy.engine.base.Engine (4256,)
2021-02-01 11:01:35,983 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,987 INFO sqlalchemy.engine.base.Engine (4257,)
2021-02-01 11:01:35,989 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,990 INFO sqlalchemy.engine.base.Engine (4258,)
2021-02-01 11:01:35,993 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:35,995 INFO sqlalchemy.engine.base.Engine (4259,)
2021-02-01 11:01:36,000 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,001 INFO sqlalchemy.engine.base.Engine (4260,)
2021-02-01 11:01:36,004 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,005 INFO sqlalchemy.engine.base.Engine (4261,)
2021-02-01 11:01:36,007 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,008 INFO sqlalchemy.engine.base.Engine (4262,)
2021-02-01 11:01:36,010 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,014 INFO sqlalchemy.engine.base.Engine (4263,)
2021-02-01 11:01:36,025 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,026 INFO sqlalchemy.engine.base.Engine (4264,)
2021-02-01 11:01:36,029 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,031 INFO sqlalchemy.engine.base.Engine (4265,)
2021-02-01 11:01:36,038 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,041 INFO sqlalchemy.engine.base.Engine (4266,)
2021-02-01 11:01:36,043 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,044 INFO sqlalchemy.engine.base.Engine (4267,)
2021-02-01 11:01:36,047 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,048 INFO sqlalchemy.engine.base.Engine (4268,)
2021-02-01 11:01:36,051 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,052 INFO sqlalchemy.engine.base.Engine (4269,)
2021-02-01 11:01:36,055 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,056 INFO sqlalchemy.engine.base.Engine (4270,)
2021-02-01 11:01:36,058 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,060 INFO sqlalchemy.engine.base.Engine (4271,)
2021-02-01 11:01:36,063 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,064 INFO sqlalchemy.engine.base.Engine (4272,)
2021-02-01 11:01:36,066 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:36,067 INFO sqlalchemy.engine.base.Engine (4273,)
2021-02-01 11:01:36,073 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,075 INFO sqlalchemy.engine.base.Engine (4274,)
2021-02-01 11:01:36,077 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,078 INFO sqlalchemy.engine.base.Engine (4275,)
2021-02-01 11:01:36,081 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,083 INFO sqlalchemy.engine.base.Engine (4276,)
2021-02-01 11:01:36,086 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,087 INFO sqlalchemy.engine.base.Engine (4277,)
2021-02-01 11:01:36,090 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,091 INFO sqlalchemy.engine.base.Engine (4278,)
2021-02-01 11:01:36,093 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,096 INFO sqlalchemy.engine.base.Engine (4279,)
2021-02-01 11:01:36,099 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,100 INFO sqlalchemy.engine.base.Engine (4280,)
2021-02-01 11:01:36,103 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,104 INFO sqlalchemy.engine.base.Engine (4281,)
2021-02-01 11:01:36,107 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,108 INFO sqlalchemy.engine.base.Engine (4282,)
2021-02-01 11:01:36,112 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,114 INFO sqlalchemy.engine.base.Engine (4283,)
2021-02-01 11:01:36,117 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,118 INFO sqlalchemy.engine.base.Engine (4284,)
2021-02-01 11:01:36,120 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,121 INFO sqlalchemy.engine.base.Engine (4285,)
2021-02-01 11:01:36,124 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,125 INFO sqlalchemy.engine.base.Engine (4286,)
2021-02-01 11:01:36,129 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,131 INFO sqlalchemy.engine.base.Engine (4287,)
2021-02-01 11:01:36,133 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,134 INFO sqlalchemy.engine.base.Engine (4288,)
2021-02-01 11:01:36,137 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,138 INFO sqlalchemy.engine.base.Engine (4289,)
2021-02-01 11:01:36,140 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,141 INFO sqlalchemy.engine.base.Engine (4290,)
2021-02-01 11:01:36,144 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,145 INFO sqlalchemy.engine.base.Engine (4291,)
2021-02-01 11:01:36,148 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,149 INFO sqlalchemy.engine.base.Engine (4292,)
2021-02-01 11:01:36,152 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,154 INFO sqlalchemy.engine.base.Engine (4293,)
2021-02-01 11:01:36,159 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:36,160 INFO sqlalchemy.engine.base.Engine (4294,)
2021-02-01 11:01:36,163 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,164 INFO sqlalchemy.engine.base.Engine (4295,)
2021-02-01 11:01:36,167 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,168 INFO sqlalchemy.engine.base.Engine (4296,)
2021-02-01 11:01:36,170 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,171 INFO sqlalchemy.engine.base.Engine (4297,)
2021-02-01 11:01:36,174 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,175 INFO sqlalchemy.engine.base.Engine (4298,)
2021-02-01 11:01:36,178 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,179 INFO sqlalchemy.engine.base.Engine (4299,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:36,378 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:36,387 INFO sqlalchemy.engine.base.Engine ((4300, 14.3, 14.3, 14.3, 152889.78600002546, 122588.80213904474), (4301, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152889.78600002546, 122588.80213904474), (4302, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152889.78600002546, 122588.80213904474), (4303, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152889.78600002546, 122588.80213904474), (4304, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152889.78600002546, 122588.80213904474), (4305, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152889.78600002546, 122588.80213904474), (4306, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152889.78600002546, 122588.80213904474), (4307, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152889.78600002546, 122588.80213904474)  ... displaying 10 of 50 total bound parameter sets ...  (4348, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152889.78600002546, 122588.80213904474), (4349, 135.9, 135.9, 135.9, 152889.78600002546, 122588.80213904474))
2021-02-01 11:01:36,392 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:36,402 INFO sqlalchemy.engine.base.Engine ('F87',)
2021-02-01 11:01:36,415 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:36,416 INFO sqlalchemy.engine.base.Engine ((2150, 'F87', 0, 'Anhydrite', 4300, 4301), (2151, 'F87', 1, 'Sandstone, grey, vf-f', 4302, 4303), (2152, 'F87', 2, 'Anhydrite', 4304, 4305), (2153, 'F87', 3, 'Dolomite', 4306, 4307), (2154, 'F87', 4, 'Anhydrite', 4308, 4309), (2155, 'F87', 5, 'Sandstone, grey, vf-f', 4310, 4311), (2156, 'F87', 6, 'Siltstone, red', 4312, 4313), (2157, 'F87', 7, 'Dolomite', 4314, 4315)  ... displaying 10 of 25 total bound parameter sets ...  (2173, 'F87', 23, 'Limestone', 4346, 4347), (2174, 'F87', 24, 'Volcanic', 4348, 4349))
2021-02-01 11:01:36,419 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:36,541 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:36,547 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:36,553 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:36,563 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:36,569 INFO sqlalchemy.engine.base.Engine ('F87',)
2021-02-01 11:01:36,572 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,573 INFO sqlalchemy.engine.base.Engine (4300,)
2021-02-01 11:01:36,575 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,578 INFO sqlalchemy.engine.base.Engine (4301,)
2021-02-01 11:01:36,580 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,583 INFO sqlalchemy.engine.base.Engine (4302,)
2021-02-01 11:01:36,586 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,587 INFO sqlalchemy.engine.base.Engine (4303,)
2021-02-01 11:01:36,590 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,591 INFO sqlalchemy.engine.base.Engine (4304,)
2021-02-01 11:01:36,594 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,595 INFO sqlalchemy.engine.base.Engine (4305,)
2021-02-01 11:01:36,601 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,602 INFO sqlalchemy.engine.base.Engine (4306,)
2021-02-01 11:01:36,604 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,605 INFO sqlalchemy.engine.base.Engine (4307,)

2021-02-01 11:01:36,607 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,609 INFO sqlalchemy.engine.base.Engine (4308,)
2021-02-01 11:01:36,611 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,612 INFO sqlalchemy.engine.base.Engine (4309,)
2021-02-01 11:01:36,615 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,617 INFO sqlalchemy.engine.base.Engine (4310,)
2021-02-01 11:01:36,619 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,620 INFO sqlalchemy.engine.base.Engine (4311,)
2021-02-01 11:01:36,622 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,623 INFO sqlalchemy.engine.base.Engine (4312,)
2021-02-01 11:01:36,626 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,627 INFO sqlalchemy.engine.base.Engine (4313,)
2021-02-01 11:01:36,630 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,631 INFO sqlalchemy.engine.base.Engine (4314,)
2021-02-01 11:01:36,633 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,634 INFO sqlalchemy.engine.base.Engine (4315,)
2021-02-01 11:01:36,637 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,638 INFO sqlalchemy.engine.base.Engine (4316,)
2021-02-01 11:01:36,640 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,641 INFO sqlalchemy.engine.base.Engine (4317,)
2021-02-01 11:01:36,643 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,644 INFO sqlalchemy.engine.base.Engine (4318,)
2021-02-01 11:01:36,646 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,648 INFO sqlalchemy.engine.base.Engine (4319,)
2021-02-01 11:01:36,650 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,651 INFO sqlalchemy.engine.base.Engine (4320,)
2021-02-01 11:01:36,653 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,655 INFO sqlalchemy.engine.base.Engine (4321,)
2021-02-01 11:01:36,657 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,658 INFO sqlalchemy.engine.base.Engine (4322,)
2021-02-01 11:01:36,663 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,665 INFO sqlalchemy.engine.base.Engine (4323,)
2021-02-01 11:01:36,667 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,668 INFO sqlalchemy.engine.base.Engine (4324,)
2021-02-01 11:01:36,671 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,672 INFO sqlalchemy.engine.base.Engine (4325,)
2021-02-01 11:01:36,674 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,675 INFO sqlalchemy.engine.base.Engine (4326,)
2021-02-01 11:01:36,678 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,679 INFO sqlalchemy.engine.base.Engine (4327,)
2021-02-01 11:01:36,682 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:36,683 INFO sqlalchemy.engine.base.Engine (4328,)
2021-02-01 11:01:36,685 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,686 INFO sqlalchemy.engine.base.Engine (4329,)
2021-02-01 11:01:36,688 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,689 INFO sqlalchemy.engine.base.Engine (4330,)
2021-02-01 11:01:36,691 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,692 INFO sqlalchemy.engine.base.Engine (4331,)
2021-02-01 11:01:36,694 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,695 INFO sqlalchemy.engine.base.Engine (4332,)
2021-02-01 11:01:36,698 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,698 INFO sqlalchemy.engine.base.Engine (4333,)
2021-02-01 11:01:36,701 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,702 INFO sqlalchemy.engine.base.Engine (4334,)
2021-02-01 11:01:36,704 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,705 INFO sqlalchemy.engine.base.Engine (4335,)
2021-02-01 11:01:36,708 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,709 INFO sqlalchemy.engine.base.Engine (4336,)
2021-02-01 11:01:36,711 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,712 INFO sqlalchemy.engine.base.Engine (4337,)
2021-02-01 11:01:36,715 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,716 INFO sqlalchemy.engine.base.Engine (4338,)
2021-02-01 11:01:36,720 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,723 INFO sqlalchemy.engine.base.Engine (4339,)
2021-02-01 11:01:36,727 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,728 INFO sqlalchemy.engine.base.Engine (4340,)
2021-02-01 11:01:36,730 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,732 INFO sqlalchemy.engine.base.Engine (4341,)
2021-02-01 11:01:36,735 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,736 INFO sqlalchemy.engine.base.Engine (4342,)
2021-02-01 11:01:36,739 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,740 INFO sqlalchemy.engine.base.Engine (4343,)
2021-02-01 11:01:36,743 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,744 INFO sqlalchemy.engine.base.Engine (4344,)
2021-02-01 11:01:36,749 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,750 INFO sqlalchemy.engine.base.Engine (4345,)
2021-02-01 11:01:36,753 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,754 INFO sqlalchemy.engine.base.Engine (4346,)
2021-02-01 11:01:36,756 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,758 INFO sqlalchemy.engine.base.Engine (4347,)
2021-02-01 11:01:36,760 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:36,761 INFO sqlalchemy.engine.base.Engine (4348,)
2021-02-01 11:01:36,764 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:36,765 INFO sqlalchemy.engine.base.Engine (4349,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 11:01:36,972 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 11:01:36,974 INFO sqlalchemy.engine.base.Engine ('F88',)
2021-02-01 11:01:36,978 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:36,979 INFO sqlalchemy.engine.base.Engine ((4350, 14.3, 14.3, 14.3, 152884.74200002538, 122588.50313904787), (4351, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152884.74200002538, 122588.50313904787), (4352, 51.24117647058824, 51.24117647058824, 51.24117647058824, 152884.74200002538, 122588.50313904787), (4353, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152884.74200002538, 122588.50313904787), (4354, 54.81764705882354, 54.81764705882354, 54.81764705882354, 152884.74200002538, 122588.50313904787), (4355, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152884.74200002538, 122588.50313904787), (4356, 56.55882352941177, 56.55882352941177, 56.55882352941177, 152884.74200002538, 122588.50313904787), (4357, 58.86470588235295, 58.86470588235295, 58.86470588235295, 152884.74200002538, 122588.50313904787)  ... displaying 10 of 50 total bound parameter sets ...  (4398, 131.47647058823532, 131.47647058823532, 131.47647058823532, 152884.74200002538, 122588.50313904787), (4399, 135.9, 135.9, 135.9, 152884.74200002538, 122588.50313904787))
2021-02-01 11:01:36,988 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 11:01:36,989 INFO sqlalchemy.engine.base.Engine ((2175, 'F88', 0, 'Anhydrite', 4350, 4351), (2176, 'F88', 1, 'Sandstone, grey, vf-f', 4352, 4353), (2177, 'F88', 2, 'Anhydrite', 4354, 4355), (2178, 'F88', 3, 'Dolomite', 4356, 4357), (2179, 'F88', 4, 'Anhydrite', 4358, 4359), (2180, 'F88', 5, 'Sandstone, grey, vf-f', 4360, 4361), (2181, 'F88', 6, 'Siltstone, red', 4362, 4363), (2182, 'F88', 7, 'Dolomite', 4364, 4365)  ... displaying 10 of 25 total bound parameter sets ...  (2198, 'F88', 23, 'Limestone', 4396, 4397), (2199, 'F88', 24, 'Volcanic', 4398, 4399))
2021-02-01 11:01:36,993 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 11:01:37,085 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:37,087 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 11:01:37,092 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 11:01:37,099 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:37,100 INFO sqlalchemy.engine.base.Engine ('F88',)
2021-02-01 11:01:37,108 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,112 INFO sqlalchemy.engine.base.Engine (4350,)
2021-02-01 11:01:37,117 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,119 INFO sqlalchemy.engine.base.Engine (4351,)
2021-02-01 11:01:37,125 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,127 INFO sqlalchemy.engine.base.Engine (4352,)
2021-02-01 11:01:37,130 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,131 INFO sqlalchemy.engine.base.Engine (4353,)
2021-02-01 11:01:37,134 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,135 INFO sqlalchemy.engine.base.Engine (4354,)
2021-02-01 11:01:37,138 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,139 INFO sqlalchemy.engine.base.Engine (4355,)
2021-02-01 11:01:37,142 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,143 INFO sqlalchemy.engine.base.Engine (4356,)
2021-02-01 11:01:37,147 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,148 INFO sqlalchemy.engine.base.Engine (4357,)
2021-02-01 11:01:37,152 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,153 INFO sqlalchemy.engine.base.Engine (4358,)
2021-02-01 11:01:37,157 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,158 INFO sqlalchemy.engine.base.Engine (4359,)
2021-02-01 11:01:37,161 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,162 INFO sqlalchemy.engine.base.Engine (4360,)
2021-02-01 11:01:37,165 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,167 INFO sqlalchemy.engine.base.Engine (4361,)
2021-02-01 11:01:37,172 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,173 INFO sqlalchemy.engine.base.Engine (4362,)

2021-02-01 11:01:37,176 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,177 INFO sqlalchemy.engine.base.Engine (4363,)
2021-02-01 11:01:37,180 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,182 INFO sqlalchemy.engine.base.Engine (4364,)
2021-02-01 11:01:37,184 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,185 INFO sqlalchemy.engine.base.Engine (4365,)
2021-02-01 11:01:37,188 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,190 INFO sqlalchemy.engine.base.Engine (4366,)
2021-02-01 11:01:37,194 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,195 INFO sqlalchemy.engine.base.Engine (4367,)
2021-02-01 11:01:37,197 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,198 INFO sqlalchemy.engine.base.Engine (4368,)
2021-02-01 11:01:37,201 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,203 INFO sqlalchemy.engine.base.Engine (4369,)
2021-02-01 11:01:37,205 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,207 INFO sqlalchemy.engine.base.Engine (4370,)
2021-02-01 11:01:37,210 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,211 INFO sqlalchemy.engine.base.Engine (4371,)
2021-02-01 11:01:37,214 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,215 INFO sqlalchemy.engine.base.Engine (4372,)
2021-02-01 11:01:37,217 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,219 INFO sqlalchemy.engine.base.Engine (4373,)
2021-02-01 11:01:37,224 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,225 INFO sqlalchemy.engine.base.Engine (4374,)
2021-02-01 11:01:37,228 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,229 INFO sqlalchemy.engine.base.Engine (4375,)
2021-02-01 11:01:37,232 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,233 INFO sqlalchemy.engine.base.Engine (4376,)
2021-02-01 11:01:37,236 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,237 INFO sqlalchemy.engine.base.Engine (4377,)
2021-02-01 11:01:37,240 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,241 INFO sqlalchemy.engine.base.Engine (4378,)
2021-02-01 11:01:37,244 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,245 INFO sqlalchemy.engine.base.Engine (4379,)
2021-02-01 11:01:37,248 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,249 INFO sqlalchemy.engine.base.Engine (4380,)
2021-02-01 11:01:37,253 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,255 INFO sqlalchemy.engine.base.Engine (4381,)
2021-02-01 11:01:37,259 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,261 INFO sqlalchemy.engine.base.Engine (4382,)
2021-02-01 11:01:37,265 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 11:01:37,266 INFO sqlalchemy.engine.base.Engine (4383,)
2021-02-01 11:01:37,268 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,269 INFO sqlalchemy.engine.base.Engine (4384,)
2021-02-01 11:01:37,272 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,273 INFO sqlalchemy.engine.base.Engine (4385,)
2021-02-01 11:01:37,276 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,277 INFO sqlalchemy.engine.base.Engine (4386,)
2021-02-01 11:01:37,280 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,281 INFO sqlalchemy.engine.base.Engine (4387,)
2021-02-01 11:01:37,286 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,287 INFO sqlalchemy.engine.base.Engine (4388,)
2021-02-01 11:01:37,291 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,292 INFO sqlalchemy.engine.base.Engine (4389,)
2021-02-01 11:01:37,294 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,295 INFO sqlalchemy.engine.base.Engine (4390,)
2021-02-01 11:01:37,300 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,301 INFO sqlalchemy.engine.base.Engine (4391,)
2021-02-01 11:01:37,303 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,304 INFO sqlalchemy.engine.base.Engine (4392,)
2021-02-01 11:01:37,306 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,307 INFO sqlalchemy.engine.base.Engine (4393,)
2021-02-01 11:01:37,310 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,311 INFO sqlalchemy.engine.base.Engine (4394,)
2021-02-01 11:01:37,313 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,314 INFO sqlalchemy.engine.base.Engine (4395,)
2021-02-01 11:01:37,317 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,320 INFO sqlalchemy.engine.base.Engine (4396,)
2021-02-01 11:01:37,323 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,324 INFO sqlalchemy.engine.base.Engine (4397,)
2021-02-01 11:01:37,327 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,328 INFO sqlalchemy.engine.base.Engine (4398,)
2021-02-01 11:01:37,331 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 11:01:37,332 INFO sqlalchemy.engine.base.Engine (4399,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !

In [19]:
p.commit()

2021-02-01 11:01:37,545 INFO sqlalchemy.engine.base.Engine COMMIT

In [20]:
p.boreholes[0].intervals[0].description

2021-02-01 11:01:37,677 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 11:01:37,679 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
WHERE "Boreholes".id = ?
2021-02-01 11:01:37,680 INFO sqlalchemy.engine.base.Engine ('F1',)
2021-02-01 11:01:37,682 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 11:01:37,683 INFO sqlalchemy.engine.base.Engine ('F1',)

'Anhydrite'

In [21]:
session.close()

2021-02-01 11:01:37,760 INFO sqlalchemy.engine.base.Engine ROLLBACK

In [22]:
p.plot3d(x3d=True, radius=0.5)