# Using the ORM to store several boreholes

Imports

In [18]:
from os import remove
from utils.io import boreholes_from_files, striplog_from_text
from core.core import Project
from core.orm import BoreholeOrm, PositionOrm, Base
from striplog import Lexicon, Striplog
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from definitions import ROOT_DIR

In [19]:
remove('tfe_orm_db.db')

Create the db engine and the database structure

In [20]:
engine = create_engine('sqlite:///tfe_orm_db.db', echo=True)

In [21]:
Base.metadata.create_all(engine)

2021-02-01 09:08:53,561 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2021-02-01 09:08:53,562 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 09:08:53,563 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2021-02-01 09:08:53,564 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 09:08:53,565 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Boreholes")
2021-02-01 09:08:53,566 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 09:08:53,568 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("Boreholes")
2021-02-01 09:08:53,569 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 09:08:53,570 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Positions")
2021-02-01 09:08:53,571 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 09:08:53,572 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("Positions")
2021-02-01 09:08:53,574 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 09:08:53,575 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Intervals")
2021-02-01 09:08:53,576 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 09:08:53,578 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("Intervals")
2021-02-01 09:08:53,579 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 09:08:53,580 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Components")
2021-02-01 09:08:53,581 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 09:08:53,582 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("Components")
2021-02-01 09:08:53,583 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 09:08:53,585 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Linkintervalcomponent")
2021-02-01 09:08:53,586 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 09:08:53,587 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("Linkintervalcomponent")
2021-02-01 09:08:53,589 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 09:08:53,592 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "Boreholes" (
	id VARCHAR(32) NOT NULL,
	PRIMARY KEY (id)
)


2021-02-01 09:08:53,593 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 09:08:53,728 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 09:08:53,729 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "Positions" (
	id INTEGER NOT NULL,
	upper FLOAT,
	middle FLOAT,
	lower FLOAT,
	x FLOAT,
	y FLOAT,
	PRIMARY KEY (id)
)


2021-02-01 09:08:53,730 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 09:08:53,812 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 09:08:53,814 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "Components" (
	id VARCHAR(32) NOT NULL,
	description VARCHAR(32),
	PRIMARY KEY (id)
)


2021-02-01 09:08:53,817 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 09:08:53,905 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 09:08:53,906 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "Intervals" (
	id INTEGER NOT NULL,
	borehole VARCHAR(32),
	interval_number INTEGER,
	description VARCHAR(32),
	top_id INTEGER,
	base_id INTEGER,
	PRIMARY KEY (id),
	FOREIGN KEY(borehole) REFERENCES "Boreholes" (id),
	FOREIGN KEY(top_id) REFERENCES "Positions" (id),
	FOREIGN KEY(base_id) REFERENCES "Positions" (id)
)


2021-02-01 09:08:53,907 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 09:08:53,980 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 09:08:53,981 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "Linkintervalcomponent" (
	int_id INTEGER NOT NULL,
	comp_id INTEGER NOT NULL,
	PRIMARY KEY (int_id, comp_id),
	FOREIGN KEY(int_id) REFERENCES "Intervals" (id),
	FOREIGN KEY(comp_id) REFERENCES "Components" (id)
)


2021-02-01 09:08:53,982 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 09:08:54,056 INFO sqlalchemy.engine.base.Engine COMMIT

### Create the objects from las files

In [22]:
lexicon = Lexicon.default()

In [35]:
borehole_dict = {'F1':ROOT_DIR+'/data/test.las', 'F2':ROOT_DIR+'/data/test.csv'} # boreholes to insert into the db

In [36]:
boreholes, components= boreholes_from_files(borehole_dict, verbose=0)

part A |  F1
part A |  F2
part B |  2  |  5  |  2  |  F3
part B |  3  |  10  |  3  |  F4

Create the session

In [27]:
Session = sessionmaker(bind=engine)
session = Session()

Create the project

In [28]:
p = Project(session)
p.add_components(components)

2021-02-01 09:08:54,545 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 09:08:54,546 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 09:08:54,547 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 09:08:54,551 INFO sqlalchemy.engine.base.Engine INSERT INTO "Components" (id, description) VALUES (?, ?)
2021-02-01 09:08:54,552 INFO sqlalchemy.engine.base.Engine ((0, 'Siltstone, grey'), (1, 'Anhydrite'), (2, 'Sandstone, vf-f, grey'), (3, 'Dolomite'), (4, 'Siltstone, red'), (5, 'Limestone'))
2021-02-01 09:08:54,555 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 09:08:54,700 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 09:08:54,701 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 09:08:54,702 INFO sqlalchemy.engine.base.Engine ()

Add boreholes into the database

In [29]:
for bh in boreholes:
    p.add_borehole(bh)

2021-02-01 09:08:54,713 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 09:08:54,714 INFO sqlalchemy.engine.base.Engine ('F1',)
2021-02-01 09:08:54,718 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 09:08:54,718 INFO sqlalchemy.engine.base.Engine ((0, 14.3, 14.3, 14.3, 0.0, 0.0), (1, 51.24117647058824, 51.24117647058824, 51.24117647058824, 0.0, 0.0), (2, 51.24117647058824, 51.24117647058824, 51.24117647058824, 0.0, 0.0), (3, 54.81764705882354, 54.81764705882354, 54.81764705882354, 0.0, 0.0), (4, 54.81764705882354, 54.81764705882354, 54.81764705882354, 0.0, 0.0), (5, 56.55882352941177, 56.55882352941177, 56.55882352941177, 0.0, 0.0), (6, 56.55882352941177, 56.55882352941177, 56.55882352941177, 0.0, 0.0), (7, 58.86470588235295, 58.86470588235295, 58.86470588235295, 0.0, 0.0)  ... displaying 10 of 50 total bound parameter sets ...  (48, 131.47647058823532, 131.47647058823532, 131.47647058823532, 0.0, 0.0), (49, 135.9, 135.9, 135.9, 0.0, 0.0))
2021-02-01 09:08:54,722 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 09:08:54,723 INFO sqlalchemy.engine.base.Engine ((0, 'F1', 0, 'Anhydrite', 0, 1), (1, 'F1', 1, 'Sandstone, grey, vf-f', 2, 3), (2, 'F1', 2, 'Anhydrite', 4, 5), (3, 'F1', 3, 'Dolomite', 6, 7), (4, 'F1', 4, 'Anhydrite', 8, 9), (5, 'F1', 5, 'Sandstone, grey, vf-f', 10, 11), (6, 'F1', 6, 'Siltstone, red', 12, 13), (7, 'F1', 7, 'Dolomite', 14, 15)  ... displaying 10 of 25 total bound parameter sets ...  (23, 'F1', 23, 'Limestone', 46, 47), (24, 'F1', 24, 'Volcanic', 48, 49))
2021-02-01 09:08:54,725 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 09:08:54,861 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 09:08:54,862 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 09:08:54,862 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 09:08:54,865 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 09:08:54,866 INFO sqlalchemy.engine.base.Engine ('F1',)
2021-02-01 09:08:54,870 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,873 INFO sqlalchemy.engine.base.Engine (0,)
2021-02-01 09:08:54,876 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,877 INFO sqlalchemy.engine.base.Engine (1,)
2021-02-01 09:08:54,879 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,880 INFO sqlalchemy.engine.base.Engine (2,)
2021-02-01 09:08:54,883 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,885 INFO sqlalchemy.engine.base.Engine (3,)
2021-02-01 09:08:54,887 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,890 INFO sqlalchemy.engine.base.Engine (4,)
2021-02-01 09:08:54,892 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,893 INFO sqlalchemy.engine.base.Engine (5,)
2021-02-01 09:08:54,896 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,898 INFO sqlalchemy.engine.base.Engine (6,)
2021-02-01 09:08:54,901 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,903 INFO sqlalchemy.engine.base.Engine (7,)
2021-02-01 09:08:54,907 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,908 INFO sqlalchemy.engine.base.Engine (8,)
2021-02-01 09:08:54,910 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,912 INFO sqlalchemy.engine.base.Engine (9,)
2021-02-01 09:08:54,914 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,916 INFO sqlalchemy.engine.base.Engine (10,)
2021-02-01 09:08:54,919 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,920 INFO sqlalchemy.engine.base.Engine (11,)
2021-02-01 09:08:54,924 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,929 INFO sqlalchemy.engine.base.Engine (12,)
2021-02-01 09:08:54,932 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,934 INFO sqlalchemy.engine.base.Engine (13,)
2021-02-01 09:08:54,936 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 09:08:54,938 INFO sqlalchemy.engine.base.Engine (14,)
2021-02-01 09:08:54,942 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,943 INFO sqlalchemy.engine.base.Engine (15,)
2021-02-01 09:08:54,945 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,947 INFO sqlalchemy.engine.base.Engine (16,)
2021-02-01 09:08:54,948 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,950 INFO sqlalchemy.engine.base.Engine (17,)
2021-02-01 09:08:54,951 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,955 INFO sqlalchemy.engine.base.Engine (18,)
2021-02-01 09:08:54,957 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,959 INFO sqlalchemy.engine.base.Engine (19,)
2021-02-01 09:08:54,961 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,962 INFO sqlalchemy.engine.base.Engine (20,)
2021-02-01 09:08:54,965 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,966 INFO sqlalchemy.engine.base.Engine (21,)
2021-02-01 09:08:54,968 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,971 INFO sqlalchemy.engine.base.Engine (22,)
2021-02-01 09:08:54,975 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,977 INFO sqlalchemy.engine.base.Engine (23,)
2021-02-01 09:08:54,979 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,980 INFO sqlalchemy.engine.base.Engine (24,)
2021-02-01 09:08:54,983 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,984 INFO sqlalchemy.engine.base.Engine (25,)
2021-02-01 09:08:54,987 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,990 INFO sqlalchemy.engine.base.Engine (26,)
2021-02-01 09:08:54,993 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,994 INFO sqlalchemy.engine.base.Engine (27,)
2021-02-01 09:08:54,997 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:54,999 INFO sqlalchemy.engine.base.Engine (28,)
2021-02-01 09:08:55,001 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,002 INFO sqlalchemy.engine.base.Engine (29,)
2021-02-01 09:08:55,011 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,014 INFO sqlalchemy.engine.base.Engine (30,)
2021-02-01 09:08:55,016 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,019 INFO sqlalchemy.engine.base.Engine (31,)
2021-02-01 09:08:55,021 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,024 INFO sqlalchemy.engine.base.Engine (32,)
2021-02-01 09:08:55,026 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,028 INFO sqlalchemy.engine.base.Engine (33,)
2021-02-01 09:08:55,032 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,035 INFO sqlalchemy.engine.base.Engine (34,)
2021-02-01 09:08:55,037 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 09:08:55,038 INFO sqlalchemy.engine.base.Engine (35,)
2021-02-01 09:08:55,040 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,042 INFO sqlalchemy.engine.base.Engine (36,)
2021-02-01 09:08:55,044 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,044 INFO sqlalchemy.engine.base.Engine (37,)
2021-02-01 09:08:55,046 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,047 INFO sqlalchemy.engine.base.Engine (38,)
2021-02-01 09:08:55,049 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,050 INFO sqlalchemy.engine.base.Engine (39,)
2021-02-01 09:08:55,052 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,058 INFO sqlalchemy.engine.base.Engine (40,)
2021-02-01 09:08:55,060 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,061 INFO sqlalchemy.engine.base.Engine (41,)
2021-02-01 09:08:55,063 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,064 INFO sqlalchemy.engine.base.Engine (42,)
2021-02-01 09:08:55,066 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,067 INFO sqlalchemy.engine.base.Engine (43,)
2021-02-01 09:08:55,071 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,072 INFO sqlalchemy.engine.base.Engine (44,)
2021-02-01 09:08:55,074 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,074 INFO sqlalchemy.engine.base.Engine (45,)
2021-02-01 09:08:55,076 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,077 INFO sqlalchemy.engine.base.Engine (46,)
2021-02-01 09:08:55,079 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,080 INFO sqlalchemy.engine.base.Engine (47,)
2021-02-01 09:08:55,082 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,083 INFO sqlalchemy.engine.base.Engine (48,)
2021-02-01 09:08:55,085 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,086 INFO sqlalchemy.engine.base.Engine (49,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 09:08:55,224 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 09:08:55,225 INFO sqlalchemy.engine.base.Engine ('F2',)
2021-02-01 09:08:55,229 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 09:08:55,230 INFO sqlalchemy.engine.base.Engine ((50, 14.3, 14.3, 14.3, 20.0, 40.0), (51, 51.24117647058824, 51.24117647058824, 51.24117647058824, 20.0, 40.0), (52, 51.24117647058824, 51.24117647058824, 51.24117647058824, 20.0, 40.0), (53, 54.81764705882354, 54.81764705882354, 54.81764705882354, 20.0, 40.0), (54, 54.81764705882354, 54.81764705882354, 54.81764705882354, 20.0, 40.0), (55, 56.55882352941177, 56.55882352941177, 56.55882352941177, 20.0, 40.0), (56, 56.55882352941177, 56.55882352941177, 56.55882352941177, 20.0, 40.0), (57, 58.86470588235295, 58.86470588235295, 58.86470588235295, 20.0, 40.0)  ... displaying 10 of 50 total bound parameter sets ...  (98, 131.47647058823532, 131.47647058823532, 131.47647058823532, 20.0, 40.0), (99, 135.9, 135.9, 135.9, 20.0, 40.0))
2021-02-01 09:08:55,236 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 09:08:55,237 INFO sqlalchemy.engine.base.Engine ((25, 'F2', 0, 'Anhydrite', 50, 51), (26, 'F2', 1, 'Sandstone, grey, vf-f', 52, 53), (27, 'F2', 2, 'Anhydrite', 54, 55), (28, 'F2', 3, 'Dolomite', 56, 57), (29, 'F2', 4, 'Anhydrite', 58, 59), (30, 'F2', 5, 'Sandstone, grey, vf-f', 60, 61), (31, 'F2', 6, 'Siltstone, red', 62, 63), (32, 'F2', 7, 'Dolomite', 64, 65)  ... displaying 10 of 25 total bound parameter sets ...  (48, 'F2', 23, 'Limestone', 96, 97), (49, 'F2', 24, 'Volcanic', 98, 99))
2021-02-01 09:08:55,244 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 09:08:55,326 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 09:08:55,327 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 09:08:55,328 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 09:08:55,331 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 09:08:55,332 INFO sqlalchemy.engine.base.Engine ('F2',)

2021-02-01 09:08:55,335 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,336 INFO sqlalchemy.engine.base.Engine (50,)
2021-02-01 09:08:55,339 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,340 INFO sqlalchemy.engine.base.Engine (51,)
2021-02-01 09:08:55,342 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,343 INFO sqlalchemy.engine.base.Engine (52,)
2021-02-01 09:08:55,346 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,347 INFO sqlalchemy.engine.base.Engine (53,)
2021-02-01 09:08:55,349 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,350 INFO sqlalchemy.engine.base.Engine (54,)
2021-02-01 09:08:55,352 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,353 INFO sqlalchemy.engine.base.Engine (55,)
2021-02-01 09:08:55,357 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,360 INFO sqlalchemy.engine.base.Engine (56,)
2021-02-01 09:08:55,363 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,364 INFO sqlalchemy.engine.base.Engine (57,)
2021-02-01 09:08:55,366 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,367 INFO sqlalchemy.engine.base.Engine (58,)
2021-02-01 09:08:55,369 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,371 INFO sqlalchemy.engine.base.Engine (59,)
2021-02-01 09:08:55,374 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,375 INFO sqlalchemy.engine.base.Engine (60,)
2021-02-01 09:08:55,377 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,378 INFO sqlalchemy.engine.base.Engine (61,)
2021-02-01 09:08:55,380 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,381 INFO sqlalchemy.engine.base.Engine (62,)
2021-02-01 09:08:55,384 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,385 INFO sqlalchemy.engine.base.Engine (63,)
2021-02-01 09:08:55,387 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,388 INFO sqlalchemy.engine.base.Engine (64,)
2021-02-01 09:08:55,395 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,396 INFO sqlalchemy.engine.base.Engine (65,)
2021-02-01 09:08:55,398 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,399 INFO sqlalchemy.engine.base.Engine (66,)
2021-02-01 09:08:55,401 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,402 INFO sqlalchemy.engine.base.Engine (67,)
2021-02-01 09:08:55,404 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,405 INFO sqlalchemy.engine.base.Engine (68,)
2021-02-01 09:08:55,408 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,409 INFO sqlalchemy.engine.base.Engine (69,)
2021-02-01 09:08:55,412 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 09:08:55,413 INFO sqlalchemy.engine.base.Engine (70,)
2021-02-01 09:08:55,415 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,416 INFO sqlalchemy.engine.base.Engine (71,)
2021-02-01 09:08:55,418 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,420 INFO sqlalchemy.engine.base.Engine (72,)
2021-02-01 09:08:55,423 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,424 INFO sqlalchemy.engine.base.Engine (73,)
2021-02-01 09:08:55,426 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,427 INFO sqlalchemy.engine.base.Engine (74,)
2021-02-01 09:08:55,429 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,430 INFO sqlalchemy.engine.base.Engine (75,)
2021-02-01 09:08:55,432 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,433 INFO sqlalchemy.engine.base.Engine (76,)
2021-02-01 09:08:55,434 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,435 INFO sqlalchemy.engine.base.Engine (77,)
2021-02-01 09:08:55,437 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,438 INFO sqlalchemy.engine.base.Engine (78,)
2021-02-01 09:08:55,440 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,441 INFO sqlalchemy.engine.base.Engine (79,)
2021-02-01 09:08:55,442 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,443 INFO sqlalchemy.engine.base.Engine (80,)
2021-02-01 09:08:55,444 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,445 INFO sqlalchemy.engine.base.Engine (81,)
2021-02-01 09:08:55,448 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,449 INFO sqlalchemy.engine.base.Engine (82,)
2021-02-01 09:08:55,451 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,452 INFO sqlalchemy.engine.base.Engine (83,)
2021-02-01 09:08:55,453 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,454 INFO sqlalchemy.engine.base.Engine (84,)
2021-02-01 09:08:55,455 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,456 INFO sqlalchemy.engine.base.Engine (85,)
2021-02-01 09:08:55,458 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,459 INFO sqlalchemy.engine.base.Engine (86,)
2021-02-01 09:08:55,461 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,462 INFO sqlalchemy.engine.base.Engine (87,)
2021-02-01 09:08:55,464 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,464 INFO sqlalchemy.engine.base.Engine (88,)
2021-02-01 09:08:55,467 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,468 INFO sqlalchemy.engine.base.Engine (89,)
2021-02-01 09:08:55,471 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,472 INFO sqlalchemy.engine.base.Engine (90,)
2021-02-01 09:08:55,474 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 09:08:55,474 INFO sqlalchemy.engine.base.Engine (91,)
2021-02-01 09:08:55,476 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,477 INFO sqlalchemy.engine.base.Engine (92,)
2021-02-01 09:08:55,481 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,481 INFO sqlalchemy.engine.base.Engine (93,)
2021-02-01 09:08:55,483 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,484 INFO sqlalchemy.engine.base.Engine (94,)
2021-02-01 09:08:55,486 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,486 INFO sqlalchemy.engine.base.Engine (95,)
2021-02-01 09:08:55,488 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,489 INFO sqlalchemy.engine.base.Engine (96,)
2021-02-01 09:08:55,491 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,492 INFO sqlalchemy.engine.base.Engine (97,)
2021-02-01 09:08:55,494 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,496 INFO sqlalchemy.engine.base.Engine (98,)
2021-02-01 09:08:55,497 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,499 INFO sqlalchemy.engine.base.Engine (99,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 09:08:55,598 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 09:08:55,599 INFO sqlalchemy.engine.base.Engine ('F3',)
2021-02-01 09:08:55,603 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 09:08:55,605 INFO sqlalchemy.engine.base.Engine ((100, 14.3, 14.3, 14.3, 5.0, 50.0), (101, 51.24117647058824, 51.24117647058824, 51.24117647058824, 5.0, 50.0), (102, 51.24117647058824, 51.24117647058824, 51.24117647058824, 5.0, 50.0), (103, 54.81764705882354, 54.81764705882354, 54.81764705882354, 5.0, 50.0), (104, 54.81764705882354, 54.81764705882354, 54.81764705882354, 5.0, 50.0), (105, 56.55882352941177, 56.55882352941177, 56.55882352941177, 5.0, 50.0), (106, 56.55882352941177, 56.55882352941177, 56.55882352941177, 5.0, 50.0), (107, 58.86470588235295, 58.86470588235295, 58.86470588235295, 5.0, 50.0)  ... displaying 10 of 50 total bound parameter sets ...  (148, 131.47647058823532, 131.47647058823532, 131.47647058823532, 5.0, 50.0), (149, 135.9, 135.9, 135.9, 5.0, 50.0))
2021-02-01 09:08:55,610 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 09:08:55,611 INFO sqlalchemy.engine.base.Engine ((50, 'F3', 0, 'Anhydrite', 100, 101), (51, 'F3', 1, 'Sandstone, grey, vf-f', 102, 103), (52, 'F3', 2, 'Anhydrite', 104, 105), (53, 'F3', 3, 'Dolomite', 106, 107), (54, 'F3', 4, 'Anhydrite', 108, 109), (55, 'F3', 5, 'Sandstone, grey, vf-f', 110, 111), (56, 'F3', 6, 'Siltstone, red', 112, 113), (57, 'F3', 7, 'Dolomite', 114, 115)  ... displaying 10 of 25 total bound parameter sets ...  (73, 'F3', 23, 'Limestone', 146, 147), (74, 'F3', 24, 'Volcanic', 148, 149))
2021-02-01 09:08:55,614 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 09:08:55,740 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 09:08:55,741 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 09:08:55,742 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 09:08:55,744 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 09:08:55,745 INFO sqlalchemy.engine.base.Engine ('F3',)
2021-02-01 09:08:55,747 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,748 INFO sqlalchemy.engine.base.Engine (100,)
2021-02-01 09:08:55,750 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,750 INFO sqlalchemy.engine.base.Engine (101,)
2021-02-01 09:08:55,752 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,753 INFO sqlalchemy.engine.base.Engine (102,)
2021-02-01 09:08:55,755 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,757 INFO sqlalchemy.engine.base.Engine (103,)
2021-02-01 09:08:55,760 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,761 INFO sqlalchemy.engine.base.Engine (104,)
2021-02-01 09:08:55,764 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 09:08:55,765 INFO sqlalchemy.engine.base.Engine (105,)
2021-02-01 09:08:55,768 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,769 INFO sqlalchemy.engine.base.Engine (106,)
2021-02-01 09:08:55,771 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,772 INFO sqlalchemy.engine.base.Engine (107,)
2021-02-01 09:08:55,776 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,777 INFO sqlalchemy.engine.base.Engine (108,)
2021-02-01 09:08:55,779 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,780 INFO sqlalchemy.engine.base.Engine (109,)
2021-02-01 09:08:55,782 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,783 INFO sqlalchemy.engine.base.Engine (110,)
2021-02-01 09:08:55,785 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,786 INFO sqlalchemy.engine.base.Engine (111,)
2021-02-01 09:08:55,790 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,791 INFO sqlalchemy.engine.base.Engine (112,)
2021-02-01 09:08:55,792 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,794 INFO sqlalchemy.engine.base.Engine (113,)
2021-02-01 09:08:55,796 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,797 INFO sqlalchemy.engine.base.Engine (114,)
2021-02-01 09:08:55,801 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,803 INFO sqlalchemy.engine.base.Engine (115,)
2021-02-01 09:08:55,805 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,805 INFO sqlalchemy.engine.base.Engine (116,)
2021-02-01 09:08:55,807 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,808 INFO sqlalchemy.engine.base.Engine (117,)
2021-02-01 09:08:55,810 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,811 INFO sqlalchemy.engine.base.Engine (118,)
2021-02-01 09:08:55,815 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,817 INFO sqlalchemy.engine.base.Engine (119,)
2021-02-01 09:08:55,819 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,821 INFO sqlalchemy.engine.base.Engine (120,)
2021-02-01 09:08:55,824 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,825 INFO sqlalchemy.engine.base.Engine (121,)
2021-02-01 09:08:55,828 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,829 INFO sqlalchemy.engine.base.Engine (122,)
2021-02-01 09:08:55,831 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,834 INFO sqlalchemy.engine.base.Engine (123,)
2021-02-01 09:08:55,836 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,838 INFO sqlalchemy.engine.base.Engine (124,)
2021-02-01 09:08:55,963 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,964 INFO sqlalchemy.engine.base.Engine (125,)
2021-02-01 09:08:55,967 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 09:08:55,968 INFO sqlalchemy.engine.base.Engine (126,)
2021-02-01 09:08:55,971 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,972 INFO sqlalchemy.engine.base.Engine (127,)
2021-02-01 09:08:55,974 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,975 INFO sqlalchemy.engine.base.Engine (128,)
2021-02-01 09:08:55,976 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,977 INFO sqlalchemy.engine.base.Engine (129,)
2021-02-01 09:08:55,979 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,981 INFO sqlalchemy.engine.base.Engine (130,)
2021-02-01 09:08:55,983 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,984 INFO sqlalchemy.engine.base.Engine (131,)
2021-02-01 09:08:55,987 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,988 INFO sqlalchemy.engine.base.Engine (132,)
2021-02-01 09:08:55,989 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,991 INFO sqlalchemy.engine.base.Engine (133,)
2021-02-01 09:08:55,994 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:55,997 INFO sqlalchemy.engine.base.Engine (134,)
2021-02-01 09:08:55,999 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,001 INFO sqlalchemy.engine.base.Engine (135,)
2021-02-01 09:08:56,003 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,006 INFO sqlalchemy.engine.base.Engine (136,)
2021-02-01 09:08:56,008 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,009 INFO sqlalchemy.engine.base.Engine (137,)
2021-02-01 09:08:56,012 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,013 INFO sqlalchemy.engine.base.Engine (138,)
2021-02-01 09:08:56,016 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,018 INFO sqlalchemy.engine.base.Engine (139,)
2021-02-01 09:08:56,024 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,025 INFO sqlalchemy.engine.base.Engine (140,)
2021-02-01 09:08:56,027 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,028 INFO sqlalchemy.engine.base.Engine (141,)
2021-02-01 09:08:56,029 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,030 INFO sqlalchemy.engine.base.Engine (142,)
2021-02-01 09:08:56,032 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,034 INFO sqlalchemy.engine.base.Engine (143,)
2021-02-01 09:08:56,038 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,040 INFO sqlalchemy.engine.base.Engine (144,)
2021-02-01 09:08:56,043 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,045 INFO sqlalchemy.engine.base.Engine (145,)
2021-02-01 09:08:56,047 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,051 INFO sqlalchemy.engine.base.Engine (146,)
2021-02-01 09:08:56,053 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 09:08:56,054 INFO sqlalchemy.engine.base.Engine (147,)
2021-02-01 09:08:56,055 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,056 INFO sqlalchemy.engine.base.Engine (148,)
2021-02-01 09:08:56,060 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,061 INFO sqlalchemy.engine.base.Engine (149,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-01 09:08:56,209 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-01 09:08:56,210 INFO sqlalchemy.engine.base.Engine ('F4',)
2021-02-01 09:08:56,214 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 09:08:56,215 INFO sqlalchemy.engine.base.Engine ((150, 14.3, 14.3, 14.3, 10.0, 2.0), (151, 51.24117647058824, 51.24117647058824, 51.24117647058824, 10.0, 2.0), (152, 51.24117647058824, 51.24117647058824, 51.24117647058824, 10.0, 2.0), (153, 54.81764705882354, 54.81764705882354, 54.81764705882354, 10.0, 2.0), (154, 54.81764705882354, 54.81764705882354, 54.81764705882354, 10.0, 2.0), (155, 56.55882352941177, 56.55882352941177, 56.55882352941177, 10.0, 2.0), (156, 56.55882352941177, 56.55882352941177, 56.55882352941177, 10.0, 2.0), (157, 58.86470588235295, 58.86470588235295, 58.86470588235295, 10.0, 2.0)  ... displaying 10 of 50 total bound parameter sets ...  (198, 131.47647058823532, 131.47647058823532, 131.47647058823532, 10.0, 2.0), (199, 135.9, 135.9, 135.9, 10.0, 2.0))
2021-02-01 09:08:56,221 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-01 09:08:56,222 INFO sqlalchemy.engine.base.Engine ((75, 'F4', 0, 'Anhydrite', 150, 151), (76, 'F4', 1, 'Sandstone, grey, vf-f', 152, 153), (77, 'F4', 2, 'Anhydrite', 154, 155), (78, 'F4', 3, 'Dolomite', 156, 157), (79, 'F4', 4, 'Anhydrite', 158, 159), (80, 'F4', 5, 'Sandstone, grey, vf-f', 160, 161), (81, 'F4', 6, 'Siltstone, red', 162, 163), (82, 'F4', 7, 'Dolomite', 164, 165)  ... displaying 10 of 25 total bound parameter sets ...  (98, 'F4', 23, 'Limestone', 196, 197), (99, 'F4', 24, 'Volcanic', 198, 199))
2021-02-01 09:08:56,225 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-01 09:08:56,292 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 09:08:56,293 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-01 09:08:56,293 INFO sqlalchemy.engine.base.Engine ()
2021-02-01 09:08:56,295 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 09:08:56,296 INFO sqlalchemy.engine.base.Engine ('F4',)
2021-02-01 09:08:56,298 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,299 INFO sqlalchemy.engine.base.Engine (150,)
2021-02-01 09:08:56,301 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,301 INFO sqlalchemy.engine.base.Engine (151,)
2021-02-01 09:08:56,305 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,306 INFO sqlalchemy.engine.base.Engine (152,)
2021-02-01 09:08:56,308 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,308 INFO sqlalchemy.engine.base.Engine (153,)
2021-02-01 09:08:56,311 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,311 INFO sqlalchemy.engine.base.Engine (154,)
2021-02-01 09:08:56,314 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,315 INFO sqlalchemy.engine.base.Engine (155,)
2021-02-01 09:08:56,318 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,319 INFO sqlalchemy.engine.base.Engine (156,)
2021-02-01 09:08:56,321 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,322 INFO sqlalchemy.engine.base.Engine (157,)
2021-02-01 09:08:56,329 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,330 INFO sqlalchemy.engine.base.Engine (158,)
2021-02-01 09:08:56,332 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,333 INFO sqlalchemy.engine.base.Engine (159,)
2021-02-01 09:08:56,335 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,336 INFO sqlalchemy.engine.base.Engine (160,)
2021-02-01 09:08:56,341 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 09:08:56,343 INFO sqlalchemy.engine.base.Engine (161,)
2021-02-01 09:08:56,346 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,347 INFO sqlalchemy.engine.base.Engine (162,)
2021-02-01 09:08:56,348 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,349 INFO sqlalchemy.engine.base.Engine (163,)
2021-02-01 09:08:56,352 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,353 INFO sqlalchemy.engine.base.Engine (164,)
2021-02-01 09:08:56,355 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,355 INFO sqlalchemy.engine.base.Engine (165,)
2021-02-01 09:08:56,357 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,359 INFO sqlalchemy.engine.base.Engine (166,)
2021-02-01 09:08:56,361 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,361 INFO sqlalchemy.engine.base.Engine (167,)
2021-02-01 09:08:56,363 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,364 INFO sqlalchemy.engine.base.Engine (168,)
2021-02-01 09:08:56,366 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,366 INFO sqlalchemy.engine.base.Engine (169,)
2021-02-01 09:08:56,371 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,372 INFO sqlalchemy.engine.base.Engine (170,)
2021-02-01 09:08:56,374 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,375 INFO sqlalchemy.engine.base.Engine (171,)
2021-02-01 09:08:56,378 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,380 INFO sqlalchemy.engine.base.Engine (172,)
2021-02-01 09:08:56,382 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,383 INFO sqlalchemy.engine.base.Engine (173,)
2021-02-01 09:08:56,386 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,387 INFO sqlalchemy.engine.base.Engine (174,)
2021-02-01 09:08:56,389 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,389 INFO sqlalchemy.engine.base.Engine (175,)
2021-02-01 09:08:56,392 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,392 INFO sqlalchemy.engine.base.Engine (176,)
2021-02-01 09:08:56,394 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,395 INFO sqlalchemy.engine.base.Engine (177,)
2021-02-01 09:08:56,397 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,398 INFO sqlalchemy.engine.base.Engine (178,)
2021-02-01 09:08:56,400 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,401 INFO sqlalchemy.engine.base.Engine (179,)
2021-02-01 09:08:56,403 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,404 INFO sqlalchemy.engine.base.Engine (180,)
2021-02-01 09:08:56,406 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,406 INFO sqlalchemy.engine.base.Engine (181,)
2021-02-01 09:08:56,408 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-01 09:08:56,409 INFO sqlalchemy.engine.base.Engine (182,)
2021-02-01 09:08:56,411 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,412 INFO sqlalchemy.engine.base.Engine (183,)
2021-02-01 09:08:56,414 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,415 INFO sqlalchemy.engine.base.Engine (184,)
2021-02-01 09:08:56,418 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,421 INFO sqlalchemy.engine.base.Engine (185,)
2021-02-01 09:08:56,423 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,424 INFO sqlalchemy.engine.base.Engine (186,)
2021-02-01 09:08:56,426 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,429 INFO sqlalchemy.engine.base.Engine (187,)
2021-02-01 09:08:56,430 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,431 INFO sqlalchemy.engine.base.Engine (188,)
2021-02-01 09:08:56,434 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,435 INFO sqlalchemy.engine.base.Engine (189,)
2021-02-01 09:08:56,438 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,441 INFO sqlalchemy.engine.base.Engine (190,)
2021-02-01 09:08:56,445 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,446 INFO sqlalchemy.engine.base.Engine (191,)
2021-02-01 09:08:56,449 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,452 INFO sqlalchemy.engine.base.Engine (192,)
2021-02-01 09:08:56,455 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,457 INFO sqlalchemy.engine.base.Engine (193,)
2021-02-01 09:08:56,461 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,462 INFO sqlalchemy.engine.base.Engine (194,)
2021-02-01 09:08:56,464 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,464 INFO sqlalchemy.engine.base.Engine (195,)
2021-02-01 09:08:56,467 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,468 INFO sqlalchemy.engine.base.Engine (196,)
2021-02-01 09:08:56,471 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,472 INFO sqlalchemy.engine.base.Engine (197,)
2021-02-01 09:08:56,478 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,479 INFO sqlalchemy.engine.base.Engine (198,)
2021-02-01 09:08:56,481 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-01 09:08:56,482 INFO sqlalchemy.engine.base.Engine (199,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !

In [30]:
p.boreholes[0].id

'F1'

In [31]:
p.commit()

2021-02-01 09:08:56,736 INFO sqlalchemy.engine.base.Engine COMMIT

In [32]:
p.boreholes[0].intervals[0].description

2021-02-01 09:08:56,811 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-01 09:08:56,813 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
WHERE "Boreholes".id = ?
2021-02-01 09:08:56,814 INFO sqlalchemy.engine.base.Engine ('F1',)
2021-02-01 09:08:56,816 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-01 09:08:56,817 INFO sqlalchemy.engine.base.Engine ('F1',)

'Anhydrite'

In [33]:
session.close()

2021-02-01 09:08:56,894 INFO sqlalchemy.engine.base.Engine ROLLBACK

In [34]:
p.plot3d(x3d=True)