# Using the ORM to store several boreholes

Imports

In [7]:
from os import remove
from utils.io import boreholes_from_files, striplog_from_text
from core.core import Project
from core.orm import BoreholeOrm, PositionOrm, Base
from striplog import Lexicon, Striplog
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from definitions import ROOT_DIR

In [8]:
remove('tmp_files/tfe_orm_db.db')

Create the db engine and the database structure

In [9]:
engine = create_engine('sqlite:///tmp_files/tfe_orm_db.db', echo=True)

In [10]:
Base.metadata.create_all(engine)

2021-02-20 14:26:31,416 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2021-02-20 14:26:31,418 INFO sqlalchemy.engine.base.Engine ()
2021-02-20 14:26:31,420 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2021-02-20 14:26:31,421 INFO sqlalchemy.engine.base.Engine ()
2021-02-20 14:26:31,423 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Boreholes")
2021-02-20 14:26:31,424 INFO sqlalchemy.engine.base.Engine ()
2021-02-20 14:26:31,425 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("Boreholes")
2021-02-20 14:26:31,425 INFO sqlalchemy.engine.base.Engine ()
2021-02-20 14:26:31,426 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Positions")
2021-02-20 14:26:31,427 INFO sqlalchemy.engine.base.Engine ()
2021-02-20 14:26:31,428 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("Positions")
2021-02-20 14:26:31,429 INFO sqlalchemy.engine.base.Engine ()
2021-02-20 14:26:31,430 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Intervals")
2021-02-20 14:26:31,430 INFO sqlalchemy.engine.base.Engine ()
2021-02-20 14:26:31,431 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("Intervals")
2021-02-20 14:26:31,431 INFO sqlalchemy.engine.base.Engine ()
2021-02-20 14:26:31,432 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Components")
2021-02-20 14:26:31,432 INFO sqlalchemy.engine.base.Engine ()
2021-02-20 14:26:31,433 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("Components")
2021-02-20 14:26:31,433 INFO sqlalchemy.engine.base.Engine ()
2021-02-20 14:26:31,434 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Linkintervalcomponent")
2021-02-20 14:26:31,435 INFO sqlalchemy.engine.base.Engine ()
2021-02-20 14:26:31,436 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("Linkintervalcomponent")
2021-02-20 14:26:31,436 INFO sqlalchemy.engine.base.Engine ()
2021-02-20 14:26:31,438 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "Boreholes" (
	id VARCHAR(32) NOT NULL,
	PRIMARY KEY (id)
)


2021-02-20 14:26:31,439 INFO sqlalchemy.engine.base.Engine ()
2021-02-20 14:26:31,443 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-20 14:26:31,445 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "Positions" (
	id INTEGER NOT NULL,
	upper FLOAT,
	middle FLOAT,
	lower FLOAT,
	x FLOAT,
	y FLOAT,
	PRIMARY KEY (id)
)


2021-02-20 14:26:31,445 INFO sqlalchemy.engine.base.Engine ()
2021-02-20 14:26:31,449 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-20 14:26:31,450 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "Components" (
	id VARCHAR(32) NOT NULL,
	description VARCHAR(32),
	PRIMARY KEY (id)
)


2021-02-20 14:26:31,451 INFO sqlalchemy.engine.base.Engine ()
2021-02-20 14:26:31,455 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-20 14:26:31,455 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "Intervals" (
	id INTEGER NOT NULL,
	borehole VARCHAR(32),
	interval_number INTEGER,
	description VARCHAR(32),
	top_id INTEGER,
	base_id INTEGER,
	PRIMARY KEY (id),
	FOREIGN KEY(borehole) REFERENCES "Boreholes" (id),
	FOREIGN KEY(top_id) REFERENCES "Positions" (id),
	FOREIGN KEY(base_id) REFERENCES "Positions" (id)
)


2021-02-20 14:26:31,456 INFO sqlalchemy.engine.base.Engine ()
2021-02-20 14:26:31,459 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-20 14:26:31,460 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "Linkintervalcomponent" (
	int_id INTEGER NOT NULL,
	comp_id INTEGER NOT NULL,
	PRIMARY KEY (int_id, comp_id),
	FOREIGN KEY(int_id) REFERENCES "Intervals" (id),
	FOREIGN KEY(comp_id) REFERENCES "Components" (id)
)


2021-02-20 14:26:31,461 INFO sqlalchemy.engine.base.Engine ()
2021-02-20 14:26:31,465 INFO sqlalchemy.engine.base.Engine COMMIT

### Create the objects from las files

In [11]:
lexicon = Lexicon.default()

In [12]:
borehole_dict = {'F1':ROOT_DIR+'/data/test.las'}#, 'F2':ROOT_DIR+'/data/test.csv'} # boreholes to insert into the db

In [13]:
boreholes, components= boreholes_from_files(borehole_dict, verbose=0)
len(boreholes)

4

Create the session

In [9]:
Session = sessionmaker(bind=engine)
session = Session()

Create the project

In [10]:
p = Project(session)
p.add_components(components)

2021-02-20 14:00:15,528 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-20 14:00:15,531 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-20 14:00:15,532 INFO sqlalchemy.engine.base.Engine ()
2021-02-20 14:00:15,537 INFO sqlalchemy.engine.base.Engine INSERT INTO "Components" (id, description) VALUES (?, ?)
2021-02-20 14:00:15,537 INFO sqlalchemy.engine.base.Engine ((0, 'Siltstone, grey'), (1, 'Anhydrite'), (2, 'Sandstone, vf-f, grey'), (3, 'Dolomite'), (4, 'Siltstone, red'), (5, 'Limestone'))
2021-02-20 14:00:15,539 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-20 14:00:15,543 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-20 14:00:15,544 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-20 14:00:15,544 INFO sqlalchemy.engine.base.Engine ()

Add boreholes into the database

In [11]:
for bh in boreholes:
    p.add_borehole(bh)

2021-02-20 14:00:16,104 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-20 14:00:16,106 INFO sqlalchemy.engine.base.Engine ('F1',)
2021-02-20 14:00:16,109 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-20 14:00:16,110 INFO sqlalchemy.engine.base.Engine ((0, 14.3, 14.3, 14.3, 0.0, 0.0), (1, 51.24117647058824, 51.24117647058824, 51.24117647058824, 0.0, 0.0), (2, 51.24117647058824, 51.24117647058824, 51.24117647058824, 0.0, 0.0), (3, 54.81764705882354, 54.81764705882354, 54.81764705882354, 0.0, 0.0), (4, 54.81764705882354, 54.81764705882354, 54.81764705882354, 0.0, 0.0), (5, 56.55882352941177, 56.55882352941177, 56.55882352941177, 0.0, 0.0), (6, 56.55882352941177, 56.55882352941177, 56.55882352941177, 0.0, 0.0), (7, 58.86470588235295, 58.86470588235295, 58.86470588235295, 0.0, 0.0)  ... displaying 10 of 50 total bound parameter sets ...  (48, 131.47647058823532, 131.47647058823532, 131.47647058823532, 0.0, 0.0), (49, 135.9, 135.9, 135.9, 0.0, 0.0))
2021-02-20 14:00:16,112 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-20 14:00:16,113 INFO sqlalchemy.engine.base.Engine ((0, 'F1', 0, 'Anhydrite', 0, 1), (1, 'F1', 1, 'Sandstone, grey, vf-f', 2, 3), (2, 'F1', 2, 'Anhydrite', 4, 5), (3, 'F1', 3, 'Dolomite', 6, 7), (4, 'F1', 4, 'Anhydrite', 8, 9), (5, 'F1', 5, 'Sandstone, grey, vf-f', 10, 11), (6, 'F1', 6, 'Siltstone, red', 12, 13), (7, 'F1', 7, 'Dolomite', 14, 15)  ... displaying 10 of 25 total bound parameter sets ...  (23, 'F1', 23, 'Limestone', 46, 47), (24, 'F1', 24, 'Volcanic', 48, 49))
2021-02-20 14:00:16,114 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-20 14:00:16,118 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-20 14:00:16,119 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-20 14:00:16,120 INFO sqlalchemy.engine.base.Engine ()
2021-02-20 14:00:16,122 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-20 14:00:16,123 INFO sqlalchemy.engine.base.Engine ('F1',)
2021-02-20 14:00:16,126 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,126 INFO sqlalchemy.engine.base.Engine (0,)
2021-02-20 14:00:16,128 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,128 INFO sqlalchemy.engine.base.Engine (1,)
2021-02-20 14:00:16,130 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,131 INFO sqlalchemy.engine.base.Engine (2,)
2021-02-20 14:00:16,132 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,133 INFO sqlalchemy.engine.base.Engine (3,)
2021-02-20 14:00:16,135 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,136 INFO sqlalchemy.engine.base.Engine (4,)
2021-02-20 14:00:16,138 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,138 INFO sqlalchemy.engine.base.Engine (5,)
2021-02-20 14:00:16,143 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,144 INFO sqlalchemy.engine.base.Engine (6,)
2021-02-20 14:00:16,145 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,145 INFO sqlalchemy.engine.base.Engine (7,)
2021-02-20 14:00:16,147 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,148 INFO sqlalchemy.engine.base.Engine (8,)
2021-02-20 14:00:16,149 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,150 INFO sqlalchemy.engine.base.Engine (9,)
2021-02-20 14:00:16,152 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,153 INFO sqlalchemy.engine.base.Engine (10,)
2021-02-20 14:00:16,154 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,155 INFO sqlalchemy.engine.base.Engine (11,)
2021-02-20 14:00:16,159 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,159 INFO sqlalchemy.engine.base.Engine (12,)
2021-02-20 14:00:16,161 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,162 INFO sqlalchemy.engine.base.Engine (13,)
2021-02-20 14:00:16,164 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-20 14:00:16,164 INFO sqlalchemy.engine.base.Engine (14,)
2021-02-20 14:00:16,165 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,166 INFO sqlalchemy.engine.base.Engine (15,)
2021-02-20 14:00:16,170 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,170 INFO sqlalchemy.engine.base.Engine (16,)
2021-02-20 14:00:16,172 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,172 INFO sqlalchemy.engine.base.Engine (17,)
2021-02-20 14:00:16,176 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,176 INFO sqlalchemy.engine.base.Engine (18,)
2021-02-20 14:00:16,178 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,178 INFO sqlalchemy.engine.base.Engine (19,)
2021-02-20 14:00:16,182 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,182 INFO sqlalchemy.engine.base.Engine (20,)
2021-02-20 14:00:16,184 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,184 INFO sqlalchemy.engine.base.Engine (21,)
2021-02-20 14:00:16,187 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,188 INFO sqlalchemy.engine.base.Engine (22,)
2021-02-20 14:00:16,189 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,190 INFO sqlalchemy.engine.base.Engine (23,)
2021-02-20 14:00:16,193 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,194 INFO sqlalchemy.engine.base.Engine (24,)
2021-02-20 14:00:16,195 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,196 INFO sqlalchemy.engine.base.Engine (25,)
2021-02-20 14:00:16,199 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,201 INFO sqlalchemy.engine.base.Engine (26,)
2021-02-20 14:00:16,202 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,203 INFO sqlalchemy.engine.base.Engine (27,)
2021-02-20 14:00:16,206 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,206 INFO sqlalchemy.engine.base.Engine (28,)
2021-02-20 14:00:16,207 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,208 INFO sqlalchemy.engine.base.Engine (29,)
2021-02-20 14:00:16,210 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,211 INFO sqlalchemy.engine.base.Engine (30,)
2021-02-20 14:00:16,213 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,213 INFO sqlalchemy.engine.base.Engine (31,)
2021-02-20 14:00:16,215 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,215 INFO sqlalchemy.engine.base.Engine (32,)
2021-02-20 14:00:16,217 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,219 INFO sqlalchemy.engine.base.Engine (33,)
2021-02-20 14:00:16,222 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,223 INFO sqlalchemy.engine.base.Engine (34,)
2021-02-20 14:00:16,224 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-20 14:00:16,225 INFO sqlalchemy.engine.base.Engine (35,)
2021-02-20 14:00:16,228 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,229 INFO sqlalchemy.engine.base.Engine (36,)
2021-02-20 14:00:16,230 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,231 INFO sqlalchemy.engine.base.Engine (37,)
2021-02-20 14:00:16,236 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,236 INFO sqlalchemy.engine.base.Engine (38,)
2021-02-20 14:00:16,237 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,238 INFO sqlalchemy.engine.base.Engine (39,)
2021-02-20 14:00:16,240 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,241 INFO sqlalchemy.engine.base.Engine (40,)
2021-02-20 14:00:16,242 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,243 INFO sqlalchemy.engine.base.Engine (41,)
2021-02-20 14:00:16,246 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,247 INFO sqlalchemy.engine.base.Engine (42,)
2021-02-20 14:00:16,249 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,250 INFO sqlalchemy.engine.base.Engine (43,)
2021-02-20 14:00:16,252 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,253 INFO sqlalchemy.engine.base.Engine (44,)
2021-02-20 14:00:16,254 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,255 INFO sqlalchemy.engine.base.Engine (45,)
2021-02-20 14:00:16,257 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,258 INFO sqlalchemy.engine.base.Engine (46,)
2021-02-20 14:00:16,259 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,259 INFO sqlalchemy.engine.base.Engine (47,)
2021-02-20 14:00:16,262 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,262 INFO sqlalchemy.engine.base.Engine (48,)
2021-02-20 14:00:16,264 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,264 INFO sqlalchemy.engine.base.Engine (49,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-20 14:00:16,313 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-20 14:00:16,314 INFO sqlalchemy.engine.base.Engine ((50, 0.0, 0.0, 0.0, 20.0, 40.0), (51, 1.5, 1.5, 1.5, 20.0, 40.0), (52, 1.5, 1.5, 1.5, 20.0, 40.0), (53, 4.0, 4.0, 4.0, 20.0, 40.0), (54, 4.0, 4.0, 4.0, 20.0, 40.0), (55, 6.0, 6.0, 6.0, 20.0, 40.0))
2021-02-20 14:00:16,315 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-20 14:00:16,316 INFO sqlalchemy.engine.base.Engine ('F2',)
2021-02-20 14:00:16,317 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-20 14:00:16,317 INFO sqlalchemy.engine.base.Engine ((25, 'F2', 0, 'Anhydrite', 50, 51), (26, 'F2', 1, 'Grey vf-f sandstone', 52, 53), (27, 'F2', 2, 'Red siltstone', 54, 55))
2021-02-20 14:00:16,318 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-20 14:00:16,323 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-20 14:00:16,324 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-20 14:00:16,325 INFO sqlalchemy.engine.base.Engine ()
2021-02-20 14:00:16,327 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-20 14:00:16,328 INFO sqlalchemy.engine.base.Engine ('F2',)
2021-02-20 14:00:16,330 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,330 INFO sqlalchemy.engine.base.Engine (50,)
2021-02-20 14:00:16,332 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,332 INFO sqlalchemy.engine.base.Engine (51,)
2021-02-20 14:00:16,335 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-20 14:00:16,336 INFO sqlalchemy.engine.base.Engine (52,)
2021-02-20 14:00:16,337 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,338 INFO sqlalchemy.engine.base.Engine (53,)
2021-02-20 14:00:16,340 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,341 INFO sqlalchemy.engine.base.Engine (54,)
2021-02-20 14:00:16,342 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,342 INFO sqlalchemy.engine.base.Engine (55,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-20 14:00:16,376 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-20 14:00:16,377 INFO sqlalchemy.engine.base.Engine ((56, 14.3, 14.3, 14.3, 5.0, 50.0), (57, 51.24117647058824, 51.24117647058824, 51.24117647058824, 5.0, 50.0), (58, 51.24117647058824, 51.24117647058824, 51.24117647058824, 5.0, 50.0), (59, 54.81764705882354, 54.81764705882354, 54.81764705882354, 5.0, 50.0), (60, 54.81764705882354, 54.81764705882354, 54.81764705882354, 5.0, 50.0), (61, 56.55882352941177, 56.55882352941177, 56.55882352941177, 5.0, 50.0), (62, 56.55882352941177, 56.55882352941177, 56.55882352941177, 5.0, 50.0), (63, 58.86470588235295, 58.86470588235295, 58.86470588235295, 5.0, 50.0)  ... displaying 10 of 50 total bound parameter sets ...  (104, 131.47647058823532, 131.47647058823532, 131.47647058823532, 5.0, 50.0), (105, 135.9, 135.9, 135.9, 5.0, 50.0))
2021-02-20 14:00:16,378 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-20 14:00:16,379 INFO sqlalchemy.engine.base.Engine ('F3',)
2021-02-20 14:00:16,382 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-20 14:00:16,383 INFO sqlalchemy.engine.base.Engine ((28, 'F3', 0, 'Anhydrite', 56, 57), (29, 'F3', 1, 'Sandstone, grey, vf-f', 58, 59), (30, 'F3', 2, 'Anhydrite', 60, 61), (31, 'F3', 3, 'Dolomite', 62, 63), (32, 'F3', 4, 'Anhydrite', 64, 65), (33, 'F3', 5, 'Sandstone, grey, vf-f', 66, 67), (34, 'F3', 6, 'Siltstone, red', 68, 69), (35, 'F3', 7, 'Dolomite', 70, 71)  ... displaying 10 of 25 total bound parameter sets ...  (51, 'F3', 23, 'Limestone', 102, 103), (52, 'F3', 24, 'Volcanic', 104, 105))
2021-02-20 14:00:16,385 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-20 14:00:16,388 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-20 14:00:16,389 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-20 14:00:16,389 INFO sqlalchemy.engine.base.Engine ()
2021-02-20 14:00:16,390 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-20 14:00:16,391 INFO sqlalchemy.engine.base.Engine ('F3',)
2021-02-20 14:00:16,392 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,393 INFO sqlalchemy.engine.base.Engine (56,)
2021-02-20 14:00:16,394 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,395 INFO sqlalchemy.engine.base.Engine (57,)
2021-02-20 14:00:16,399 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,400 INFO sqlalchemy.engine.base.Engine (58,)
2021-02-20 14:00:16,402 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,403 INFO sqlalchemy.engine.base.Engine (59,)
2021-02-20 14:00:16,407 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,408 INFO sqlalchemy.engine.base.Engine (60,)
2021-02-20 14:00:16,409 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,410 INFO sqlalchemy.engine.base.Engine (61,)
2021-02-20 14:00:16,413 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,413 INFO sqlalchemy.engine.base.Engine (62,)
2021-02-20 14:00:16,415 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,415 INFO sqlalchemy.engine.base.Engine (63,)
2021-02-20 14:00:16,417 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,418 INFO sqlalchemy.engine.base.Engine (64,)
2021-02-20 14:00:16,419 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,419 INFO sqlalchemy.engine.base.Engine (65,)
2021-02-20 14:00:16,422 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,422 INFO sqlalchemy.engine.base.Engine (66,)

2021-02-20 14:00:16,424 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,424 INFO sqlalchemy.engine.base.Engine (67,)
2021-02-20 14:00:16,428 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,428 INFO sqlalchemy.engine.base.Engine (68,)
2021-02-20 14:00:16,430 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,431 INFO sqlalchemy.engine.base.Engine (69,)
2021-02-20 14:00:16,433 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,433 INFO sqlalchemy.engine.base.Engine (70,)
2021-02-20 14:00:16,434 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,434 INFO sqlalchemy.engine.base.Engine (71,)
2021-02-20 14:00:16,436 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,437 INFO sqlalchemy.engine.base.Engine (72,)
2021-02-20 14:00:16,438 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,438 INFO sqlalchemy.engine.base.Engine (73,)
2021-02-20 14:00:16,440 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,441 INFO sqlalchemy.engine.base.Engine (74,)
2021-02-20 14:00:16,442 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,442 INFO sqlalchemy.engine.base.Engine (75,)
2021-02-20 14:00:16,444 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,445 INFO sqlalchemy.engine.base.Engine (76,)
2021-02-20 14:00:16,446 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,446 INFO sqlalchemy.engine.base.Engine (77,)
2021-02-20 14:00:16,448 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,448 INFO sqlalchemy.engine.base.Engine (78,)
2021-02-20 14:00:16,449 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,450 INFO sqlalchemy.engine.base.Engine (79,)
2021-02-20 14:00:16,452 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,452 INFO sqlalchemy.engine.base.Engine (80,)
2021-02-20 14:00:16,453 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,454 INFO sqlalchemy.engine.base.Engine (81,)
2021-02-20 14:00:16,456 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,456 INFO sqlalchemy.engine.base.Engine (82,)
2021-02-20 14:00:16,457 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,458 INFO sqlalchemy.engine.base.Engine (83,)
2021-02-20 14:00:16,461 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,461 INFO sqlalchemy.engine.base.Engine (84,)
2021-02-20 14:00:16,462 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,462 INFO sqlalchemy.engine.base.Engine (85,)
2021-02-20 14:00:16,465 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,466 INFO sqlalchemy.engine.base.Engine (86,)
2021-02-20 14:00:16,468 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-20 14:00:16,468 INFO sqlalchemy.engine.base.Engine (87,)
2021-02-20 14:00:16,470 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,471 INFO sqlalchemy.engine.base.Engine (88,)
2021-02-20 14:00:16,472 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,472 INFO sqlalchemy.engine.base.Engine (89,)
2021-02-20 14:00:16,474 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,475 INFO sqlalchemy.engine.base.Engine (90,)
2021-02-20 14:00:16,476 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,476 INFO sqlalchemy.engine.base.Engine (91,)
2021-02-20 14:00:16,478 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,478 INFO sqlalchemy.engine.base.Engine (92,)
2021-02-20 14:00:16,480 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,480 INFO sqlalchemy.engine.base.Engine (93,)
2021-02-20 14:00:16,482 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,482 INFO sqlalchemy.engine.base.Engine (94,)
2021-02-20 14:00:16,483 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,484 INFO sqlalchemy.engine.base.Engine (95,)
2021-02-20 14:00:16,486 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,486 INFO sqlalchemy.engine.base.Engine (96,)
2021-02-20 14:00:16,487 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,488 INFO sqlalchemy.engine.base.Engine (97,)
2021-02-20 14:00:16,490 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,490 INFO sqlalchemy.engine.base.Engine (98,)
2021-02-20 14:00:16,491 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,491 INFO sqlalchemy.engine.base.Engine (99,)
2021-02-20 14:00:16,493 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,494 INFO sqlalchemy.engine.base.Engine (100,)
2021-02-20 14:00:16,495 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,495 INFO sqlalchemy.engine.base.Engine (101,)
2021-02-20 14:00:16,497 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,498 INFO sqlalchemy.engine.base.Engine (102,)
2021-02-20 14:00:16,498 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,499 INFO sqlalchemy.engine.base.Engine (103,)
2021-02-20 14:00:16,501 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,502 INFO sqlalchemy.engine.base.Engine (104,)
2021-02-20 14:00:16,503 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,503 INFO sqlalchemy.engine.base.Engine (105,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !
2021-02-20 14:00:16,546 INFO sqlalchemy.engine.base.Engine INSERT INTO "Positions" (id, upper, middle, lower, x, y) VALUES (?, ?, ?, ?, ?, ?)
2021-02-20 14:00:16,547 INFO sqlalchemy.engine.base.Engine ((106, 14.3, 14.3, 14.3, 10.0, 2.0), (107, 51.24117647058824, 51.24117647058824, 51.24117647058824, 10.0, 2.0), (108, 51.24117647058824, 51.24117647058824, 51.24117647058824, 10.0, 2.0), (109, 54.81764705882354, 54.81764705882354, 54.81764705882354, 10.0, 2.0), (110, 54.81764705882354, 54.81764705882354, 54.81764705882354, 10.0, 2.0), (111, 56.55882352941177, 56.55882352941177, 56.55882352941177, 10.0, 2.0), (112, 56.55882352941177, 56.55882352941177, 56.55882352941177, 10.0, 2.0), (113, 58.86470588235295, 58.86470588235295, 58.86470588235295, 10.0, 2.0)  ... displaying 10 of 50 total bound parameter sets ...  (154, 131.47647058823532, 131.47647058823532, 131.47647058823532, 10.0, 2.0), (155, 135.9, 135.9, 135.9, 10.0, 2.0))

2021-02-20 14:00:16,548 INFO sqlalchemy.engine.base.Engine INSERT INTO "Boreholes" (id) VALUES (?)
2021-02-20 14:00:16,549 INFO sqlalchemy.engine.base.Engine ('F4',)
2021-02-20 14:00:16,551 INFO sqlalchemy.engine.base.Engine INSERT INTO "Intervals" (id, borehole, interval_number, description, top_id, base_id) VALUES (?, ?, ?, ?, ?, ?)
2021-02-20 14:00:16,552 INFO sqlalchemy.engine.base.Engine ((53, 'F4', 0, 'Anhydrite', 106, 107), (54, 'F4', 1, 'Sandstone, grey, vf-f', 108, 109), (55, 'F4', 2, 'Anhydrite', 110, 111), (56, 'F4', 3, 'Dolomite', 112, 113), (57, 'F4', 4, 'Anhydrite', 114, 115), (58, 'F4', 5, 'Sandstone, grey, vf-f', 116, 117), (59, 'F4', 6, 'Siltstone, red', 118, 119), (60, 'F4', 7, 'Dolomite', 120, 121)  ... displaying 10 of 25 total bound parameter sets ...  (76, 'F4', 23, 'Limestone', 152, 153), (77, 'F4', 24, 'Volcanic', 154, 155))
2021-02-20 14:00:16,553 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-20 14:00:16,557 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-20 14:00:16,558 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
2021-02-20 14:00:16,558 INFO sqlalchemy.engine.base.Engine ()
2021-02-20 14:00:16,560 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-20 14:00:16,560 INFO sqlalchemy.engine.base.Engine ('F4',)
2021-02-20 14:00:16,561 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,562 INFO sqlalchemy.engine.base.Engine (106,)
2021-02-20 14:00:16,564 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,565 INFO sqlalchemy.engine.base.Engine (107,)
2021-02-20 14:00:16,568 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,569 INFO sqlalchemy.engine.base.Engine (108,)
2021-02-20 14:00:16,570 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,570 INFO sqlalchemy.engine.base.Engine (109,)
2021-02-20 14:00:16,572 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,573 INFO sqlalchemy.engine.base.Engine (110,)
2021-02-20 14:00:16,574 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,574 INFO sqlalchemy.engine.base.Engine (111,)
2021-02-20 14:00:16,576 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,577 INFO sqlalchemy.engine.base.Engine (112,)
2021-02-20 14:00:16,577 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,578 INFO sqlalchemy.engine.base.Engine (113,)
2021-02-20 14:00:16,581 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,581 INFO sqlalchemy.engine.base.Engine (114,)
2021-02-20 14:00:16,583 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,584 INFO sqlalchemy.engine.base.Engine (115,)
2021-02-20 14:00:16,587 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,588 INFO sqlalchemy.engine.base.Engine (116,)
2021-02-20 14:00:16,588 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,589 INFO sqlalchemy.engine.base.Engine (117,)
2021-02-20 14:00:16,591 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,591 INFO sqlalchemy.engine.base.Engine (118,)
2021-02-20 14:00:16,592 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,593 INFO sqlalchemy.engine.base.Engine (119,)
2021-02-20 14:00:16,595 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,596 INFO sqlalchemy.engine.base.Engine (120,)
2021-02-20 14:00:16,597 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,597 INFO sqlalchemy.engine.base.Engine (121,)
2021-02-20 14:00:16,599 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-20 14:00:16,600 INFO sqlalchemy.engine.base.Engine (122,)
2021-02-20 14:00:16,601 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,602 INFO sqlalchemy.engine.base.Engine (123,)
2021-02-20 14:00:16,603 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,604 INFO sqlalchemy.engine.base.Engine (124,)
2021-02-20 14:00:16,605 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,605 INFO sqlalchemy.engine.base.Engine (125,)
2021-02-20 14:00:16,607 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,608 INFO sqlalchemy.engine.base.Engine (126,)
2021-02-20 14:00:16,609 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,610 INFO sqlalchemy.engine.base.Engine (127,)
2021-02-20 14:00:16,611 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,612 INFO sqlalchemy.engine.base.Engine (128,)
2021-02-20 14:00:16,614 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,615 INFO sqlalchemy.engine.base.Engine (129,)
2021-02-20 14:00:16,617 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,617 INFO sqlalchemy.engine.base.Engine (130,)
2021-02-20 14:00:16,619 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,619 INFO sqlalchemy.engine.base.Engine (131,)
2021-02-20 14:00:16,621 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,621 INFO sqlalchemy.engine.base.Engine (132,)
2021-02-20 14:00:16,623 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,623 INFO sqlalchemy.engine.base.Engine (133,)
2021-02-20 14:00:16,626 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,627 INFO sqlalchemy.engine.base.Engine (134,)
2021-02-20 14:00:16,628 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,628 INFO sqlalchemy.engine.base.Engine (135,)
2021-02-20 14:00:16,631 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,632 INFO sqlalchemy.engine.base.Engine (136,)
2021-02-20 14:00:16,633 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,634 INFO sqlalchemy.engine.base.Engine (137,)
2021-02-20 14:00:16,636 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,636 INFO sqlalchemy.engine.base.Engine (138,)
2021-02-20 14:00:16,637 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,638 INFO sqlalchemy.engine.base.Engine (139,)
2021-02-20 14:00:16,641 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,642 INFO sqlalchemy.engine.base.Engine (140,)
2021-02-20 14:00:16,644 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,644 INFO sqlalchemy.engine.base.Engine (141,)
2021-02-20 14:00:16,648 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,649 INFO sqlalchemy.engine.base.Engine (142,)
2021-02-20 14:00:16,650 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?

2021-02-20 14:00:16,652 INFO sqlalchemy.engine.base.Engine (143,)
2021-02-20 14:00:16,655 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,655 INFO sqlalchemy.engine.base.Engine (144,)
2021-02-20 14:00:16,656 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,657 INFO sqlalchemy.engine.base.Engine (145,)
2021-02-20 14:00:16,659 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,659 INFO sqlalchemy.engine.base.Engine (146,)
2021-02-20 14:00:16,661 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,661 INFO sqlalchemy.engine.base.Engine (147,)
2021-02-20 14:00:16,664 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,665 INFO sqlalchemy.engine.base.Engine (148,)
2021-02-20 14:00:16,666 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,667 INFO sqlalchemy.engine.base.Engine (149,)
2021-02-20 14:00:16,670 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,671 INFO sqlalchemy.engine.base.Engine (150,)
2021-02-20 14:00:16,672 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,673 INFO sqlalchemy.engine.base.Engine (151,)
2021-02-20 14:00:16,675 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,675 INFO sqlalchemy.engine.base.Engine (152,)
2021-02-20 14:00:16,676 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,677 INFO sqlalchemy.engine.base.Engine (153,)
2021-02-20 14:00:16,679 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,680 INFO sqlalchemy.engine.base.Engine (154,)
2021-02-20 14:00:16,681 INFO sqlalchemy.engine.base.Engine SELECT "Positions".id AS "Positions_id", "Positions".upper AS "Positions_upper", "Positions".middle AS "Positions_middle", "Positions".lower AS "Positions_lower", "Positions".x AS "Positions_x", "Positions".y AS "Positions_y"
FROM "Positions"
WHERE "Positions".id = ?
2021-02-20 14:00:16,681 INFO sqlalchemy.engine.base.Engine (155,)
No legend given or incorrect format ! A default legend will be used
Borehole geometry created successfully !

In [12]:
p.boreholes[0].id

'F1'

In [13]:
p.commit()

2021-02-20 14:00:16,731 INFO sqlalchemy.engine.base.Engine COMMIT

In [14]:
p.boreholes[0].intervals[0].description

2021-02-20 14:00:16,736 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-20 14:00:16,737 INFO sqlalchemy.engine.base.Engine SELECT "Boreholes".id AS "Boreholes_id"
FROM "Boreholes"
WHERE "Boreholes".id = ?
2021-02-20 14:00:16,737 INFO sqlalchemy.engine.base.Engine ('F1',)
2021-02-20 14:00:16,738 INFO sqlalchemy.engine.base.Engine SELECT "Intervals".id AS "Intervals_id", "Intervals".borehole AS "Intervals_borehole", "Intervals".interval_number AS "Intervals_interval_number", "Intervals".description AS "Intervals_description", "Intervals".top_id AS "Intervals_top_id", "Intervals".base_id AS "Intervals_base_id"
FROM "Intervals"
WHERE ? = "Intervals".borehole
2021-02-20 14:00:16,739 INFO sqlalchemy.engine.base.Engine ('F1',)

'Anhydrite'

In [15]:
session.close()

2021-02-20 14:00:16,873 INFO sqlalchemy.engine.base.Engine ROLLBACK

In [16]:
p.plot3d(x3d=True)